### ISSUE TITLE
Cursors don't stop at the beginning of line in blockwise visual mode

### ISSUE THREAD

**Issue by yoshitakame** [t9md/atom-vim-mode-plus#10]
Thanks for v0.1.5 release. It perfectly fixed #8! :tada:

You might have already noticed, but another problem seems to appear. Please see the GIF below.

This problem happens only on soft wrapped lines. Otherwise blockwise visual mode works fine.

<a href="https://gyazo.com/110ec0846276d35d256cc4b470164cfd"><img src="https://i.gyazo.com/110ec0846276d35d256cc4b470164cfd.gif" /></a>

**Comment by t9md** [comment]
Yes i know its on TODO list. Currently the priority is low.
I have lots of todo mainly for refactoring and specs.
But I always appreciate people report the issue since I can know that other user use and hit this issue.
That is good input to pick next todo as I and you did on issue #8.
