### ISSUE TITLE
I cannot get desired behavior of updateRegisterOnChangeOrSubstitute

### ISSUE THREAD

**Issue by zwing99** [t9md/atom-vim-mode-plus#1005]
Atom: 1.23.1
vim-mode-plus: 1.24.4

When i call cw the text is put in the paste board even with this option set:
  "vim-mode-plus":
    updateRegisterOnChangeOrSubstitute: false

#739

**Comment by t9md** [comment]
The issue you referring is old.
Basically any valid setting have corresponding ui-form in setting-view.
If you couldn't find setting in setting-view, should be understood as that setting is not supported.

For the setting you are finding, use this, this is explained in other issue and also in CHANGELOG.md.

<img width="762" alt="settings_ ___github_atom-vim-mode-plus" src="https://user-images.githubusercontent.com/155205/34216004-5cb2571c-e5ea-11e7-9ed3-36b497ed80c1.png">

**Comment by zwing99** [comment]
Ahhh sorry. Thanks for the fast response your prescribed fix works brilliantly!
