### ISSUE TITLE
search-current-word no longer respecting editor word boundaries

### ISSUE THREAD

**Issue by bennypowers** [t9md/atom-vim-mode-plus#1008]
# Check list

You have to check all before open issue.

- [x] Try with latest Atom and latest vim-mode-plus.
- [x] Pick descriptive and non-ambiguous subject
- [x] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [x] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [x] Include real use case so that maintainer can understand "why" you need help.
- [x] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).
- [x] If keybinding issue, Read https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

macOS High Sierra 10.13.2

VMP 1.24.4

I use atom's default word boundaries, including `-`.

In previous version of VMP, hitting `*` on a word-inside-hyphens would move to the next word.

I will illustrate previous behaviour with `[s]` to represent the normal-mode cursor over the `s` char.

```
word-in[s]ide-hyphens word inside hyphens word-inside-hyphens

// press *

word-inside-hyphens word [inside] hyphens word-inside-hyphens

// press *

word-inside-hyphens word inside hyphens word-[inside]-hyphens
```

Current behaviour:

```
word-in[s]ide-hyphens word inside hyphens word-inside-hyphens

// press *

word-inside-hyphens word inside hyphens [word-inside-hyphens]

// press *

[word-inside-hyphens] word inside hyphens word-inside-hyphens
```

I would like `*` to respect word boundaries again.

This also affect commands like `c o i l`

My use-case is searching for terms in dash prefixed customElement names,
like
```html
  <link rel="lazy-import" href="./pages/eve-terms/eve-terms.html" group="terms">
  <script>
    this.importLazyGroup('terms')
  </script>
```

I should note the it would also be useful to have both behaviours, e.g. for transforming the first line below to the second

```html
<link rel="import" href="../../../bower_components/iron-form/iron-form.html">
<link rel="import" href="../../../bower_components/paper-input/paper-input.html">
```

Thank you for the awesome plugin. It makes a huge difference to my daily work.

**Comment by t9md** [comment]
OK I could reproduce it.
I haven't changed that code in recent release.
So it still works in grammar like markdown, javascript.

But at least I could reproduce this issue in **HTML grammar**.

I believe what have changed is HTML grammar's `nonWordCharacters` definition.

**Comment by t9md** [comment]
To be clear

- language-html(HTML grammar) define `-` as part of word char.
- So `*` select `hyphen-separated-word` as single word.

I technically make this behavior grammar independent( I thinks which is the behavior you want ).
But priority is not high, I'm working on different project now and it's more important for me than this issue .

**Comment by bennypowers** [comment]
Thanks for looking into it, I appreciate your diagnosis. Sounds like I might be able to override the new defaults in config. Will post if I succeed
