### ISSUE TITLE
Open to unimpaired-style bindings and Atom IDE?

### ISSUE THREAD

**Issue by wbinnssmith** [t9md/atom-vim-mode-plus#1028]
はじめまして！

Would you be open to contributions to implement [vim-unimpaired](https://github.com/tpope/vim-unimpaired)-style bindings? It seems like a couple were [implemented in the past](https://github.com/t9md/atom-vim-mode-plus/issues/568).

I'd like to contribute implementions for a number of these, even dispatching commands for their equivalents in [Atom IDE](https://atom.io/beta) when needed, such as for advancing to the next linter error (we can also do the same for the linter package.

Of course, I understand if you feel these should be external to vim-mode-plus, but given Atom IDE's official status I think they could belong here instead. ありがとうございます ：）

**Comment by wbinnssmith** [comment]
here's a link to a more complete [list of the kinds of bindings I'd like to implement](https://github.com/tpope/vim-unimpaired/blob/master/doc/unimpaired.txt#L18-L146)

**Comment by t9md** [comment]
Hi, I'm not vim-unimpaired user.
So I don't understand it's goodness correctly.
As far as I checked the link for the list of keymaps it's provides, I want you to try to implement it as vmp-plugin.

Why I recommend it  as plugin is
- I don't know it's feature set correctly.
- it seems it provide lots of `[` and `]` starting keymaps, but I don't want vmp's default `[` and  `]` overridden it's bound to `move-up-to-edge`, `move-down-to-edge`.

There is no big diff between core-operations and plugin-operations.
I can help you if you find something difficult while developing vmp-plugin.
How to create vmp-plugin? Please see following links.

- https://github.com/t9md/atom-vim-mode-plus/wiki/CreateVimModePlusPlugin
- https://github.com/t9md/atom-vim-mode-plus/wiki/ListOfVimModePlusPlugins

**Comment by wbinnssmith** [comment]
thanks @t9md. I'll get back to you soon!

**Comment by t9md** [comment]
Noticed  information in [CreateVimModePlusPlugin](https://github.com/t9md/atom-vim-mode-plus/wiki/CreateVimModePlusPlugin) is a bit old(I need to update this sorry).

[ExtendVimModePlusInInitFile](https://github.com/t9md/atom-vim-mode-plus/wiki/ExtendVimModePlusInInitFile) is better for starter. and Of course published vmp-plugins are reliable example too.

**Comment by t9md** [comment]
@wbinnssmith 
Vmp provides un-explained developer helper command, I quickly put explanation for these command here.
Hope it help your devlopment.

https://github.com/t9md/atom-vim-mode-plus/wiki/DeveloperTIPS
