### ISSUE TITLE
Key command for "hover to reveal" behaviour?

### ISSUE THREAD

**Issue by jackfranklin** [t9md/atom-vim-mode-plus#1029]
Hey,

Firstly, I've said this before but your hard work on this plugin is amazing and I'm so thankful!

I had one question / feature request - although you may have not done it for good reason in which case I'll go away :)

I use atom-ide and one of the useful features it has is that I can hover over a variable with my mouse and get a small overlay with some type information. Similarly if I've made an ESLint error in my JS, I can hover over it to see what the error is. 

Given that I use this plugin, and I tend to avoid touching my mouse if I can, I was wondering if it would be feasible (or even possible, I'm not sure), to have a key stroke defined that would act as if my mouse was hovering over where my cursor is, and trigger the pop up. I'd love to see a red underline squiggle from ESLint, navigate to it and then hit <some shortcut> to have the error pop up. Similarly, being able to do this over a variable to see the type information would also be great.

Thank you :)

**Comment by jackfranklin** [comment]
And of course, the moment I hit 'Enter' on this issue I find the solution!

For those following along, Atom calls these data tips, and you can toggle them via the DataTip: Toggle command which can be mapped to anything you'd like :)

**Comment by tylerthehaas** [comment]
did this work for you in elm files @jackfranklin? I tested this in a javascript file and it worked perfectly but not in an elm file.
