### ISSUE TITLE
Ability to use additional keyboard layouts in Insert mode

### ISSUE THREAD

**Issue by theubermanishere** [t9md/atom-vim-mode-plus#1030]
Currently vim supports different keyboard layouts in the normal mode and the insert mode.

If you use "set keymap=dvorak" in .vimrc, then your vim will have the Dvorak keyboard layout in the Insert mode but it will otherwise operate with the Qwerty Layout.

This could be an additional feature for the users of this package.

**Comment by t9md** [comment]
I'm not dvorak user, so cannot provide practical advice for you.
Here some link to use dvrorak in Atom.

https://github.com/atom/atom-keymap/pull/22
http://www.blog.bdauria.com/?p=1071
