### ISSUE TITLE
Crashes with the latest atom-latex

### ISSUE THREAD

**Issue by dionyziz** [t9md/atom-vim-mode-plus#1035]
```
% atom --version
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
macOS Sierra 10.13.3
vim-mode-plus 1.28.1
atom-latex 0.8.4
```

When I type `$\$` in a LaTeX (`.tex`) file with both vim-mode-plus and atom-latex enabled, the editor hangs. This issue is for reference the dual of the main issue reported at the atom-latex package on https://github.com/James-Yu/Atom-LaTeX/issues/135

**Comment by t9md** [comment]
Will close, since I have no idea what to do to solve this issue.
Plus I think this is not vmp's issue.
Reopen if you find concrete reproduction step and find it's really vmp's issue.
