### ISSUE TITLE
Executing `yg_` from within the line doesn't copy from cursor till end of line but rather copies the whole line.

### ISSUE THREAD

**Issue by JasoonS** [t9md/atom-vim-mode-plus#1036]
In vim `yg_` copies from cursor till end of line including the new line character, but in vim-mode-plus it copies the whole line (in other words it is the same as `yy`).

OS: Ubuntu 17.10
Atom version: 1.24.0
atom-vim-mode-plus version: 1.28.1

# Check list

You have to check all before open issue.

- [ x] Try with latest Atom and latest vim-mode-plus.
- [x ] Pick descriptive and non-ambiguous subject
- [x ] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [x ] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [x ] Include real use case so that maintainer can understand "why" you need help.
- [x ] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).
- [x ] If keybinding issue, Read https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working

**Comment by t9md** [comment]
`y` is yank operator, `g _` is motion to move to last-non-blank-char.
Both are implemented in vmp too.
So it's work in my environment.
See this GIF, flashed area is where vmp yanked.

![help](https://user-images.githubusercontent.com/155205/36655606-0c69a66e-1b07-11e8-86db-98790c79c853.gif)



I think `g _` is correctly mapped in your env.
Does sole `g _` motion wok in your environment?

**Comment by JasoonS** [comment]
It seems to be working now, sorry to waste your time, I really don't know what changed.

Thank you for the great work!
