### ISSUE TITLE
Missing ctrl-h command

### ISSUE THREAD

**Issue by falsandtru** [t9md/atom-vim-mode-plus#1041]
Could you support `ctrl-h` command in insert mode? This is very common command. Currently I'm using the following workaround.

```
'atom-text-editor.vim-mode-plus.insert-mode':
  'ctrl-h': 'core:backspace'
```

<details>
  <summary>debug info</summary>

```json
{
  "atom": "1.22.1",
  "platform": "linux",
  "release": "4.13.0-36-generic",
  "vmpVersion": "1.29.0",
  "vmpConfig": {
    "blackholeRegisteredOperators": [],
    "startInInsertModeScopes": [],
    "charactersToAddSpaceOnSurround": [],
    "highlightSearchExcludeScopes": [],
    "flashOnOperateBlacklist": []
  }
}
```

</details>

# Check list

You have to check all before open issue.

- [x] Provide your environment info clipped by `Vim Mode Plus: Clip Debug Info` command.
- [x] Try with latest Atom and latest vim-mode-plus.
- [x] Pick descriptive and non-ambiguous subject
- [x] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [x] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [x] Include real use case so that maintainer can understand "why" you need help.
- [x] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).
- [x] If keybinding issue, Read [this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).

**Comment by t9md** [comment]
I don't want to modify `insert-mode`'s keymap basically.
To make `insert-mode`'s UX to be atom's native UX.

I use MacOS, it have that keymap.

https://github.com/atom/atom/blob/1dc700182171ae2fe8773bed703a62104aad0b8e/keymaps/darwin.cson#L17

But linux doesn't have.

https://github.com/atom/atom/blob/1dc700182171ae2fe8773bed703a62104aad0b8e/keymaps/linux.cson

I think there must be some reason. You can ask or request to atom/atom repository.

**Comment by t9md** [comment]
Close since no update and nothing to do by my side.

**Comment by falsandtru** [comment]
I see, I defined those commands myself.

```
'body':
  'ctrl-h': 'core:backspace'
  'ctrl-d': 'core:delete'
'atom-text-editor.vim-mode-plus.insert-mode':
  'ctrl-d': 'core:delete'
```
