### ISSUE TITLE
Disable (enable) vim-mode with command

### ISSUE THREAD

**Issue by trkoch** [t9md/atom-vim-mode-plus#1042]
Is it feasible to add a command (available Cmd+Shift-P command palette) to quickly toggle vim-mode? Why is this useful? For example, I find myself switching to insert mode in all tabs, disabling vim-mode altogether would be easiest. Another scenario is pairing with users unfamiliar with vim.

**Comment by trkoch** [comment]
For reference, you can achieve this with https://atom.io/packages/toggle-packages. Still, a built-in command may be useful.

**Comment by t9md** [comment]
Adding command to disable vim-mode-plus(vmp) pkg is easy.
But vim-mode-plus cannot provides command to enable vmp such as `vim-mode-plus:enable`.

So implementing this feature is not simple and easy(need disable/enable by not completely disabling vmp).
If you can achieve by other pkg, use that pkg please.

**Comment by trkoch** [comment]
Thinking about it, it makes total sense vim-mode-plus cannot provide a command to enable. Sorry! Thanks for your clarification.
