### ISSUE TITLE
add-blank-line-* commands exit insert mode

### ISSUE THREAD

**Issue by paradox460** [t9md/atom-vim-mode-plus#1057]
When calling the `add-blank-line-*` operators (`add-blank-line-above` and `add-blank-line-below`) in insert mode, the editor is transitioned out of insert mode, into normal mode.

These functions are particularly useful for inserting a newline around the current line, while maintaining cursor position.

**Comment by t9md** [comment]
Basically every operator in vmp is designed to be invoked from `normal-mode`.
So invoking  it from `insert-mode` is out of scope.

For your case, using following native command solve problem.

![tryit_txt_ ___tryit](https://user-images.githubusercontent.com/155205/38401110-cf36f2d2-398e-11e8-830c-c125fda0852f.jpg)

**Comment by paradox460** [comment]
Huh, I opened my command palette in an effort to find the exact command I wanted to bind. Thank you!
