### ISSUE TITLE
Suggestion: After pressing "No thanks" in "scroll past end" dialog, it shouldn't ask again

### ISSUE THREAD

**Issue by corence** [t9md/atom-vim-mode-plus#1062]
Hi, vim-mode-plus is great!

I have a request: **if the user presses No Thanks in the editor.scrollPastEnd popup, then that popup should no longer appear.**

I'm talking about the popup that appears when, after I've first installed the plugin in a fresh Atom install, then I press `zz` in a small file.

It's cool that this popup exists and it's really handy for the majority of people, who will want the vim-like behaviour.

But, I actually prefer if it doesn't scroll past end. So I want to leave it disabled, but, that isn't really practical, because the popup will keep appearing until I cooperate :)

**Comment by hcgatewood** [comment]
@t9md any thoughts on this? Would be very helpful!

**Comment by t9md** [comment]
Wow, this is very bad popup behavior.
I did not notice. Will fix.

**Comment by t9md** [comment]
v1.36.2 have the fix with new popup option "never ask again".
