### ISSUE TITLE
[bug] exmode takes long to appear and misses my keystrokes.

### ISSUE THREAD

**Issue by trusktr** [t9md/atom-vim-mode-plus#1071]
Execute `Vim Mode Plus: Clip Debug Info`(which write info to clipboard) then paste here.

<details>
  <summary>debug info with package info</summary>

```json
{
  "atom": "1.27.1",
  "platform": "darwin",
  "release": "17.5.0",
  "vmpVersion": "1.32.0",
  "vmpConfig": {
    "keymapYToYankToLastCharacterOfLine": true,
    "blackholeRegisteredOperators": [],
    "startInInsertModeScopes": [],
    "charactersToAddSpaceOnSurround": [],
    "highlightSearchExcludeScopes": [],
    "flashOnOperateBlacklist": []
  },
  "activeCommunityPackages": [
    "atom-material-syntax: 1.0.8",
    "atom-vim-like-tab: 1.5.1",
    "ex-mode-sort: 1.0.0",
    "hey-pane: 1.1.0",
    "keystroke: 0.4.0",
    "minimap: 4.29.8",
    "minimap-quick-highlight: 1.0.1",
    "one-tab: 0.10.0",
    "quick-highlight: 0.13.0",
    "teletype: 0.13.2",
    "vim-mode-plus: 1.32.0",
    "vim-mode-plus-keymaps-for-surround: 0.2.1",
    "language-pug: 0.0.22",
    "platformio-ide-terminal: 2.8.1",
    "ex-mode: 0.18.0"
  ]
}
```

</details>

Read and check all "Check list" bellow.

# Check list

You have to check all before open issue.

- [x] **Provide your environment info clipped by `Vim Mode Plus: Clip Debug Info` command.**
- [x] **Try with latest Atom and latest vim-mode-plus.**
- [x] **Pick descriptive and non-ambiguous subject**
- [x] **Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).**
  behavior change
- [x] **Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.**
  current behavior is that exmode can take some time before it appears, and by the time it appears I may have already typed what I wanted, but it won't appear in the exmode. This is a horrible experiene because while waiting for exmode to appear, the keystrokes can run other commands and modify the text buffer, making me have to cancel what I was doing and go fix it, then again hit `:` but this time wait for possibly more than 1 second before typing. It's quite frustrating and disruptive to workflow.
- [x] **Include real use case so that maintainer can understand "why" you need help.**
  We need to be able to type something like `:w` quickly to save a file, without having to wait for exmode to open.
- [x] **Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).**
- [ ] **If keybinding issue, Read [this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).**

**Comment by trusktr** [comment]
I'm trying to get by, but it is completely unusable.

**Comment by t9md** [comment]
Which ex-mode pkg are you using?

**Comment by trusktr** [comment]
Oops, wait, I have `ex-mode` installed. I'll post there. Sorry!

**Comment by t9md** [comment]
I can understand your issue, theoretically it can be happen.
But I'm not so interested to fix this issue unless I get more reasonable input for background, frequency, no alternative solution for that something like these...

For `:w` issue. I recommend you to use save`cmd-s`(macOS).
And taking over 1sec for launching ex-mode is too long.
At least from 2nd invocation, it should open instantly.

**Comment by trusktr** [comment]
@t9md I figured out what was causing it! I had some keymaps like this in keymaps.cson:

```cson
    ': t a b n enter': 'atom-vim-like-tab:new'
    ': t a b c enter': 'atom-vim-like-tab:close'
```

So because the keymap uses `:`, if I press `:`, it will wait for the time out before executing the `:` command to open ex-mode.

So, I removed these type of maps and turned ex-mode back on. Woo hoo!
