### ISSUE TITLE
Inline comment text object

### ISSUE THREAD

**Issue by Sergeeeek** [t9md/atom-vim-mode-plus#1076]
Hello, I would like to have a text object for manipulating inline comments such as:

```javascript
/* comment */
```

Is there a default command for that? Or maybe someone has implemented that as a plugin?

Love your work, btw!

**Comment by t9md** [comment]
No there isnt.
Implementing it is not difficult, but I want keep comment text-object always be **linewise**.
If I implement inline-comment text-object and make existing comment text-object works for both line-comments(linewise) and inline-comment(characterwise), it introduce confusion to use it consistently.

Will keep open until I come up with some solution to introduce it without confusion.

**Comment by Sergeeeek** [comment]
I think making it a separate text object makes more sense.

**Comment by t9md** [comment]
Try just now-released v1.33.0.
