### ISSUE TITLE
Relative line number counts screen lines while [Num] + j/k only counts buffer line.

### ISSUE THREAD

**Issue by eric-smithson** [t9md/atom-vim-mode-plus#1079]
<details>
  <summary>debug info</summary>

```json
{
  "atom": "1.27.2",
  "platform": "darwin",
  "release": "17.5.0",
  "vmpVersion": "1.32.0",
  "vmpConfig": {
    "blackholeRegisteredOperators": [],
    "startInInsertModeScopes": [],
    "charactersToAddSpaceOnSurround": [],
    "highlightSearchExcludeScopes": [],
    "flashOnOperateBlacklist": []
  }
}

MacOS High Sierra Version 10.13.4 (17E202)
```

</details>

Not sure if this is working as intended, but the default behavior of moving up/down multiple lines by typing something like `10j` (10 lines down) or `10k` (10 lines up) has a bit of dissonance with how relative line numbering counts screen lines when using soft wrap.

Starting position.
![image](https://user-images.githubusercontent.com/5624783/41251825-1de22270-6d89-11e8-9079-fd93f289e02a.png)

Finishing position after typing `5k`. notice how this is where the relative line number had pegged 9 lines above.
![image](https://user-images.githubusercontent.com/5624783/41251839-2c9439ac-6d89-11e8-8f7e-e067edcecc80.png)

For many people, the whole point of turning on relative line numbering is to be able to quickly determine the result of multi line move commands, this is also inconsistent with how vim determines relative line numbers.

![image](https://user-images.githubusercontent.com/5624783/41252275-a5553a7a-6d8a-11e8-8584-ceafaa0ee6c7.png)

After typing all this I now realize multi line move commands isn't the issue here, it's how relative line numbering increments on soft wrapped lines. If this is working as intended then go ahead an mark this as closed.

**Comment by t9md** [comment]
From your capture 5k moving up 5 bufferlines from line 25 to 20, which is correct behavior.
You can use gk and gj to move in screen-line-wisely.
Plus for inconsistency of relative number, open issue to relative-number package repo. Vmp is irrelevant.
