### ISSUE TITLE
Error with selection begin/end that are outside the screen

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#109]
First, a repro:

```
// need 2+ lines at the beginning

{






























// enough lines to overflow the editor view






// cursor on this line let's say
}

// need 2+ lines at the end
```

Doing `viB` will correctly select the region, then jump to the beginning of the selection (vim doesn't jump). At this point we've scrolled enough that the cursor isn't actually visible. I suspect that there's some atom logic here that hides it.

The problem is now that if we try something like `o` to jump between the beginning and the end of the selection, the cursor isn't actually there. So, for example, if we do escape while the cursor's at the beginning of the selection, the actual cursor's still at the end (so it's not positioned correctly). `o` was just an example. It's might be just the tip of the iceberg.

Gif: 
![vim-2](https://cloud.githubusercontent.com/assets/1909539/12073465/13c13946-b0f0-11e5-8c7b-aa92cf548764.gif)

**Comment by t9md** [comment]
Thanks, nice catch, I'll check to fix this.

**Comment by t9md** [comment]
@chenglou fixed

And I find one more issue, cursor marker position is wrong on `viB` in above example.
Cursor is shown on first column of line 41, but when you escaped to normal mode cursor is put on EOL of line 41. This is cosmetic bug and I should show cursor at EOL of line 41.

By the way I'll handle this bug as distinct issue.
