### ISSUE TITLE
[tree-sitter] Fix function-text-object

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#1095]
Related #1093

TreeSitter is becoming default in near future so I need to support function text-object in TreeSitter.

## What's function text-object

User can select

- body of function(`inner-function`) by `i f`
- whole function(`a-function`) by `a f`

```javascript
function fun(arg) {
  console.log("hello");
}
```

`y i f` yank(copy) `console.log("hello");\n` text
`y a f` yank(copy) whole 3 lines of function text

## How it works in TextMate language-mode

1. Pick fold start row.
2. Then get tokenizedLine for fold start row(line of `function fun(arg) {` text)
  https://github.com/t9md/atom-vim-mode-plus/blob/d8e38e3cc7a5984fcc9ebdd4fbe083ce5aff6a9f/lib/utils.js#L476-L483
3. get newly opened tag for that tokenized line(odd and negative tag) and translate it to scope name
https://github.com/t9md/atom-vim-mode-plus/blob/d8e38e3cc7a5984fcc9ebdd4fbe083ce5aff6a9f/lib/utils.js#L406-L413

4. match list of scope names against known function scope name(e.g `meta.function`)
https://github.com/t9md/atom-vim-mode-plus/blob/d8e38e3cc7a5984fcc9ebdd4fbe083ce5aff6a9f/lib/utils.js#L486-L505

5. if matched, return that fold range as function range.

Above is very rough sketch of what vmp is doing.
Actually it also does extra work to support diffelent style of function declaration.
In folloing GIF of `y i f`(yank innner-function) and `y a f`(yank a-function) for rust function, it select off-cursor position of inner-function body and whole-function-body which spans **TWO** fold.
Which is done by concatnating conjoined fold huristically, which I think TreeStter is further good at to provide such kind of syntax informations than current one.

![extra-work-in-function-to](https://user-images.githubusercontent.com/155205/45337092-5853c280-b5c1-11e8-8dd7-b5f542a9bb51.gif)

## How it can be implemented in TreeSitter parser

I can't find solution currently

- Can I get list of token or list of scopes which starts at particular line?(Seemingly not).
- I want use that list to match against known function scope to determine particular row include **start of function**.
- Is it possible for the first place in TreeSitter?

@maxbrunsfeld 
Could you kindly help me by commenting on how I can implement this in TreeSitter?
I tried to implement it in TreeSitter but I couldn't find good solution for now.

**Comment by Aerijo** [comment]
> Can I get list of token or list of scopes which starts at particular line?

I believe you can ask for the node of a given Point. That node can then provide it's parent, etc., until you reach the root. There may already be an API method to get an array of node types, but I don't know it.

> I want use that list to match against known function scope to determine particular row include start of function

[This is the definition of a function in JS](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/grammar.js#L553-L559) with Tree-sitter. I don't know what part you'd consider the start of it, but  you could look for the start Point of the `function` node for the start row.
