### ISSUE TITLE
Can't j to the last line

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#110]
`j` gets stuck at the before-last line.

**Comment by t9md** [comment]
Pls put example text content

**Comment by chenglou** [comment]
Any text content that spans many lines will do actually

**Comment by t9md** [comment]
Isn't it behavior described in #56?
If so, its spec of vim-mode-plus.
vim-mode-plus change meaning of EOF(last position in buffer cursor can put at)..

This make compatible to pure Vim and internally allow me to eliminate lots of border check code.

**Comment by chenglou** [comment]
Ah I see. Yeah the last line is elf in my repro. Alright then, thanks!

**Comment by t9md** [comment]
OK, I put not for future reference for other people.

- Pure Atom allow to put cursor at last empty line.
- But in vim-mode-plus, not allow to cursor at last empty line.
