### ISSUE TITLE
This is a feature request, not a bug submission

### ISSUE THREAD

**Issue by linjialiang** [t9md/atom-vim-mode-plus#1100]
> In the pop-up window interface (such as `ctrl-shift-p ctrl-p ctrl-b`), use `ctrl-j` and `ctrl-h` to move up and down

  ![Popup window options](https://user-images.githubusercontent.com/8848263/47767674-a2c70500-dd0f-11e8-970a-9303dfba4a12.png)

> code completion moves up and down using `ctrl-j` and `ctrl-h`

  ![code completion](https://user-images.githubusercontent.com/8848263/47767685-ad819a00-dd0f-11e8-8cef-7711b2c8f656.png)

**Comment by linjialiang** [comment]
> I'm very sorry！
> I don't know whether the request is submitted to you or to atom

**Comment by linjialiang** [comment]
> @t9md  I'm very sorry！
> I don't know whether the request is submitted to you or to atom

**Comment by t9md** [comment]
Actually, your question is not vim-mode-plus related, but I will help you this time.
You can set below in your `keymap.cson`

Note: I use `ctrl-k` and `ctrl-j` to move up/down in menu items. You can replace whichever key you want.

```coffeescript
# When autocomplete plus pop-up active in insert-mode
'atom-text-editor.vim-mode-plus.insert-mode.autocomplete-active':
  'ctrl-k': 'core:move-up'
  'ctrl-j': 'core:move-down'

# In select-list such like fuzzy-finder
'.select-list atom-text-editor':
  'ctrl-k': 'core:move-up'
  'ctrl-j': 'core:move-down'
```

For further information, read [keymap in depth](https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/).

**Comment by linjialiang** [comment]
> @t9md Thank you very much for your help

**Comment by linjialiang** [comment]
> I think atom itself caused this, but I think it should be solved. Can you continue to help me?Thank you very much!

**Comment by t9md** [comment]
Sorry, I cannot help you further. Lean Atom or ask in Atom Slack channel.

**Comment by linjialiang** [comment]
@t9md In fact, I've been blocked from the atom website
