### ISSUE TITLE
Update overwrites custom keybindings

### ISSUE THREAD

**Issue by jasmith79** [t9md/atom-vim-mode-plus#1107]
Just updated `vim-mode-plus` to find that all my modifications to `keymap.cson` have vanished. 

Fortunately I have a back up. 

Unfortunately, this is a pretty big issue. If me modifying the package's `keymap.cson` was not the correct way to do this, I haven't seen anything in the README or wiki that would tell me the correct way/tell me not to.

How do I avoid this problem in the future?

**Comment by t9md** [comment]
<img width="615" alt="_and_menubar_and_sic_md_ ___github_memo" src="https://user-images.githubusercontent.com/155205/48589613-997ca000-e97f-11e8-85e5-2346824e2f6b.png">


You should not update vim-mode-plus's kemap directly.
You have your own `keymap.cson` which can be opened from menu.
This is super super basic of Atom editor, not vim-mode-plus.
