### ISSUE TITLE
TextObject Pair range is not consistent to Vim when its inner `vi(`, `vi[` etc.

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#111]
![text-object-pair-range-not-consistent](https://cloud.githubusercontent.com/assets/155205/12073890/e0e220c4-b178-11e5-8fa0-2698a4af1498.gif)

This is bug,

##  start position of range:

When opening char is only text in buffer line, start position should be column 0 of **next line**.
But currently it is set to EOL column of line where opening char found.
When you `o` to reverse selection then `escape` cursor position is put on EOL(its bad).

## end position of range:

When closing pair is found at beginning of line, end point should be set to EOL of **previous line**.
This bug also cursor marker position shown at incorrect position.

I think don't have to fix cursorStyleManager's logic.
Just fix to Pair text-object return correct range.

**Comment by t9md** [comment]
Still not yet perfect compatibility, but reasonable difference at least current internal submode handling.
I'll look into this after I reconsider auto submode detection for visual-mode.

I'll treat it in distinct issue in future.

**Comment by bendc** [comment]
FYI, `vi[` and `vi{` don't work at all on a French (Belgian) keyboard (but `vi(` does work). I imagine it's because of the key combinations needed for writing `[` and `{`.
