### ISSUE TITLE
activate-blockwise-visual-mode tab

### ISSUE THREAD

**Issue by joonro** [t9md/atom-vim-mode-plus#1114]
Hi,

It seems activate-blockwise-visual-mode does not work on a tab. For example, if I have the following lines:

```
            test
            test
            test
            test
```

When the cursor is on the first `t`, I can press `ctrl+v` to got into the blockwise-visual-mode. But if my cursor is on one of the tabs before `t`, pressing `ctrl+v` just get me into visual mode it seems. I'm using soft tabs FYI.

<details>
  <summary>debug info</summary>

```json
{
  "atom": "1.34.0",
  "platform": "win32",
  "release": "10.0.17763",
  "vmpVersion": "1.36.0",
  "vmpConfig": {
    "ignoreCaseForSearch": true
  }
}
```

</details>

Execute `Vim Mode Plus: Clip Debug Info`(which write info to clipboard) then paste here.

Read and check all "Checklist" below.

# Checklist

You have to check all before open issue.

- [X] Provide your environment info clipped by `Vim Mode Plus: Clip Debug Info` command.
- [X] Try with latest Atom and latest vim-mode-plus.
- [X] Pick a descriptive and non-ambiguous subject
- [X] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [X] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [X] Include real use case so that maintainer can understand "why" you need help.
- [X] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).
- [X] If keybinding issue, Read [this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).

**Comment by t9md** [comment]
Maybe you have enabled AtomicSoftTab, I strongly recommend to disable it since it's really confusing.
Plus, I think you really are visual-block-mode, you can check at right-bottom corner of the status bar which indicates current mode.

![image](https://user-images.githubusercontent.com/155205/51791345-de754c00-21e4-11e9-807b-025d43e06559.png)

**Comment by joonro** [comment]
Thank you - unchecking `AtomicSoftTab` solved the issue. And I always disliked this behavior and I did not know how to disable it - so thank you very much!!
