### ISSUE TITLE
How to set motion speed with  h j k l?

### ISSUE THREAD

**Issue by bohdandrahan** [t9md/atom-vim-mode-plus#1116]
Is there any way to make cursor move faster?

**Comment by keevan** [comment]
> Is there any way to make cursor move faster?

Hey @bohdandrahan, you should be able to adjust this via your system (look for keyboard repeat delay/interval), but as it is a system configuration change, it's going to affect more than just your editor.

Here are settings I've set under Ubuntu, but your system might be different so you might have to look for a way to do that.
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 30
gsettings set org.gnome.desktop.peripherals.keyboard delay 250

Hope it helps

**Comment by bohdandrahan** [comment]
@keevan,
Thank you, this solution indeed helped improve the speed!
I found it even more useful as the backspace key became more sensitive and rapid as well, and in my opinion it is much better after your brain adjust to it.
