### ISSUE TITLE
keymap for ctrl-o/ctrl-i not working on Linux Atom

### ISSUE THREAD

**Issue by cotterjd** [t9md/atom-vim-mode-plus#1117]
<details>
  <summary>debug info</summary>

```json
{
  "atom": "1.34.0",
  "platform": "linux",
  "release": "4.15.0-45-generic",
  "vmpVersion": "1.34.0",
  "vmpConfig": {}
}
```

</details>

I updated to the latest Atom version (1.34)
and I updated to the latest version of vim-mode-plus (1.36.0)

but my keymaps still don't work for ctrl-i and ctrl-o to move the cursor to previous locations and back again. 

Here's my keymap.cson. I've tried all the commented versions

```'atom-text-editor':
  'ctrl-i': 'cursor-history:next'
  'ctrl-o': 'cursor-history:prev'

#'atom-workspace':
#  'ctrl-i': 'cursor-history:next'
#  'ctrl-o': 'cursor-history:prev'

# ctrl-o opens file
#'.vim-mode:not(.insert-mode)':
#  'ctrl-i': 'cursor-history:next'
#  'ctrl-o': 'cursor-history:prev'

# ctrl-o opens file
#'.vim-mode:not(.insert-mode)':
#  'ctrl-i': 'vim-mode:cursor-history:next'
#  'ctrl-o': 'vim-mode:cursor-history:prev'

# ctrl-o opens file
#'.vim-mode':
#  'ctrl-i': 'vim-mode:cursor-history:next'
#  'ctrl-o': 'vim-mode:cursor-history:prev'

#'.workspace':
#  'ctrl-i': 'vim-mode:cursor-history:next'
#  'ctrl-o': 'vim-mode:cursor-history:prev'

#
#'.workspace':
#  'ctrl-i': 'cursor-history:next'
#  'ctrl-o': 'cursor-history:prev'
```

The following works for my atom on my mac, but only for ctrl-o, not for ctrl-i
```'atom-workspace':
  'ctrl-i': 'cursor-history:next'
  'ctrl-o': 'cursor-history:prev'
```

The keystroke seems to be registering according to the pic, but it's not doing anything

![csonmap](https://user-images.githubusercontent.com/2576700/53064064-0d9d7700-348c-11e9-86d4-207d21d8df56.png)

**Comment by t9md** [comment]
Have you installed cursor-history package? It's maintained separately.

**Comment by t9md** [comment]
Btw you can simply test if the command works or not by invoking that command from command-palette.
If it didn't work, it would NOT keymap issue.

**Comment by cotterjd** [comment]
installed cursor-history package. Works now. Thank you so much.
