### ISSUE TITLE
Cursor ends up on the last line after a multiline yank

### ISSUE THREAD

**Issue by Yakimych** [t9md/atom-vim-mode-plus#1122]
Execute `Vim Mode Plus: Clip Debug Info`(which write info to clipboard) then paste here.

Read and check all "Checklist" below.

# Checklist

You have to check all before open issue.

- [x] Provide your environment info clipped by `Vim Mode Plus: Clip Debug Info` command.
<details>
  <summary>debug info</summary>

```json
{
  "atom": "1.38.2",
  "platform": "darwin",
  "release": "18.6.0",
  "vmpVersion": "1.36.0",
  "vmpConfig": {}
}
```

</details>
- [x] Try with latest Atom and latest vim-mode-plus.
- [x] Pick a descriptive and non-ambiguous subject
Cursor ends up on the last line after a multiline yank.

- [x] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
Behavior change - cursor should end up on the first line after a multiline yank.

- [x] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
Cursor should end up on the first line after a multiline yank. E.g. if we start on line 1 and press `VjjjY`, the cursor stays on line 4. In vanilla Vim, as well as all emulators I've used before, the cursor stays on line 1.

- [x] Include real use case so that maintainer can understand "why" you need help.
I usually duplicate multiple lines by selecting (e.g. `Vjj`) followed by `YP`. Since the cursor ends up on the last line, this results in the duplicated block ending up just before the last line, rather than before the whole "old" block.

For example, if I were to duplicate the following function with `VjjYP`:
```
function sum(a, b) {
  return a + b;
}
```
I would get the following result:
```
function sum(a, b) {
  return a + b;
function sum(a, b) {
  return a + b;
}
}
```

- [x] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).
Atom 1.38.2, vmp: 1.36.0, macOS Mojave 10.14.5

- [x] If keybinding issue, Read [this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).

**Comment by Yakimych** [comment]
Just saw that this is controllable via setting `stayOnYank: false` in the settings. Closing this.

**Comment by t9md** [comment]
Yes. This is intentional aggressive decision.
You can see others here.
https://github.com/t9md/atom-vim-mode-plus/wiki/DifferencesFromPureVim

**Comment by Yakimych** [comment]
Good stuff, thanks!
