### ISSUE TITLE
[Feature Request] Count for matches of a search

### ISSUE THREAD

**Issue by nwaywood** [t9md/atom-vim-mode-plus#1128]
I use the [highlight-selected](https://atom.io/packages/highlight-selected) package which display the number of matches in the bottom bar when you double click on a word, for example:

![image](https://user-images.githubusercontent.com/3773641/67725790-b0ed5580-fa37-11e9-840b-4dc99311c060.png)

It would be nice if we could see something similar when searching with `/`, `?` and `*`.

I have this set up in my vim to also display which match you are currently at which is extra nice:

![image](https://user-images.githubusercontent.com/3773641/67725870-fad63b80-fa37-11e9-801d-83607d0e7b7d.png)

**Comment by t9md** [comment]
Enable below in vim-mode-plus's setting panel.

[image](https://user-images.githubusercontent.com/155205/67751831-2fb4b380-fa75-11e9-854d-e6ee58aa2fa5.png)

**Comment by nwaywood** [comment]
Awesome thank you! I personally would prefer the information in the bottom bar over in a hover, but at least this option displays the information :)
