### ISSUE TITLE
Escape in Insert Mode during autocomplete requires two keystrokes to exit insert mode

### ISSUE THREAD

**Issue by mbahnmiller** [t9md/atom-vim-mode-plus#1152]
ISSUE: When in insert mode, if the autocomplete is visible, Vim Mode Plus now requires _two_ keystrokes to exit insert mode - one click to exit the autocomplete and one to exit insert mode. This did not use to be the case, and now, I find myself accidentally typing because I'm in still in insert mode, and messing things up and having to undo/fix what I've done.

If requiring two keystrokes is the desired functionality, then please create a preference/setting that allows for putting it how it used to be. That is, to allow a single Escape keystroke to exit normal mode.

Thank you!

---

Execute `Vim Mode Plus: Clip Debug Info`(which write info to clipboard) then paste here.

<details>
  <summary>debug info</summary>

```json
{
  "atom": "1.57.0",
  "platform": "darwin",
  "release": "20.5.0",
  "vmpVersion": "1.36.5",
  "vmpConfig": {
    "automaticallyEscapeInsertModeOnActivePaneItemChange": true,
    "hideCommandsFromCommandPalette": true,
    "keymapBackslashToInnerCommentOrParagraphWhenToggleLineCommentsIsPending": true,
    "keymapCCToChangeInnerSmartWord": true,
    "keymapPToPutWithAutoIndent": true,
    "keymapSemicolonToInnerAnyPairInOperatorPendingMode": true,
    "keymapUnderscoreToReplaceWithRegister": true,
    "keymapYToYankToLastCharacterOfLine": true,
    "setCursorToStartOfChangeOnUndoRedo": true,
    "useSmartcaseForFind": true,
    "useSmartcaseForSearch": true
  }
}
```

</details>

Atom    : 1.57.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1

OS: macOS Big Sur 11.4

Read and check all "Checklist" below.

# Checklist

You have to check all before open issue.

- [x] Provide your environment info clipped by `Vim Mode Plus: Clip Debug Info` command.
- [x] Try with latest Atom and latest vim-mode-plus.
- [x] Pick a descriptive and non-ambiguous subject
- [x] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [x] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [x] Include real use case so that maintainer can understand "why" you need help.
- [x] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).
- [x] If keybinding issue, Read [this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).

**Comment by t9md** [comment]
Sorry for breaking your workflow. See duplicate #1151

**Comment by mbahnmiller** [comment]
Thank you! And thank you for the fast turnaround on that, also!! Can't tell you how much I love Vim Mode Plus and always hope to see new releases!
