### ISSUE TITLE
Duplicating a block of lines using `YP` in visual mode isn't consistent with Vim

### ISSUE THREAD

**Issue by mattalxndr** [t9md/atom-vim-mode-plus#1156]
Execute `Vim Mode Plus: Clip Debug Info`(which write info to clipboard) then paste here.

<details>
  <summary>debug info</summary>

```json
{
  "atom": "1.58.0",
  "platform": "linux",
  "release": "5.15.7-arch1-1",
  "vmpVersion": "1.36.7",
  "vmpConfig": {
    "startInInsertMode": true
  }
}
```

</details>

## Steps to reproduce

1. Put this into a new buffer:

        xxx
        ooo

1. Exit insert mode.
2. Put cursor on first line (`xxx`).
1. `Vj` to select both lines.
2. `YP` to duplicate the block of lines.

## Expected

```
xxx
ooo
xxx
ooo
```

## Actual Result

```
xxx
xxx
ooo
ooo
```

Read and check all "Checklist" below.

# Checklist

You have to check all before open issue.

- [x] Provide your environment info clipped by `Vim Mode Plus: Clip Debug Info` command.
- [x] Try with latest Atom and latest vim-mode-plus.
- [x] Pick a descriptive and non-ambiguous subject
- [x] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [x] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [x] Include real use case so that maintainer can understand "why" you need help.
- [x] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).
        - Arch Linux, KDE Plasma 5
- [x] If keybinding issue, Read [this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).

**Comment by t9md** [comment]
Here is the reason for inconsistency with pure Vim and you can disable it by unchecking `StayOnYank` like the following gif on vmp package setting.
https://github.com/t9md/atom-vim-mode-plus/wiki/DifferencesFromPureVim#config-vmp-stayontransformstring-stayonyank-stayondelete

![image](https://user-images.githubusercontent.com/155205/146111389-43d955cc-7a64-4afa-a59e-73d9f8436eaa.png)

**Comment by mattalxndr** [comment]
> How can I make vmp behave as close to pure-vim's default as possible?

Thank you, very nice
