### ISSUE TITLE
dk not delete empty line if cursor is at empty line

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#118]
Repro:

```
a

b
```

Cursor at second line (empty), do `dk`. This only happens when the second line's empty I think.

**Comment by t9md** [comment]
change subject

**Comment by t9md** [comment]
This is degradation from official vim-mode.

**Comment by t9md** [comment]
This affect all operator like `ck`.
The cause is when cursor is at blank row and operate on `k` direction.
It omit original blank row from operator target(=selection area).
