### ISSUE TITLE
cursor-style-manager throw Uncaught TypeError: Cannot read property 'column' of undefined

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#121]
Reproduce

text

```
AAAAAAAAAAAAAAAAAAAAAAAAA
    aaaaaaa
```

Put cursor on first line column 0 , then `V`.
Add selection on `aaa` with **mouse** by "cmd-drag" throw error.

**Comment by bronson** [comment]
Looks like this has changed a little.  I'm getting `lib/selection-wrapper.coffee:95 Uncaught TypeError: Cannot read property 'isGreaterThanOrEqual' of undefined`

No doubt the underlying issue is still the same.

**Comment by t9md** [comment]
Can not reproduce this issue anymore in current stable, regardless of `editor.showCursorOnSelection` setting value.  
Maybe because of I changed selection property is always saved in `visual-mode` or by change-in-upstream-atom-core part.

```
$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
