### ISSUE TITLE
`I` command doesn't always go to the first non-blank character in the line

### ISSUE THREAD

**Issue by axelson** [t9md/atom-vim-mode-plus#122]
When you are in command mode and press `I` while on a line with text I expect vim-mode-plus to "Insert text before the first non-blank in the line" (from vim docs). Instead it sometimes goes to the very first column on the line (this seems to happen when you are already on the first non-blank character in the line).

This is what happens:
![bad_behavior](https://cloud.githubusercontent.com/assets/9973/12181439/4696b23a-b526-11e5-9320-48df6917115b.gif)

This is what I expect to happen:
![what_is_expected](https://cloud.githubusercontent.com/assets/9973/12181477/8568f428-b526-11e5-8648-bc88d612bc34.gif)

**Comment by t9md** [comment]
Thanks.
This is very stupid degradation from vim-mode.
It was exists from vim-mode-plus's initial publish.

I couldn't believe why I think I can remove `@editor.moveToBeginningOfLine()`.
I checked commit history, but I couldn't remember situation.
I believe I simply was careless.

Thanks for catching this.
I'll release patch version 0.14.1 from now.

**Comment by axelson** [comment]
Thanks for the quick fix!
