### ISSUE TITLE
Unclear on the operation of VMP surround

### ISSUE THREAD

**Issue by MatthewMDavis** [t9md/atom-vim-mode-plus#125]
I'm incredibly dependent on Tim Pope's surround plugin at this point, and that's probably the main thing keeping me from moving over to Atom full-time. Your surround works better than the surround add-on for vim-mode, when it's working, but most times I can't get it to perform the operation.

Most commonly, "ysiw )" (surround inner word with parentheses) and the like, and just fail. The bottom of the cursor (but not the whole thing) will blink, and it'll move to one end of the word as if it's recognized the text object I gave it, but nothing will happen.

Is there any documentation on the surround functionality, aside from the list of the keymappings? It would be useful to know whether I'm coming up against limitations of the system or am misunderstanding what I'm supposed to be doing.

**Comment by t9md** [comment]
Whats the version of Atom, vim-mode-plus, whats your keymap and other setting.
Surround should be work in every case.
If you experienced its work or not work occasionally depending on situation, its BUG should be fixed.
But its maybe your keystroke is to slow to timeout pending keymap determination by Atom keymap system give up to match.
So to investigate further observe keybindig resolver by pressing `cmd-.` or alike.
And another thing you try is map `vim-mode-plus:surround` to more shorter keymap like to `S` in normal mode which reduce keystroke you have to type.
Or you can try to map `S` to `vim-mode-plus:surround-inner-word`, if most of your use case is targeting to  innner-word.
