### ISSUE TITLE
I'd like to be able to remap my `escape` key.

### ISSUE THREAD

**Issue by RafaelCosman** [t9md/atom-vim-mode-plus#130]
Maybe use one of these: https://github.com/atom/vim-mode/issues/334?

**Comment by t9md** [comment]
Pls explain what you want to do.

**Comment by crshd** [comment]
Uhm... how about:

``` cson
'atom-text-editor.vim-mode-plus:not(.normal-mode)':
  'j k': 'vim-mode-plus:activate-normal-mode'
```

And, as an added bonus:
``` cson
'atom-text-editor[mini]':
  'j k': 'core:cancel'
```
Works like a charm, no problem whatsoever.

**Comment by t9md** [comment]
@crshd Thanks for answering.

**Comment by john1625b** [comment]
This works for me
#keymap.cson

'atom-text-editor.vim-mode':
  'j k': 'vim-mode:reset-normal-mode'

Sidenote: I also like to have k j binded to escape, is there a way to have multiple bindings per command?

**Comment by gcman105** [comment]
I like to use **jj** instead of **jk**, so I used:

`'atom-text-editor.vim-mode-plus:not(.normal-mode)':
  'j j': 'vim-mode-plus:activate-normal-mode'`

and:

`'atom-text-editor[mini]':
  'j j': 'core:cancel'`

All seemed fine until I go into visual select with **Shift-V** the trying to move down a few lines with multiple **j**'s exits **visual select**

**Comment by gcman105** [comment]
I just used:

`'atom-text-editor.vim-mode-plus.insert-mode':`

instead of:

`'atom-text-editor.vim-mode-plus:not(.normal-mode)':`

and all seems okay now.

**Comment by gcman105** [comment]
My final try is:

```
'atom-text-editor.vim-mode-plus.insert-mode':
  'j j': 'vim-mode-plus:activate-normal-mode'
  'j k': 'vim-mode-plus:activate-normal-mode'

'atom-text-editor[mini]':
  'j j': 'core:cancel'
  'j k': 'core:cancel'
```

Seems to be working okay and has multiple bindings @john1625b

**Comment by imgovind** [comment]
@gcman105 Your solution works, where I can just type `j j` and it would escape the insert mode, but when I type `j` it takes a while, even for the first `j` to appear on the screen.

How can I avoid this?

**Comment by dustMason** [comment]
@imgovind i'm seeing the same thing, but note that the following letter appears immediately as long as its not a `j`. ie, typing `jo` exhibits a little pause but you can type without stopping

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/issues/670#issuecomment-277502647

This comment answer the delay, you can shorten this delay, but this also mean, you have to type `jk` within timeout(so gonna be difficult to escape by `j k`).

Also Atom keymap config can express keyup/keydown differently by using special `^` modifier syntax, using this, you can improve `jk` as `escape` further(I believe so).
I myself haven't try though, here is the hint for this syntax.


Blog when its released.
http://blog.atom.io/2016/04/12/atom-1-7-and-1-8-beta.html#keyup-keystroke-support-in-keybinds

Original PR is this.
https://github.com/atom/atom-keymap/pull/113

**Comment by phzbox** [comment]
Here's how I did it to trigger escape on "jk". It works by triggering on the "k" and checking if the previous key was "j". If you trigger on the "j" first then it waits for the next key to know which mapping to run.

I'm definitely not an expert on the subject, learn more on this thread:
(From this thread: https://github.com/atom/vim-mode/issues/334).

In your keymap file:
```coffee
'atom-text-editor.vim-mode-plus.insert-mode':
    'k': 'exit-insert-mode-if-preceded-by-j'
```

In your init file:
```coffee
atom.commands.add 'atom-text-editor', 'exit-insert-mode-if-preceded-by-j': (e) ->
    editor = @getModel()
    pos = editor.getCursorBufferPosition()
    range = [pos.traverse([0,-1]), pos]
    lastChar = editor.getTextInBufferRange(range)
    if lastChar != "j"
        e.abortKeyBinding()
    else
        editor.backspace()
        atom.commands.dispatch(e.currentTarget, 'vim-mode-plus:activate-normal-mode')
```

**Comment by t9md** [comment]
So `k j` to escape insert-mode? How do you insert "kj" string then?

**Comment by phzbox** [comment]
For me it's not an issue, I never have to type "kj". But if I had to, either I'd put a delay "k <wait .5s> j" or I'd just type k<esc>aj. I think it's about trade off and it's been working fine for me for the last 10 years, but I see how it may not work for everyone.

**Comment by t9md** [comment]
OK, for me, I cannot accept if I can't insert`kj`  by `kj` keystroke.
Mine is here as same as others.
```
'atom-text-editor.vim-mode-plus.insert-mode':
  'j k': 'vim-mode-plus:activate-normal-mode' # jk to escape
```

I'll experiment with atom's keyup/down modifier from now and put update here.

**Comment by t9md** [comment]
Here is the collection of example I've evaluated.

- The notation `a ^a` means "keydown of a then keyup of a"
- The notation `a j ^a` means "keydown of a then keydown/up j then keyup of a"
- If you explicitly express `^a` notation, single `a` means both keydown/keyup.

```coffeescript
  # Case-1: `j j`
  # Good: simple
  # Bad: delay when you insert `j j`
  'j j': 'vim-mode-plus:activate-normal-mode'

  # Case-2: `j k`
  # Good: simple
  # Bad: delay when you insert `j k`
  'j j': 'vim-mode-plus:activate-normal-mode'

  # Case-3: `cmd` key only, press command then release, keydown then keyup command
  # Good: simple, single key, no delay when you insert characters in insert-mode.
  # Bad: Anything?
  'cmd ^cmd': 'vim-mode-plus:activate-normal-mode'

  # Case-4: jk, kj arrpegio, choard
  # Good: jk or kj pressing simultaneously works.(arpeggio, chords)
  # Bad: delays to insert `jk` or `kj`
  'j k ^j': 'vim-mode-plus:activate-normal-mode'
  'k j ^k': 'vim-mode-plus:activate-normal-mode'
```

**Comment by t9md** [comment]
But I mainly use `ctrl-[` which is default of vmp and pure Vim!

**Comment by emadbaqeri** [comment]
In settings press [Open Config Folder] to open all your atom configurations.
go to packages folder look for vim-mode-plus folder and over there keymaps.

'atom-text-editor.vim-mode-plus':
  'escape': 'vim-mode-plus:reset-normal-mode'
  'ctrl-c': 'vim-mode-plus:reset-normal-mode'
  'ctrl-[': 'vim-mode-plus:reset-normal-mode'

# all except normal
# -------------------------
'atom-text-editor.vim-mode-plus:not(.normal-mode)':
  'escape': 'vim-mode-plus:activate-normal-mode'
  'ctrl-[': 'vim-mode-plus:activate-normal-mode'

and over here change escape to ---> 'j k'  <-----
