### ISSUE TITLE
`viB` then `V` deselects the selections

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#131]
Repro:

```
{
a
b // cursor here
}
```

`viB` works fine, `V` is expected not to deselect region.

This issue doesn't happen when one of the brackets is on the same line as the letter, e.g. this is fine:

```
{a
b // cursor here
}
```

**Comment by t9md** [comment]
Yes, this behavior difference from pure Vim is where I couldn't decided how should be.

The first text you put is `linewise` selection, next text is `characterwise` selection.
When `V` in `linewise` selection it escape from visual-linewise.
This is what happening.

Currently when text-object is selected, its final submode(linewise, characterwise) is automatically detected from selection range and shift submode if needed.
The above behavior diff is have root in this design.

In pure vim when you select paragraph with `vip`, it shift submode to `characterwise` to `linewise`.
But Vim is not consistent for this shift, some text-object not shift submode even its slection range is not diff from linewised selection range.

Of course I don't think current my implementation is OK, but don't want to fix specifically only for `viB`.
Let me think about how it should be...

Btw, any problem when `viBV` return to normal-mode? Is that real situation you frequently face and frustrated about it?

**Comment by chenglou** [comment]
> Btw, any problem when viBV return to normal-mode? Is that real situation you frequently face and frustrated about it?

Well, I guess I'd like the behaviour to be consistent across `viBV` usages. I usually press `V` to go to linewise-mode and then select a few more lines up and down. In the latter example in my issue above this works fine, in the former it deselects, which prompts me to do `viB` again.

**Comment by t9md** [comment]
Got it! Good expression about how it should be.
I'll take your suggestion.
But your rule can't apply to vip, I'm thinking about adding `Textobject::changeSubmode` like  property to control whether its allow or disallow to shift submode automatically.

**Comment by t9md** [comment]
I'll close this in favor of #135

**Comment by t9md** [comment]
Fixed, covered your use case.
Thanks for pointing out to me.
