### ISSUE TITLE
Easymotion

### ISSUE THREAD

**Issue by slavaGanzin** [t9md/atom-vim-mode-plus#134]
Hi, @t9md, thanks for awesome work.
I want to implement some features from vim-easymotion and merge it. Any thoughts?

**Comment by t9md** [comment]
Not the same but there is some package similar to eazy-motion.
- [my smalls](https://atom.io/packages/smalls)
- [jumpy](https://atom.io/packages/jumpy)

Currently I don't think those feature should provided out side of vmp.
Maybe for better integration to vmp, I can enhance my smalls package.

**Comment by slavaGanzin** [comment]
> Rapid cursor positioning across any visible chars with search and jump.
Easymotion allow to search all file length. That's a deal.

And I just like interface.

I think you are right in not bundling this functionality. I'll look at smalls(tried before), thanks
