### ISSUE TITLE
Auto disable IME in normal mode?

### ISSUE THREAD

**Issue by hh9527** [t9md/atom-vim-mode-plus#148]
VIM already support this feature for many years.

When switch to normal mode from insert/replace mode via ESC, the IME should be disabled automatically, and re-enable IME when go back to inser/replace mode.

Is it possible to support this feature in atom/vim-mode-plus? It is very important feature for writing documents in non-western languages.

**Comment by t9md** [comment]
I know it's very important feature of course(I'm Japanese using IME).
But currently not supported.
But unless atom core provides the way to disable/enable IME, I won't try to implement this feature.

The options you can choose is to find the way
 - disable/enable IME with certain keyboard trigger via your using IME's configuration.
 - use more generic keyboard customization tool to link certain keytype trigger IME disable/enable event.

If you use Mac, keyremap4Mac can do the trick, I believe.

Related.
https://github.com/atom/atom/issues/1092

**Comment by hh9527** [comment]
I do have a quick & dirty but workable patch to resolve this problem:
```coffee
# file: lib/node-manager.coffee
  updateEditorElement: ->
    # update input.hidde-input type to 'password' to prevent IME 
    inputElement = @editorElement.rootElement.querySelector('.hidden-input')
    inputElement.setAttribute('type', (@mode is 'normal') and 'password' or '') if inputElement
    # end of my code

    for mode in ['normal', 'insert', 'visual', 'operator-pending']
      @editorElement.classList.toggle("#{mode}-mode", mode is @mode)

```

Will you merge it?

**Comment by t9md** [comment]
Seems great!, will evaluate and investigate what this patch really do.

Thanks for great idea.
Will handle different issue.

**Comment by hh9527** [comment]
thank you for this great project, happy Spring Festival!
