### ISSUE TITLE
 Delete word (dw) consumes LF linebreaks

### ISSUE THREAD

**Issue by cswartzvi** [t9md/atom-vim-mode-plus#150]
Hi, I wanted to report a really frustrating bug that appears to be inherited from vim-mode (atom/vim-mode#550 ).

When using `dw` to delete the last word of a line ending with a _LF linebreak_ the linebreak is consumed and the next line is appended to the current line (see below).
![deleteword-lf-lines](https://cloud.githubusercontent.com/assets/1111348/12864335/5d72ce4e-cc55-11e5-9a77-8d75022d2de7.gif)

However if you switch to _CRLF linebreaks_ the behavior matches that of vim, as shown below.
![deleteword-crlf-lines](https://cloud.githubusercontent.com/assets/1111348/12864336/5f934532-cc55-11e5-98ea-73464c07f211.gif)

It's such a small triviality, but I can't tell you how many times it has tripped me up.

BTW, I love what you're doing with this package. Thanks for all your hard work!

**Comment by t9md** [comment]
From Vim help
Following special behavior for `cw` and `w` has to be implemented.  
Partially already have been implemented, but complicated in implementation.  
I will rewrite that part to solve this issue completely.  

```
Special case: "cw" and "cW" are treated like "ce" and "cE" if the cursor is
on a non-blank.  This is because "cw" is interpreted as change-word, and a
word does not include the following white space.  {Vi: "cw" when on a blank
followed by other blanks changes only the first blank; this is probably a
bug, because "dw" deletes all the blanks}

Another special case: When using the "w" motion in combination with an
operator and the last word moved over is at the end of a line, the end of
that word becomes the end of the operated text, not the first word in the
next line.
```
