### ISSUE TITLE
[Feature request] better wrapper for the status bar display?

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#152]
My status bar is getting full and I was disabling a few things I didn't look at often, vim-mode-plus' mode indicator being one of them. However the element `#status-bar-vim-mode-plus` is wrapped inside an `.inline-block` div, and I couldn't disable that one with CSS selector (unless there's some parent element selector I didn't know). So I was wondering if we could either remove that inline-block element or have an id on it or something.

Really small request though. Thanks for considering =).

**Comment by chenglou** [comment]
Thanks!

**Comment by t9md** [comment]
OK what you want is inline-block container's ID right to completely save space for vmp status information.
Confirmed with following `uses.less`
```
#status-bar-vim-mode-plus-container {
  display: none;
}
```

**Comment by t9md** [comment]
Use this info, sorry I changed selector for status-bar at some point.

https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#hide-vmps-statusbar-information-completely
