### ISSUE TITLE
Search next leaves multiple words highlighted simultaneously - for a brief moment.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#153]
If you have the following text:
```
hello
hello
hello
```

Search `/` for `hello` and hit `n` very quickly. You will see that two different `hello` words are highlighted at the same time for a few hundred milliseconds. This makes the editing experience feel unreliable.

**Comment by crshd** [comment]
Man, I practically need to hold down `n` to even see this.

Nonetheless, the setting `flashOnSearch` should actually do something. It's defined, but not used anywhere currently.

The above commit will toggle the flash depending on the setting. Unfortunately, you'll also lose the flash on the **current** search.

**Comment by t9md** [comment]
@crushed Thanks for catching `flashOnSearch` is ignored. I've mistakenly removed conditional check for this.


@jordwalke I think I'm understanding what you pointed, you mean highlight word should be done for single word at the given moment right?
I've once did , so this is kind of degradation.
I removed in the process of another refactoring for code simplicity.
Will try to revert that mechanism keep track of highlight marker and clear it before highlighting next.

**Comment by jordwalke** [comment]
Yes that sounds right. This used to work wonderfully but now it doesn't
