### ISSUE TITLE
No way to do search-and-replace

### ISSUE THREAD

**Issue by raffomania** [t9md/atom-vim-mode-plus#157]
Since vim-mode-plus overrides atoms traditional ctrl-f shortcut, there is no way to replace all occurences of a word in a buffer.

I searched the documentation for similar keybindings and only found the ReplaceModeBackspace operation, triggered by ctrl-h, but pressing that shortcut did nothing for me.

Is there an obvious way to do this that I'm missing?

**Comment by t9md** [comment]
You use Windows?
C-f bound to find-and-replace and want to keep native kybind from overridden from vmp?

Whats the c-h of ReplaceModeBackspace thing, how this related to this topic?

**Comment by raffomania** [comment]
I'm using Arch Linux, but the behavior should be the same on all systems, shouldn't it?

What I'm trying to find is the "vim way" of doing search-and-replace; When in insert mode, I can still do C-f and be happy, but in command mode there's no such thing. In traditional vim you would do `:%s/foo/bar`, but there's no such thing in vmp. That's why I thought replaceModeBackspace could have something to do with it.

**Comment by t9md** [comment]
Yea ideally behavior should be same across all platform but if you report *issue* I need always platform you use.

There is no vim way like `:%s` in vim-mode-plus and no motivation to support it.
To workaround your issue please set manual keymap to invoke find-and-replace.
`c-f` is overridden by cim-mode-plus, removing or platform dependent keymapping trigger another issue popping up to ask `c-f` to map scroll page down by default.

And I still cannot understand why you think replacemodeBackspace is relating this topic, you want to use `c-h` for keymap?
