### ISSUE TITLE
Create BountySource to allow people to support/donate financially.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#16]

**Comment by t9md** [comment]
I don't have well understanding of BountySource for now.
Is this the service letting people vote some feature to collect money?
I don't want people push me to develop feature. I want to go direction I decided to go.

Maybe I misunderstood the characteristics of this service, but I dont have such motivation for now.

**Comment by jordwalke** [comment]
It can be used to just pledge general support. Sometimes people can put money on particular issues as well, which are given when the issue is closed. In either case, no one pushes anyone in my experience.

**Comment by t9md** [comment]
OK thanks, I'll check later nice suggestion, thanks!

**Comment by bronson** [comment]
There's also Patreon (I use it to send $4/mo to AvE).  Not sure which is better.  Agreed, I'd contribute to vim-mode-plus too, whatever direction it wants to go in.

**Comment by t9md** [comment]
I created team

https://www.bountysource.com/teams/atom-vim-mode-plus

Also new service Salt page are created automatically I believe.

https://salt.bountysource.com/teams/atom-vim-mode-plus

I totally have no idea how is the standard way for this kind of personal project.
So hope give me advice if you guys have any insight of this service.

**Comment by bronson** [comment]
:zap: :clap: :+1:

**Comment by t9md** [comment]
Thanks for your first bounty!
I still is struggling to integrate issue tracker to BountySource page, I don't like UI of this service very much :angry: 

Anyway, I will close this issue. Thanks @jordwalke for suggestion and @bronson for your encouraging direct contribution!
