### ISSUE TITLE
Is look-behind search supported?

### ISSUE THREAD

**Issue by kWhittington** [t9md/atom-vim-mode-plus#164]
Hi guys,

I've been trying (and failing) to find any documentation on look-behind search. I've tried the Perl-style (`(?<=)`) and the `\zs` and `\ze` flags but they do not seem to work.

Thanks in advance!

**Comment by t9md** [comment]
You can input regexp which javascript supported.

See: [this URL](http://stackoverflow.com/questions/7376238/javascript-regex-look-behind-alternative.)

* `editor\.(?!get)`: Match to `editor.abc`, but not match to `editor.get` 
* `editor\.(?=get)`: Match to `editor.get`, but not match to `editor.abc`
