### ISSUE TITLE
Scrolling re-highlights search.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#165]
After clearing search `vim-mode-plus:clear-highlight-search`, scrolling rehighlights the search. It should remain unhighlighted. This should be easy to repro.

**Comment by t9md** [comment]
Already fixed and released in v0.21.2 when you commented about tab change rehighlight in #158.
Did you updated to latest version?

**Comment by t9md** [comment]
Already fixed and released in v0.21.2 when you commented about tab change rehighlight in #158.
Did you updated to latest version?

**Comment by jordwalke** [comment]
Ah, sorry - my Atom wasn't detecting package updates.
