### ISSUE TITLE
Hitting enter on wrapped text does not move cursor down.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#166]
In this markdown file, when text is wrapped, the cursor does not move at all when hitting return.

![screen shot 2016-02-19 at 10 49 57 pm](https://cloud.githubusercontent.com/assets/977348/13195028/27c8ba0e-d75b-11e5-8807-a69fbaaa8d3f.png)

**Comment by jordwalke** [comment]
The circle in the gutter shows that the line is wrapped.

**Comment by t9md** [comment]
Although this is bug, I might postpone to fix this bug.
Not only this bugs, there are so many bugs, caveat in soft-wrapped support.

I can fix each bug on soft-wrapped one-by-one.
But first want to define strategy, principle about how and how much(which commands) soft-wrap text is supported.

Supporting soft-wrapped is hard(not impossible, but need many additional code) for some command in spite of use case is limited.

**Comment by t9md** [comment]
Forget about above comment.
I checked the cause and I think how to fix is clear, so try to fix as example.
