### ISSUE TITLE
Copy in insert mode fails first time and then copy whole line

### ISSUE THREAD

**Issue by slavaGanzin** [t9md/atom-vim-mode-plus#167]
Self descriptive gif
![out](https://cloud.githubusercontent.com/assets/1011721/13198917/3f3194c2-d81e-11e5-8c18-49bbdb8df9c9.gif)

**Comment by t9md** [comment]
Whats the issue?
Need consice explanation.

**Comment by slavaGanzin** [comment]
Sorry for unclear.

When I select text with visual mode and yank it, all works as it should.
But when I select text with mouse in insert mode, first time yank do nothing and second time it yanks row and not selection.

**Comment by t9md** [comment]
This is why

- When you invoke operator(like `yank`) from non-visual-mode
- first `yank` put mode into `operator-pending` mode
- 2nd `yank` put `yank` operation into operation-stack, when two identical operation is pushed to stack, it works as linewise(like `yy`, `dd`, `gugu` and so one).
- So your operation is simply treated as `yy`.

So not bug, and directly invoking commands from `insert-mode` is a bit b peculiar operation.
I have no motivation to make it all vim-mode-plus command works properly in `insert-mode`.
Some commands might work but it not intended to be used directly from insert-mode.

**Comment by slavaGanzin** [comment]
Thanks for such clarification. Great! Now I don't want this to be 'fixed'.

Is it possible in atom to trigger visual mode on selection? Like in vim?

**Comment by t9md** [comment]
What operation you want to achieve?
I need keystroke sequence(by step-by-step) and buffer result.

**Comment by slavaGanzin** [comment]
In insert mode: selecting text using mouse - triggers visual mode.

But really, I don't care if this isn't a bug.

**Comment by t9md** [comment]
Understood.
But don't want to support it.

**Comment by slavaGanzin** [comment]
Clever decision. Thanks for clear position.
