### ISSUE TITLE
Add space when surround

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#171]
PR #169 

Request is when surround with opening pair chars(`({[`), it add padding spaces before and after the pair char.

e.g. when surround `abc`.

- `(` result in `( abc )`.
- `)` result in `(abc)`.

This is original surround.vim supported feature.

I don' need this behavior and I don't want to make it default.
Adding space or not before/after parenthesis is depending on coding style.
So I will try to provide this feature enhancement through configuration option.

**Comment by ypresto** [comment]
> configuration option

:+1:

**Comment by t9md** [comment]
Better setting name than current `addSpaceOnSurroundChars`?
