### ISSUE TITLE
support for asymmetric pairs

### ISSUE THREAD

**Issue by Byron** [t9md/atom-vim-mode-plus#172]
### Motivation

VMP is great and improves efficiency while coding, but requires plenty of practice to be useful. In pair programming, it can be good for one part of the pair, but be prohibitive to another.

Currently VMP takes over Atom as long as the plugin is active, and there should be a way to use the command-palette to toggle it on or off. That way, it's easy to provide each developer an environment they are most comfortable in.

### Suggested Implementation

Here is an attempt to analyze the feature.

* VMP is *active* after loading the plugin to not alter expected behavior.
* given VMP is *active* and the toggle command is executed
 - state changes
   * deregister all commands, except for the toggle
    * deregister all keybindings, menu-items, context-menu items
    * *?* explicitly keep services to not confuse dependent plugins *?*
 - VMP is now *inactive*
* given VMP is *inactive* and the toggle command is executed
 - state changes
   * register all commands, keybindings, menu-items, context-menu items
  - VMP is now *active*

### RFC

Without this being anything like a fully-fledged RFC, something that comes to my mind is an additional command reachable through the command-palette, which allows to toggle VMP on or off without deactivating the plugin.

What do you think of this feature. Is there anything you see makes it difficult to implement, or is this issue missing anything of importance ?
Also do you think such a feature would be reasonably easy to implement, to maybe even allow others to chime in ?

Thanks a lot for the time and dedication you put into VMP !

**Comment by t9md** [comment]
You want to quickly toggle vmp enable/disable in pair programming situation?
Atom natively provides Disabling/enabling via setting-view.
This is completely out-of-scope of vmp.
vmp should focus core editing experience.

**Comment by Byron** [comment]
Further thinking about it, I also came to believe that it will be easiest to have another plugin do that, if more convenience is desired; i.e. just executing a single command to toggle another plugin on or off.
The benefit of such a solution would be that atom will do all the work of registering and deregistering everything related to VMP.
