### ISSUE TITLE
vim-mode-plus:mode-line-up/down no longer exist?

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#176]
I discovered these two commands from [this wiki section](https://github.com/t9md/atom-vim-mode-plus/wiki/Keymap-example#keymap), but it seems that as of today (0.21.3) this command's no longer there?

**Comment by t9md** [comment]
are you saying about
```
'atom-text-editor.vim-mode-plus.visual-mode':
  'ctrl-k': 'vim-mode-plus:move-line-up'
  'ctrl-j': 'vim-mode-plus:move-line-down'
```

part?
if so see #145.
I need to update keymap example though...

**Comment by chenglou** [comment]
Ahh yes, thanks! That one only works in visual mode though.

**Comment by t9md** [comment]
Yes atom core already provide linewise movement up/down. If you want normal-mode behavior you can worrkaround to mapping it in normal-mode.
My move-selected-text package is big and still early phase, I wanted to start minimum feature.
