### ISSUE TITLE
Undo/Redo should *never* leave text selected.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#18]
`atom-vim-mode-plus` does a better job than `vim-mode` at avoiding selection after an undo/redo. However, I found a critical bug in `atom-vim-mode-plus` where text is left highlighted after redo/undo.

Repro:

Use a `JavaScript` snippet  (`for`, then `tab`).
Instead of typing in the placeholder of the snippet, press escape.
Then undo, then redo.
Now you'll see the text is highlighted!

This is very critical because if you undo/redo back to some long ago point in time where the text is selected, and then hit `u`, all of your forward history is *lost* because the `u` causes case change!

Thanks for looking into this.

**Comment by t9md** [comment]
Ok, I will check this, thanks for reporting.
By the way, I'm curious about what kind of people use my vim-mode-plus.
Does your main editor is Atom and use vim-mode or vim-mode-plus in daily development?

**Comment by jordwalke** [comment]
I use Vim exclusively (MacVim). Every time a new Vim mode emulator comes out for another IDE/editor, I always try them and usually within twenty seconds I can spot about twenty things that are wrong/different from Vim, so I just file issues for them - this helps the developers refine their emulators.

I can never find one that matches Vim well enough, so I am stuck with Vim. I hope for the day when my options are more than just a single editor (which is why I try *every* Vim mode ever created in any editor). One day, I might just find one that gets all the important things right.

Almost always, the plugins don't do undo/redo similar to Vim, so that's the thing I test first.

I like that `atom-vim-mode-plus` is going beyond Vim and adding cool features such as incremental search (with tab navigation).

**Comment by t9md** [comment]
OK, thanks for explaining that. I was also heavy user of MacVim, and I still use MacVim for simple text editing like writing Markdown document.
But I'm frustrated Vim's syntax highlight/fold/fileTree/Tag, it always need manual configuration and sometime need tweaking minor things, so I moved Atom for about 5 months ago.

By the way, this kind of issue report is always welcome, I want to get feedback especially heavy Vim user.

**Comment by jordwalke** [comment]
(BTW: I put together [VimBox](https://github.com/jordwalke/VimBox)).

Yes, I'm very frustrated with Vim's file tree as well. Many people in the Vim community insist on making people think about windows/buffers in a way that is *totally* different from every other modern editor There is no good solution that keeps a single tree docked on the left/right side - VimBox is as close as I could get. It works great, but I'm hoping one day I can have a true file tree, as well as overlay command dialog (command+P) and overlay quick open (command+T).

Both Atom and Sublime (with Vintageous) might offer hope of that.
