### ISSUE TITLE
Pasting *over* text should put replaced text into register/clipboard.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#180]
Repro:

- Visually select some text.
- hit `p` to paste over it.
- Then observe that the replaced contents are not in the clipboard/paste-register. Vim would put it in the clipboard/paste-register.

If this is intentional because you prefer this behavior, perhaps a config setting to restore the vim behavior would be ideal.

**Comment by t9md** [comment]
Ok I will check. Although I rarely use this feature.

Reference: [v_p](http://vimhelp.appspot.com/change.txt.html#v_p)

I don't like this feature for which it do special care only in visual-mode.
I'd rather implement `YankAndPaste` operator, it yank target(it can be visual-area or text object) then paste from register).

**Comment by t9md** [comment]
Implemented it as `SwapWithRegister`, there is already very similar `ReplaceWithRegister` operator(which is not exists in pure Vim), `SwapWithRegister` is just different for which it preserver text to register before replacing target with register.

I'm not sure it should be enabled by default. For compatibility its better to enable by default.
Technically I can add setting parameter and enable/disable update keymap of `p` and `P` in visualmode.
But don't want to go too much.

Just provided workaround for people who want `v_p`, `v_P` behavior of pure Vim.

**Comment by t9md** [comment]
Btw @jordwalke are your really use this feature when you used to use oure Vim.
For me this visual-mode special behavior diff is rathe confusing than useful.

**Comment by jordwalke** [comment]
It's useful when you want to swap two words.

Imagine swapping `one` and `two`.
```
one
two
```

You would highlight `one`, `x` to cut it.
Then highlight over `two` and `p` to paste over it.
Then hit `p` to paste what was just clobbered.

This is the primary use case for this feature and I've come to rely on it (as many others likely have).

**Comment by t9md** [comment]
OK, thanks for providing use case.
I prefer to move-text directly via my vmp plugin https://github.com/t9md/atom-vim-mode-plus-move-selected-text in your case.

Anyway I swap-with-register have some usefulness since its can be used with combination of operator(not specific in visual-mode). I'll include this in next-release without default keymap.
