### ISSUE TITLE
"*" to search highlights all casing.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#181]
Suppose I have the text:

```
hello
Hello
hello
```

If I hit `*` on the first `hello`, all words will be highlighted. But then if I hit `n`, only the lower case `hello`s will be highlighted (correctly). I think the initial highlighting should be consistent with whatever `n` is about to jump through. In Vim, by default `*` is case sensitive.

**Comment by t9md** [comment]
Here the excerpt from vim help
```
                                                       star E348 E349
*                       Search forward for the [count]'th occurrence of the
                        word nearest to the cursor.  The word used for the
                        search is the first of:
                                1. the keyword under the cursor 'iskeyword'
                                2. the first keyword after the cursor, in the
                                   current line
                                3. the non-blank word under the cursor
                                4. the first non-blank word after the cursor,
                                   in the current line
                        Only whole keywords are searched for, like with the
                        command "/\<keyword\>".  exclusive  {not in Vi}
                        'ignorecase' is used, 'smartcase' is not.
```
Currently vmp treat `*` and `#` always case insensitive.
TODO to confirm with pure Vim
- [ ] Provide ignoreCaseForSearch parameter
- [ ] In `*` and `#` respect ignoreCaseForSearch parameter, and ignore `useSmartcaseForSearch` config option.

Is this what you want?

**Comment by t9md** [comment]
Specification
- `ignoreCaseForSearch` affects for motions `/`, `?`, `*`, `#`.
  - `true`: search case sensitive.
  - `false`: search case insensitive.

-  `useSmartcaseForSearch` affects for motions `/`, `?`. not includes `*`, `#`.
  - `true`: if search term includes capital letter then search case sensitive, else search case insensitive. Regardless of `useSmartcaseForSearch` value.
  - `false`: do nothing

**Comment by t9md** [comment]
I'm feeling didtinctive config parameter for `*` and `#`  is better than blindly mimicing pure Vim behavior.
So the user can useSmartcase for `/` but use case sensitive match for `*`.
So I'm thinking to provide distnct `ignoreCaseForSearchCurrentWord` option.

**Comment by jordwalke** [comment]
Sounds like you're suggesting a way to *configure* vmp to be just like Vim. That sounds good.

It seems like most generally, there's three values of sensitivity:
1. `caseSensitive`.
2. `caseInsensitive`
3. `smartCaseSensitive`

I could imagine configuring any of these three for `search`, and `searchCurrentWord`, for a total of 8 possibilities.

**Comment by t9md** [comment]
I'm not trying to strately convert config option from pure Vim.
The problem of Vim's `ignorecase` option is.

`ignorecase` is used in both `/`, `?` and `*` and `#`.
pure Vim config option can't cover following my want. So I will provide distinctive config parameter for `*`, `#`. 

I want use case SENSITIVE for `/`, `?`, but want case IN-SENSITIVE search for `*` and `#`.

If user want same behavior of pure Vim, simply set `true` for both `useIgnoreCaseForSearch` and `useIgnoreCaseForSearchCurrentWord`.

Currently vmp still yet provided `useIgnoreCaseForSearch` so I will add this option too in this issue.

**Comment by t9md** [comment]
Thinking about HOW IT SHOULD BE on earth.
Provide caseSensitivity select option rather than current boolean option for `/`, `?` and `*`, `#` separately.

- caseSensitivityForSearch: for `/` and `?`
 possible value is one of `sensitive`, `insensitive`, `smartcase`

- caseSensitivityForSearchCurrentWord: for `*` and `#`
 possible value is one of `sensitive`, `insensitive`, `smartcase`

This will better in conde simplicity and avoid user confusion about when ignoreCase is overriten when both `ignoreCase` and `smartCase` is enabled.
pure Vim mistakenly introduce this confusion.

But changing config parameter and migrate previous value with properly notifying use is tiresome...
For long term goodness I should make config option like above, but short term benefit I will simply add some config parameter to provide ignore case option etc...

**Comment by t9md** [comment]
OK I will go simple add option approach, then when if I truly consolidate config option I described above, I will migrate both `ignoreCase` and `smartCase` config option to new `caseSensitivityForSearch` option.
Settled!

**Comment by jordwalke** [comment]
Okay, sounds like we're in agreement.

**Comment by t9md** [comment]
I added `useSmartcaseForSearchCurrentWord` option for thoroughness.
