### ISSUE TITLE
Basic implementation of wrap lines `gq`

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#187]
There seems to be missing a good line wrapping shortcut in Atom that can be used to intelligently wrap comments like in Vim (with `gq`). It's not simple line wrapping because it should pay attention to `*` at the beginning of comments for example. I'm really missing this from Vim. I imagine vmp could provide an implementation (or even improvement upon the idea).

The current implementation that somewhat matches Vim, is pretty broken (check out the github issues). 
https://atom.io/packages/docblockr
Also, while that plugin has the correct behavior when hitting `<return>` at the end of a line (continuing the comment with leading `*` on next line), it doesn't work with vim keymapings (`o`/`O`) etc.

Maybe vmp should provide merely the basic features of comment wrapping (and continuing comment on next line when hitting `<return>`/`o`/`O`.

**Comment by t9md** [comment]
Atom provides, https://github.com/atom/autoflow.
This is mapped to `option+command+q` for macOS.

This is bundled package, and it's not likely someone disabled it.

## TODO

 - [ ] Create Operator `AutoFlow`
 - [ ] default keymap `g q`

**Comment by t9md** [comment]
For `g q` feature part , DONE.

`AutoFlow` operator is mapped to `g q`.
Now `g q i p`, `g q g q`, `V j j g q` works as like pure-Vim.
The important reflow work is just delegating to `autoflow:reflow-selection` command.
**I don't know how much feature compatible.**

**Comment by t9md** [comment]
I think I can close this issue. `g q` is already implemented.
If behavior is not fit for you, open new is with **how different in behavior** information.
