### ISSUE TITLE
How does replace with register works? 

### ISSUE THREAD

**Issue by hnguyen94** [t9md/atom-vim-mode-plus#190]

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/wiki/Keymap-example

It's Operator which paste register valuse to target area.
Provides `_` is mapped to this command.
You can replace word under cursor by `_iw` instead of visually select then paste which require more keystrokes.

**Comment by hnguyen94** [comment]
Wow Thanks!
