### ISSUE TITLE
Better placement of search result on `n`/`N`.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#192]
- Suppose my editor shows 100 lines of text in a very large file.
- Suppose I hit `n` to find the next occurrence of a search word.
- If that word is on the screen, it will simply be highlighted and the cursor moves to it - the text does not scroll. (vmp does this, and Vim does this).
- In Vim, if that word is *below* the visible region of text, but only 1-30 lines below the last visible line, hitting `n` will scroll just enough so that the highlighted word is near the bottom of the screen. But if that next occurrence is more than about 50 lines below the last visible line, then the word highlights and the text scrolls such that the highlighted match is exactly in the middle of the screen.
- This seems very intuitive and natural because if something is very close to the visible portion of your screen, you don't want to scroll a huge amount - you want to scroll as little as possible to try to keep as much of what you were *already* looking at on the screen. But if the text is so far away that scrolling to it is in a different part of the code, it makes sense to optimize for getting as much mental context in that new part of the code as possible.

I'm not asking for Vim compatibility, I'm just noticing that Vim did this really well and it probably makes sense for vpm to have this good feature too.

**Comment by t9md** [comment]
Understood, you are sayng 'keep original visible area as much as possible when scrolling by n and N to avoid  mental context switching'.
I like this kind of miner but important usability improvement. Will look into later.
Thanks for catching this!

**Comment by jordwalke** [comment]
> keep original visible area as much as possible when scrolling by n and N to avoid mental context switching

I think I need to take communication lessons from you. Thank you for the brevity!


(Note: I think this also applies to searching as you type with `/`)

**Comment by t9md** [comment]
> (Note: I think this also applies to searching as you type with /)

Yes, off course.

Aside from this topic, I released v0.24.0 now.
I want you to try new `vim-mode-plus:inner-any-pair-allow-forwarding` text-object.

This is one of killer feature of vmp along with `move-to-edge`(this exists long before) in my opinion.
I aggressively, experimentally override very essential `;` keymap for this in normal-mode.
But it's not bad. you can directly select next pair(like inner-string) from normal-mode, then next `;` select next string within line then you can `c` to change 2nd inner-string.

```
# for any-pair-allow-forwarding text-object
'atom-text-editor.vim-mode-plus.operator-pending-mode, atom-text-editor.vim-mode-plus.visual-mode':
  ";": 'vim-mode-plus:inner-any-pair-allow-forwarding'
'atom-text-editor.vim-mode-plus.normal-mode':
  ";": 'vim-mode-plus:inner-any-pair-allow-forwarding'

# for edge motion
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'ctrl-cmd-k': 'vim-mode-plus:move-up-to-edge'
  'ctrl-cmd-j': 'vim-mode-plus:move-down-to-edge'
```

**Comment by t9md** [comment]
Implemented.
I checked VIm's behavior(v7.4 on OSX). it only works when scroll downwards, not upwards.
Not did deeper investigation though.

vmp support both direction for smart scroll.

**Comment by jordwalke** [comment]
> vmp support both direction for smart scroll.

:D

**Comment by jordwalke** [comment]
Tried this out and I must say it feels great - I couldn't put my finger on what was missing, but this might have been it.
