### ISSUE TITLE
Q&A How does the Allow forwarding works?

### ISSUE THREAD

**Issue by hnguyen94** [t9md/atom-vim-mode-plus#197]

**Comment by t9md** [comment]
See links bellow

https://github.com/t9md/atom-vim-mode-plus/issues/188
https://github.com/t9md/atom-vim-mode-plus/issues/195

Default text-object for `(`, `[`, `{` works only when your cursor enclosed in paired chars.
AllowForwarding can find text-object even if cursor is out of paired char.

In this text, suppose your cursor is first column, you can directly change text in parenthesis by `ci)`.
If you map `i )` to `vim-mode-plus:inner-parenthesis-allow-forwarding`


```
      vimState = new VimState(this, editor, @statusBarManager)
```
I want to recommend everyone to use more generic  `vim-mode-plus:inner-any-pair-allow-forwarding`.

Btw,  you tried before creating this issue?

**Comment by hnguyen94** [comment]
Ahh thanks, yes i tried, but it was a little bit confusing for me
