### ISSUE TITLE
[New TextObject] function parameter, or arguments or comma-separated-word

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#198]
Not sure how I should name it.
I want to bring directly select function argument with this text-object.
Should take count to specify Nth argument in comma-separated argument list.

https://github.com/b4winckler/vim-angry
https://github.com/sgur/vim-textobj-parameter

**Comment by shemerey** [comment]
@t9md I think `arguments` or `comma-separated-word` fits more, for instance you can have 

```ruby
case grade
when "A", "A+"
  puts 'Well done!'
when "B", "B+"
  puts 'Try harder!'
when "C"
  puts 'You need help!!!'
else
  puts "You just making it up!"
end
```
 `when` is not a function, but potentially  you can use it here, any way it's just and idea :) awesome work

**Comment by t9md** [comment]
Thanks, I always needs this kind of practical input!

**Comment by t9md** [comment]
I have an idea.
- new Operator `SplitAndRotateByCharacter` to rotate argument.
- SplitAndRotateByComma split selected string by comma then rotate and join by comma.
- If selected text includes just one comma, rotating is same as swapping.
- separation char can take input from user.

Or
- New operator to find occurrence of argument then let general Rotate operator rotate selected text.
