### ISSUE TITLE
Visual Mode does not support home/end

### ISSUE THREAD

**Issue by Daemoen** [t9md/atom-vim-mode-plus#20]
Although the plugin supports visual + 0/$ it does not support visual + home/end, which is differentiated behavior from true vim behavior.  Suggest adding support for this.

**Comment by t9md** [comment]
What is the expected behavior? for home/end support.

**Comment by Daemoen** [comment]
Home should return the selection to beginning of line, end should highlight to end of line;  just alternative keys to 0 and $.  I think it will be pretty easy to just add it to the keymap cson file, was looking at it earlier, just havent tested it yet.

**Comment by t9md** [comment]
OK thanks, will check later

**Comment by t9md** [comment]
I added keymap.cson.
But curious, are you really use this keymap?

Since vim-mode-plus is not pure Vim. I want set keymap which is not used for many user.  
This is off course depending on personal preference I know.
