### ISSUE TITLE
`o` doesn't jump correctly (visually) after selection + editor:duplicate-lines

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#202]
Repro:

```
a
b
```

Select the two lines, call editor:duplicate-lines (cmd + D), then do `o`. The cursor, instead of jumping on the line of the second `a` (third line), it'll jump back to first `a` (first line).

The actual cursor under the hood is at the right place. It's just displayed wrongly.

**Comment by t9md** [comment]
Thanks for reporting.
