### ISSUE TITLE
unable to add characters at the end of a line sometimes

### ISSUE THREAD

**Issue by rvnath** [t9md/atom-vim-mode-plus#209]
When editing text using this plugin in Atom, I find that I am unable to add chars beyond the last char of a line.  I use a/Shift+A to start adding chars, but they get added *before* the last char.  Is this a known bug?

**Comment by rvnath** [comment]
<img width="485" alt="atom-vi-error" src="https://cloud.githubusercontent.com/assets/4309494/14016893/2601283e-f1e9-11e5-863c-41b24cd1cc99.png">

In the above pic, I am unable to add chars beyond the comma character on line#6.  This is true for any line. Line#6 is an example screenshot, but it happens for all lines.  But sometimes it works correctly. For example, if I erase the entire line and retype it, it works.

**Comment by rvnath** [comment]
Just now found that it happens becoz of conflict with vim-mode.  I disabled vim-mode, but found that :w kind of commands do not work.  I ended up disabling vim-mode-plus and enabling vim-mode and ex-mode.

**Comment by t9md** [comment]
vmp also have separate ex-mode package.
https://github.com/t9md/atom-vim-mode-plus-ex-mode

**Comment by rvnath** [comment]
Unfortunately this didn't work either.
<img width="677" alt="screen shot 2016-03-25 at 00 38 50" src="https://cloud.githubusercontent.com/assets/4309494/14028344/0bd8ec74-f222-11e5-841f-8e7fa0e71ee7.png">

Disabled vim-mode and ex-mode, but enabled vim-mode-plus vom vim-ode-plus-ex-mode.  I cannot access the :xxx operations.
