### ISSUE TITLE
Patch is null.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#212]
This only repro's occasionally, but it happens when I save:

Version 1.7.0-beta0

<img width="563" alt="screen shot 2016-03-24 at 11 52 04 pm" src="https://cloud.githubusercontent.com/assets/977348/14039638/aac49c7c-f21b-11e5-9297-50794e12b0ff.png">

**Comment by jordwalke** [comment]
Patch is `null` so we cannot perform an `instanceof` check.

**Comment by t9md** [comment]
Thnks
