### ISSUE TITLE
Undo after delete should move cursor to position of inserted text

### ISSUE THREAD

**Issue by iamjwc** [t9md/atom-vim-mode-plus#217]
In real vim, deleting text and then performing an undo moves the cursor back to the position of the first character that was undeleted.
![vim-real-undo](https://cloud.githubusercontent.com/assets/4146/14212801/a05b705c-f802-11e5-8783-842e41d0f7c4.gif)

In atom vim+, deleting text and performing an undo moves the cursor to the character after the character that was undeleted.
![vim-atom-undo](https://cloud.githubusercontent.com/assets/4146/14212802/a05bd862-f802-11e5-8f2f-2033728e4ce1.gif)

**Comment by jordwalke** [comment]
I had the same issue, but I reported it a long time ago and then @t9md added the option for "Set Cursor To Start Of Change On Undo". It works quite well for me in all but a few cases.
As far as I know, VMP is the only Vim mode emulator that does this somewhat correctly!

**Comment by t9md** [comment]
Thanks @jordwalke.
I want enable `setCursorToStartOfChangeOnUndoRedo` by default soon(after I updated some test spec).
