### ISSUE TITLE
Escaping from normal-mode move cursor to line above when inserting single space at column 0

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#226]
If you have the following content:

```
one
| 
three
```
Where the second line `|` represents the cursor, and where there is one *blank* space after the cursor (which you cannot see in that sample above).

Then inserting a _second_ space, then pressing escape, will put the cursor on the `e` from line one.

**Comment by t9md** [comment]
Oh, I could reproduce, thanks for concise explanation.
I think I can fix this and will fix, but I believe this inconsistency is bug(?) of Atom core.
Normally inserting character move cursor to after inserted char.
But when cursor is at first column and character is  single space, cursor remain at same column.

**Comment by t9md** [comment]
Humm I checked behavior and I think this seem to limitation of Atom which cannot stop in the middle of soft tab. Postponed to report upstream.

**Comment by t9md** [comment]
Fixing this is not easy.
To fix this I should not depend on atom's `cursor.moveLeft()` function.
This should be fixed in the gradual progression would be handled in #225.

**Comment by jordwalke** [comment]
You can see my stance on the "cannot stop between soft tab" issue which I posted last week here:
https://github.com/atom/atom/issues/3174#issuecomment-206424239

I would consider this behavior of Atom a bug. There are some comments which cannot even be typed without some very specific deletion/insertion pattern which is not discoverable.

**Comment by t9md** [comment]
What the worst part of this issue(wrap to upper line) is, I can not believe cursor position.
`cursor.getBufferPosition()` claiming its column is 1, but it actual position is 0 or it become 0 at the timing of clipping screen position in `cursor.moveLeft`.
So my fix would be dirty workaround..
I will open or comment issue on that later.

**Comment by jordwalke** [comment]
Do you think you have enough context to make Atom behave like _literally_ every other text editor (having the ability to move the arrow through soft tabs)?

**Comment by t9md** [comment]
Not sure, but its just needless special care, basically developer who use text-editor expects cursor move consistent way regardress of characters.
Atom's special care for softwrap add extra complexity to caluculate cursor position in package. Can not simply +1 or -1 column from current position, so have to consult to displayBuffer to ask **clipped** cursor position. It add some extra performance overhead I believe.

**Comment by jordwalke** [comment]
It would be cool if vmp would restore the traditional cursor movement (individual char), but I fear we cannot handle the performance hit!

**Comment by t9md** [comment]
I won't or can't do that.
Vmpis just a plugin can breath with Atom's great natire.
Can't fly high withoug supporting of Atom-core.

**Comment by t9md** [comment]
Not sure when it is, Atom seem to provides `atomicSoftTabs` configuration to disable softTab as unit.
So my workaround code is very temporal and no motivation to maintain this workaround.

**Comment by t9md** [comment]
![image](https://cloud.githubusercontent.com/assets/155205/15089710/055567ac-1445-11e6-90f7-50cc65c77805.png)

I checked behavior with current master branch of Atom core.
Which have new atomicSoftTabs options

- `atomicSoftTabs` = on(default): Still happen. Inserting space at column 0 move cursor one-line-up.
- `atomicSoftTabs` = off: No issue.
