### ISSUE TITLE
After canceling search, selection remains highlighted

### ISSUE THREAD

**Issue by carlisia** [t9md/atom-vim-mode-plus#227]
First of all, loving your package. Thank you for the great work!

When I cancel out of a search (with `escape` or `ctrl-g`, the string I had just searched, if it existed, remains highlighted. The only way I found to get out of it is to do a search for some random string I know won't be found.

**Comment by t9md** [comment]
Not sure what's your issue.
What is your vim-mode-plus setting?
Are you saying about incrementalSearch highlight  or highlightSearch feature which add persisted highlight after search finish?

**Comment by carlisia** [comment]
Maybe the SS will shine some light.

`Are you saying about incrementalSearch highlight or highlightSearch feature which add persisted highlight after search finish?`
I think so. I like the feature, but once I'm done with the search I want to move on and not have those strings highlighted. Is there a way to clear it? 

![image](https://cloud.githubusercontent.com/assets/16508/14466984/05ec4c8c-008e-11e6-8f9d-e3e012e47cba.png)


![image](https://cloud.githubusercontent.com/assets/16508/14466940/b7a92964-008d-11e6-971b-9e3b9b6be656.png)

**Comment by t9md** [comment]
Check CANGRLOG.md and search `vim-mode-plus:clear-highlight-search`.
You can invoke it to clear highlight from command-pallete or via keymap(you need to set).
I map it to space / in normal-mode.

**Comment by carlisia** [comment]
Thank you so much. I key-mapped mine to `escape` and it's perfect.

**Comment by t9md** [comment]
Good to hear!
