### ISSUE TITLE
some commands do not work in visual selection from double click

### ISSUE THREAD

**Issue by quarterto** [t9md/atom-vim-mode-plus#228]
When you highlight a region via click and drag and press `c`, it works as expected (clears the region and enters insert mode). If the selection was from a double click, however, the command doesn't work, it just behaves like there was no selection (i.e. waits for a motion).

**Comment by t9md** [comment]
OK I could reproduce it, I didn't much care about mouse-operation till now and from now.
But anyway I think this request is common use case many user expects.
Will check to if I can implement it.

**Comment by quarterto** [comment]
I've checked a bit further, and `d`, `y` and `x` also don't work, but for some reason `s` does.
