### ISSUE TITLE
Dot shortcut (vim-mode-plus:repeat) not working in 1.7.0

### ISSUE THREAD

**Issue by dudeinthemirror** [t9md/atom-vim-mode-plus#232]
After upgrading to Atom version 1.7.0, the "dot" shortcut for vim-mode-plus:repeat doesn't work anymore
Thanks

**Comment by t9md** [comment]
Use latest vmp I just released now. v0.33.0.

**Comment by dudeinthemirror** [comment]
Awesome! That did the trick. Thanks so much.
