### ISSUE TITLE
Mouse selection broke on latest update in insert mode

### ISSUE THREAD

**Issue by dsifford** [t9md/atom-vim-mode-plus#240]
When I attempt to select text with the mouse in insert mode, the cursor changes back to normal mode when I release the mouse button and selection doesn't work.

This began after the latest update.

**Comment by dsifford** [comment]
@t9md You are the man. 👍 Thank you so much.

**Comment by t9md** [comment]
Thanks for reporting this, will release in a minute after test pass on TravisCI.

**Comment by dsifford** [comment]
Ahh, much better. Thanks again! 👍
