### ISSUE TITLE
Add `gn`and `gN`: Operating on search matches (ex `cgn`)

### ISSUE THREAD

**Issue by bradens** [t9md/atom-vim-mode-plus#241]
One of my favourite uses of the search in vim is to perform operations on the matches, and arguably the most useful is the `g n`. 

when doing an incremental search it seems to changing everything in between your cursor and the next match, which is incorrect, it should change the current match.

ex. with a current search of `test`

```
<cursor>test

Here is a line of text that ends in test

another line
```
typing `cgn` will leave you with

```
<cursor>test

another line
```

when it should be

```
<cursor> (insert mode with first match deleted)

Here is a line of text that ends in test

another line
```

**Comment by t9md** [comment]
Your example is the behavior of latest vmp?
As I checked, its not like your example.
Anyway vmp currently not support `gn`, so I take this issue as request to add support of `gn`.

**Comment by bradens** [comment]
version 0.35.1
atom 1.7.2

**Comment by t9md** [comment]
DONE for intial implementation. Seem to work well for `gn`, `gN`, `dgn`, `dgN`, `cn`, `cgN`.

- Need spec
- Implemented as text-object for composability of operator
- Slightly different behavior with pure Vim
- vmp don’t change selection’s reversed state of initial selection.
