### ISSUE TITLE
Select block -> indent -> Error: unselect block

### ISSUE THREAD

**Issue by Ravencrow** [t9md/atom-vim-mode-plus#243]
This is the scenario:

1- I select a block of code that I want to tabulate several times.
2- I press "<" and it indents correctly backward.
3- Error: the block of code that was selected then gets unselected, so I have to select it again to make a second backward indentation.

Thanks for this incredible plugin.

**Comment by t9md** [comment]
What the operation(=precise keystroke you typed) you did?

For 3-Error,  do you see some exception error on chrome console log or you want to say it's erroneous behavior?

As far as I checked with latest version of vmp, its seems no problem, clearing selection after indent/outdent operation is as designed, yes pure Vim do the same way.
You can repeat indent with `.` command btw. Thanks.

**Comment by crshd** [comment]
I believe @Ravencrow meant the deselection is incorrect.

I agree, it's annoying having to re-select the range to repeat the command, but as @t9md said, that's what `.` is for. That's what Vim does, and it's what vmp does. Works fine.

Remember `.`. It's often overlooked, but it's your friend ;)

**Comment by Ravencrow** [comment]
Indeed. That was what I was saying. And yes, `.` works great, so ignore this report. `.`saved the day!

Thanks for this incredible plugin!

**Comment by t9md** [comment]
Thanks @crshd .
@Ravencrow Yes sometime I forget power of `.`.
I released and using [this vmp plugin package](https://atom.io/packages/vim-mode-plus-move-selected-text) for moving text including indent/outdent.
It's more intuitive way to moving text block for me.
