### ISSUE TITLE
Keymaps in non-English keyboards, search with '/'

### ISSUE THREAD

**Issue by trylks** [t9md/atom-vim-mode-plus#251]
I have tried to use this plugin, but I had to uninstall it. Keymaps do not seem to work properly. For 
example, I usually use shift+7 to type a '/' (Spanish keyboard), but this is not detected by the plugin 
(Atom does normally print a '/' when not using the plugin, though, so I don't know what is the
problem). In addition, there is another '/' in the numeric keyboard, and it works properly.

If you need more information for reproducibility please let me know what information and how to get it. 
It may be some configuration problem on my side, if so, I would appreciate instructions. It may be a 
more general problem with Atom, in such a case, please let me know if (and where) I should "escalate" it.

Thank you very much, the plugin looks awesome except for this detail.

**Comment by t9md** [comment]
I can not help you much, since keyboard issue is difficult unless I have same keyboad and motivation.

Similar issue?
https://github.com/t9md/atom-vim-mode-plus/issues/63

You tried keyboard-localization?
https://atom.io/packages/keyboard-localization

**Comment by trylks** [comment]
Same issue in fact. Solved. Thank you.
