### ISSUE TITLE
`f` fail, throw error when `fx` success then change nextTab then back then `fx`

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#258]
The cause is the change I introduced in v0.37.0, for hidden-input, I no longer use panel and appendChild to parentNode of vimState.editorElement, but when I switch to anotherTab, it change order of DOM?(Not sure well investigated yet).

I'll do quick fix, then re-consider the better way afterward.

**Comment by axelson** [comment]
This doesn't fix an issue for for me in v0.37.1 with the `f` command. Unfortunately I don't have a good reproducible test-case. But it "seems" to be related to unclosed parentheses (but I could be totally wrong).

I get the error reported in #185 `Uncaught TypeError: this.peekTop(...).setTarget is not a function`.

**Comment by t9md** [comment]
Interesting.

Can you reproduce this issue by `fx` success then change next tab by clicking tab bar then back to original tab then `fx`?

Or your issue is caused by another custom `f` prefixed keymap I descripbed in #260?

**Comment by axelson** [comment]
The issue is not caused by another custom `f` keymap. When the issue begins to occur it is not solved simply by switching tabs, I need to close the tab and then re-open to fix. Here is a screenshot with the key binding resolver open:
![settargetnotafunction](https://cloud.githubusercontent.com/assets/9973/14874552/5cb664ce-0c9d-11e6-9a97-334467bed0c9.png)

**Comment by t9md** [comment]
Can you explain minimum reproduction procedure?
I feel this is very important issue I should fix.

What I said to switch tab is not for solving but reproducing. but this issue should be fixed in the version you are using already 0.37.1

What I can tell about what's happenning in your env from your screen capture is
- hidden mini-editor can not get focused for some reason where I SHOULD be focused.
- So, `x` keystoke goes normal editorElement and mapped to `delete` command where `x` should be handled by mini-editor.

When multiple keymapping starting with `f` exists, this situation happen, and there is no workaround
unless this [PR](https://github.com/atom/atom-keymap/pull/132) would be merged.

```
 "f": `vim-mode-plus:find"
 "f a": `other-command"
```

So, please observe keymap-resolver with understanding of this mechanism.
Hope this info give you some insight.

**Comment by t9md** [comment]
I saw error even though I don't have any `fX` keymap.
So I will revert code to previous implementation soon, sorry for this degradation all.

**Comment by axelson** [comment]
Yeah I wasn't able to reliably reproduce it, but if I used the `f` command 10 or 15 times it would usually crop up (and once it happened in a tab it kept happening). 👍  to the revert.
