### ISSUE TITLE
'*' and '#' search word not working in certain conditions

### ISSUE THREAD

**Issue by BetterWang** [t9md/atom-vim-mode-plus#259]
I have a C macro:
```C++
void test()
{
	TGraphErrors * gr_R = gr_V2[1][c]->Clone();
	for ( int i = 0; i < gr_R->GetN(); i++ ) {
		gr_R->GetY()[i] = gr_R->GetY()[i] / grMB_v2[1][c]->GetY()[i];
	}
}
```
At the `gr_R` in L3, if I press '\*', the search will go through all `gr_R`.
At the first `gr_R` in L5, if I press '\*', the search will not work.
'#' is similar.
At `gr_R` in L4, neither '\*' nor '#' works.
I am running atom on OS X.

**Comment by BetterWang** [comment]
Looks like it is searching for `gr_R-` instead of `gr_R`.
How do I change the word breaking?

**Comment by t9md** [comment]
Improve, word selection, so now word selected is same word when you do `editor.select-word` `ctrl-shift-w` by default.

And breaking :bomb: for compatibility for this commit.
I removed `vim-mode-plus.iskeyword` setting, which allow user to customize list of keyword char.
But it don't have default setting so not appear in setting-view, most of user won't notice this change.
And this setting is not ideal solution, no one want to tweak this setting when Atom's each language package provide this information via `cursor.wordRegep()`.
