### ISSUE TITLE
Can't navigate to last character in line in insert mode

### ISSUE THREAD

**Issue by artembarmin** [t9md/atom-vim-mode-plus#263]
Reproduced only in vim-mode-plus. In standard vim-mode works ok

Reproduce:

1. Enable vim-mode-plus 
2. Go to insert mode(i)
3. Type 'test'
4. Move cursor left on time
5. Try to move cursor right(impossible)

Atom: 1.7.2
vim-mode-plus: 0.37.1
vim-mode: 0.65.0

**Comment by t9md** [comment]
SHOULD READ README.md BEFORE OPEN ISSUE.
Disable vim-mode.
