### ISSUE TITLE
visual selection in ex-mode

### ISSUE THREAD

**Issue by psifertex** [t9md/atom-vim-mode-plus#264]
Not sure whether vim-mode-plus or vim-mode-plus-ex-mode is the proper package for this. I'd like to be able to visually select rows and have them automatically set marks the way vim does.

My use case is:

1) Visually select a block of text
2) `:'<,'>s/one/two/g` (replaces "one" with "two", but only in the block of text selected). 

Note that VIm will automatically prefix ex-mode with `'<,'>` when entering ex-mode after making a visual selection.

This is similar to https://github.com/lloeki/ex-mode/issues/31

**Comment by t9md** [comment]
This is not vmp issue, should go to vmp-ex-mode, but again read README.md of vim-mode-plus-ex-mode.
I have no motivation to work on vim-mode-plus-ex-mode.
