### ISSUE TITLE
Yank to last char of line not working

### ISSUE THREAD

**Issue by romgrk** [t9md/atom-vim-mode-plus#265]
I was about to open an issue about this and I just realized that the command doesn't even exist for YankToEndOfLine. As always. (This is such a bug in Vim)
I think it would be correct to include `shift-Y` as `y$`, it just fits so well with the other operators (`C == c$`, `D == d$`, etc)

I gist you here my implementation.
```coffee
  'romgrk:yank-to-end-of-line': (event) ->
    return if (not window.vim?) # window.vim is attached in my atomrc, 
    state = window.vim.getEditorState this.getModel()
    state.operationStack.run "Yank", target: "MoveToLastCharacterOfLine"

# Though I wrote it this afternoon, might not be accurate.
# I think is doesnt preserve linewiseness.
```

Oh btw, have you some `[n/v/i/o]map` function planned to release soon? The only thing I miss from [n]vim is being able to define my keymap easily. Usually I go through obscure ways to make atom work as I want.

**Comment by t9md** [comment]
For reference, if you want to extend vmp in your `init.coffee`.
https://github.com/t9md/atom-vim-mode-plus/wiki/Extend-vmp-in-init-file

For mapping, NO PLAN for syntax sugar.
Atom already provide scope based granular keymap, you can achieve as granular keymap as pure Vim for keymap.

**Comment by romgrk** [comment]
And would you accept PRs for this? IMO the Atom way feels sluggish compared to vim.
And also it avoids the need to delve in the code for people who do not develop this package… (Like a good part of the users of this package) (:
Basically what I would like to have is some function that I can call in my rc script so I don't have to declare commands for every keybinding, akin to `*[nore]map`. (Think about the users!)

**Comment by t9md** [comment]
The answer for this type of question is always "depends on how PR is like", amount of complexity the PR introduces.

I basically don't want to spend my time for feature I don't use.
But I understand your point.
This and I have some idea.
But it's better to treat in separate issue.
