### ISSUE TITLE
Pressing w does not wrap to next line.

### ISSUE THREAD

**Issue by DrowsySaturn** [t9md/atom-vim-mode-plus#267]
Pressing w does not move to the next line. I'm not certain what wrap left to right motion does, but even with that on, the w key does not go to the next line.

**Comment by DrowsySaturn** [comment]
e and b both switch lines when the edges of lines are reached.

**Comment by t9md** [comment]
Not sure why can't move to next line since I can.
I need minimum repro fo this issue.
Text you are editing, and **precise** keystroke. Make sure `w` is bound to `vim-mode-plus:move-to-next-word` by cheking keymabinding resolver(`cmd-.`).

**Comment by DrowsySaturn** [comment]
I am on windows. I looked at the keybindings in settings and that was set for the w key. The precise keystroke, is that as soon as I open a file I press w, and it never goes to the end of the line. I repeatedly press w, but it remains at the _last character_ of the line. When I reach the beginning of the last word on a line, after I press w it goes to the last letter of that word. I have just reached the source of the issue I think. After checking the LF and CRLF line endings, this issue seems to only happen with the CRLF line ending enabled.

**Comment by t9md** [comment]
OK, thanks.
- You see issue only when line ending is CRLF.
- When line ending is LF, you have not problem.
Right?

**Comment by DrowsySaturn** [comment]
Right, this issue seems to be true for atom's vim-mode too. Or at least I assume it's the same issue, because w doesn't work with that either.

**Comment by t9md** [comment]
What version of Atom you use? pls put necessary info so that I don't have to ask one by one.

**Comment by DrowsySaturn** [comment]
Atom 1.7.3, Windows 64-bit, vim-mode-plus 0.38.0, vim-mode-plus-ex-mode 0.2.0. Installed with default settings. No configuration has been changed aside from adding lua syntax and your vim-mode plugins, and my theme.

**Comment by t9md** [comment]
Thanks I'll look into later.
