### ISSUE TITLE
`j` has a delay when in Visual Mode and `j k` is escape sequence.

### ISSUE THREAD

**Issue by jessejanderson** [t9md/atom-vim-mode-plus#271]
I just started using vim-mode-plus a week or so ago but first noticed this behavior today. Not sure when I updated to 0.39.0 but that's the version I'm using currently. It's possible this error existed for a few days and I didn't notice it until now.

If I enter visual mode, pressing `j` takes 1-2 seconds before moving down a line. It appears to have no delay in the other modes.

With Key Binding Resolver, when I first press `j` I get:
`j ^j (partial)`
`vim-mode-plus:activate-normal-mode j k atom-text-editor.vim-mode-plus:not(.normal-mode) /Users/Jesse/.atom/keymap.cson`

Then after the 1-2 second delay I get all the normal listings (`vim-mode-plus:move-down`, `core:move-down`, etc).

**Comment by jessejanderson** [comment]
Hmm, I am seeing the same behavior when I am using `j` to delete multiple lines of code.

`d 5 j` will hang for 1-2 seconds, and then delete the 5 lines of code.

**Comment by t9md** [comment]
As far as I read from your explanation, it's right behavior.
Just conflicting `j` keymap. It should be without vim-mode-plus when multiple keybinding is set which keymap starts `j`.

You want to escape from inset mode by `jk`? Just map it only in insert-mode solve this problem.

**Comment by jessejanderson** [comment]
I never had an issue with this before. I've been using `j k` as my escape key without issue until today.

**Comment by t9md** [comment]
What changed with recent version is `j` is also mapped here.
http://github.com/t9md/atom-vim-mode-plus/blob/c036784ab24344e2298185e2837c6a57dbe4f3b2/keymaps/vim-mode-plus.cson#L239

With solve issue described in #252, #254.

But not sure this is related, with your operation `5 d j` this issue should be still happen in previous version of vim-mode-plus.
What I can say is this is normal keybinding issue. Please investigate further by your self.

As I mentioned in first comment, you should set your custom  `j k` map to more narrow scope like blow.

'atom-text-editor.vim-mode-plus.insert-mode':
  'j k': 'vim-mode-plus:activate-normal-mode'
