### ISSUE TITLE
Key mappings to use system clibpoard

### ISSUE THREAD

**Issue by nesmyslny** [t9md/atom-vim-mode-plus#272]
Hey there,

maybe this is more a question (didn't found it in the documentation): I used to have `<Leader>y` (and other yank/put operations) mapped to use the system clipboard. Is it possible have something like this in vmp?
Here is what I used in vim:

``` viml
"copy & paste to system clipboard
vnoremap <Leader>y "+y
nnoremap <Leader>y "+y
nnoremap <Leader>Y "+y$
vnoremap <Leader>d "+d
nnoremap <Leader>p "+p
nnoremap <Leader>P "+P
vnoremap <Leader>p "+p
vnoremap <Leader>P "+P
```

Thanks for this awesome plugin!

**Comment by t9md** [comment]
So you want to save to system clipboard only when you use Leader key.
keystroke `"+y` is supported.
But binding keymap above is out of scope of vmp.

https://atom.io/packages/keystroke is package to complement request like this, but currently **NOT** solve above problem. Technically can solve, I'll put comment on this issue after I enhanced keystroke package.

**Comment by nesmyslny** [comment]
Yes, exactly. For example, I want to hit `space y y` (space = leader) to yank a line to system clipboard.
Thanks for letting me know!

**Comment by sandman21dan** [comment]
Not sure if this is directly related to this.

But can I configure vim-mode-plus to use Only and Always the system clipboard?

Thanks!

**Comment by nesmyslny** [comment]
In the settings of this package is an option called `Use Clipboard As Default Register`. Maybe this is what you are looking for.

**Comment by t9md** [comment]
@sandman21dan Yes. Check settings-view of vim-mode-plus.

**Comment by sandman21dan** [comment]
I've just recently installed the package, and the settings panel wasn't even there, an Atom reboot made it appear and all makes sense.

Thanks!

**Comment by nesmyslny** [comment]
Are such mappings possible now? I don't see anything related to this in the changelog.
Or did you close it because you won't support it ?

**Comment by t9md** [comment]
Closed by mistake sorry.

**Comment by bronson** [comment]
This issue seems pretty similar to https://github.com/t9md/atom-vim-mode-plus/issues/473

Probably worth playing with that answer and seeing if it could work here too.

Of course you might need to add a `set-register-name-to-system-clipboard` command like https://github.com/t9md/atom-vim-mode-plus/commit/dead1024050e12b7da5a3c28ea363f37c3106af6, but that should be pretty easy.

**Comment by t9md** [comment]
@bronson Nice catch! You are correct. Implemented.

@nesmyslny

Your request would be supported from next release v0.66.0.

Wrote TIPS for this.
https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#use-system-clipboard-only-when-you-use-space-as-leaderkey

Try after release. and re-open when it's not fixed.

**Comment by nesmyslny** [comment]
Sorry for not replying. I wasn't able to test it until now.

Works great so far 🎉 Thanks @bronson and @t9md, of course 👍

**Comment by t9md** [comment]
oh, glad to hear that 👍
