### ISSUE TITLE
'A' key doing insert not append

### ISSUE THREAD

**Issue by JKeeter** [t9md/atom-vim-mode-plus#273]
at end of line, cursor on last character in command-mode.  hitting A or a opens insert mode just in front of last character, not after the character/end of line.

**Comment by t9md** [comment]
vim-mode disabled? You read README?

**Comment by JKeeter** [comment]
That was it, I had re-enabled it accidentally while trying to troubleshoot atom crashing on large file.  works now after re-disabling it
