### ISSUE TITLE
Ctrl + y should keep scrolling up when cursor is at the bottom

### ISSUE THREAD

**Issue by sandman21dan** [t9md/atom-vim-mode-plus#275]
Using Ctrl + e scrolls down line by line, if the cursor reaches the top of the view, then Ctrl + e lowers the cursor one line, then scrolls the view one line.

This should be the behaviour for Ctrl + y however it doesn't happen, the view just bounces with the cursor at the bottom.

ENV: Windows 10

**Comment by t9md** [comment]
Thanks for pinging me, this is what I wanted to fix.
To fix this I just followed the way original vim-mode has fixed.
This fix on vim-mode was made at around I forked vim-mode and actively developing vim-mode-plus.
So didn't cherry-picking till now.

**Comment by sandman21dan** [comment]
Brilliant! Thanks!

**Comment by t9md** [comment]
released as v0.40.1.
