### ISSUE TITLE
* and # should fill search box

### ISSUE THREAD

**Issue by jonlemmon** [t9md/atom-vim-mode-plus#280]
When in visualization mode and pressing * on a word, it should copy the word to the search box (along with the default behavior of jumping to the next instance of the word within the file). Then when you open the search box the term will already be in there. That way you can quickly do a project-wide search of a word just by doing `* + command-shift-F + enter`.

**Comment by t9md** [comment]
I understand your motivation but, don't do that.
use `cmd-e` then `cmd-shift-f`. `cmd-e` pick word under cursor.

**Comment by jonlemmon** [comment]
Oh that's brilliant! Thanks!! :D Amazing work btw.

**Comment by t9md** [comment]
For clarify, the reason why I won't implement this enhancement request is just want to avoid dependency to other package's feature for maintainability.
