### ISSUE TITLE
support quick move in insert mode

### ISSUE THREAD

**Issue by wangxiexe** [t9md/atom-vim-mode-plus#281]
In vim, in insert mode, we can do ctrl-o and motion and continue to edit,  can we have same capability in vmp ?

thanks a lot!

**Comment by t9md** [comment]
Not supported yet, and I basically don't want to.
Technically I can.
But why I don't want to is, Atom have many outer-vim-mode command.
So to achieve this feature, 

1. Change mode to `normal` temporarily from insert-mode by `ctrl-o`
2. Observe all atom command including vim-mode-plus's and outer-vim-mode-plus's commands only once
3. Start insert mode again.

I can' but I'm in dought this is really useful especially when compared to amount of work/codes I have to manage.

I basically want to avoid touching outer-world of vim-mode-plus.

**Comment by t9md** [comment]
Changed my mind, it was easy to support this feature, so I experimentally add this feature for compatibility.
Thanks for suggestion.

**Comment by wangxiexe** [comment]
hi t9md, has this feature been included in 0.44.1 ? thx

**Comment by t9md** [comment]
No, not yet released. Will be included in v0.45.0.
You can check it by clicking above commit, and if you see version tag, it means its included from that tagged release version. If not yet tagged, its not released yet.
