### ISSUE TITLE
% motion for tags

### ISSUE THREAD

**Issue by aeosynth** [t9md/atom-vim-mode-plus#285]
the `%` motion should work on open/close tags

**Comment by t9md** [comment]
Not sure your point, need example text.

**Comment by aeosynth** [comment]
```html
<p>_
  some text
</p>
```

cursor on `<p>` open tag. after pressing `%`:

```html
<p>
  some text
</p>_
```

cursor on `</p>` closing tag

**Comment by t9md** [comment]
oops, understood.
I thought I've already support this feature, thats why I asked your example.
OK, will check from now.
