### ISSUE TITLE
Insert Mode cannot write at end-of-line

### ISSUE THREAD

**Issue by shaunlebron** [t9md/atom-vim-mode-plus#286]
Given the following versions:

<img width="739" alt="screen shot 2016-06-04 at 3 51 45 pm" src="https://cloud.githubusercontent.com/assets/116838/15802014/455b6d8c-2a6c-11e6-8459-bb209d9cef9c.png">

And the following text in a file:

```
foo bar
```

The furthest you can place a cursor in insert mode is here:

```
foo ba|r
```

The cursor cannot reach the end of the line.

__NOTE__: this bug goes away when disabling vim-mode-plus.

**Comment by t9md** [comment]
Disable vim-mode, pls read README.
