### ISSUE TITLE
Indent and outdent unaffected by command multipliers

### ISSUE THREAD

**Issue by sebastjaeger** [t9md/atom-vim-mode-plus#287]
Indenting (>>) and outdenting (<<) do not react to command multipliers. For instance, the command
```
5>>
``` 
still only indents once and not 5 times as expected.

**Comment by t9md** [comment]
from vim help
```
>>			Shift [count] lines one 'shiftwidth' rightwards.
```

The count is used to how many lines to indent.
So current behavior is as expected and compatible with pure Vim.
