### ISSUE TITLE
Suggestion: Use "vim-mode" as editor class.

### ISSUE THREAD

**Issue by jackcasey** [t9md/atom-vim-mode-plus#29]
For compatibility with vim-mode and vim-mode-new with regard to user customised styles and keybinds.

Some users might find it useful to switch back and forward from vim-mode and vim-mode-plus to test features or if one becomes problematic due to a missing feature or a bug. Because they cannot run side by side for other reasons, I think reusing the class: `vim-mode` should grant that compatibility without any other problems?

I might be missing something that makes this a bad idea though.

FYI: The driver behind this is that I'm working on an atom plugin that adds many spacemacs style keybinds ([spacemacs-evil-keys](https://github.com/jackcasey/atom-spacemacs-evil-keys)) for vim, and it needs to refer to the `vim-mode` class. When I switched to vim-mode-plus I had to redo all the [keybinds](https://github.com/jackcasey/atom-spacemacs-evil-keys/blob/master/keymaps/spacemacs-evil-keys.cson).

**Comment by t9md** [comment]
I changed css class intentionally at the timing of public release.

I want to avoid misleading user to think its compatible.
And dont want to confuse vim-mode with vim-mode-plus.
I understand your motivation but for this topic I won't change my mind.
Want to being explicit the fact vim-mode-plus isnt vim-mode.

**Comment by jackcasey** [comment]
Fair enough! :+1:
