### ISSUE TITLE
Surround stopped working after latest update

### ISSUE THREAD

**Issue by alexeygolev** [t9md/atom-vim-mode-plus#290]
`c s` and `d s` switches mode to something I can't even understand. Not sure how to debug.
If I move these keystrokes into `'atom-text-editor.vim-mode-plus:not(.insert-mode)'` then my `d d` has a delay.

**Comment by t9md** [comment]
What's version when you say latest update, for vim-mode-plus or Atom?
vim-mode-plus not providing default keymap for surround related operation, so I can't answer your issue since I don't know your original keymaps.

I'm not asking you for detail, I think you can fix by yourself.
I still can use surround without problem with latest vim-mode-plus(0.44.1)  and atom stable and beta release.

How about checking my keymap exposed at https://github.com/t9md/dotfiles .

**Comment by t9md** [comment]
@alexeygolev You could solve this issue?
If not wast this vmp fault? if so, I want to know detail to fix bug.

**Comment by alexeygolev** [comment]
For some reason the problem occurs when I have this in my keymap
```
'atom-text-editor.vim-mode-plus.normal-mode':
  ':': 'vim-mode-plus-ex-mode:open'
  '!': 'vim-mode-plus-ex-mode:toggle-setting'

```

**Comment by t9md** [comment]
As I said, I can use surround without problem with above keymap.
Did you see my keymap setting?
I think I can help you but I don't want to ask question one by one.
You didn't provide OS, Atom version etc..
If you compare your keymap with my keymap, I believe you can narrow down the cause.

**Comment by t9md** [comment]
If you find this is definitely vim-mode-plus's problem, I welcome to reopen this issue.
Until then I'll close to focus to pure issue(bug, enhancement).

**Comment by masa-beheim** [comment]
Thanks for vmp! It's great. 
Somehow I am experiencing the same issue. So I just [uninstalled](https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/34) atom. Reinstalled. Installed vmp. Atom 1.8.0 on OS X, vmp 0.49.0. Keymaps are still empty. Gets stuck after `cs` and `'` or `"` don't have an effect.

**Comment by t9md** [comment]
You need to set keymap by youself, id you did how keybinding resolver says? Cmd-.  to activate keybinding resolver which report binded command by each of your keystroke.

**Comment by masa-beheim** [comment]
Ahh, thanks so much for the hint. I didn't read until the _Keymaps_ section, now I understand. I just saw that surround is a built-in, so I thought that it will work out of the box. It's working now and I love the visual cues.
