### ISSUE TITLE
how to set custom keymap for activating visual-block mode

### ISSUE THREAD

**Issue by trusktr** [t9md/atom-vim-mode-plus#291]
I have this in keymap.cson:

```cson
'atom-text-editor.vim-mode-plus.normal-mode':
    'cmd-v': 'vim-mode-plus:activate-blockwise-visual-mode'
'atom-text-editor.vim-mode-plus.visual-mode':
    'cmd-v': 'vim-mode-plus:activate-blockwise-visual-mode'
```

But when I press `cmd-v` it just pastes like before. Does the Atom `cmd-v` command have priority? Can I disable it?

**Comment by trusktr** [comment]
I see in resolver that the vim-plus-command is at the bottom:

![screen shot 2016-06-12 at 12 48 53 pm](https://cloud.githubusercontent.com/assets/297678/15993469/1f75c3ca-309c-11e6-8f74-6a63d9b78083.png)

**Comment by t9md** [comment]
I could use `cmd-v` to start visual-block mode with the keymap you pasted above.
If you have another section where `'atom-text-editor.vim-mode-plus.normal-mode':` scope is used, you need to put keymap definition under that scope.
Don't use same scope again in `keymap.cson`, instead you need to append it to existing section of that scope.

DONT
```
'atom-text-editor.vim-mode-plus.normal-mode':
    'cmd-a': 'command-a'
'atom-text-editor.vim-mode-plus.normal-mode':
    'cmd-b': 'command-b'
```

DO
```
'atom-text-editor.vim-mode-plus.normal-mode':
    'cmd-a': 'command-a'
    'cmd-b': 'command-b'
```

**Comment by bronson** [comment]
For more discussion on this topic: https://github.com/atom/atom/issues/6718
