### ISSUE TITLE
Use ctrl-w to close pane. how can I remap prefixed key like `ctrl-w`

### ISSUE THREAD

**Issue by PabloDinella** [t9md/atom-vim-mode-plus#292]
Ctrl + W doesn't work anymore, so what is the right key for closing a tab?

**Comment by deleted** [comment]
I'm also having this issue (on Linux). With vim-mode-plus installed, if you type `ctrl-w` from command mode nothing happens. But if you type `ctrl-w`, and then a key that would enter insert mode (e.g. `a` or `i`, it closes the window.

**Comment by PabloDinella** [comment]
I figured it out, you need to press ```ctrl + w``` then ```q```

**Comment by t9md** [comment]
This is FAQ for all Atom user not specific to vim-mode-plus.
I understand user who switched from pure Vim to Atom want to tweak their own keymap and hit this issue.
So I wrote TIPS for this.

https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#how-can-i-use-ctrl-w-to-close-pane

And I updated issue title to be hit easily in future.

**Comment by enricribas** [comment]
I love VIM in atom, and switched from VSCode back to Atom because VIM in Atom works so much better. BUT you shouldn't modify commands like Ctrl-W. While in insert mode, sure, but don't hijack standard Atom commands.
