### ISSUE TITLE
Support "ge" and "gE"

### ISSUE THREAD

**Issue by amzaf** [t9md/atom-vim-mode-plus#294]
In Vim "ge" and "gE" commands move the cursor backwards to the end of the previous word or WORD, while in vim-mode-plus the cursor is moved forward, similar to the "e" and "E" commands respectively.

**Comment by AmZaf** [comment]
https://github.com/atom/vim-mode/issues/871

**Comment by t9md** [comment]
Just not implemented yet. I'll check when I have time.

**Comment by bronson** [comment]
Here's an attempt: https://github.com/t9md/atom-vim-mode-plus/pull/479
