### ISSUE TITLE
Repeat Find not working with different keyboard localization

### ISSUE THREAD

**Issue by PabloDinella** [t9md/atom-vim-mode-plus#295]
I use keyboard localization for my pt_BR keyboard, but when I press `;` the search bar is opened as if I pressed `/`

![image](https://cloud.githubusercontent.com/assets/2482730/16084111/e6cef812-32ed-11e6-8968-bafafe875fde.png)

Any hints?

**Comment by t9md** [comment]
From the screen capture, the keyinput is recognized as `/` instead of `;`.
You have to solve this: find proper keystroke to be recognized as `;`.
Not sure this is because of your configuration or keyboard localization package itself.

**Comment by t9md** [comment]
What's the status of this issue?
vim-mode-plus is not touching underlying keybinding what keystroke is recognized to what keycode is basically out-of-vim-mode-plus.
If you type `;` key but recognized as `/`, I believe this is still happen even if you disabled vim-mode-plus.
