### ISSUE TITLE
how to quickly move outside the closing pair

### ISSUE THREAD

**Issue by wangxiexe** [t9md/atom-vim-mode-plus#296]
when coding, when I insert { atom will automatically add the } and then I can start insert , 

{
   type here|
}

so, when inserting is done, the cursor is at the end of the line as show above (|)

in vmp, how can I move the cursor to be outside the closing pair } just like below 

{
   type here
}|

it seems possible in vim

http://stackoverflow.com/questions/25466055/vim-autopairs-jiangmiao-how-to-get-out-of-pairs

thx!

**Comment by t9md** [comment]
Go to https://github.com/atom/bracket-matcher
The behavior you mentioned is done [here](https://github.com/atom/bracket-matcher/blob/master/lib/bracket-matcher.coffee#L78-L82).
So search existing issue or create new issue or make PR.
vmp not handle this and don't want to.

**Comment by wangxiexe** [comment]
Ok, thanks a lot for the info
