### ISSUE TITLE
Hit ESC once to enter normal mode

### ISSUE THREAD

**Issue by guma44** [t9md/atom-vim-mode-plus#298]
Hi,
I could not find how to switch it off. It is really annoying I have to press ESC twice before it enters normal mode. I using vim interchangeably and it is just in my head that I hit once and I start do do other things. How can I set this up?

**Comment by t9md** [comment]
I don't know. This is strange behavior and first time it's reported.
So what you can do is to disable other package to narrow down the cause.
I want to know if you find the cause so that someone might be helped with your investigation.
Thanks!

**Comment by guma44** [comment]
Thanks, I try to go through the packages and check this.

**Comment by guma44** [comment]
Actually, I checked different thing. I updated atom from 1.7 to 1.8 and now everything is working as expected. I am closing the issue.
