### ISSUE TITLE
Visual-linewise mode shrinks top of selection if moving up and then down 

### ISSUE THREAD

**Issue by tmunro** [t9md/atom-vim-mode-plus#3]
Verified that this is not how vim behaves:
![off-by-one-visual-line](https://cloud.githubusercontent.com/assets/3076428/10118888/d509e8d6-6439-11e5-8168-f8e132f78ed9.gif)

**Comment by t9md** [comment]
Oh, thanks, nice catch.
This is very critical degradation!! Thanks will check.
