### ISSUE TITLE
Startup time:

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#30]
`atom-vim-mode-plus` adds about 200ms to startup time to atom. It's definitely worth it! I would not use `atom` if it were not for this plugin. However, is there anything you can think of to improve startup time? (This is low priority, but I thought I'd mention it).

**Comment by t9md** [comment]
I quickly checked, but I have no idea currently.
Just like you said.

I occasionally check not adding unexpected long start up time so this 200ms I already know.
Its very important to improve startup time
I always in my mind to reduce startup time, and will improve gradually or (wont' add extra time when adding new feature).

**Comment by jordwalke** [comment]
:+1: 

I've recommended `atom-vim-mode-plus` to some Vim diehards so far, and the feedback has been positive.

**Comment by t9md** [comment]
That's very encouraging for me :smile: 
Since I don't have TODO  **specifically** for this topic currently, will close this issue.
