### ISSUE TITLE
make scrolling shortcuts work on autocomplete-plus popup

### ISSUE THREAD

**Issue by doubleloop** [t9md/atom-vim-mode-plus#300]
It would be awesome if scrolling with ctrl+e/y would work after autocomplete-plus popup. Sometimes help message is wrapped and currently to see it mouse scrolling is required

**Comment by t9md** [comment]
How about this? set following keymap in your `keymap.cson`.
To save normal ctrl-e behavior in `insert-mode`, limit scope only to autocomplete-plus is active.

```coffeescript
'atom-text-editor.autocomplete-active.vim-mode-plus.insert-mode':
  'ctrl-e': 'vim-mode-plus:scroll-down'
  'ctrl-y': 'vim-mode-plus:scroll-up'
```

**Comment by doubleloop** [comment]
Works like charm! Thx
