### ISSUE TITLE
Feature request: visualization for marks?

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#303]
The built-in atom bookmark is neat because it leaves a trace in the gutter and has an option to display the list of all bookmarks. I like vim-mode-plus' mark, but I can't remember all the marks I put.

**Comment by t9md** [comment]
Do you really use multiple mark?
Any reason using this feature?
If your don't like default keymaps, how about this?

```coffeescript
'atom-text-editor.vim-mode-plus.normal-mode':
  'm m': 'bookmarks:toggle-bookmark'
  'm n': 'bookmarks:jump-to-next-bookmark'
  'm p': 'bookmarks:jump-to-previous-bookmark'
  'm l': 'bookmarks:view-all'
  'm c': 'bookmarks:clear-bookmarks'
```

Related:
https://github.com/t9md/atom-vim-mode-plus/pull/274 this PR is what you want, but I suggested to implement it as vmp-plugin package.
And prepared API for necessary to implement this kind of packages in https://github.com/t9md/atom-vim-mode-plus/issues/276
@adityavm was him who sent original PR.

And I'm not sure in following situation
Vim's mark can set multiple mark in single line. How to indicate this?

Btw my workfrow to quickly moving in buffer is use [cursor-history](https://atom.io/packages/cursor-history) package, its auto-saved and I don't have to remember multiple keymaps.

**Comment by chenglou** [comment]
Sorry for the late reply. I do use cursor-history (thanks for that!).
It turned out that I don't really need the bookmark history. Closing this! =)
