### ISSUE TITLE
Can't switch to insert mode.

### ISSUE THREAD

**Issue by roachsinai** [t9md/atom-vim-mode-plus#304]
I wrongly pressed 'ctrl-c' and 'crtl-v'. Then I pressed 'crtl-v' again. But I can't switch to insert mode anymore, even  after I restarted atom. If I set vim-mode-plus 'start in insert mode', the first time I open a file I was in insert mode. But if I press 'esc', I can't back to insert mode. 

And I also reinstalled 'vim-mode-plus', the problem also exists. What should I do? :( :(((((

Laptop: Fedora24 x86_64.

**Comment by t9md** [comment]
Do you install other community package(packages except core)?
If so disable all the package and enable ONLY vim-mode-plus then try.

**Comment by roachsinai** [comment]
I did what you told me. It didn't work.
I reboot my laptop, everything OK. Whether I enable other packages or not.

**Comment by t9md** [comment]
So you are no longer have problem now?
Rebooting computer solved this issue?
If you can reproduce it please report more detail, if not, close issue.

**Comment by roachsinai** [comment]
Sorry, can't reproduce it.

**Comment by roachsinai** [comment]
Hi, maybe I found something.
As a Chinese, I use Chinese input method. And there are two input motheds in my PC, ibus-libpinyin(fedora23 default), another is ibus-rime(sudo dnf install ibus-rime).

When I change to the ibus-libpinyin method, I can't input any chars after I enable your package. 

Same like can't input Chinese use these two Chinese input method in sublime_text(you know, a text editor), if I do nothing to input method.

So, the problem is about different input method? 
But if I disable your package, these input methods are work well( can input Chinese and English chars).

**Comment by t9md** [comment]
Is this issue still happen with [vim-mode](https://github.com/atom/vim-mode)?
How did you solve sublime's issue and that approach is effective to this issue?
When you cant input any char(?? can't enter `inert` mode? not sure). What atom's keybinding-resolver(`cmd-.`) says each of your key-input?

**Comment by roachsinai** [comment]
Yes, ibus-libpinyin still doesn't work.
If I use ibus-rime, can enter _insert_ mode.
Solve sublime problem, I have to use Fcitx input frame, not ibus. [Sublime input method fix](https://github.com/lyfeyaj/sublime-text-imfix)
So, what I found is ibus-libpinyin (fedora23 default Chinese input method) can't work with vim-mode. But ibus-rime does work.

**Comment by t9md** [comment]
OK, what about my other question? keybinding-resolver?

**Comment by roachsinai** [comment]
Keybinding-resolver: a low case character **a** and a '.' above this character, If I input all those numbers and characters. Others, like 'shift', 'capslock', 'f1', 'home' are OK.

**Comment by t9md** [comment]
Sorry I can't understand your explanation, maybe my english undestanding is limited.
To make things simple, I want to know following information.

1. activate keybinding resolver when your are in normal-mode
2. type `i` to enter insert-mode and observe what keymap-resolver report your keystroke

**Comment by roachsinai** [comment]
Yeah, keymap-resolver does report the keystroke! But the report is just an odd character, if I type `i`.
Maybe,I can't describe it correctly. So, I sent a mail with a screenshot to your gmail.

What's more, if I type `shift i`, resolver report as it should be (work well). Same result as `o`, `a`, with `shift` will be OK.

And, I all type like `w`, `x`, keymap-resolver alse report that odd character.

![unnamed](https://cloud.githubusercontent.com/assets/9500049/16898362/4207eb32-4b9c-11e6-95e4-fd4f3b91369b.png)

Above is that **odd** character, the resolver doesn't report anything but these 3 words and an odd char, when I type `i`.
OK, now I know how to add an image :-(. 
Dragging & dropping, :-(.
Or, pasting! :-(

**Comment by t9md** [comment]
I just want to stick one key `i` for simplicities.
When you type i, its NG but for I its OK right?
How about keymap-resolver of i when you disabled vmp.

**Comment by roachsinai** [comment]
YES. When I type `i`, it NG but for I its OK.
If I disabled vmp:

1. When I type `i`, resolver report that odd character, too.
2. When I type `I`, resolver report `shift-I`.

**Comment by t9md** [comment]
In that case with having vmp disabled, can you type `i` character by the key i?
What char is inserted when you type i?

**Comment by roachsinai** [comment]
I can type `i` character by the key i with having vmp disabled, though the resolver reports that odd charactor.

**Comment by t9md** [comment]
Ok. Thanks.
Btw I don't think I can solve this issue with my vmp package.
Keybinding system is provided as atom-keymap node module, it bind keystroke to key event. Its out of scope of each package I believe.
Do you use normal US keyboard layout? If not have you check keyboard-localization package?
What is special for vmp and vim-mode's normal mode is it disables input for editor component.
https://github.com/t9md/atom-vim-mode-plus/blob/master/lib/mode-manager.coffee#L80

This might make inout method bahave differently, but not sure. Anyway how it should be is keystroke you typed is correctly resolved what you type in keybinding resolver.

**Comment by roachsinai** [comment]
My keyboard layout is cn. 
And zh_CN(China) is not in the keyboard-localization package supported list.
Thank you.
