### ISSUE TITLE
use "jk" in insert mode to activate normal mode

### ISSUE THREAD

**Issue by jinjiren** [t9md/atom-vim-mode-plus#305]
I want to use "j k" instead of "ESC" to activate normal mode, and I have tried adding following code in keymaps.cson:

```
'atom-text-editor.vim-mode-plus.insert-mode':
  'j k': 'vim-mode-plus:activate-normal-mode'
```

but it doesn't work. Do you have any suggestions?

**Comment by t9md** [comment]
I'm doing exactly the same thing in my [dotfiles](https://github.com/t9md/dotfiles).
Your keymap seems not problem as long as you don't use same CSS selector scope twice in `keymap.cson`.

See this comment for detail.
https://github.com/t9md/atom-vim-mode-plus/issues/291#issuecomment-225481880

**Comment by jinjiren** [comment]
@t9md Thanks for your reply! I checked that again and finally found that it acctually worked when I started a new window of Atom...
I just started to use Atom today, and I'm sorry for making such mistakes :(
Anyway, thank you for your suggestions to help me avoid that kind of problems in future.
