### ISSUE TITLE
Cant move to last char, even with right navi key

### ISSUE THREAD

**Issue by AlexanderChen1989** [t9md/atom-vim-mode-plus#306]
![image](https://cloud.githubusercontent.com/assets/2957936/16756401/5db74854-4837-11e6-952a-7da578950325.png)

**Comment by AlexanderChen1989** [comment]
When I uninstall vim-mode, bug fixed

**Comment by t9md** [comment]
It's not bug. READ README.md first before opening issue and claim it's bug.
