### ISSUE TITLE
[bug?] Undo state is wrong, undoing causes weird changes to code.

### ISSUE THREAD

**Issue by trusktr** [t9md/atom-vim-mode-plus#307]
I was trying to undo, and each undo (pressing `u`) the editor inserting text in weird fashion, not the text as I had before.

I'm not sure if this is an issue with `vim-mode-plus`, or if another package is the culprit. I also have the `persistent-undo` package installed, could that be interfering with the undo state somehow?

**Comment by t9md** [comment]
I believe this issue is caused with combination of persistent-undo package,

- Give me precise procedure to reproduce this issue.(condition, operation, screen capture).
- Issue still happen even if you disable `persistent-undo`?

**Comment by trusktr** [comment]
It happened again (second time ever for me), but I'm not sure exactly what caused it. I'll keep paying attention.

I did however realize that when it happens, then if I close and reopen the tab (not more than one tab with the file), then the problem goes away and undoing a few ways back seems to introduce the correct modifications to the file. When the error happens, I just have to be sure not to save!! I'm not sure if it'll corrupt file data, or if it's just a rendering problem.

**Comment by t9md** [comment]
Reopen if you saw again and found how to reproduce.
I haven't see this issue.
So what I can do is nothing, will close-to-re-evaluate.
