### ISSUE TITLE
Exiting visual blockwise mode requires Escape to be hit twice after having insert text

### ISSUE THREAD

**Issue by benlakey** [t9md/atom-vim-mode-plus#308]
Exiting visual blockwise mode appears to require that `ESC` be hit twice after having inserted text.

1. Enter visual blockwise mode (`CTRL-v` from normal mode)
2. Select a column
3. Insert some text (`SHIFT-I` and then type)
4. Hit `ESC`

At this point you are back in normal mode but there is still a column of cursor. You then have to hit `ESC` again one more time for the column of cursor to stop.

This differs from vim in that pressing `ESC` after a column insertion drops you back into normal mode with no column of cursor. 

Is this something that can be addressed in the plugin? Or with a key binding change?

**Comment by t9md** [comment]
I understand your point.
I intentionally keep cursor(=or selection) after escaping from `inesert` mode.
Yes behavior diff, but some people think this is useful to work with multiple cursor(=or selection).

If you don't like this diff, try following snippet.
Paste this in your `init.coffee`. and restart Atom.

```coffeescript
consumeService = (packageName, providerName, fn) ->
  disposable = atom.packages.onDidActivatePackage (pack) ->
    return unless pack.name is packageName
    service = pack.mainModule[providerName]()
    fn(service)
    disposable.dispose()

consumeService 'vim-mode-plus', 'provideVimModePlus', (service) ->
  {observeVimStates} = service

  observeVimStates (vimState) ->
    vimState.modeManager.onDidDeactivateMode ({mode}) ->
      if mode is 'insert'
        vimState.editor.clearSelections()
```

**Comment by benlakey** [comment]
Excellent. This solves my issue.

Want me to create a pull-request to update the FAQ?

**Comment by t9md** [comment]
Added Tips here https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#clear-multiple-selection-when-escaped-from-insert-mode
