### ISSUE TITLE
AParagraph on one-line paragraph should include trailing blank line

### ISSUE THREAD

**Issue by jdanbrown** [t9md/atom-vim-mode-plus#309]
It does include the trailing blank line on multiline paragraphs, but fails to include the trailing blank line on one-line paragraphs. Illustration with `Vap`:

|||
|---|---|
| <img width="373" alt="screen shot 2016-07-15 at 13 01 49" src="https://cloud.githubusercontent.com/assets/627486/16886998/5905ef16-4a8c-11e6-8779-850ad871e3e3.png"> | <img width="375" alt="screen shot 2016-07-15 at 13 02 03" src="https://cloud.githubusercontent.com/assets/627486/16886999/5a91de76-4a8c-11e6-86a4-3d2ff94146a6.png"> |

**Comment by jdanbrown** [comment]
Additional illustration with `dap`:

||||
|---|---|---|
| <img width="365" alt="screen shot 2016-07-15 at 13 03 20" src="https://cloud.githubusercontent.com/assets/627486/16887038/9671abec-4a8c-11e6-9db5-99c79dbd3675.png"> | <img width="364" alt="screen shot 2016-07-15 at 13 04 36" src="https://cloud.githubusercontent.com/assets/627486/16887056/bcd96fea-4a8c-11e6-9446-4d037f25c44a.png"> |
| <img width="368" alt="screen shot 2016-07-15 at 13 05 40" src="https://cloud.githubusercontent.com/assets/627486/16887094/deab3ad6-4a8c-11e6-91f7-a735c865765f.png"> | <img width="359" alt="screen shot 2016-07-15 at 13 04 45" src="https://cloud.githubusercontent.com/assets/627486/16887068/c7ba4114-4a8c-11e6-89a3-9463acbd1d60.png"> |

**Comment by t9md** [comment]
Oh, indeed.. thanks for reporting.

I'll check to see how I can fix this.

**Comment by jdanbrown** [comment]
Thanks!
