### ISSUE TITLE
ScrollDown/ScrollUp broken by inline images

### ISSUE THREAD

**Issue by jdanbrown** [t9md/atom-vim-mode-plus#310]
Using [hydrogen](https://github.com/nteract/hydrogen)'s inline images in combination with vim-mode-plus breaks ScrollDown (^E) / ScrollUp (^Y). Not sure which code is doing the wrong thing, figured I'd start here.

Repro:
- Above inline image:
  - ScrollDown moves +1 (as expected)
  - ScrollUp moves -1 (as expected)
- Below inline image:
  - ScrollDown moves +13
  - ScrollUp moves +11

![bug-6](https://cloud.githubusercontent.com/assets/627486/16892154/c918029e-4abe-11e6-82fa-a9ad2e3d55c9.gif)

**Comment by t9md** [comment]
Confirmed fixed in latest version.
