### ISSUE TITLE
Question: How to search and replace?

### ISSUE THREAD

**Issue by NoahDragon** [t9md/atom-vim-mode-plus#320]
Hello,

I'm a noob for VIM, this question may be dumb or duplicate.

Is there any way to search and replace strings in a document?

Thanks

**Comment by t9md** [comment]
Use atom's native way. Cmd-shift-f.
Refer atom's well written good manual on official site for detail.

**Comment by NoahDragon** [comment]
@t9md Thanks. 
Just curious, is there any plan that vim-mode-plus will support VIM style search and replace?

**Comment by t9md** [comment]
No.
