### ISSUE TITLE
Visual Line Mode Bugs

### ISSUE THREAD

**Issue by irrationalistic** [t9md/atom-vim-mode-plus#325]
There are a couple bugs with visual line mode.

First, it no longer handles out-dented content well. Test by creating a new text file, put in the following content:
```
test
  testing
  test 1

whatever
```
Put the cursor on the first (or second or third) line, switch to visual line mode with `V`, then try to move it down to "whatever." I am unable to progress that far. However, starting on the 4th line works, selecting down, and starting on the last line works selecting upwards.
![vmp-linewise-nodown](https://cloud.githubusercontent.com/assets/851856/17561688/1241f160-5edc-11e6-80ba-f174593c980c.gif)

Second, with the same text content, put the cursor on the first line, switch to visual line mode, then try to select to the last line. Press `o` to switch selection to the top of the block. Press `j` to move down. Observe the selection changes strangely.

Similarly, follow the same steps but press `k` to move up and observer another issue.

Finally, move the cursor to the 4th line and switch to visual line mode. Start selecting upwards with `k`. Observe that the selection does not actually expand.

Hopefully this is enough information! I am thinking these issues are pretty closely related, but if not I can split them out into separate reports! I am currently using Atom 1.8.0. I believe these issues all correlate to not being able to select that "whatever" line, since my guess is that the selections get out-of-sync.

**Comment by t9md** [comment]
> Put the cursor on the first (or second or third) line, switch to visual line mode with V, then try to move it down to "whatever." I am unable to progress that far.

You mean you cant select 4th line('whatever') line? Not in my case.

Btw latest vim-mode-plus support onl [atom 1.9.0 or later](https://github.com/t9md/atom-vim-mode-plus/blob/master/package.json#L10).
What's version of vmp are you using?

Anyway the issue you report is not exist for older version.

**Comment by irrationalistic** [comment]
Ah, I understand. I am using 1.8 so that is probably it :) I'll close for now since I cannot update version yet.

**Comment by t9md** [comment]
What the version of your vim-mode-plus?

**Comment by irrationalistic** [comment]
0.50.0. Does that change anything?

**Comment by t9md** [comment]
Humm, You use 1.8 right? and if so, you can't install 0.50.0 it demand minimum atom version 1.9.0 later?
Sorry I cannnot understand your situation, please make it clarify your version, environment, issue if you need further assistance.

**Comment by irrationalistic** [comment]
It's possible that i upgraded then downgraded :)
