### ISSUE TITLE
gg and G do not work in treeview

### ISSUE THREAD

**Issue by udnaan** [t9md/atom-vim-mode-plus#326]

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/pull/133

Out of scope of this package for setting keymap of tree-view.
Set it by yourself if you want.

**Comment by udnaan** [comment]
I understand. Just so you know that it seems to work in vim-mode which this package is suppose to be a superset of, not subset. 

Thanks

**Comment by t9md** [comment]
Vim-mode pulled PR to add tree-view keymap, but vim-mode-plus didn't.
I just made different decision. Not trying to blindly being superset of vim-mode.

**Comment by udnaan** [comment]
Fair enough. Thanks for your response.
