### ISSUE TITLE
Add option to keep cursor fixed when using `vim-mode-plus:scroll-{direction}`

### ISSUE THREAD

**Issue by kress95** [t9md/atom-vim-mode-plus#329]
I'm using these commands to scroll over my code on both insert and normal modes.

```
vim-mode-plus:scroll-up
vim-mode-plus:scroll-down
vim-mode-plus:scroll-left
vim-mode-plus:scroll-right
```

I wanted to use them to be able to look over my code without changing the cursor position, but the cursor just follows the view.

Since changing the behavior is **not ok**, I suggest adding a checkbox option to toggle this `cursor-following-view` behavior of these scroll functions (and perhaps of the others too) and let it checked by default.

I didn't wanted to create a separate plugin or change my init script to add this since `vim-mode-plus` almost nails this functionality.

**Comment by t9md** [comment]
You don't want to use mouse scroll for that purpose?
If you are in MacOS two finger swipe down on track-pad do that behavior.

**Comment by t9md** [comment]
Also ctrl-y and ctrl-e in normal-mode don't move cursor. Also incremental-search allow you to scroll searching word without changing cursor.
All options not acccommodate your use case?

**Comment by kress95** [comment]
The point is not using the cursor, the two finger swipe works here too, but just moves too fast.
Both `ctrl-y` and `ctrl-e` moves the cursor with the view.

I don't know how vim behaves by default (I never used vim, really, I'm trying to learn now), so maybe adding a switch for that is out of this project's scope.

**Comment by t9md** [comment]
I understand your suggestion for new behavior swiching option, no need to knowledge for original Vim behavior, if it improve productivity I'll consider to implement it.
Thanks for new idea.
But I need evaluation to know amount of complexity it will introduce to current code-base vs how much it is useful.

**Comment by kress95** [comment]
I've found a pretty lightweight plugin that does exactly what I wanted, so this will not be a problem for now, my only fear is with the plugin breaking with updates and the author won't noticing it (no updates since January, but maybe this API is frost).

But I gave the source a look and maybe I'm able to update it, so, unless you're interested on including this feature it's no issue for me anymore.

**Comment by t9md** [comment]
I quickly evaluated how it is like and I found that I don't want to includes it directly into vim-mode-plus.
If you want, you can try and modify it based on following example below.

https://github.com/t9md/atom-vim-mode-plus/wiki/Extend-vmp-in-init-file#advanced-modifying-existing-motion

**Comment by kress95** [comment]
Alright, thanks anyway :)
