### ISSUE TITLE
Is there a way to disable all ctrl based vim keys

### ISSUE THREAD

**Issue by slifin** [t9md/atom-vim-mode-plus#332]
I'd like to use things like 
select all: ctrl + a
copy: ctrl + c
paste: ctrl + v 
close tab: ctrl + w 

there's probably some others I've forgotten

**Comment by t9md** [comment]
Neither Atom core or vim-mode-plus doesn't provide direct solution.
You can re-override those keymap by yourself.
Or
Try https://atom.io/packages/disable-keybindings. You can disable specific keybinding.

This is very similar topic of [this](https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#how-can-i-use-ctrl-w-to-close-pane).
