### ISSUE TITLE
Highlight current line with mode color?

### ISSUE THREAD

**Issue by miguelcarax** [t9md/atom-vim-mode-plus#333]
It's possible to highline the color based on the actual mode? Ex. get current line at yellow at normal mode or blue at insert mode, thx.

**Comment by t9md** [comment]
I added wiki.
Read [this](https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#change-style-depending-on-operation-mode).
For further customization, please ask atom community via slack or [atom discuss](https://discuss.atom.io/).
