### ISSUE TITLE
surround not working with backticks and underscores

### ISSUE THREAD

**Issue by ssfrr** [t9md/atom-vim-mode-plus#336]
On my linux machine running atom 1.8, I can use vim-mode-plus's surround features to surround with backticks and underscores, but on my OSX machine (with the below versions) it doesn't seem to work. I have the following in my keymap:

```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'g q': 'autoflow:reflow-selection'
  's': 'vim-mode-plus:surround-smart-word'
  's d': 'vim-mode-plus:delete-surround-any-pair'
  's c': 'vim-mode-plus:change-surround-any-pair'
  's y': 'vim-mode-plus:surround'
```

but if I type ```s ` <any key>```, the word seems to be surrounded with whatever letter I press after the ``` ` ```. If I run ```s _ <any key>``` then the paragraph is surrounded by the third key. Any thoughts on how to troubleshoot?

Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
vim-mode-plus@0.52.0

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/blob/master/ISSUE_TEMPLATE.md

Pleae report keybinding resolver's result.

**Comment by t9md** [comment]
Oh I might introduce some bug in 0.52? Will check immediately.

**Comment by ssfrr** [comment]
I tried backing down to version 0.46 (which works on my linux machine) and it doesn't seem to work there, so I don't think it's a regression in vim-mode-plus. Seems it's either a difference between atom 1.8 and 1.9 or something different between my systems.

Maybe something's changed with how 1.9 handles multi-character keybindings? On 1.9 (the one that's not working),  it looks like if I press `s (` it activates the `vim-mode-plus:set-input-char-)` matching in `vim-mode-plus-input-char-waiting`. I'll have to wait until Monday to check behavior on my other machine.

Interestingly, if I press `s` and then wait a sec, it matches `vim-mode-plus:surround-smart-word` so it's probably unhappy that my smart word keybinding is the same as the prefix for the other surround commands. It seems to work in Atom 1.8 though.

**Comment by t9md** [comment]
Yep not regression, I can surround with `\`` and `_` without any issue.

**Comment by ssfrr** [comment]
OK. I just changed by keybinding to `S` instead of `s` so it doesn't conflict with the other prefixes and it's working well. Minor bummer that it worked on Atom 1.8 but not 1.9, but not a big deal.

**Comment by t9md** [comment]
Not sure why 1.8 worked.
For the `s` issue(`s` is used to as mapping to command and also used as prefix key).
This issue is not fixable by vim-mode-plus, as I described in https://github.com/t9md/atom-vim-mode-plus/issues/327. When multi keystroke is settled, atom-keymaps replay the pending keystroke to emulate user's keystroke, but when it replay keystroke it won't follow change of activeElement
Since surround change focus to get user input via input-form, it wont properly work when replayed.

https://github.com/atom/atom-keymap/issues/130
