### ISSUE TITLE
Is there a way to make the mode switch to normal upon loss of focus?

### ISSUE THREAD

**Issue by NullVoxPopuli** [t9md/atom-vim-mode-plus#337]
Where I'm running in to issues is when I'm switching tabs.
I have my left/right tab navigation bound to o and p in normal mode, and if I come across a pane not in normal mode, either typing or some other action happens.

Is there a way I can make the pane go back to normal mode?

```
$ atom --version
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

even if it's something I have to put in init.coffee, I'm cool with that. :-)
I've already changed a ton of the shortcuts and styles anyway. :-)

**Comment by t9md** [comment]
I tried it by myself and it reveals minor bug of vim-mode-plus.
So I will fix that bug to make it easy what you want. Wait for a moment.

**Comment by t9md** [comment]
Try [this](https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#escape-insert-mode-when-focus-lost) when v0.53.0 released.

**Comment by NullVoxPopuli** [comment]
@t9md I didn't even know there was a bug!

btw, I'm already doing something similar with: https://github.com/NullVoxPopuli/dotfiles/blob/master/home/.atom/keymap.cson#L84

I think I just need to bind to whatever `:blur` event on `atom-text-editor` and trigger `vim-mode-plus:activate-normal-mode`

**Comment by t9md** [comment]
Yeah, your approach to bind 'blur' is correct, but it won't work because of bug I described #338.
Trying to answer your question result in fix of very important bug. 
Thank for great question!

**Comment by NullVoxPopuli** [comment]
oh! well, I'm glad I could help!

I'll post my result when I figure it out :-)
(workin on other stuff atm)

**Comment by t9md** [comment]
released v0.53.0

**Comment by NullVoxPopuli** [comment]
Here is what Lee Dohm and myself came up with:

```coffeescript
##################################################
# Force Vim Mode Plus to be in normal mode on blur
##################################################
activateNormalMode = 'vim-mode-plus:activate-normal-mode'

atom.workspace.observeActivePaneItem (activeItem) =>
  for item in atom.workspace.getPaneItems() when item isnt activeItem
    element = item.editorElement
    className = element?.className

    isVimMode = className?.includes('vim-mode-plus')
    isNormalMode = className?.includes('normal-mode')

    if isVimMode and not isNormalMode
      atom.commands.dispatch(element, activateNormalMode)
```

**Comment by t9md** [comment]
example I put on wiki by this comment didn't work?
https://github.com/t9md/atom-vim-mode-plus/issues/337#issuecomment-242980290

**Comment by NullVoxPopuli** [comment]
oh! *that's* what you were talking about

```coffeescript
atom.commands.add 'atom-text-editor.vim-mode-plus.insert-mode', 'blur', ->
  atom.commands.dispatch(this, 'vim-mode-plus:reset-normal-mode')
```

So, I don't know the api here, but `atom.commands.add` is used for adding commands *for* hotkeys? does it have other purposes? like how you use it?

I see this: https://atom.io/docs/api/v0.210.0/CommandRegistry#instance-add
so, `blur` is a *command* that this should handle.

It works! (just tried it in a new atom window).

Thanks! I def feel less horrible about looping through everything now. :-)

**Comment by NullVoxPopuli** [comment]
why reset-normal-mode rather than activate?

**Comment by t9md** [comment]
`activate-normal-mode` is fine. The caveat of my example is it escape `insert-mode` on `blur`, so if you use command-palette, it returns to `normal-mode`. 
Your version is more limited to only paneItem change.

**Comment by NullVoxPopuli** [comment]
oh cool.

So, I made one small modification:

```coffeescript
toNormalMode = 'vim-mode-plus:reset-normal-mode'
selector = 'atom-text-editor.vim-mode-plus:not(.normal-mode)'

atom.commands.add selector, 'blur', ->
  atom.commands.dispatch(this, toNormalMode)
```

I also wanted to return to normal mode if I was in visual mode.

Man, I wasted like.. 20 minutes earlier today, and all I had to do is read the wiki better! ha
(isn't that everyone's problem?) :-)

**Comment by t9md** [comment]
> Man, I wasted like.. 20 minutes earlier today, and all I had to do is read the wiki better! ha
(isn't that everyone's problem?) :-)

hahaha, it's always. But experimenting things by oneself is fun. 😄

**Comment by NullVoxPopuli** [comment]
> But experimenting things by oneself is fun. 

I did learn a lot about Atom's API today :-)

**Comment by t9md** [comment]
> So, I don't know the api here, but atom.commands.add is used for adding commands for hotkeys? does it have other purposes? like how you use it?

You can register any valid [Event](https://developer.mozilla.org/en/docs/Web/Events) as commandName.
Since Atom's command is listener function bound to specific event which event name is commandName.
As you can bind `click` or `blur` to DomNode, Atom command system dispatches event(=commandName) to appropriate listener function.

So you can do like this
```coffeescript
atom.commands.add 'atom-text-editor', 'click', (event) ->
  console.log 'clicked'
```
OR
Instead of bind your command by matching CSS selector as in above example, you can also bind listener function to specific DOM Element like below.

```coffeescript
editorElement = atom.workspace.getActiveTextEditor().editorElement
atom.commands.add editorElement, 'click', (event) ->
  console.log 'clicked'
```
