### ISSUE TITLE
Canceling auto−complete popup by Escape trigger mode change to normal-mode

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#339]
I noticed this via [this tweet](https://twitter.com/yinm_cminor9/status/769890375540445184)

autocomplete-plus also using `escape`, and its bound to `auto-complete-plus:cancel`
https://github.com/atom/autocomplete-plus/blob/master/keymaps/autocomplete-plus.cson#L5

Because atom command is propagated,  `escape` to cancel autocomplete-plus's popup also trigger `vim-mode-plus:activate-normal-mode`.
I this is not normal user expect, what normal user expect is `escape` only close popup and remain in `insert-mode`.
If user really want to escape `insert-mode`,  another `escape` should be typed.
Current behavior taking the choice by user. Not good.

**Comment by lukebarton** [comment]
This issue brought me here, because it was resolved - it's now super annoying to hit escape twice, just because the autocomplete prompt happened to be showing.

Can we have an option?

**Comment by t9md** [comment]
Oh understand. Sorry.
I don't want to provide option.
What Im thinking is to **revert** to previous behavior.
Original issue have simple solution to set explicit keymap to close autocomplete popup.
Thanks for notifying this. Will revert soon.

**Comment by lukebarton** [comment]
In the meantime:
`'atom-text-editor.vim-mode-plus:not(.normal-mode)':
  'escape': 'vim-mode-plus:activate-normal-mode'`

**Comment by t9md** [comment]
I wrote following wiki.

https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#in-insert-mode-hitting-escape-to-close-autocomplete-popup-result-in-normal-mode-but-want-to-remain-in-insert-mode

**Comment by averrin** [comment]
Yeah, I want close autocomplete AND escape insert mode. Can you release this revert?

**Comment by t9md** [comment]
released patch as v0.54.1

**Comment by averrin** [comment]
Thanks! :+1:
