### ISSUE TITLE
tab key in normal mode

### ISSUE THREAD

**Issue by mattsawyer77** [t9md/atom-vim-mode-plus#34]
Wondering if the tab key can be prevented from indenting text while in normal mode. I tried to map it as follows:

```cson
'atom-text-editor.vim-mode-plus.normal-mode':
  'tab': ''
```
but it didn't seem to have any effect.

**Comment by t9md** [comment]
This is not actually package specific issue, but anyway I'll share what I know.

To directly translate what you want (disable `tab` effect on `normal-mode` right?), here it is.

```
'atom-text-editor.vim-mode-plus.normal-mode':
  'tab': 'unset!'
```

But this unbind `tab`'s atom's keymap and then `tab` works as chrome's native-keybind which means focus next focusable element. So I think this will better fit for your purpose.

```
'atom-text-editor.vim-mode-plus.normal-mode':
   'tab': 'vim-mode-plus:reset-normal-mode'
```

**Comment by mattsawyer77** [comment]
@t9md Tried the second snip of code you posted. Works perfectly, thanks!

**Comment by t9md** [comment]
Good!
