### ISSUE TITLE
[new Operator] ReplaceString or ReplaceCharacter

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#340]
# What I want

Replace Text-1 to Text-2 quickly

### Text-1
```
min:1, max:3, update:true, link:false
```

##### Case-1 ( replacing `,` to empty string(`''`) to remove `,`
`min:1 max:3 update:true link:false`

##### Case-2 ( then replacing `:` to comma and space (`: `) to add padding.
`min: 1 max: 3 update: true link: false`

# Why?

Atom have already find-and-replace package to replace text.
But for trivial string replacement, its too big(heavy).
I want easy and quick character replacement in lighter way.

**Comment by Haggus** [comment]
The way I do this in Atom:

1. Go to insert mode
2. Select the first ","
3. Keep pressing Ctrl+D to select them all
4. Backspace to delete
5. Select the first ":"
6. Ctrl+D
7. Right arrow (to move one right)
8. Space

This works, but I also feel is not ideal. What is the "correct" way of doing this in vim?

**Comment by t9md** [comment]
In pure Vim, there is no ctrl-d(Atom is better for this part), but pure Vim has ex-mode which allos you to 'select' then `:` then `s!,! !` replace , to single space. You can use any char for separator like `s#,# #`.

In atom you can also do ctrl-d without entering inser-mode in the first place then `c space` or `r space`.

If your target range is big and there is multiple instance of `,`, range-marker would very useful.
Range-marker is original feature of vmp(I still not documented well).

Anyway in this new feature I want quick char replacement like `g r , space i p`.
`g r` is mapped to replace-char
`r` replaced to `space` and target range is `i p` inner-paragraph.

**Comment by t9md** [comment]
Oh, I should(wanted to) link above commit to #344.

**Comment by t9md** [comment]
Close in favor of #357 
This issue is the original trigger to reach to occurrence operator modifier.
