### ISSUE TITLE
Visit next match in same direction of original search

### ISSUE THREAD

**Issue by alha02** [t9md/atom-vim-mode-plus#343]
When we do an incremental search, pressing the tab button will always visit the next match (downwards in buffer), while shift-tab will always visit the previous match (upwards in buffer). 

It would be great if there was a setting so that the behaviour would be that tab goes to the next match in the direction of the original search, i.e. downwards if search started with "/" and upwards if started with "?", while shift-tab would go in the opposite direction. This would also be consistent with using "," and ";" for find next. #

**Comment by t9md** [comment]
Currently not.
Will try to experiment and evaluate it.

**Comment by t9md** [comment]
New `incrementalSearchVisitDirection` config option control this.
I tried, but it didn't fit me(I believe it's counter intuitive for most user).
But I will include experimentally to next release(v0.54.0), will see.
Thanks for suggestion.
