### ISSUE TITLE
Redo occasionally leaves editor in multi-cursor mode.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#35]
I believe that undo/redo should never leave the editor with any visual selection (multi or single). There should probably be a check to make sure this never happens.

**Comment by t9md** [comment]
@jordwalke This issue is still active? I myself didn't see this issue.
Can I close this issue?

**Comment by jordwalke** [comment]
Can close. Have not seen in a long time.
