### ISSUE TITLE
Paste text at an empty line will cause the text appears at the head of next line

### ISSUE THREAD

**Issue by li-zhirui** [t9md/atom-vim-mode-plus#359]
- Atom version : 1.10.2
- vim-mode-plus version : 0.54.1

Paste text at an empty line should put the text in the front of that line, but current implementation puts the text at the head of next line. This bug occurs might because the `put-after` command puts the text after current char, but if the line is empty, it only contains a `'\n'` char, and then the text appears at the next line.

**Comment by t9md** [comment]
Thanks, I'll fix it later.
