### ISSUE TITLE
d keybinding throws exception

### ISSUE THREAD

**Issue by Cutuchiqueno** [t9md/atom-vim-mode-plus#362]
- Atom version: 1.10.0
- vim-mode-plus: latest
- System: Arch Linux, i3wm
- vim-mode is deinstalled

any `d`-key related action like `dd` or `d` in visual mode results in:

    Uncaught Error: Cannot read property 'object' of undefined TypeError: Cannot read property 'object' of undefined at ObjectsRegistry.get (/usr/lib/electron/resources/electron.asar/browser/objects-registry.js:44:28) at EventEmitter. (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:305:31) at emitMany (events.js:127:13) at EventEmitter.emit (events.js:201:7) at WebContents. (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:218:13) at emitTwo (events.js:106:13) at WebContents.emit (events.js:191:7)

**Comment by t9md** [comment]
https://github.com/atom/atom/issues/11692
