### ISSUE TITLE
[idea] selectOccurrenceBySelectList

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#373]
Occurrence modifier is very powerful feature to bulk-edit multiple instance of  keyword.
But sometime picking keyword under cursor is not sufficient.
So I provided "Select occurrence of keyword by pattern" feature using incremental-search UI.
But still another glitch, pattern have to be manually input by your finger, the idea of `selectOccurrenceBySelectList` is to provide `selectList` to choose commonly used pattern.
1. invoke selectOccurrenceBySelectList
2. select list opens.
3. pick the one like `Number` which is representing `/\d+/g` pattern.
4. Specify target(motion or text-object).
5. selectOccurrence of text that matches `/\d+/` would be selected.
# What pattern do we need to provide?

Just idea. give me your idea!
- Hexadecimal Number: `0[xX][0-9A-F]+`
- Number
- IP Address
- Capital word: `[A-Z][a-zA-Z]+`

Not much good idea... but will try after I finished this time intensive refactoring...

**Comment by zhaocai** [comment]
I like this idea :+1: 

I think the patterns in the select list should be customizable. 

One thing I repeat most is to select occurrence of keyword with `-` like `atom-vim-mode-plus`; Have to do it from search or visual selection for now.

**Comment by t9md** [comment]
> P.S. I just notice select-occurrence in visual-mode does not work as expected - it is supposed to use the visual selection for occurrence selection like select-occurrence-from-search.

![select-occurrence](https://cloud.githubusercontent.com/assets/155205/18569583/73f7f87c-7bde-11e6-9457-c5e183ad23a7.gif)

`select-occurrence` is mapped from `cmd-d` in `visual-mode`. 
It's pick the keyword from cursor position and select matches within visually selected range.
The GIF is select some line, then `cmd-d` on `param` keyword that result in all the `param` keyword selected in that visual area.

Doesn't this work for you? I couldn't get the meaning of your comment sorry.

**Comment by t9md** [comment]
This visual are only search for occurrence behavior is activated only on multi-line seleciton.
This does not work for single line selection(not including `\n`), `cmd-d` is preserved for native `find-next` command to avoid interfering existing feature.

**Comment by zhaocai** [comment]
> select-occurrence is mapped from cmd-d in visual-mode. 
It's pick the keyword from cursor position and select matches within visually selected range.

I think this behavior is **unexpected** because the cursor serves two purposes: 

1. mark range
2. mark keyword for occurrence selection

Therefore, it is hard to get both range and keyword right. Use the gif you provide as example. What do I do if I want to select the occurrence of `@instanceof` in this function?

![visual-select](https://cloud.githubusercontent.com/assets/155205/18569583/73f7f87c-7bde-11e6-9457-c5e183ad23a7.gif)

It is better to mark range first, then select occurrence within the marked range with `i r`	( if the range is not easily define by predifined range like `i z`, `i f`, etc. )

I think the **expected** behavior is to use the **visual selection** to trigger **operator-pending-mode** for occurrence selection like `select-occurrence-from-search`.

**Comment by t9md** [comment]
> I think this behavior is unexpected because the cursor serves two purposes:
> 
> mark range
> mark keyword for occurrence selection
> Therefore, it is hard to get both range and keyword right. Use the gif you provide as example. What do I do if I want to select the occurrence of @instanceof in this function?

I can't understand your point sorry.
You want select `@instanceof` within selection? In that case you can 

1. `v j j j j` to select area
2.  then `/` to invoke search(`?` is better to prevent inc-search scroll-down in most case)
3. input `@instanceof`
4. `cmd-d` (explicit  keymap configuration needed for non Mac user)
5. all occurrence of keyword `@instanceof` selected within selection.

Visual-mode's `cmd-d` to select occurrence of word just pick cursor-word, user don't have to specify manually, this is sugar command to accommodate common use-case, no need to be perfect.

If you have better idea to improve, I need keystorke, mode-shift change in each step(I really need to discuss productively!).

> I think the expected behavior is to use the visual selection to trigger operator-pending-mode for occurrence selection like select-occurrence-from-search.

What is the flow of keystroke and state change? Can you explain with explicit keystroke and mode shift?
It's always difficult someone's explaining what the want from sentence.

**Comment by zhaocai** [comment]
> It's always difficult someone's explaining what the want from sentence.

I agree. It is really hard and waste a lot time.

First of all, we are discussing the behavior of **occurrence-selection** from **visual-mode**. I know It can be done from search mode. 

> select the occurrence of @instanceof

What I meant is **this** cannot be done from visual-mode based on current behavior.

---


> I think the expected behavior is to use the visual selection to trigger operator-pending-mode for occurrence selection like select-occurrence-from-search.

I will clear my thought using the following example.

## A. Select `vim-mode-plus-user` occurrence from search

![from-search](https://dl.dropboxusercontent.com/u/1897501/Screencasts/atom-vim-mode-plus_occurrence-selection-from-search.gif)

## keystrokes

`/` `vim-mode-plus-user` `ctrl-d` `i z`

## B. Select `vim-mode-plus-user` occurrence from visual selection
![from-visual](https://dl.dropboxusercontent.com/u/1897501/Screencasts/atom-vim-mode-plus_occurrence-selection-from-visual.gif)

## keystrokes

`v i S` `ctrl-d`

> `i S` : `inner-smart-word` 

### What is the **expected**? 

* after the `vim-mode-plus-user` is selected
* press the hotkey for `vim-mode-plus:select-occurrence`
* trigger `operator-pending-mode` as the hotkey is pressed [from-search](https://dl.dropboxusercontent.com/u/1897501/Screencasts/atom-vim-mode-plus_occurrence-selection-from-search.gif)
* occurrence of `vim-mode-plus-user` is selected


### Why?

Save many keystrokes to type `vim-mode-plus-user` in the search bar.

Of course, I can first `yank` from visual-mode and use `/` to enter search mode, `paste`, ...... However, again, we are discussing the behavior of visual mode.

**Comment by t9md** [comment]
So what you want is picking the search-word to use occurrence from visual selection right?

**Comment by zhaocai** [comment]
> So what you want is picking the search-word to use for occurrence from visual selection right?

Right! All the explanations we did is summed up in one sentence. :ok_hand:

**Comment by t9md** [comment]
If above my understanding is collect, (picking word to use for occurrence from visual area), that's the feature I removed intentionally.

https://github.com/t9md/atom-vim-mode-plus/issues/351
https://github.com/t9md/atom-vim-mode-plus/issues/349#issuecomment-244486353

**Comment by t9md** [comment]
> So what you want is picking the search-word to use for occurrence from visual selection right?
> Right! All the explanations we did is summed up in one sentence. 👌

I always need this kind of short sentence to explain what they want before diving into detail. 😄

**Comment by t9md** [comment]
> If above my understanding is collect, (picking word to use for occurrence from visual area), that's the feature I removed intentionally.

Implementing it is not difficult. but again my intention why I removed that feature is

- Selection should be always treated as target of operator.
- I want to use `cmd-d` keymap to select occurrence in selection that is same keymap of default `select-next` in Mac, and since purpose of command is same except `select-occurrence` is just selection-narrowed.
- Native `select-next` take keyword to find-next from current-selection if selection is not empty

Oh,oh,,, by providing different keymap, I'm getting thinking that I can provide removed feature...

But my brain is not have space to think about it now(I'm doing intensive refactoring for operator).
Think after current task finished.
Thanks for bring me to this theme again!

**Comment by zhaocai** [comment]
Thanks for the explanation; I appreciate! :thumbsup:

As a choice by design, I agree with you.

After I read the mentioned issues, I have one more question about register:

> When user want to specify static word to change, then use register.
> No longer get static-word from selection.

**Is there anyway to use register from search?**

**Comment by t9md** [comment]
You want insert registered text into search input? Currently no search input not aware of register command.

**Comment by zhaocai** [comment]
> want insert registered text into search input

Yes.

Thanks for the answer.

**Comment by t9md** [comment]
When I created issue, I'm thinking how to improve occurrence **interfaces** to programmer, but now I found so so good solution in #395.
So motivation for this is relatively got low.

**Comment by t9md** [comment]
This should be implemented as `insert-pattern-from-select-list`.
It's special command available only in search-mini editor.

User can set preset-occurrence or change or select for matches by `-from-search` command family.

**Comment by t9md** [comment]
I'm happy with occurrence and subword-occurrence.
For me the idea/feature described this issue is too much. I don't need this for now.
