### ISSUE TITLE
New change occurrence operator leaves multi-cursor even after escape.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#376]
# Check list

- Newest beta of atom, bleeding edge vmp.

I notice that `coi{` will leave the multi-cursor mode enabled even after I hit escape. I feel like after you hit escape the multi-cursors should be disabled. It's kind of like hitting escape when filling in a snippet placeholder (which are essentially multi-cursors). Once you hit escape, you're always back "home" to normal mode.

**Comment by t9md** [comment]
Just confirm, `coi{` on `this` keyword change all `this` keyword within `{,}`, then you enter `that`, then 

1. `escape` to return `normal-mode`, multi-cursor remains
2. then you enter `escape` again multi-cursor cleared.

You want to clear multi-cursors on first `escape` right?
I want to have user choice to clear or keep multi-cursor.
You never face that situation where you want to continue multi-cursor editing with occurrence position?

**Comment by t9md** [comment]
Although I want to know our opinion above my qustion, the tips below would help as quick workaround.

https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#clear-multiple-selection-when-escaped-from-insert-mode

If this kind of request or expectation is normal for broad user, I'd better to provide config option like `clearMultiCursorOnEscapeInsertMode` and enabled by default?

**Comment by jordwalke** [comment]
You describe the situation accurately.

> You never face that situation where you want to continue multi-cursor editing with occurrence position?

I do, but the number of times I need that are far fewer (probably 1/10 times). So it seems 9/10 times you pay the price to have to hit escape twice. It's cool to be able to configure the behavior, but I think for most people the default of clearing selection on first escape is more intuitive and familiar. The config option should probably be for all of `vmp` including snippet interaction.
In fact, I noticed this behavior with visual block selection in vmp and it was so strange that I just thought it was a very long-standing bug in visual block mode. The behavior does not match the behavior for many things like visual block mode in Vim, which is probably why it was so unexpected.

**Comment by t9md** [comment]
OK, thanks for feedback, maybe I should include the code on TIPS.md and have `keepMultiCursorOnEscapeInsertMode`(`false` by default).

**Comment by jordwalke** [comment]
Sounds good to me!

**Comment by t9md** [comment]
I noticed your comment on commit above to care about visual-block mode.
But I want it treat in different issue(I can not fix quickly as I did on this issue).

**Comment by jordwalke** [comment]
Sounds good. You imagine it would be a separate config?

**Comment by admosity** [comment]
![image](https://cloud.githubusercontent.com/assets/4655972/18760888/e0d2d7cc-80d0-11e6-894c-4ed502e5c282.png)

I agree on default off. I was very confused (and sad) when my multiple cursors disappeared after pressing escape.

**Comment by t9md** [comment]
@admosity I agree with you,  that's why I intentionally not cleared multi cursors in previous version.

I prefer to use power of multi-cursor as much as possible, so being automatically cleared is frustrating.

The concern by making `clearMultiCursorsOnEscapeInsertMode=true` by default is, new user coming from pure Vim might never learn how to use multi-cursors.

Lot's of `.` repeat is even unnecessary if user leverages power of multi-cursors(multi-selections)
Sticking to pure-vim-way is sometimes lead to taking away the-atom-way which is occasionally  better than the-vim-way.

**Comment by jordwalke** [comment]
What about default clear=true for change operations, and asp for for vim block mode (because that's how vim would operate in block mode). But for manually initiated multicursor I would expect them to persist even after pressing escape.

**Comment by t9md** [comment]
It's heavy, difficult to clear or not based on operation kind.
I'm thinking to revert previous `clearMultiCursorsOnEscapeInsertMode` to `false` by default.

If you really want to more granular multi-cursor clear or not handling based on operation, I need example text and keystroke to understand situation correctly.
Anyway I haven't frustrated about previous behavior and myself locally `clearMultiCursorsOnEscapeInsertMode` to `false`.

The issue of remaining multi-cursor in vmp sometimes involves bugs or immature cursor restore handling after operation finished.
So I'm not saying all the remaining multi-cursor is by intention.

But good news, I did big refactoring in last week , haven't not released yet.
It's includes consistent cursor restoring mechanism in operator, so I believe something getting better 👍

**Comment by t9md** [comment]
vmp's visual-block is achieved by Atom's multi-cursor, multi-selection feature.
When I want to create multiple-cursor, I don't use `ctrl-shit-up` or `ctrl-shift-down`.
I use `ctrl-v j j j I` then `escape`. Here I leverages remaining-multi-cursors feature to create multi-cursor.
What is better than `ctrl-shift-up`(or down) is , its' more accessible for me and easily remove(undoable) by `j`, `k`
When `j j j k` in vB mode, last `k` actually removed 3rd selection, but native `ctrl-shift-up/down` doesn't provide that.

I frequently use multi-cursor, and it's reduce my use of `.` repeat.
Here is example, 

![multicursor-edit](https://cloud.githubusercontent.com/assets/155205/18804838/ad29ca0e-823b-11e6-8309-f4fbc04d7388.gif)

1. `ctrl-v j  j j j j j`, then `I` then `escape`. result in remaining multi cursor on each line
2. `f >` to find `>` char, then `i` to insert and remove to head of line
3. `escape` move to single-quoted string, each cursors are intersecting single-quote string on respective line.
4. `d s`(`delte-surround-any-pair` in my mapping) to delte single-quote in bulk.

In pure Vim without multi-cursors, I have to type lots' of `.` repeat to trying to achieve same transformation of text.

Of course @jordwalke 's point is not multi-cursor's effectiveness.
But I like multi-cursors, and appreciating remaining-multi-cursors on escape from insert-mode.
If vmp user get familiar with multi-cursor editing, the more people get also frustrated about 'multi-cursors cleared on escape from insert!'.

**Comment by t9md** [comment]
Reverted, So from next-version keeping multi-cursor on escape insert-mode is default again.
If you want to clear multi-cursors, manually enable it.
