### ISSUE TITLE
[idea] set-occurrence-for-next-operation command.

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#385]
Occurrence is powerful.
I want this feature further accessible, easy to use with this command.
Just experiment and evaluate if it works.

Let's say `g o` is mapped to `vim-mode-plus:set-occurrence-for-next-operation` in normal-mode.

The keystroke `g o` request operationStack to process **NEXT** operation with occurrence mode.
What's benefit of this feature?
 
- User don't have to type tricky keybinding. Don't have to insert `o` key in the middle of accustomed `cip`, `vip` like `coip` or `voip`(although user can use `cop` now).
- With highlight, user can specify operator with confident. Since occur highlight is happen **before** deciding operator to use(very important).
- One bonus, when this command is called in `visual-mode`, it take `occurrencePattern` from visual selection to use for next operation.

This is one time ask command to operationStack for next-operation so once any command is processed, that request is popped and have no effect to operation after that.

- `govip` select occur in paragraph
- `gocip` change occur in paragraph

Yes `go` is works as prefix of well accustomed `cip`, `vip`.

# TODO
Moved to #388

**Comment by t9md** [comment]
@zhaocai
I think this feature would cover the issue we discussed in #373 in more consistent flexible manner.

**Comment by zhaocai** [comment]
@t9md this is an excellent feature. 👍

**Comment by t9md** [comment]
Close in favor of #395
