### ISSUE TITLE
Double quote commands don't work anymore

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#387]
Atom 1.10.2
vim-mode-plus 0.57.0
Restarted Atom
Disabled custom keybindings

Stuff like `ci" `va"` no longer work. Single quote still works.

**Comment by t9md** [comment]
Strange, I'll check later but all spec test pass before release which include double quote text obj.
How about directly invoke inner-double-quotes via command palette? Does is work? Then observe keybind resolver via cmd-.

**Comment by chenglou** [comment]
Invoking via command palette works. With the keybinding resolver, I see that upon pressing shift, the `ci` part of `ci` gets reset.

Which also means this doesn't work with `ci(` anymore, etc.

**Comment by chenglou** [comment]
Sorry nevermind, issue on my side. Just upgraded to macOS Sierra and using the new [Karabiner](https://github.com/tekezo/Karabiner-Elements) to map caps lock to esc...

**Comment by t9md** [comment]
Ok
