### ISSUE TITLE
Can't map keys to move cursor in insert mode

### ISSUE THREAD

**Issue by sevenmaxis** [t9md/atom-vim-mode-plus#389]
I need to move cursor in insert mode. Here's my snippet from `keymap.cson`
```
'body':
  ...
  'ctrl-h': 'unset!'
...
'atom-text-editor.vim-mode-plus.insert-mode':
  'ctrl-h': 'vim-mode-plus:move-left'
  'ctrl-l': 'vim-mode-plus:move-right'
```
But this mappings doesn't work: `ctrl-h` works as `backspace`, `ctrl-l` doesn't work at all.
The similar selector is only `'atom-text-editor.vim-mode-plus.insert-mode.autocomplete-active'
`

**Comment by bronson** [comment]
Strange.  That all works for me.  Atom 1.11.1.

When I insert this into my keymap.cson, `ctrl-h` correctly stops working.  Same for you?

```cson
'body':
  'ctrl-h': 'unset!'
```

If not, try emptying your keymap.cson of everything else.  Make sure you don't reassign 'body' later.

**Comment by bronson** [comment]
Also, just making sure: you know about `cmd-.` to show the bindings that are firing?  `cmd-.` again to turn it off.
