### ISSUE TITLE
Should not permit mouse clicking beyond last line character.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#39]
In Vim, you cannot move the cursor past the final character. In MacVim, accordingly, you cannot click beyond the final character. In `atom-vim-mode-plus`, the cursor movement is correct, but then the mouse behavior does not match. It's one of those minor "cracks in the seam" that reminds you it's not Vim and likely easy to fix.

**Comment by t9md** [comment]
I have no interest to FIX this.
I don't want to auto cursor adjustment as minimum as possible.
Some user might think if he/she click EOL position they want cursor stay EOL position and not happy if vim-mode-plus automatically move cursor to char before EOL.

I don't think I should touch this kind of semi-out-of-scope-from-vim-mode-plus world unless it lead BIG problem.
