### ISSUE TITLE
Weird end of file copy edge case after visual line mode selection

### ISSUE THREAD

**Issue by admosity** [t9md/atom-vim-mode-plus#393]
### Atom version info

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
vmp: 0.57.0

I have a weird issue and only for HTML files where if I select lines up until the last line and then use atom's native copy, it collapses the selection to the beginning and end cursor positions.

![vmp-issue](https://cloud.githubusercontent.com/assets/4655972/18762793/631b22f0-80d8-11e6-87c3-9fd135d0590d.gif)

For some reason that particular file fixed itself, but other files I was able to reproduce.

**Comment by t9md** [comment]
I cannot understand above, could you follow issue report instruction you can see when you create issue.

**Comment by admosity** [comment]
I think you can close this now... For some reason it's working just fine now. Sorry!

**Comment by t9md** [comment]
Ok, thanks for responding quickly. Will close.
