### ISSUE TITLE
Should scope for surround `y s` in example keymap.cson be 'visual-mode'?

### ISSUE THREAD

**Issue by jonboiser** [t9md/atom-vim-mode-plus#394]
- Atom version info(`atom --version`) 1.10.2
- vim-mode-plus version. 0.57.0

I spent a couple of minutes trying to figure out surround with the `y s` keymap, as suggested [here](https://github.com/t9md/atom-vim-mode-plus/blob/master/keymaps/vim-mode-plus.cson#L326) :

```
'atom-text-editor.vim-mode-plus.normal-mode':
  'y s': 'vim-mode-plus:surround'
```

But I would select a block of text in visual mode (e.g. `v $` to select a whole line), but `y s` will trigger `yank` then `substitute`, according to the key binding recorder.

It was only until I moved the keybinding here:
```
'atom-text-editor.vim-mode-plus.visual-mode':
  'y s': 'vim-mode-plus:surround'
```

That I get the results I expected:
```
this text is selected in visual mode
// then i go `y s (`
(this text is selected in visual mode)
```

**Comment by t9md** [comment]
If you want map surround in `visual-mode`, yes you need to choose scope `atom-text-editor.vim-mode-plus.visual-mode`.
Example keymap is just for `normal-mode`.

The problem when you set `y s` in `visual-mode` is, when you type `y` to yank visual selection, you have to wait some for keybinding system to give up another possibility(`y s` is another possibility).

In convention from surround plugin from pure vim, `S` is mapped to `surround` in `visual-mode`.
