### ISSUE TITLE
Introduce event onDidChange, onDidSelect to cleanly track mutation and selection

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#40]
Currently operator.coffee to imperative way to flash mutated range.
But when I try to introduce `[`, `]` marker to store last changed start and end position which is updated on text mutation, it is difficult without introducing mess to the code.

So in this issue, I'll try to implement onDidChange, onDidSelect event on vimState.
Then I'll use to those event to flash and update last changed position marker `[`, `]`.
This event system could be used to further simplification of code and support another feature.

**Comment by jordwalke** [comment]
Could this be used to make the redo cursor behavior match Vim's?

**Comment by t9md** [comment]
i don't know. I still cant understand whats the problem and the cause correctly and yet not investigated.
Can you describe it?

**Comment by jordwalke** [comment]
I created the following issue to track it: https://github.com/t9md/atom-vim-mode-plus/issues/14

I just updated it to elaborate the specific behavior.

**Comment by t9md** [comment]
Ok thanks! Will check and tackle soon!

**Comment by jordwalke** [comment]
If so, this would be the only vim emulator that I know of that handles redo correctly (besides emacs IIRC).
