### ISSUE TITLE
Add support for paragraph commands `{` and `}`

### ISSUE THREAD

**Issue by jon49** [t9md/atom-vim-mode-plus#41]
Great project, much better than vim-mode. I didn't realize how essential `{` and `}` are to my workflow until I starting using atom. Not sure how long I will be using it but thought I would put this up here for whenever it could be worked on. If I keep using Atom, maybe I'll see about integrating it.

**Comment by t9md** [comment]
What operation you want to achieve?
I'm asking since `{`, `}` paragraph motion is already implemented  in vim-mode(not new from vim-mode-plus).

**Comment by jon49** [comment]
I just tried it and it is working on Ubuntu. Maybe I was having trouble with it on the windows machine at work. I'll try it on Monday and see if it is working properly. If it is. Then I'm not sure what I was doing to make it so it wasn't working before!

**Comment by jon49** [comment]
I'm not sure what I was doing before when I couldn't seem to get it work, I was probably doing something stupid :-/ . If I run into it again I'll let you know.

**Comment by jon49** [comment]
OK, when I press `shift+]` (`}`). It is just going to the end of the line and only up certain lines.

It looks like it is being caused when they settings for the line endings are set to `CRLF` but when I set them to just `LF` it works fine.

**Comment by t9md** [comment]
Paragraph motion simply use atom's  cursor's method.

This commit will solve issue.
Pls. check after Atom(v1.4.0) released.

https://github.com/atom/atom/commit/fe5b1b70e8b0b85a3d7fa2a06fee625aca3e70ca
