### ISSUE TITLE
cs' removes space

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#418]
Repro:

Doing `csi'` on `"hello "` produces `'hello'`

Same for other `cs` whatever

**Comment by t9md** [comment]
This is an bad-side-effect introduced when I implement removing, adding padding spaces around pair char in following PRs.

https://github.com/t9md/atom-vim-mode-plus/pull/331

I don't think this side-effect comes from original PR author, I think I introduced it in the process of simplification of PRed code.

I don't want make things complicated, so I'll quickly work around this(your) issue by limiting trimming effect only to asymmetric pair char such as `(`, `)` or `[`, `]`.
Then symmetric pair char `"`, `'`, ``` ` ``` would be free from triming.

**Comment by t9md** [comment]
Did quick but practical(I believe so) compromising fix.
Will release as v0.58.5 from now.
