### ISSUE TITLE
j, k moves bufferRow-wise, gk, gj moves screenRow-wise

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#423]
Current implementation mixes `j` and `g j` also `k` and `g k`.
Which makes refactoring difficult, increase code complexity.
Furthermore current mixed behavior have bug because of this mix.
In certain point with soft-wrapped text, move-up/down movement lock(can't move anymore).

So
- separate `move-up` and `move-screen-up`, also `move-down` and `move-screen-down`.
- keymap `j`, `k` to `move-up` , `move-down`
- keymap `g j`, `g k` to `move-screen-up`, `move-screen-down`
- update test spec

**Comment by elmewo** [comment]
I would really appreciate if this behaviour was customizable. When writing LaTeX, I use soft wrapping heavily. Moving screenRow-wise with j and k saves a lot of effort for me.

**Comment by t9md** [comment]
Use gk and gj in that case. I think you also can remap keymap for latex grammer specifically.

**Comment by wmayner** [comment]
@episodeyang, what he means is that you can just remap `j` and `k` to `vim-mode-plus:move-down-screen` and `vim-mode-plus:move-up-screen`, respectively, and you'll get that functionality without having to type the `g`.

**Comment by episodeyang** [comment]
Yep, did exactly that.
