### ISSUE TITLE
Visual mode performing repeat find doesn't extend selection

### ISSUE THREAD

**Issue by admosity** [t9md/atom-vim-mode-plus#425]
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
vmp: 0.58.5

Text:
```
one.two.three.four.five
```
Keystrokes:
`vf.;;;`

Expect `one.two.three.four.` to be selected, but instead selection is cleared.

**Comment by t9md** [comment]
Thanks for very very clear issue report.
This is degradation I introduced without noticing.
Will fix soon.
