### ISSUE TITLE
[bug] 'vim-mode-plus:select-latest-change' doesn't select latest change

### ISSUE THREAD

**Issue by axelson** [t9md/atom-vim-mode-plus#426]
# Check list

- Atom version info(`atom --version`)

1.10.2

- vim-mode-plus version.

0.58.5

- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.

yes

- Tried to latest stable atom version with latest vim-mode-plus.

yes

- Restarting Atom itself solve your problem?

no

- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

# Details

I'm a big fan of 'vim-mode-plus:select-latest-change' and often use it for selecting the text that I just pasted. However, as of a recent update (I believe about 1 week ago) `select-latest-change` no longer behaves as it once did.

Here's one reproduction case. Start with the text:

    1
    2
    3

With the cursor on the 2 (in normal mode of course) type `yyp` then run `select-latest-change`.

**What happens?** Both 2's are selected

**What is expected?** Only the second 2 is selected

There are other cases as well. If instead of `yyp` you run `yyjp` and then `select-latest-change` you get only the original `2` selected.

Let me know if I can help debug in any way.

**Comment by t9md** [comment]
Sorry this is degradation I introduced as a result of overhauling operator code.
Will check, thanks for clear reporting.(I also already noticed before your report, I use this feature frequently)

**Comment by t9md** [comment]
Tracking change for `p` and `P` was disabled by mistake, what you see in `yyp` or `yyjp` is because of just yanked-area-is-tracked.

**Comment by axelson** [comment]
It works! Thanks 🎉
