### ISSUE TITLE
Replace mode Should work with numbers

### ISSUE THREAD

**Issue by wldcordeiro** [t9md/atom-vim-mode-plus#427]
# Check list

- Atom version info(`atom --version`)

```
Atom    : 1.11.0-beta0-538aa94
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

- vim-mode-plus version. 0.60.0
- You disabled vim-mode? Yes.
- Tried to latest stable atom version with latest vim-mode-plus. Yes
- Restarting Atom itself solve your problem? No

To recreate this try to use the single replace `r` command with a number like `r4` the expected result here is that the character your cursor is over gets replaced with a `4` but instead the "action overlay" appears to do repeat motions and you don't get the replacement.

This doesn't affect `R` replacement, just single character replacement.

**Comment by t9md** [comment]
Give me **example text** and keystroke. I couldn't reproduce your issue.
My env is this

```
master github/atom-vim-mode-plus% atom-beta --version
Atom    : 1.11.0-beta5
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```
vmp is v0.60.0

**Comment by aldaty** [comment]
In case this is helpful: I also experienced this issue right after updating to version 0.60.0, but restarting atom fixed it immediately.

**Comment by wldcordeiro** [comment]
@aldaty weird yeah, I had to restart a couple of times but it started working after. Closing for now.
