### ISSUE TITLE
`r *` on whitespace doesn't respond

### ISSUE THREAD

**Issue by bronson** [t9md/atom-vim-mode-plus#437]
Minor issue: when I'm in normal mode with the cursor on some indentation and I hit `r *`, nothing happens.  `r *` works properly everywhere else.

To reproduce:

- open a new editor, type some text, and indent it away from the left margin.
- type `0` to go to column 0, on top of whitespace.
- type `r *`.  Nothing changes.

Hitting `^ r *` works.  It seems to matter if the cursor is over leading whitespace.

Checklist:

- Atom version: 1.11.2
- vim-mode-plus version: 0.60.1
- Tried to latest stable atom version with latest vim-mode-plus.  yep!
- Restarting Atom itself solve your problem?  nope!
- doesn't seem like a keybinding or --safe issue.

**Comment by t9md** [comment]
This issue only happen in you set `editor.atomicSoftTabs` to `true` which is Atom's default.
But many user including me think this is bad choice of default configuration.

https://github.com/atom/atom/issues/3174

Anyway the issue @bronson  reported is off course vim-mode-plus's bug, so fixed.

**Comment by bronson** [comment]
That's great!  I didn't know I could turn that off.  :fire: :fire: :fire:

Atomic soft tabs is one of those features that sounds great but feels terrible.
