### ISSUE TITLE
Provide subword navigation?

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#44]
Is it possible to provide this out of the box? What are the ramifications? Thanks.

**Comment by t9md** [comment]
No, 
I think subword movement is too small for amount of movement. So have no motivation at least now.

By the way Atom itself provides subword navigation.
Here is the Mac keymap atom provide for subword movement, you can use these keymap in insert-mode. And if you set keymap in normal-mode for those commands, you can use these feature in normal-mode. 

https://github.com/atom/atom/blob/master/keymaps/darwin.cson#L139-L144

**Comment by chenglou** [comment]
Thanks!

**Comment by t9md** [comment]
I finally can close this old request 🎉
