### ISSUE TITLE
Normal mode `r` now requires motion

### ISSUE THREAD

**Issue by CGamesPlay** [t9md/atom-vim-mode-plus#444]
It looks like 2b0a230346f4a40f9fd80da09f3d071366518235 broke `r`. at least, on 0.60.1, `r` worked fine, but on 0.61.0, it requires a motion, and replaces everything over the motion.

Test case: `iabc^[hhrd^[`

Expected output (matches vim, and 0.60.1): `dbc`
Actual output: `abc`

This get silly when you do something like `r.j`, where it just replaces every character on the current and following line with `.`.

```
$ atom --version
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by t9md** [comment]
I can't reproduce your issue.
And it's strange since all test-spec for `r` is passed without change.
What OS are you using? Restarting Atom solve your problem?

**Comment by CGamesPlay** [comment]
After re-upgrading and restarting atom it isn't reproducing now :( I seem to remember restarting atom previously, but it's probably safe to assume I didn't.

I'll re-open this if it happens again.
