### ISSUE TITLE
replace does not work well

### ISSUE THREAD

**Issue by oknixus** [t9md/atom-vim-mode-plus#445]
![10 -24-2016 10-53-40](https://cloud.githubusercontent.com/assets/4592706/19632351/3d492040-99d8-11e6-8c53-0b4075521734.gif)

**Comment by t9md** [comment]
Sorry I can't understand. Please follow issue template **you see in opening form**.
Otherwise I will close this issue.

**Comment by oknixus** [comment]
I want to replace the number '6' to ',',  but after I press ',', the number 6 does not change to a ',',  then I press other key, it change the whole line to ','

**Comment by oknixus** [comment]
Could you try to replace some characters ？

**Comment by t9md** [comment]
Restart Atom first.
For your question.
Yes as I said, I can't reproduce, you even give me version, os, sample text.

I can't help you unless you give enough information. Don't give me answer one by one, just follow issue report form you see when opening issue.

**Comment by oknixus** [comment]
@t9md Hahaha……you are right. It's ok after restart Atom.
Thank you a lot.👍

**Comment by t9md** [comment]
No one can understand from only GIF you uploaded first.
I'm not special resource available specially for you.
Please invest your time to accurately report issue and try to give enough information when you open next issue.

**Comment by oknixus** [comment]
Sorry, I see. I will.

**Comment by t9md** [comment]
Nice!
