### ISSUE TITLE
h j k l does not work in "find in project" tabs

### ISSUE THREAD

**Issue by rumpelsepp** [t9md/atom-vim-mode-plus#447]
- Atom version info(`atom --version`): 1.11
- vim-mode-plus version: 0.61

Navigating with h j k l does not work in "find in project" buffers created with <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd>

**Comment by bronson** [comment]
I don't quite understand...  If `l` navigated, then how would you type it?

**Comment by rumpelsepp** [comment]
?

* Create a a find in project buffer with <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>
* Enter your search pattern und press <kbd>enter</kbd>
* The results show up, you can only navigate them with the arrow keys.

**Comment by bronson** [comment]
Sorry, I must have misread.  I thought you were talking about ctrl-p.

Install t9md's project-find-navigation plugin.

**Comment by rumpelsepp** [comment]
I am sorry, I mistyped it and I corrected it later on. You might have missed that edit... :)

**Comment by t9md** [comment]
@rumpelsepp
I understand what you are saying, but currently vim-mode-plus keymaps works only in text-editor.
Result of project find is not text-editor.
Tree view is not text-editor.

This is big diff from original pure-Vim where all window(pane in atom term) you see is all text-editor.
But In Atom there is some none-editor pane and panel(another different component)

I'm not trying to make it work in non-editor-pane or panel. It's just hard and heavy to support.

**Comment by bronson** [comment]
t9md, your project-find-navigation works great and supports j/k in its default keymap.  One might argue that you already support it even if vim-mode-plus doesn't (and, agreed, shouldn't).

**Comment by rumpelsepp** [comment]
@t9md Got it. But it might be possible to set my own keymaps to just h j k l, isn't it?

**Comment by bronson** [comment]
@rumpelsepp that's likely to be... complex.   But you could try.

Why not just install the plugin?

**Comment by t9md** [comment]
For project find-result: as @bronson  says try https://atom.io/packages/project-find-navigation.

For file-tree-view navigation, you `j`, `k` is already available which is not scope of vim-mode-plus, keymap is managed by tree-view package. To customize this, check un-merged this [PR]( https://github.com/t9md/atom-vim-mode-plus/pull/133/files)

As you can see above, all non-text-editor pane/panel require specific customization depending on characteristics of each pane/panel.

**Comment by rumpelsepp** [comment]
> @rumpelsepp that's likely to be... complex. But you could try.

```
'.results-view':
  'j': 'core:move-down'
  'k': 'core:move-up'
  'h': 'core:move-left'
  'l': 'core:move-right'
```

**Comment by bronson** [comment]
Right on.  I meant, it will likely be complex to make them work in every potential pane.

Love how flexible Atom is.
