### ISSUE TITLE
How to get surround working?

### ISSUE THREAD

**Issue by felixjung** [t9md/atom-vim-mode-plus#449]
This is probably a dumb question and I have misconfigured something. I'm trying to get surround working -- in any way. I've uncommented and copied the following from the atom-vim-mode-plus config to my `keymap.cson`:

```
# Surround mode in vim-mode-plus
'atom-text-editor.vim-mode.normal-mode':
  'y s': 'vim-mode-plus:surround'
  'y s w': 'vim-mode-plus:surround-word'

  'd s': 'vim-mode-plus:delete-surround'
  'd s': 'vim-mode-plus:delete-surround-any-pair'
  'd s': 'vim-mode-plus:delete-surround-any-pair-allow-forwarding'

  'y s c': 'vim-mode-plus:change-surround'
  'y s c': 'vim-mode-plus:change-surround-any-pair'
  'y s c': 'vim-mode-plus:change-surround-any-pair-allow-forwarding'

  'y m s':  'vim-mode-plus:map-surround'
```

My understanding is, that if I press the keys <kbd>y</kbd>, then <kbd>s</kbd>, and finally <kbd>)</kbd> inside a word (.e.g. `foo`), this word should be surrounded by `()` (i.e. `(foo)`). However, when I try this, nothing happens. What am I missing? What's the best way to debug this?

I'm on a Mac using the latest version of Atom and atom-vim-mode-plus.

**Comment by bronson** [comment]
You need to tell it what to surround.  Try `ysiw)` or `ysaw)`

**Comment by bronson** [comment]
Check out Vim's text objects if the `iw` and `aw` aren't immediately obvious. http://blog.carbonfive.com/2011/10/17/vim-text-objects-the-definitive-guide/

**Comment by felixjung** [comment]
If I press `ysiw)` while the cursor is inside a word, nothing happens. If I try the same with `ysiw"` I get an overlay showing the `"`. I can press `"` once more and the overlay will display `""`, but nothing will happen. Often when trying various versions of the key combinations listed in the code block above, the word I'm trying to surround will get deleted or the cursor will jump to some other part of the file.

**Comment by t9md** [comment]
Remove ysc and ysw and use ys only.
I can explain why but it will be fixed soon.
You can refer working example in my dotfiles linked in READEME.md.

**Comment by felixjung** [comment]
Thanks @t9md. But how does this work with just `ys`? How do I wrap the the variable foobar in brackets?

``` javascript
const fb = foobar;
```

In Vim, with surround, I would select the word in visual mode and press <kbd>S</kbd>+<kbd>]</kbd>. Probably not the most efficient way, but it worked.

**Comment by t9md** [comment]
Did you make it work at-leaset-one-surround-operation?
If so, gradually tweak your mapping through try&error by referencing mydotfile as I said above.
If you know vim-surround. It's same, just you have to learn atom's keymap-system trough your own try&error.

**Comment by t9md** [comment]
For your question. `ysiw]` surround `foobar` with `]`.
If you have following keymap

```coffeescript
'atom-text-editor.vim-mode-plus.normal-mode':
  'S': 'vim-mode-plus:surround-word'
```

keystroke `S]` transform(surround) `foobar` to `[foobar]`.

Don't take above keymap as final version, just learn how keymap works in Atom trough your own ty&error.

**Comment by felixjung** [comment]
Wow, I feel so stupid... I had the wrong selector... `keymap.cson` was using `'atom-text-editor.vim-mode.normal-mode'`. Thanks a lot for the help.
