### ISSUE TITLE
Hover involved operation is slow

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#450]
## Problem
- `j` is fast, but `1 0 j` is  slow.
- `l` is fast, but `3 l` is slow

## Why?
Count is displayed **synchronously**.
It delays following motion operation.

## How to fix?
I don't want to remove hover feature itself.
So try first to make hover display async to not interfere following operation.
If result was bad, might making hover display is optional by config option.

**Comment by bronson** [comment]
Mine doesn't have any appreciable delay -- the hover goes away the moment I press the motion.  Did I change a setting?

https://github.com/bronson/dotfiles/blob/master/.atom/config.cson#L83-L96

**Comment by t9md** [comment]
try `2 j` with `2` and `j` press almost same timing.
If hover feature is not exist, it immediately move 2 line below, but not.

**Comment by bronson** [comment]
Ah yep, I see that delay.  I guess I naturally put a small pause between the count and the motion.  :)
