### ISSUE TITLE
Request: Option to use old longer text on status bar.

### ISSUE THREAD

**Issue by thancock20** [t9md/atom-vim-mode-plus#451]
First, let me explain my use case. I have my status bar styled so that the mode text on the status bar looks similar to how it does in vim with powerline. A different background color and such for each mode. Since the switch to only one or two characters - instead of the longer text - it just doesn't look right to me. 

I read the commit that changed it, and it's easy to change it back. But that would have to be redone every update. I know it's an aesthetic rather than functional thing, but I was wondering if either:

1.) You could add an option in the settings to use the old longer text

OR

2.) Is there a way to do it by adding code to the init.coffee file?

**Comment by t9md** [comment]
Could you put the style setting you are using.
I want to check and let me understand the background.

**Comment by thancock20** [comment]
Yes. Here's the relevant part:

```
.status-bar-vim-mode-plus-normal,
.status-bar-vim-mode-plus-operator-pending,
.status-bar-vim-mode-plus-insert,
.status-bar-vim-mode-plus-visual {
  font-weight: bold;
  text-align: center;
  font-size: 1.5em;
  width: 21rem;
  text-transform: uppercase;
}


.status-bar-vim-mode-plus-normal {
  background: rgb(105, 238, 103);
  color: rgb(4, 111, 11);
}

.status-bar-vim-mode-plus-insert {
  background: rgb(7, 193, 242);
  color: white;
}

.status-bar-vim-mode-plus-visual {
  background: rgb(255, 206, 98);
  color: rgb(168, 117, 5);
}

.status-bar-vim-mode-plus-operator-pending {
  background: rgb(204, 204, 204);
  color: black;
}
```

**Comment by t9md** [comment]
Changed in #428.
Will add options to allow user choose long or short status-bar-mode-string.

One note, Replace-mode is displayed as `Insert Replace` instead of `Replace`.
This is because Replace mode is actually submode of Insert mode. It's not related to normal user.
But I prefer explicitness.

**Comment by thancock20** [comment]
Awesome. Thank you.

**Comment by zhaocai** [comment]
Any suggestion to change the background-color of the whole status-bar on different vim mode?

**Comment by t9md** [comment]
@zhaocai 

Try this

## init.coffee

```coffeescript
consumeService = (packageName, providerName, fn) ->
  disposable = atom.packages.onDidActivatePackage (pack) ->
    if pack.name is packageName
      service = pack.mainModule[providerName]()
      fn(service)
      disposable.dispose()

getEditorState = null
consumeService 'vim-mode-plus', 'provideVimModePlus', (service) ->
  {Base, getEditorState, observeVimStates} = service

  observeVimStates (vimState) ->
    vimState.modeManager.onDidActivateMode ({mode, submode}) ->
      statusBarElement = document.querySelector('status-bar.status-bar')
      statusBarElement.classList.add(mode)
      statusBarElement.classList.add(submode) if submode?
      console.log statusBarElement.classList

    vimState.modeManager.onDidDeactivateMode ({mode, submode}) ->
      statusBarElement = document.querySelector('status-bar.status-bar')
      statusBarElement.classList.remove(mode)
      statusBarElement.classList.remove(submode) if submode?
      console.log statusBarElement.classList
```

## style.less

```less
.status-bar {
  &.insert {
    background: green;
  }
  &.visual.characterwise {
    background: red;
  }
}
```

**Comment by zhaocai** [comment]
@t9md Thanks! Works great!
