### ISSUE TITLE
visual cursor position screwed when visually select line on fold 

### ISSUE THREAD

**Issue by xh3b4sd** [t9md/atom-vim-mode-plus#452]
# Check list
- Atom version info(`atom --version`)

```
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```
- vim-mode-plus version.
  `0.62.0`
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
  vim-mode is not installed
- Tried to latest stable atom version with latest vim-mode-plus.
  I am using these
- Restarting Atom itself solve your problem?
  No
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
  I am using the key binding provided by the package
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!
  I read that
### issue

I have some arbitrary code in a `test.go` file with a function that can be folded. I am folding all folds, e.g. using the command palette, `Editor: Fold All`. When going to the function declaration and selecting the line visually with shift-v, the line is visualized but the cursor moves up, which looks weird. 

```
package main

import "fmt"

func main() {
    fmt.Printf("%#v\n", "foo")
}
```

When moving the cursor to the beginning of the line and selecting it, the result is this.

<img width="306" alt="screen shot 2016-10-25 at 23 45 57" src="https://cloud.githubusercontent.com/assets/552769/19706292/73b37b46-9b11-11e6-832b-e6340356e942.png">

When moving the cursor more forward on that line the result is this.

<img width="293" alt="screen shot 2016-10-26 at 00 15 17" src="https://cloud.githubusercontent.com/assets/552769/19706297/787f271a-9b11-11e6-93af-201d82e2aa68.png">

As far as I experienced this, this issue is only visually. No functionality breaks as far as I know now. It is only that it looks buggy. So low priority here.

**Comment by t9md** [comment]
Yes, it's cosmetic, but I want to fix this after some relating part was fixed.
Thanks for reporting.
