### ISSUE TITLE
switching cases using `~` should not autocomplete suggestions of insert mode

### ISSUE THREAD

**Issue by xh3b4sd** [t9md/atom-vim-mode-plus#453]
# Check list

- Atom version info(`atom --version`)
```
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

- vim-mode-plus version.
`0.62.0`

- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
vim-mode is not installed

- Tried to latest stable atom version with latest vim-mode-plus.
I am using these

- Restarting Atom itself solve your problem?
No

- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
I am using the key binding provided by the package

- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!
I read that

### issue

I am not sure if this is the right repo for this issue, but since I am here I thought I give you a shout and see what the folks think. So I have some arbitrary code in a `test.go` file. When going to the letter `m` of the word `main` and try to switch its case using `~`, the autocompletion dialog is shown. This should not happen. I am not really in insert mode. I only switch cases. I expect to stay in normal mode without any interruptions or suggestions for insert mode.

```
package main

import "fmt"

func main() {
	fmt.Printf("%#v\n", "foo")
}
```

<img width="361" alt="screen shot 2016-10-26 at 00 22 09" src="https://cloud.githubusercontent.com/assets/552769/19706574/d278897c-9b12-11e6-8925-cd50a1587028.png">

**Comment by t9md** [comment]
You can disable it in autocomplete-plus setting.
Check FAQ section in vim-mode-plus's README.md.

**Comment by xh3b4sd** [comment]
Cool. Works for me. Thanks.
