### ISSUE TITLE
moving in visual block mode screws selection completely

### ISSUE THREAD

**Issue by xh3b4sd** [t9md/atom-vim-mode-plus#454]
# Check list

- Atom version info(`atom --version`)
```
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

- vim-mode-plus version.
`0.62.0`

- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
vim-mode is not installed

- Tried to latest stable atom version with latest vim-mode-plus.
I am using these

- Restarting Atom itself solve your problem?
No

- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
I am using the key binding provided by the package

- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!
I read that

### issue

Consider the following file.

```
package main

import "fmt"

func Main() {
	fmt.Printf("%#v\n", "foo")

	if something == something {
		fmt.Printf("%#v\n", "foo")

		if something == something {
			fmt.Printf("%#v\n", "foo")
			fmt.Printf("%#v\n", "foo")
		}
		fmt.Printf("%#v\n", "foo")
		fmt.Printf("%#v\n", "foo")
	}
}
```

<img width="763" alt="screen shot 2016-10-26 at 00 42 14" src="https://cloud.githubusercontent.com/assets/552769/19707077/c05da896-9b15-11e6-9e10-2cb32d7eea7b.png">

I am on line 13 with the cursor at character 1. Then I do the following.

- ctrl-v
- e 
- e 
- k
- e 
- j

The result is this.

<img width="762" alt="screen shot 2016-10-26 at 00 42 03" src="https://cloud.githubusercontent.com/assets/552769/19707095/e16fa16a-9b15-11e6-9249-ee14bed7fa56.png">

The expected result should be this.

<img width="766" alt="screen shot 2016-10-26 at 00 48 46" src="https://cloud.githubusercontent.com/assets/552769/19707111/000e2768-9b16-11e6-97b9-376998df7ffe.png">

**Comment by bronson** [comment]
Hah, confirmed.

Going to line 7 column 1 and hitting `j` `k` `k` also messes up (won't keep going up).

**Comment by t9md** [comment]
@xh3b4sd Thanks for catching this.
Your expected result is not correct,  selection should exist only on line 13, since its equal to `ctrl-v k j`(single line selection remains).

Will fix anyway.

Related #222

**Comment by t9md** [comment]
Fixed both case, original case and @bronson  mentioned case.
vB and vL and vC selection manipulation with supporting motion command in all these visual-mode's submode is really confuse my brain. Get my brain CPU usage hot/high..

Still want to simplify / clarify these logic further.
