### ISSUE TITLE
What is holding this project back from going 1.0 ?

### ISSUE THREAD

**Issue by Byron** [t9md/atom-vim-mode-plus#457]
I am using the plugin every day, and don't really find anything missing in functionality, not to say: I love it !
Thanks for updating it so frequently!

This leaves me puzzled why there is no 1.0 available yet.
Personally I would prefer going 1.0 early, just to have the patch-level of the semantic version available. If needs be, one can always increment the major version, provided that some agreed-on contract is actually broken/adjusted.

What is your stance on this ?

**Comment by t9md** [comment]
No special reason

- Just I'm lazy
- I'm still experimenting several-ideas phase adding/removing feature frequently.
- That does not mean vim-mode-plus is unstable, but want to avoid too much expectation from broad user.
- Just I don't want to be responsible to respect `provided that some agreed-on contract is actually broken/adjusted`.

Yeah, just want to be loose, lazy.

**Comment by Byron** [comment]
Thanks, I see your point.
If you would go 1.0, I think the user wouldn't be disappointed at all, as vim-mode-plus is already awesome. Thanks to the decent test-coverage, there should be no fear of breaking things really bad.
In other words, going 1.0 could not only help adoption, but might help getting more contributions as well.
This plugin has so much potential, just as there are so many vim-people out there which want to use atom as well without loosing the ergonomics they are used to from vim, so I would really like this project to take off (and overtake the stalling vim-mode).

To my mind, the only disadvantage of going 1.0 is that you would probably have to think more about breaking changes, but ... it's just a matter of definition what a breaking change is.

For instance, if you declare the internals of the plugin private, then a breaking change would only be if something breaks for the user when updating to the newer version of the plugin.
If that is the case, you could also increment the major version - but in any case, you would have to be aware. On the other hand, so far I have not witnessed a user-facing breaking change that was not an accident (i.e. bug).

Anyway, thanks for taking the time to reply, maybe this conversation has an effect after all. Something tells me that you are not actually lazy, just looking at what you have accomplished single-handedly :) !

**Comment by t9md** [comment]
@byron Thanks for your message.
It's great input and also encouraging me a lot.
From I published vim-mode-plus I gradually fixed several bugs which was not reported by user but I  noticed it has to be fixed.
I have still lots of bugs want to fix which was not necessarily reported to issue.
I might bump version to 1.0 after finished these bug fixed.
