### ISSUE TITLE
Empty line behaviour

### ISSUE THREAD

**Issue by Hedgepig** [t9md/atom-vim-mode-plus#459]
A useful feature I used in Vim was the empty line behaviour, which is only partially implemented in VMP.

That is whenever one leaves a line with no content, that is, just tabs/spaces, those tabs/space are removed, leaving the line completely empty. 

Currently VMP has this working when one performs a carriage return on an empty line in edit mode. But doesn't work if say, you open a new line then go to normal mode.

**Comment by t9md** [comment]
I don't know that feature is really exists in pure-Vim.
In Atom, the feature you are mentioning is provided by [whitespace](https://github.com/atom/whitespace) pacakge.

You can tweak setting via settings of whitespace package.
1. `cmd-,`
2. Click `Packages`
3. search `whitespace`
4. click `Settings`.
