### ISSUE TITLE
Replacing a character under the cursor in normal mode

### ISSUE THREAD

**Issue by AlexDisler** [t9md/atom-vim-mode-plus#460]
When I try to replace the character under the cursor in normal mode (by entering 'r' followed by the character), it doesn't work.

When I enter 'r' it shows 'vim-mode-plus:replace' in the key binding resolver but then when I enter the new character, nothing happens.

Atom: 1.11.2
vim-mode-plus: 0.63.0 (issue appeared after last update)

This is a great plugin, thank you for your work.

**Comment by t9md** [comment]
Restart atom? Was solved similar issue check closed one.

**Comment by AlexDisler** [comment]
Restart solved it, sorry I thought I already tried it. Thanks.
