### ISSUE TITLE
Using search with multiple cursors always loses the first cursor

### ISSUE THREAD

**Issue by admosity** [t9md/atom-vim-mode-plus#461]
Version info:
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
vmp: 0.63.0

![multi-search](https://cloud.githubusercontent.com/assets/4655972/19823829/057723d8-9d39-11e6-8951-d994016bf6bd.gif)

**Comment by t9md** [comment]
This issue treat `/` and `?`.
Issue happens only when `IncrementalSearch` is `true`.

**Comment by t9md** [comment]
Was difficult to fix for me(maybe tired and my skill?). I need refresher.

**Comment by admosity** [comment]
Thanks! I tried to get into the codebase a couple times, but I haven't had the time to sit down and really look through it. This plugin has helped me improve my workflow greatly!
