### ISSUE TITLE
Preferred way to search & replace

### ISSUE THREAD

**Issue by plbowers** [t9md/atom-vim-mode-plus#463]
This is a question, not an issue...

I am used to using

:s/foo/bar/g
:1,$ s/foo/bar/g
:% s/foo/bar/g
:.,.+3 s/foo/bar/g

and the like to do search & replace in vim. What is the preferred way to do this since this capability seems not to be supported in vim-mode-plus nor vim-mode-plus-ex-mode?

ALT-CTRL-F seems to be awkward typing from a vim perspective when speed typing of commands is a priority... Also there's no support (that I see) for limiting the search&replace to just a given portion of the file in question...

**Comment by t9md** [comment]
Short answer is "Train yourself to use Atom's feature, it's not Vim".

For more longer answer.
- Read wiki of vim-mode-plus, especially
https://github.com/t9md/atom-vim-mode-plus/wiki/AdvancedTopicTutorial
https://github.com/t9md/atom-vim-mode-plus/wiki/OccurrenceModifier

occurrence, preset-occurrence, persistent-selection make you edit faster
I won't say all case, but its better than native find-and-replace feature in some case.

- Familiarize yourself for working with multiple-cursors
In many cases `cmd-d`  multiple time or `ctrl-cmd-g` is faster.

I understand motivation who request ex-mode's compatible feature, I've asked again and again.
But for myself I WONT, have no resource and motivation. Don't want to parse arbitrary user input in `:` prompt to transform it appropriate action.

If someone really want this feature, he/her can create it as independent package.

**Comment by plbowers** [comment]
OK, I read nearly all of that. (And made a few updates in the wiki - hopefully improvements)

I'm working on windows so cmd-d is not available - there's probably some way to do it, but my few minutes of googling came up with nothing. (It seems that ctrl is usually a substitute for cmd, but in this case ctrl-d is already mapped...) Anyway, I'll search further to try to figure out how to access cmd-d and ctrl-cmd-g.

I may explore forking and expanding ex-mode. Obviously that's not your preferred work flow and I fully get that.

Thanks for your time and answers.

**Comment by t9md** [comment]
You can find from here https://github.com/atom/find-and-replace/blob/master/keymaps/find-and-replace.cson.

Also you can see keymaps which find-and-replace pckage provides from setting-view of find-and-replace.

**Comment by t9md** [comment]
I checked wiki. It's great help! Thanks a lot!!!
