### ISSUE TITLE
Pressing 'e' on blank new line freezes Atom

### ISSUE THREAD

**Issue by thatsnotright** [t9md/atom-vim-mode-plus#469]
~ ❯❯❯ atom -version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

vim-mode-plus 0.63.0

vim-mode is not installed
vim-modeling is installed at 0.4.2

Situation:

When editing a file, if I end up with the cursor on the last empty line of the file and am not in insert mode, if I press the 'e' key the editor locks up and I have to restart the edit session losing any unsaved changes.  I didn't see anything obvious in the code for moveToNextWord.  I attached some screenshots.  I don't get any log output from atom when I run with 

`atom -f -d -l log` 

![screen shot 2016-10-31 at 12 26 43 pm](https://cloud.githubusercontent.com/assets/54635/19866309/4faad98a-9f65-11e6-9938-542f912838cb.png)

![screen shot 2016-10-31 at 12 22 02 pm](https://cloud.githubusercontent.com/assets/54635/19866235/f8fd62ce-9f64-11e6-8202-71146460a651.png)
![screen shot 2016-10-31 at 12 23 03 pm](https://cloud.githubusercontent.com/assets/54635/19866236/f9002306-9f64-11e6-8fa6-7d733cc6002d.png)
![screen shot 2016-10-31 at 12 23 44 pm](https://cloud.githubusercontent.com/assets/54635/19866237/f901fbae-9f64-11e6-871a-c375d2c50162.png)

**Comment by t9md** [comment]
Thanks, I could reproduce it.
This is very critical bug, so will fix soon.

**Comment by thatsnotright** [comment]
Thank you very much for fixing this problem, I really appreciate it!
