### ISSUE TITLE
:<linenumber> goes to (current line number + <linenumber>)th line

### ISSUE THREAD

**Issue by SixFiveSoftware** [t9md/atom-vim-mode-plus#480]
# Check list

- Atom version info(`atom --version`)
1.11.2
- vim-mode-plus version.
0.65.0
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
Yes
- Tried to latest stable atom version with latest vim-mode-plus.
Yes
- Restarting Atom itself solve your problem?
No
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
Not that I can tell.
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

This appears to be an issue remaining from the original vim-mode project (https://github.com/atom/vim-mode/issues/975). Jumping to a line with a given line number jumps to current_line + desired_line. For example,

    2 this is line 2
    ...
    10 this is line 10
    11
    12 this is line 12

If cursor is on line 10, and I press `:2`, the cursor should go to line 2, not 12. I do not have much knowledge of how the package works, so I haven't yet tried to find a way to fix to propose a solution.

**Comment by jondot** [comment]
I solved this by installing ex-mode and mapping `;` (not `:`) to opening it.

```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  ';':'ex-mode:open'
```

In any case in Vim, I map ';' to ':'.

**Comment by t9md** [comment]
> current_line + desired_line
What package were you used with vim-mode?

From my understanding, when you type `:2` you go to absolute line, so you land on line `2`.
For this purpose you can use ex-mode(mainly for vim-mode), vim-mode-plus-ex-mode(maintained by me, but not actively), and default go-to-line command(if you didn't override it `ctrl-g` is default keymap).

If you can go down to 2 line bellow, type `2 j`(`j` by prepending count `2`).

**Comment by t9md** [comment]
Anyway `:`(ex-mode or command-mode command) is not scope of vim-mode-plus package.
If you want support for relative-number movement of by `:+2` or `:-2`(in pure vim you can use +/- to go-to-line relative-number-wise).to 

Open issue to respective package project.
