### ISSUE TITLE
Deprecated selector in `vim-mode-plus/styles/vim-mode-plus.less`

### ISSUE THREAD

**Issue by rumpelsepp** [t9md/atom-vim-mode-plus#485]
In `vim-mode-plus/styles/vim-mode-plus.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor.vim-mode-plus.normal-mode.is-focused::shadow .cursor,
atom-text-editor.vim-mode-plus.visual-mode.is-focused::shadow .cursor` => `atom-text-editor.vim-mode-plus.normal-mode.is-focused.editor .cursor,
atom-text-editor.vim-mode-plus.visual-mode.is-focused.editor .cursor`

* `atom-text-editor.vim-mode-plus-input-char-waiting.is-focused::shadow .cursor` => `atom-text-editor.vim-mode-plus-input-char-waiting.is-focused.editor .cursor`

* `atom-text-editor.vim-mode-plus.operator-pending-mode.is-focused::shadow .cursor` => `atom-text-editor.vim-mode-plus.operator-pending-mode.is-focused.editor .cursor`

* `atom-text-editor.vim-mode-plus.operator-pending-mode.is-focused::shadow .cursors.blink-off .cursor` => `atom-text-editor.vim-mode-plus.operator-pending-mode.is-focused.editor .cursors.blink-off .cursor`

* `atom-text-editor.vim-mode-plus.insert-mode.replace.is-focused::shadow .cursor` => `atom-text-editor.vim-mode-plus.insert-mode.replace.is-focused.editor .cursor`

* `atom-text-editor.vim-mode-plus.insert-mode.replace.is-focused::shadow .cursors.blink-off .cursor` => `atom-text-editor.vim-mode-plus.insert-mode.replace.is-focused.editor .cursors.blink-off .cursor`

* `atom-text-editor .vim-mode-plus-flash .region,
atom-text-editor::shadow .vim-mode-plus-flash .region` => `atom-text-editor .vim-mode-plus-flash .region,
atom-text-editor.editor .vim-mode-plus-flash .region`

* `atom-text-editor .vim-mode-plus-flash.added .region,
atom-text-editor::shadow .vim-mode-plus-flash.added .region` => `atom-text-editor .vim-mode-plus-flash.added .region,
atom-text-editor.editor .vim-mode-plus-flash.syntax--added .region`

* `atom-text-editor .vim-mode-plus-flash.removed .region,
atom-text-editor::shadow .vim-mode-plus-flash.removed .region` => `atom-text-editor .vim-mode-plus-flash.removed .region,
atom-text-editor.editor .vim-mode-plus-flash.syntax--removed .region`

* `atom-text-editor .vim-mode-plus-search-match .region,
atom-text-editor::shadow .vim-mode-plus-search-match .region` => `atom-text-editor .vim-mode-plus-search-match .region,
atom-text-editor.editor .vim-mode-plus-search-match .region`

* `atom-text-editor .vim-mode-plus-search-match.first .region,
atom-text-editor::shadow .vim-mode-plus-search-match.first .region` => `atom-text-editor .vim-mode-plus-search-match.first .region,
atom-text-editor.editor .vim-mode-plus-search-match.syntax--first .region`

* `atom-text-editor .vim-mode-plus-search-match.last .region,
atom-text-editor::shadow .vim-mode-plus-search-match.last .region` => `atom-text-editor .vim-mode-plus-search-match.last .region,
atom-text-editor.editor .vim-mode-plus-search-match.syntax--last .region`

* `atom-text-editor .vim-mode-plus-search-match.current .region,
atom-text-editor::shadow .vim-mode-plus-search-match.current .region` => `atom-text-editor .vim-mode-plus-search-match.current .region,
atom-text-editor.editor .vim-mode-plus-search-match.syntax--current .region`

* `atom-text-editor .vim-mode-plus-highlight-search .region,
atom-text-editor::shadow .vim-mode-plus-highlight-search .region` => `atom-text-editor .vim-mode-plus-highlight-search .region,
atom-text-editor.editor .vim-mode-plus-highlight-search .region`

* `atom-text-editor .vim-mode-plus-persistent-selection .region,
atom-text-editor::shadow .vim-mode-plus-persistent-selection .region` => `atom-text-editor .vim-mode-plus-persistent-selection .region,
atom-text-editor.editor .vim-mode-plus-persistent-selection .region`

* `atom-text-editor .vim-mode-plus-target-range .region,
atom-text-editor::shadow .vim-mode-plus-target-range .region` => `atom-text-editor .vim-mode-plus-target-range .region,
atom-text-editor.editor .vim-mode-plus-target-range .region`

* `atom-text-editor .vim-mode-plus-occurrence-match .region,
atom-text-editor::shadow .vim-mode-plus-occurrence-match .region` => `atom-text-editor .vim-mode-plus-occurrence-match .region,
atom-text-editor.editor .vim-mode-plus-occurrence-match .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by t9md** [comment]
released as v0.67.0 which is only available for v1.13.0-beta user
