### ISSUE TITLE
Extra new line created when using p or P after line-wise yank

### ISSUE THREAD

**Issue by mertzt89** [t9md/atom-vim-mode-plus#49]
When i do a line-wise yank (either by using yy or making a selection in line-wise visual mode then yanking) then a put operation, either before or after, it not only puts what I have yanked but it will be appended with an extra new line. For example:

```c
int main() {
    printf("Hello World!"); /* If I use yy on this line */
}
```

Using put-after
Key sequence: yyp
I get
```c
int main() {
    printf("Hello World!"); /* original line */
    printf("Hello World!"); /* put line */
    /* Extra new line here */
}
```

Using put-after
Key sequence: yyP
I get
```c
int main() {
    printf("Hello World!"); /* put line */
    /* Extra new line here */
    printf("Hello World!"); /* original line */
}
```

**Comment by t9md** [comment]
I coudn't reproduce issue.
What version, config, OS?
Is it happen if you execute `vim-mode-plus:put-after` from command-palette?
How is the keybinding resolver says when you type `ypp`?

**Comment by mertzt89** [comment]
Atom version: 1.2.4
vim-mode-plus version: 0.7.1
OS: Windows 7

When running vim-mode-plus:put-after from command palette I have the same problem.

According to keybinding resolver:

y -> vim-mode-plus:yank
p -> vim-mode-plus:put-after

I just had the idea that it could have to do with line endings. In my fail case I was using a Windows line ending file (CRLF). I just tried a new file using Unix line endings and the problem did not occur.

**Comment by t9md** [comment]
Thanks for nice investigation, this seem bug.
Still this kind of bug is everywhere in this packages since I simply use "\n" for new line.
I use Mac, sorry I should fix but need some time.
Does this issue happen in official vim-mode I'm glad if you could kindly check?

**Comment by mertzt89** [comment]
I just verified vanilla vim-mode handles this correctly regardless of line endings. If it would help I could possibly track it down and submit a PR.

**Comment by t9md** [comment]
Thanks very much, thats make fix easier since I can check diff from vim-mode.
Currently code is very actively changed I'm happy to get PR but I coudn't merge directly.
For my current dev style and for this specific issue, I'm happy if you put code fragment or give me hint on this discussion thread.
Anyway I will start investigation later.
Thanks!

**Comment by mertzt89** [comment]
I tested it again with b1fe03d and it seems to be fixed. Thanks!
