### ISSUE TITLE
Suggestion for toggle comments.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#500]
Does `vmp` offer a command to toggle comments and *then deselect* the currently selected text? Right now, I want to recreate the common Vim plugins that toggle comments for the visually selected region, but as soon as I comment I would like the visual selection to go away completely. Do you know of a way? I would like to put the customization in my keymap configuration.

**Comment by t9md** [comment]
`g /` for toggle comment operator.
So `g i i p` comment out paragraph.
`g i G` to comment out to end-of-line.
Also `i /` comment text-object is provided, so you can comment in your current comment by `g / i /`(toggle-comment targeting inner-comment text obj).
And of course you can repeat it by `.`.

**Comment by jordwalke** [comment]
The original question is how to toggle comment on whatever is visually selected, and then have the visual selection automatically cleared afterwards (without any other keystrokes)

**Comment by t9md** [comment]
Did you tried?
Visual select then `g /`.
When operator is executed in visual-mode, it target is current selected area.
So works against visual-selection and selection is automatically cleared.
This gives you answer?

**Comment by jordwalke** [comment]
Oh, I apologize. That one works very well. I originally just thought it was just using the built-in atom feature. Thank you.

**Comment by t9md** [comment]
Good to know you noticed another unknown vmp operator!
