### ISSUE TITLE
Find/Search-and-replace in selection does not work with vim-mode-plus

### ISSUE THREAD

**Issue by fkjogu** [t9md/atom-vim-mode-plus#504]
If vim-mode-plus is activated, the "Only in selection" scoping option of the find panel does not work in normal mode. Only for selections done in input mode it seems to work.

For selections done in visual-mode `v` it seems to loose the selection, when activating the "Only in selection" button. Line select `V` does not work at all.

Can somebody confirm this?

Atom version: 1.12.0, vim-mode-plus version: 0.66.1

**Comment by tangledhelix** [comment]
I cannot reproduce this today.

Both visual-mode `v` and line select `V` work fine for me in normal mode. Only matches in the current selection are found in the find panel when "Only in selection" is active. (And yes I made sure the non-selected parts of the file should have had further matches.)

I also tried in visual-block mode (`ctrl-v`) but no matches were found in that case.

- Atom version: 1.12.7
- vim-mode-plus version: 0.66.1
- Platform: macOS

I see we have the same version of VMP, but my Atom is newer. Perhaps you can try on latest Atom and see if the issue has gone away for you too?

**Comment by fkjogu** [comment]
Seems to be fixed.
