### ISSUE TITLE
install failed on Mac

### ISSUE THREAD

**Issue by leohxj** [t9md/atom-vim-mode-plus#509]
Atom: 1.12.1
vim-mode-plus: 0.66.1, atom says: "Version 0.66.1 is not the lastest version available for this package, but it's the latest that is compatible iwth your version of Atom"

When I click install or run `apm install vim-mode-plus` in terminal, it always:

```
~ apm install vim-mode-plus
Installing vim-mode-plus to /Users/leohxj/.atom/packages ✗

npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/leohxj/.atom/.apm/.apmrc" "--userconfig" "/Users/leohxj/.atom/.apmrc" "install" "/private/var/folders/sy/tvg9w8pn16lc3ryhgl3cmx5r0000gn/T/d-1161017-7053-1jxo1wk/package.tgz" "--runtime=electron" "--target=1.3.6" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5

npm ERR! shasum check failed for /var/folders/sy/tvg9w8pn16lc3ryhgl3cmx5r0000gn/T/npm-7064-d5352123/registry.npm.taobao.org/emoji-images/download/emoji-images-0.1.1.tgz
npm ERR! Expected: f992dc72092c03fbe092827631987eb3b1319b67
npm ERR! Actual:   c51ea6e8f3e3bd0e06a3cfc6b4ff0cb7ea09ad7a
npm ERR! From:     https://registry.npm.taobao.org/emoji-images/download/emoji-images-0.1.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/sy/tvg9w8pn16lc3ryhgl3cmx5r0000gn/T/apm-install-dir-1161017-7053-wa5g4h/npm-debug.log
```
ps: I have changed the apm registry to https://registry.npm.taobao.org/.

What reason is this problem?

After that, I try to using git to clone vim-mode-plug, then `npm install`. put the whole folder to `~/.atom/packages`, restart Atom, vim-mode-plus works, but no setting options on it. how to fixed this ?

**Comment by t9md** [comment]
If you are using stable(=v.1.12) v0.66.1 is latest. So no problem just install by clicking install button from setting-view.

If you are using beta(=v1.13-betaX) v0.67 is latest and it is no compatibility with atom stable(v1.12).
Wait until v1.13 become stable if you don't want to stick to atom-beta.
