### ISSUE TITLE
yy and p leaves extra blank line below

### ISSUE THREAD

**Issue by ytnmgg** [t9md/atom-vim-mode-plus#51]
When using yy to copy one line and then typing p to paste that line, I'll always get two lines, one of which is an annoying blank line that i have to delete it manually...

**Comment by t9md** [comment]
What version you use?

**Comment by ytnmgg** [comment]
Atom:1.2.4
vim plus: 0.8.0

**Comment by ytnmgg** [comment]
windows os by the way

**Comment by ytnmgg** [comment]
Haha, i did update it to 0.8.0 but didn't reload Atom, 
I just checked that this bug is fixed after reload Atom...
Thanks! Nice!

**Comment by t9md** [comment]
Good!
