### ISSUE TITLE
Feature Request: Project find from search preview window.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#511]
Latest everything (atom, vmp). Old deprecated project-find-from-search plugin is disabled.

The `cmd+enter` for the new project find from search is great, and it thankfully reuses existing windows when you hit enter on a result. But it used to show a vertical split preview window along side the results window. That was very helpful. Now it is removed. I believe the removal was intentional for simplicity of implementation. That is understandable. I just wanted to make a new issue for the long term, to track the ability to add it back some day.

**Comment by t9md** [comment]
Check `Open Project Find Result In Right Pane`.

<img width="607" alt="settings_ ___github_atom-narrow" src="https://cloud.githubusercontent.com/assets/155205/20459453/d2bc002a-af04-11e6-8cc4-3625f92028ff.png">

The behavior diff you explained is not comes from recent change(inclusion to vmp-core).
If it works well t9md/atom-project-find-navigation#6 is the same reason?
I want say also this issue is not comes from my change.

**Comment by jordwalke** [comment]
Oh, thank you.

Two questions about your experience.
- When you have that option enabled (Right pane), and you hit `cmd+w` to close the search results pane, does it correctly focus the text editor. For me it does not - I have to click explicitly on it after closing the results pane.
- When you navigate with `j/k`, it will (thankfully) show a preview of the result in the vertical split. If the file is already open, it thankfully shows the existing file (which is nice). If the file is *not* already open, it will open up the file in a new temporary tab. When cycling through the results, all files that were *not* already opened by me originally, will be previewed in this special temporary tab. The title of the tab ie *italicized* to represent this. I would expect that if I hit `enter`, on any of the items in the results pane, then the temporary tab becomes permanent. That part is working correctly. The temporary tab becomes permanent when I hit `enter` on a result in the results pane. But suppose I *don't* hit `enter` on any of the results. When I close the results pane, the temporary tab is not removed in that case. I would expect it to be removed if I never hit `enter` on any of the results. Do you see the same, and do you agree?

**Comment by t9md** [comment]
- For the first question, yes same, frustrating regression from atom v1.13.0, I opened [this](https://github.com/atom/atom/issues/13206).

- For the second question. the `j/k` navigation is still not comes from vmp's core, this comes from  `project-find-navigation` package you are using, and what you are explaining here is exactly same as [this](https://github.com/t9md/atom-project-find-navigation/issues/6) issue isn't it?
What happened is same as me, and for `DestroyPendingPaneItemOnFindResultPaneWasDestroyed` like feature, I don't want to do it, if I try to do so, I have to distinguish originally-opened-pending-item and pending-item-opened-while-navigation, and I should not simply destroy the paneItem if it's originally opened before find-result was opened. Nevertheless the benefits by this enhancement will not match the amount of logic/code/complexity it will require from my assumption).
I'm not recognizing it as **preview**, so current behavior is natural, if I try to implement it's own **preview** window I don't think I can do with understandable behavior(can Implement but it's seem to hard to define what the **correct** behavior is)

**Comment by jordwalke** [comment]
> this comes from project-find-navigation package you are using, and what you are explaining here is exactly same as this issue isn't it?

I thought I disabled that package, but it looks like I didn't. Yeah, I guess the `j/k` behavior was coming from `project-find-navigation`. Now that I fully disabled it, the `j/k` keys don't work (as expected), and the arrow keys do work, however there is *no* live preview in the "temporary" tab as I described earlier. Who implemented the temporary tab feature?


Thanks for filing that issue on Atom about focusing the window.

**Comment by t9md** [comment]
> Who implemented the temporary tab feature?

For explicitness what actually is, I call `"temporary" tab` as pending-pane-item.

`project-find-navigation` open `pending-pane-item(what you are calling preview)`, while `j/k` navigation.

If you disable, that feature is disappear, isn't it so natural?

the allow key navigation is comes from original `find-and-replace` but it doesn't open item automatically that was not useful(that's why I monkey patching it by `project-find-navigation`).

**Comment by jordwalke** [comment]
Okay, I understand now.  I understand why `DestroyPendingPaneItemOnFindResultPaneWasDestroyed` may not be worth the complex logic required to implement it.


On the other hand - it seems *someone* *somewhere* knows which tabs to destroy. The answer is whichever tabs have an *italic* title. Now, maybe the harder question is how you can easily determine that from `project-find-navigation`'s code. Who is setting the title of the tab to be italic?

**Comment by jordwalke** [comment]
And I agree that selling the plugin as **preview** is wrong. I think it's better than just *preview* right now. It helps me actually open the code in the original tabs if they were already open.

**Comment by t9md** [comment]
>  Now, maybe the harder question is how you can easily determine that from project-find-navigation's code. Who is setting the title of the tab to be italic?

Is this question? When never you  single click on `tree-view`, it opened as pending state.
pending state item is shown as italic, and pending-item is replaced when another pending item was opened(single pending-item per pane rule).
If you edit or doubleclick tab of pending-item, it become normal item which is no longer replaced by new pending-item.

When I open item by `j/k` motion of `project-find-navigation`, open as `pending-item` if there is not existing buffer for that item was opened.

**Comment by jordwalke** [comment]
So you're saying that simply looking at whichever panes are pending, is not a good enough solution? I was probably wrong to assume. You know much better than I do.

**Comment by t9md** [comment]
> So you're saying that simply looking at whichever panes are pending, is not a good enough solution? I was probably wrong to assume. You know much better than I do.

For feature request?
You are suggesting "close pending-item on result pane closed timing" and don't care thorough which  command that pending-item was opened, right?

**Comment by t9md** [comment]
It might be easy to implement, I just thought it is not intuitive and is rude(destroying paneItem which was originally opened outside of `project-find-navigation` command).
So didn't think it's worth.

**Comment by jordwalke** [comment]
Okay, I understand. Good call. I didn't realize other plugins open things in pending panes. I can't recall ever seeing pending panes lasting a long time. I kind of assumed, if a pane is pending, the user has to do something to make it non-pending, or else they can't expect it to stay open.

**Comment by t9md** [comment]
So what's conclusion?
Do you want to add setting like `ClosePendingItemOnFindResultPaneWasDestroyed ` for `project-find-navigation`

**Comment by jordwalke** [comment]
No, that isn't the conclusion. The conclusion is that you understand the tradeoffs best and I totally trust you when you say it's not worth it to implement `ClosePendingItemOnFindResultPaneWasDestroyed` at this time. I just wanted to learn about pending panes, so I asked.

**Comment by t9md** [comment]
OK, thanks for clarifying.
