### ISSUE TITLE
ci' not working

### ISSUE THREAD

**Issue by Hedgepig** [t9md/atom-vim-mode-plus#517]
- Atom version 1.11.1
- vim-mode-plus version 0.66.1.

Currently I can't seem to get ci' or ci" working. When attempting with double quotes, it seems to leave it at the "ci" stage, and ci' puts the editor into insert mode.

**Comment by t9md** [comment]
Works my environment, so I wonder somewhat depending to you environment.

If you want to move investigation forward, read and follow the instruction in the following template.

https://github.com/t9md/atom-vim-mode-plus/blob/master/ISSUE_TEMPLATE.md

**Comment by farhaanbukhsh** [comment]
I am facing the same issue , `ci"` stops at `ci`.

**Comment by t9md** [comment]
give me, your environment info
- atom, vmp, os version)
- exact same text to reproduce, and keystroke

**Comment by t9md** [comment]
Close in favor of #668
