### ISSUE TITLE
Yanking certain text objects to specified register does not seem to work

### ISSUE THREAD

**Issue by traytonwhite** [t9md/atom-vim-mode-plus#522]
When yanking certain objects to a specified register, it fails to copy to the register. Examples below:

```
" a y y
" a p
```

This movement for yank works. It copies the line into register `a`, and then pastes the line from register `a`.

```
" b y f ,
" b p
```

This appears to copy the text from the cursor through to the first comma - there is a highlight blip showing the yank seems to work. But pasting from the register results in no output (as if the register is empty).

**Comment by t9md** [comment]
#520
