### ISSUE TITLE
Searching for search-text with `$` not at end should remove special meaning of `$`

### ISSUE THREAD

**Issue by plbowers** [t9md/atom-vim-mode-plus#523]
Normally with regex a `$` matches end-of-line.

If someone searches for `$foo` this will never match anything.

It would be a nice feature if the `$` lost its anchor function at that point or was automatically replaced with `\$`.

Reference vim behavior - when you search for `$` it finds the end of the line but when you search for `$foo` it finds that variable.

**Comment by plbowers** [comment]
If you search using `*` or `#` on `$foo` then it correctly finds that variable (`$` is not an anchor).

But if you then `/` or `?` and up-arrow to pull up the last search value it cannot find it because now in `$foo` the `$` is treated as an anchor, thus an impossible-to-match search term.

**Comment by t9md** [comment]
`$` starting pattern is still valid when user want to search `$\nabc`(`abc` after `\n`).
Currently auto-escaping regex-pattern is happen only when regex was INVALID

This is not really useful I understand, but I prefer explicitness  over doing-some-accommodation-automatically.

So, won't fix.

> If you search using * or # on $foo then it correctly finds that variable ($ is not an anchor).
> 
> But if you then / or ? and up-arrow to pull up the last search value it cannot find it because now in $foo the $ is treated as an anchor, thus an impossible-to-match search term

OK, I could reproduce it in perl grammar, I thinks I can improve in some way.
