### ISSUE TITLE
Sum up undocumented feature.

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#54]
### Replace with register

- `vim-mode-plus:replace-with-register`
Replace target(selected or text-object) obj with the content of register.

e.g. precondition: you mapped this cmd to `_`.

`yiw` then move next word `w`, `_iw` replace word under cursor with content of register and can repeat it with `.`.

### Surround

default mapping is subject to re-think.

```
'g s s': 'vim-mode-plus:surround'
'g s w': 'vim-mode-plus:surround-word'
'g s d': 'vim-mode-plus:delete-surround'
'g s c': 'vim-mode-plus:change-surround'
```

### CamelCase, DashCase, SnakeCase

```
  'g c':   'vim-mode-plus:camel-case'
  'g /':   'vim-mode-plus:toggle-line-comments'
  'g -':   'vim-mode-plus:dash-case'
#  'g _': 'vim-mode-plus:snake-case'
```

### Examples operation using new features.

e.g.
- `gci'`: CamelCase inner-single-quote.
- `g/il`: Toggle comment for current line
- `g/ip`: Toggle comment for paragraph
- `g/i/`: Toggle comment for commented-area(text-object comment)
- `g-is`: DashCase for the area of inner-any-pair(`is` is mapped to inner-any-pair)
- `dii`: Delete inner-indentation(deeper level of indentation stop at blank row).
- `vaf`: Select a-function.
- `yif`: Yank inner-function.
- `ciz`: Change inner-fold
- `vae`: Select a-entire buffer(not diff from inner-entire).

### Select Latest change

When you Change/Yank text, it saved to `[`, `]` marker.
This command simply select range maked by those maker.

e.g. precondition: you map it to `gc` like bllow.
```
  'g c':    'vim-mode-plus:select-latest-change'
```
`yap`: Yank current function.
`}` to move next blank line
`pgcu` paste then select area just pasted with `gc` then lowercase this pasted paragraph with `u`.

### Insert last inserted

Disabled by default, intended to be mapped in insert-mode.
In pure Vim its provided as `ctrl-a` keymap to re-insert previously inserted-text again in different insertion timing'
Each time you escape from insert-mode, inserted text are remembered as `.` register.
You can insert it by `ctrl-r.` by referencing `.` register.
`insert-last-inserted` command is merely shorthand version of above operation. I mapped it to `ctrl-i` in insert-mode.  

### Increment/Decrement

Very experimental state. Vim also have similar feature.
But behavior is slitely different.
Increment/decrement number selected by using first instance of number as base number in selection.

```
  'g ctrl-a': 'vim-mode-plus:increment-number' # experimental
  'g ctrl-x': 'vim-mode-plus:decrement-number' # experimental
```

### stayOnTransformString, stayOnYank, flashOnOperate

in pure Vim, most of operation move cursor to start position of target object.
e.g `yip` move your cursor to first line even if you type this command from 3rd line of this paragraph.
You can notice your yanking operation is success by this cursor movement.
But for movement-wise I don't want this auto-move, I just want to `yip` here without moving cursor position to move downword after `yip`.
By enabling `stayOnYank`, cursor position won't be auto-changed after yank. `stayOnTransformString` is same purpose for other string transformation operation like surround, uppercase, lowercase etc..
The probmem is you no longer can depend on auto-cursor-movement to know your yanking operation is scceeded. To compliment this `flashOnOperate` is there.
`yip` not move cursor but you can have confidence of your yanking(`y`) operation by seeing short flash of inner paragraph(`ip`).

### showHoverOnOperate

Show hover icon/emoji/none.
Even if you disable this fancy feature.
count(e.g. `10dd`) and register(e.g `"add`) prefix are shown on hover.
I believe this is better than Vim's way showing count on statusbar(need  more eye movement).

Even if you don't want fancy feature,
 `showHoverOnOperate=true`, `showHoverOnOperateIcon=none` helps a lot when you ChangeSurround. This opertion demands two char(e.g `[{`) and then require target text-object.
You lost where you are in this long road ride of ChangeSurround operation.
Hover show char as you type so you don't have confidently proceed this long road.

### My favorite keymapping

```
'atom-text-editor.vim-mode-plus.operator-pending-mode':
  'c': 'vim-mode-plus:inner-word'

atom-text-editor.vim-mode-plus.visual-mode':
  ';': 'vim-mode-plus:inner-any-pair'
  "'": 'vim-mode-plus:inner-any-quote'

'atom-text-editor.vim-mode-plus.normal-mode':
  'S':   'vim-mode-plus:surround-word'
  'd s': 'vim-mode-plus:delete-surround-any-pair'
  'c s': 'vim-mode-plus:change-surround-any-pair'
```

- `yc` to yank current word.
- `cc` to change current word
- `y;` to yank innser-any-pair like inside text of `'` single quote.
- `_;` to replace yanked(register value) text to inner-any-pair(like inside of parenthesis).

### advancement from vim-mode

- `gi` to start insert mode where you exited from insert-mode previously.
- `gv` re-select last selection.

- Target requiring operator can operate on line when duplicated.

When target requiring Operator are invoked twise in a row, it operate on linewise range.

e.g. `dd`, `gUgU`, `yy`, `gugu`.

### Issue

 The cursor position in visual-mode become strange in multi-byte char buffer.

**Comment by t9md** [comment]
@bronson here is very rough sketch of significant feature I should mention(maybe I'm not complete though).

I thinks document should be go into wiki.
I'm OK if you edit this wiki directly.

I also put old features not to here.
https://github.com/t9md/atom-vim-mode-plus/wiki/Features

**Comment by bronson** [comment]
I'll start looking at this.  I'm not real stoked to put a lot of content in the wiki because it's guaranteed to get out of date but I don't have a better idea...  I'll try to figure something out.

Just curious, why not emulate surround's mappings closer?  I've grown to like `ysiw"` and `cs'"`.  :)  Also, why not use text objects when surrounding?  Finally, is there any way to prevent `g s w` from inserting a space at the end of the word?  (`g s i w` could insert without any space, and `g s a w` could insert with space....?)

**Comment by t9md** [comment]
> I'll start looking at this. I'm not real stoked to put a lot of content in the wiki because it's guaranteed to get out of date but I don't have a better idea... I'll try to figure something out.

Guaranteed to get out of date is theory to be applied ALL DOCS not only wiki.
But for me wiki is easier / lower hurdle to update.

> Just curious, why not emulate surround's mappings closer? I've grown to like ysiw" and cs'". :) Also, why not use text objects when surrounding? Finally, is there any way to prevent g s w from inserting a space at the end of the word? (g s i w could insert without any space, and g s a w could insert with space....?)

No particular reason, I might should disable default `gss` keymapping.
I'll try keymap vim-surround provide(`ysiw` I mean).
For 'why not use text objects' is about internal implementation of Surround class?
Assuming that, the reason is because its bit old and I can rewrite to user text-object internally, but benefit of current implementation is, you can surround text by ANY input char like `|`.
OK I should create PairByInput text object and use it by SurroundByInput for consistency but not sure its provide any goodness...

**Comment by t9md** [comment]
Oversights for your comment

> is there any way to prevent g s w from inserting a space at the end of the word? 

Will investigate.

**Comment by t9md** [comment]
Another new feature I came up with a few minutes ago.

https://github.com/t9md/atom-vim-mode-plus/commit/48be41367b10775c3b2b4685251b3bee12051405

Since I rewrote test case using mini DSL.
This test case is self explanatory I think.
Map surround apply surround to each word of target(textobject or visual-selection).

btw: In vim-mode-plus,, command name are derived from ClassName and auto-registered at initialization, adding new Operation/TextObject/Motion is very easy.

**Comment by t9md** [comment]
I should explicitly name it as `MapSurroundByWord` since its apply token scanned by regexp `/\w+/g`.
Maybe I might introduce `MapSurroundByRegexp` to read scan pattern(=regexp) from user.

**Comment by t9md** [comment]
Here the GIF https://github.com/t9md/atom-vim-mode-plus/wiki/GIFs#mapsurround

**Comment by bronson** [comment]
Wow, it's been 9 days already?  Writing docs is still on my TODO list, I'll get to it.

**Comment by t9md** [comment]
This is continuous task. Not completed, but no need to managed by this issue.
