### ISSUE TITLE
vim-mode not by default / Please add a hotkey to activate vim-mode

### ISSUE THREAD

**Issue by ManuelSchneid3r** [t9md/atom-vim-mode-plus#548]
Well it would be nice if we could choose to enter or leave vim mode.

**Comment by t9md** [comment]
Check setting `startInInsertMode`

**Comment by ManuelSchneid3r** [comment]
Is the insert mode exactly the same as if there were no vim-mode at all?

**Comment by t9md** [comment]
No.
If your request is disable/enable vim-mode-plus like you can do from settting-view, it can not do by this package. Out of scope.
Search packages to find control disable/enable package(I donn't know its exist though)

**Comment by t9md** [comment]
Correction, technically achiavable, but I wont.

**Comment by ManuelSchneid3r** [comment]
My request is, like in some other IDEs, the option to hit a hotkey to activate the vim mode. Some users like me use the normal editor most of the time but use vim-mode for more complex editing. If you don't want this by design please close this issue.

**Comment by ManuelSchneid3r** [comment]
I dont mean to completely deactivate the extension on the atom-plugin level, but just deactivate whatever this plugin does under the hood.

**Comment by t9md** [comment]
I cannot decide to implement your request at this point. 
But you can try following setting.

#### Define command to activate/deactivate in your `init.coffee`

```coffeescript
atom.commands.add 'atom-workspace',
  'user:activate-vim-mode-plus': -> atom.packages.activatePackage('vim-mode-plus')
  'user:deactivate-vim-mode-plus': -> atom.packages.deactivatePackage('vim-mode-plus')
```

#### Then keymap to that command in `keymap.cson`

```coffeescript
'atom-workspace:not(.editor)':
  'ctrl-up': 'user:activate-vim-mode-plus'
  'ctrl-down': 'user:deactivate-vim-mode-plus'
```

**Comment by t9md** [comment]
Easily implemented by user's command.
I wont implement it by vmp itself.
This should be the command executed out of subjective package.
