### ISSUE TITLE
support startofline option for pure-Vim

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#549]
Ref: http://vimdoc.sourceforge.net/htmldoc/options.html#'startofline'

This option affects **many commands and it's effect is very important**.

### Summary

- pure-Vim have `startofline` option.
- This option is to control behavior of **vertical movement** motion.
- This option is default `on`
- When `on` cursor's column is set to start of first character of line.
- When `off` cursor's column is kept.

## Affected behaviors in pure-Vim

- Motions
  - `ctrl-f`, `ctrl-b`, `ctrl-d`, `ctrl-u`, `G`, `g g`, `H`, `M`, `L`
- Operators
  - `d`, `< <`, `> >`
    - with linewise motion(vim-help says "linewise operator")
    - with `%`
    - with count(e.g. `3 > >`)

## Design decision

- Configuration OptionName: `moveToFirstCharacterOnVerticalMotion` (default `true`)
- Affected to only motions
  - [x] `ctrl-f`, `ctrl-b`, `ctrl-d`, `ctrl-u`
  - [x] `G`, `g g`
  - [x] `H`, `M`, `L`

- For operators, use existing `stayOnXXX` options
  - `d`: `stayOnDelete`
  - `> >`, `< <`: `stayOnTransformString`

## off-topic: `d` with startofline=off is same as `stayOnDelete` behavior?

Yes, when I came up with idea of `stayOn`, I didn't understand `startofline` option correctly.
So I introduced `stayOnDelete` independently. Just my ignorance!

**Comment by t9md** [comment]
what is the better option name?
- `setCursorToFirstCharacterOfLineOnVerticalMotion`: (default `true`, equal to startofline)
- `keepColumnOnVerticalMotion`: (defaullt `false`, opposite of startofline)

**Comment by t9md** [comment]
? `moveToFirstCharacterOnVerticalMotion`

**Comment by bronson** [comment]
Very cool!

I'd go for `keepColumnOnVerticalMotion` because it's shorter and ideally things should default to false.  But any of those seem fine.

**Comment by t9md** [comment]
I like `keepColumnOnVerticalMotion` name, but I go for `moveToFirstCharacterOnVerticalMotion`  since it's describe **action** it will do.

With `keepColumnOnVerticalMotion` what happens when it was `false` is not obvious.

For default value, I'll follow vim's default.

**Comment by bronson** [comment]
Can't argue with that -- since Vim's default is true, might as well continue that tradition.
