### ISSUE TITLE
surround doesn't work with multi-line <>

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#552]
- Atom 1.12.6
- vim-mode-plus 0.66.1

Repro:

```
<bla
  a=1
>
```

change-surround-any-pair inside the angle brackets doesn't work. It works with the brackets are on the same line.

**Comment by t9md** [comment]
Thanks you reporting,
I checked, the `<` is `AngleBracket` text-object, which I intentionally disabled multiline search.
AFAICR, I disabled it when I introduced Tag text object and add `Tag` to member of AnyPair.
But don't remember.
I'll fix.

### New spec

- Make `AngleBracket` can find outer-current-line area.
- Exclude `Tag` from `AnyPair` TextObject which frequently conflict with `AngleBracket`.
- When user want to manipulate `Tag`, use `i t` or `a t` text-object explicitly.

**Comment by t9md** [comment]
@chenglou Fixed, my main dev is now at Atom-dev based.
If you stick to Atom-stable, this fix will be available when Atom 1.13 become new stable.
