### ISSUE TITLE
Text object for { seems to not work in some case.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#556]
# Check list

- Latest version of Atom Beta as of right now.
- Latest vmp version as of right now.

With this gist, put your cursor on the second instance of `module`. Then try `vi{`.

https://gist.github.com/jordwalke/ff38d938507389e54fed2c2adf060252

**Comment by t9md** [comment]
OK confirmed the reason is because of this line 

https://gist.github.com/jordwalke/ff38d938507389e54fed2c2adf060252#file-gistfile1-txt-L236

It's include `{` in string , so this make pair of `{`, `}`, unbalanced.

I'll check how vim handle this situation.

**Comment by t9md** [comment]
- here is minimum text to reproduce issue
- language is `javascript`.

```javascript
if (a) {
  if (b) {
    "hello {";
  }
  console.log("bye");
}
```

- Place cursor at 2nd line( line of `if (b)` text ).
  - vmp: `v i {` fail to select.
  - pure-Vim: `v i {` select correct range.( from 1st line `{` to last-line `}`)
    - But bracket matcher fail to highlight correct pair
    - `%` motion fail to move to paired `}`

- when I change quote char from `"` to `'`(from `"hello {"` to `'hello {'`
  - vmp: `v i {` fail to select.
  - pure-Vim: `v i {` fail too

- So pure-Vim seems doing some special treatment for `"` quote.

Will think for a while what I can do.

**Comment by t9md** [comment]
To fix this
- First, I will mimic pure-Vim behavior(add special care for char(`{`) in double quoted range)
- 2nd, Will consider using syntax-scope information for more accuracy(in different issue)
