### ISSUE TITLE
`dd` in last line of buffer move cursor one line up.

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#56]
Maybe long living issue from vim-mode,  I didn't investigated yet.

When you `dd` in last line of buffer, Vim remove entire line that result in upper line become last line.
But vim-mode-plus, it only delete text of line but cursor remain same line.
`dd` always remove 'current whole line on any-line' is more intuitive and consistent ux.
So I should follow original Vim's behavior but currently not.

**Comment by bronson** [comment]
Yep, it's been in vim-mode since day one I think.

The problem is that vim-mode (and v-m-p) allow the normal mode cursor to go past the last line in the file.  Here's an example: create a new buffer, hit `a b esc` to insert a b, and notice you can't navigate up and down.  Perfect behavior.  Save the buffer.  Now you can!  And there's the bug.

Really, Atom isn't very good about handling newlines at the end of the file: https://github.com/atom/atom/issues/4741

I agree with that issue: it's bizarre edit the file without the final newline, then have it magically appear when the file is saved.  Ideally, Atom would just ensure that the final newline is always there or never there.  So maybe this is an upstream bug.

**Comment by t9md** [comment]
Oh I finally understand whats the problem correctly.
The last row I thought its last row is not last row actually.
When I open same buffer in Vim or simply counting row by `wc -l FILE`, its one line smaller than where I can  move in Atom text buffer.
So preventing put cursor on Atom's last row is more reasonable approach I feel.
I'll try to find some solution with this approach.

**Comment by t9md** [comment]
## Requirement

Should not put cursor on **last-empty-row**.
Why?
Because **last-empty-row** where you can move in Atom is the row where pure Vim don't allow to move to.

* In Vim's semantics.
- EOF is next position of very last character.
- LastRow is Row of EOF position.

## TODO

1. Define function which return EOF position in Vim's semantics.
2. Update `Motion::getLastRow` to return Vim's LastRow. affect `G`, `N%`, `L`
3. Adjust cursor position for Delete(`d`) operator when cursor is on LastRow.
4. Ensure `j` don't past LastRow.
5. Ensure `w` don't past EOF.
6. Ensure `l`, `h` don't past EOF when `wrapLeftRightMotion` is enabled.

## My thought about this feature:

I feel this effort is a little too much flight from Atom's native feature.
Ideally vim-mode-plus should be thin layer of Atom's core editing functionality and never change meaning of fundamental concept.

Should I make this feature optional by providing config param like `disallowCursorOnLastBlankRow`?
No, I don't want to manage two different scenario.
Let's try and evaluate then the result was bad I can learn and willingly remove this feature(willingly give up this feature).

## DONT go too far

DONT trying to adjust cursor position done in outer world of vim-mode-plus.
Mouse still can click **last-empty-low** but I don't care.
Non-vim-mode-plus commands can go past EOF, I don't care.
In insert-mode you can go past EOF by `c-f` and cursor position is not adjusted when returned to normal-mode.
I don't care.
An Attempt to being perfect would perfectly fail.
It's not Vim, Atom, vim-mode-plus can exists because of underlying core Atom feature, don't trying to concur your mother earth.
And respect other package, don't disturb other package's attempt by trying to adjust cursor position on every case.

**Comment by t9md** [comment]
Released as v0.9.0

**Comment by t9md** [comment]
Still lots of overlooking...

**Comment by bronson** [comment]
Works great.  Really impressive.
