### ISSUE TITLE
[bug] Move Cursor "a lot" causes Atom to Hang or Crash

### ISSUE THREAD

**Issue by zeroem** [t9md/atom-vim-mode-plus#560]
Atom: 1.12.6
Electron: 1.3.9
Chrome: 52.0.2743.82
Node: 6.5.0

vim-mode-plus: 0.66.1

In `normal` mode enter, `123123123123k`, observe.

Smaller numbers will cause it to hang less, eg `123123k` will still hang for a few moments before going to the top of the file.

**Comment by t9md** [comment]
Thanks for reporting, will check.

**Comment by t9md** [comment]
What make Atom freeze is by doing lots of `Motion::moveCursor(cursor)` by count times.

Should stop at the timing of NO-MORE-MOVABLE point.

IDEA to fix this

- Introduce `fail-to-move` event and `@onDidFailToMove`
- Calling `@stopMoving()` in `@onDidFailToMove` hook for necessary motions.
- Which prevent stupidly doing useless `moveCursor` tryout anymore.
