### ISSUE TITLE
atom gets stuck if hold '5' key in command mode

### ISSUE THREAD

**Issue by prog666** [t9md/atom-vim-mode-plus#561]
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
vim-mode-plus: 0.66.1

![screen shot 2016-12-05 at 13 54 55](https://cloud.githubusercontent.com/assets/6894885/20882629/f622d06c-baf2-11e6-9ad2-51328e034ad9.png)

had to force quit atom. I know holding key '5' makes no sense, did it accidentally.

**Comment by t9md** [comment]
Dup of #560
