### ISSUE TITLE
respect last cursor position when clearMultipleCursorsOnEscapeInsertMode is true

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#562]
What currently doing is just call `@editor.clearSelections()`.
I noticed recently that `@editor.clearSelections()` not respect original lastSelection's cursor position when clear selection and destroy multiple cursors.

So I want improve it  by respecting last selection's cursor position.

**Comment by t9md** [comment]
Done, affects

- when `clearMultipleCursorsOnEscapeInsertMode` was `true`
- e.g. `c o f` then insert something then `escape` return original cursor's position. WAS not older version
- e.g. `cmd-d` multiple time then `c` to insert something, then `escape` return to last selection's position.

Even older behavior seems to work well in most case(return to topmost place), it's was not correctly managed and not consistent across different operation.
So I'll set this new behavior is **base**.
Will improve, tweak from this base.


# before v0.69.0

![before](https://cloud.githubusercontent.com/assets/155205/20887488/2e5c796a-bb3e-11e6-9124-5ea0dd6eea16.gif)


# after


![after](https://cloud.githubusercontent.com/assets/155205/20887493/31a5f0d8-bb3e-11e6-9fea-32c640d3db08.gif)

**Comment by itsthatguy** [comment]
@t9md was this fixed?

**Comment by t9md** [comment]
Yes.
If you found some issue, open new issue.

**Comment by itsthatguy** [comment]
@t9md yea, not working for me.

**Comment by t9md** [comment]
Open new issue. since it work for me. I won't comment on this issue.
