### ISSUE TITLE
Why are vim-surround keymaps disabled?

### ISSUE THREAD

**Issue by arnm** [t9md/atom-vim-mode-plus#565]
# Check list

- Atom version info
```
↳ atom --version
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
- vim-mode-plus version  `0.66.1`

Why are vim-surround keymaps disabled? https://github.com/t9md/atom-vim-mode-plus/blob/v0.66.1/keymaps/vim-mode-plus.cson#L398-L409

**Comment by t9md** [comment]
As a general rule, I won't provide keymap which is not pure-vim provides by default.
But put keymap with commenting out as  reference purpose for user.

**Comment by arnm** [comment]
Ok sounds good to me. It was a little confusing though since in the README it states vim-surround is built-in. Maybe a disclaimer that it is not enabled by default would be good.

**Comment by t9md** [comment]
OK, will do, thanks for suggestion.

**Comment by t9md** [comment]
I decided to provide default-keymap-for-surround by [this package](https://github.com/t9md/atom-vim-mode-plus-keymaps-for-surround).
And mentioned in README.md of vim-mode-plus.
