### ISSUE TITLE
Question: Is it possible to emulate vim-unimpaired ]-space and [-space bindings?

### ISSUE THREAD

**Issue by nwaywood** [t9md/atom-vim-mode-plus#568]
I use the `[-space` and `]-space` bindings quite a lot from [vim-unimpaired](https://github.com/tpope/vim-unimpaired) and am trying to emulate their behaviour. I have added the following to my `init.coffee`:

```
atom.commands.add 'atom-text-editor', 'custom:unimpaired-new-line-below', ->
    editor = atom.workspace.getActiveTextEditor()
    atom.commands.dispatch(atom.views.getView(editor), "vim-mode-plus:insert-below-with-newline")
    atom.commands.dispatch(atom.views.getView(editor), "vim-mode-plus:activate-normal-mode")
    atom.commands.dispatch(atom.views.getView(editor), "vim-mode-plus:move-up")

atom.commands.add 'atom-text-editor', 'custom:unimpaired-new-line-above', ->
    editor = atom.workspace.getActiveTextEditor()
    atom.commands.dispatch(atom.views.getView(editor), "vim-mode-plus:insert-above-with-newline")
    atom.commands.dispatch(atom.views.getView(editor), "vim-mode-plus:activate-normal-mode")
    atom.commands.dispatch(atom.views.getView(editor), "vim-mode-plus:move-down")
```

which nearly works except for the fact that the cursor position is lost. Is it possible to do this and keep the cursor at its original position?

**Comment by nwaywood** [comment]
Sorry disregard this request. I was just doing some work in vim and realised that the `]-space` and `[-space` bindings in vim don't remember the cursor position either.

**Comment by t9md** [comment]
I didn't understand what you wanted.

**Comment by t9md** [comment]
Just insert newline below or above without moving your cursor?

**Comment by t9md** [comment]
Is this what you want?
ignore content of text, see behavior "new-line" inserted below or above with N count support, without moving cursor position.

![insert-newline-operator](https://cloud.githubusercontent.com/assets/155205/21003921/428e67a6-bd71-11e6-921e-ecb51b360155.gif)

**Comment by nwaywood** [comment]
Yes that is the behaviour I am after 😃 

How are you doing that? When I use the `Editor: Newline Above` and `Editor: Newline Below` commands the cursor moves to the new line

**Comment by t9md** [comment]
OK, will provide at vim-mode-plus feature.
Are you using atom-beta? My main dev is for Atom-beta now.

**Comment by nwaywood** [comment]
Wow thank you, that's awesome! 

Yes I am using the beta :)

**Comment by t9md** [comment]
OK. fine. Will include next release.

**Comment by awilliams-atx** [comment]
How can I use this now? I see it in the command palette but am having trouble using it. I'm trying a keymap.cson but no luck, thanks!

```
'.editor':
  'shift-enter': 'vim-mode-plus:add-blank-line-below'
  'cmd-shift-enter': 'vim-mode-plus:add-blank-line-above'
```

**Comment by nwaywood** [comment]
I think you issue is that your selector isn't specific enough, try:

```
'atom-text-editor.vim-mode-plus.normal-mode':
  'shift-enter': 'vim-mode-plus:add-blank-line-below'
  'cmd-shift-enter': 'vim-mode-plus:add-blank-line-above'
```

If that doesn't work you can debug the issue by pressing `cmd - .` to activate the keybinding resolver thingy.
