### ISSUE TITLE
Multi-cursor + delete + insert mode undo bugs

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#57]
Repro: select more than one piece of text using multi-cursor (in normal mode), hit `d`, then cmd+z. It only undoes the last cursor's word removal.

Vim-mode-plus' `u` undo works fine.

**Comment by t9md** [comment]
I couldn't reproduce. What's the problem since you said "Vim-mode-plus' u undo works fine.".
You want to change behavior of  cmd-z?
Dirty workaround is cmd-z map to `vim-mode-plus:undo` but I know its not your point.

When you select text, delete text what is the vim-mode at each operation timing?

**Comment by chenglou** [comment]
Here's a gif (a bit slow for some reason): 
![untitled-2](https://cloud.githubusercontent.com/assets/1909539/11750419/3d9981ba-a001-11e5-94a7-40be3b6098d0.gif)

Keystrokes: `esc cmd+d cmd+d cmd+d s cmd+z`

Expected behavior is that it restores all three "abc"s

**Comment by t9md** [comment]
FIXED.

I checked if degradation from official vim-mode, but was not. Official vim-mode also have same issue.
The reason was Change operator's text mutation was done in one transaction when multi-cursor.
`s` is subclass of Change(`c`) so also had same issue.
