### ISSUE TITLE
Block cursor not showing in visual mode. Window only.

### ISSUE THREAD

**Issue by deshiknaves** [t9md/atom-vim-mode-plus#586]
Going into visual mode does not show the block cursor on Windows. I have all the same builds on my Mac and everything works as expected.

I have tried uninstalling atom entirely and removing the .atom folder. Then reinstalling Atom, Nuclide and vim-mode (versions below).

The theme is One Dark and so is the syntax.

When I install vim-mode-plus I get the message 0.66.1 is not the latest available for this package, but it's the latest compatible with your version of Atom. However when I look at the version that gets installed it's 0.72.0.

I've also tried restarting the machine/atom. Disabling re-enabling.

The only 2 community plugins I have installed are Nuclide and vim-mode-plus. All the functionality works as expected, just the block cursor never shows, has the same cursor in both visual and insert mode.

My custom keybindings are:

'atom-text-editor.vim-mode-plus:not(.normal-mode)':
  'j j': 'vim-mode-plus:activate-normal-mode'

'atom-text-editor[mini]':
  'j j': 'core:cancel'

It's either Windows related or something specific to my machine. Is there anything you can recommend I try?

- Atom version: 1.12.7
- vim-mode verion: 0.72.0
- Nuclide version: 0.188.0

**Comment by t9md** [comment]
Are you using atom-1.12 with vim-mode-plus 0.72.0?
Then that's is not supported combination.
You maybe using synching `.atom` or package folder across different machines and OSs?

Atom 0.72.0 should be installable from atom-1.13(currently in beta-release).
So if you use atom-1.12 and try to install vim-mode-plus from setting-view, latest installable version should be 0.66.1.

Could you uninstall vim-mode-plus then install it from setting-view with atom-1.12(stable-release) on windows?

**Comment by deshiknaves** [comment]
That's what I thought was fishy as well.

I used to sync my .atom. But I uninstalled atom and then removed .atom folder in my user account. However, whenever I uninstall and reinstall vim-mode-plus, it shows me the message in the settings page, but installs 0.72.0 anyway. Maybe there is something else cached somewhere that is causing this?

I haven't used the beta version on any of my machines.

**Comment by t9md** [comment]
OK, let me check if I can install 0.72 from stable-1.12.

Anyway you can install latest vmp for stable manually by `apm install vim-mode-plus@0.66.1`.

**Comment by deshiknaves** [comment]
Alright, I've got it to work. I uninstalled using the interface. Then installed using apm install vim-mode-plus. The apm installed the correct version 0.66.1.

Issue resolved. Thanks for your help.

**Comment by deshiknaves** [comment]
I didn't have to put the version number, from the command line, it did exactly what it should have.

**Comment by t9md** [comment]
So the reason is you used `apm install` from command-line?
I thought apm command bundled with atom-stable should work in same way in clicking install from setting-view, you saying it wasn't that right?

**Comment by deshiknaves** [comment]
Yep, I tried uninstalling and re-installing from the packages/install view in the app about 3 times. Each time I got the message about 0.66.1 but in the packages view it said 0.72. I checked the .atom folder and the package was getting removed.

The last time, I uninstalled it using the same method and an apm install vim-mode-plus and it installed the correct version.

I would have thought they would work in exactly the same way.

I've found the issue. If I click it too quickly before the message appear, it will install the newer version. If I wait for the message to show up, then it will install 0.66.1.

**Comment by t9md** [comment]
> The last time, I uninstalled it using the same method and an apm install vim-mode-plus and it installed the correct version.

The last time you use CLI or GUI to install vim-mode-plus, which?



> I've found the issue. If I click it too quickly before the message appear, it will install the newer version. If I wait for the message to show up, then it will install 0.66.1.

If it's really reproducable it's issue should be fixed in Atom-core or setting-view package. Every package developer would be confused by similar issue in future.
Thanks for narrow down it. I'm happy if you open issue to setting-view repo.

**Comment by deshiknaves** [comment]
Sorry, I should have specified. I uninstalled using the GUI then installed using CLI.

Yep, I can reproduce it every time now. I will open an issue with them. I don't know much about how packages for atom work. What would you call this version check mechanism?

**Comment by t9md** [comment]
Atom package's `package.json` has **engine** field, it allow installable atom engine(=version) with semver format.

https://github.com/t9md/atom-vim-mode-plus/blob/master/package.json#L10

This blog also explain limiting engine version for recent shadowDOM removal happened in `1.13-beta`
http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html

**Comment by deshiknaves** [comment]
I'm told this will be fixed in Atom 1.14.0.

**Comment by t9md** [comment]
OK, thanks for reporting.
