### ISSUE TITLE
move cursor up/down at a specific number

### ISSUE THREAD

**Issue by wangsongiam** [t9md/atom-vim-mode-plus#588]
can I bind `J` to move the cursor 5 lines down and `K` to move 5 lines up(!insert mode)? 
like this answer in `vim-mode` https://github.com/atom/vim-mode/issues/600
I've read the [ExtendVimModePlusInInitFile](https://github.com/t9md/atom-vim-mode-plus/wiki/ExtendVimModePlusInInitFile) but guess I was too dumb to get this done😿, please help

**Comment by t9md** [comment]
First try `[`, `]` motion, it stops **edge**. 
I think it's cover your use case for moving up/down more rapidly.
Don't ask me what the **edge** is, just try.

Also for your specific request to move 5 lines up/down motion.

Added example to wiki.
See this.

https://github.com/t9md/atom-vim-mode-plus/wiki/ExtendVimModePlusInInitFile#basic-5-lines-moveupmovedown-motion
