### ISSUE TITLE
Tab remapping is VERY breaking

### ISSUE THREAD

**Issue by averrin** [t9md/atom-vim-mode-plus#597]
> Keymap, Breaking: Mapped in all mode except insert-mode, opinionated decision.

By default tab uses for indent code, but now its broken.

**Comment by t9md** [comment]
You use tab in normal-mode? Even pure-Vim have no mapping for tab. And for indent `>` is available.

But I understand your point. But want you to evaluate after trying to feature for a while.

**Comment by averrin** [comment]
I think, many people use tab in normal and visual mode, its universal shortcut.

**Comment by t9md** [comment]
For what command?

**Comment by averrin** [comment]
editor:indent. 
Imho tab remapping - bad idea, for hardcore vimmers (i always use tab in vim, learned about > from you), you can add setting.

**Comment by t9md** [comment]
OK i got your imput but will see other feedbak.
For now you can override tab in your init.coffee.
Overriding keymap in Atom now far easier than before since its prioritize users custom keymap than package's.

**Comment by averrin** [comment]
@t9md i will use ">", but i read changelog every release and know why its broken. But other people...

**Comment by t9md** [comment]
Will make it fail safe when no occurrence-marker exists then dispatch to editor:indent so that user who dont use occurrence not being interfered by this remapping.

**Comment by t9md** [comment]
Released v0.73.1.
For user who don't need this fallback, I introduce new config param `fallbackTabAndShiftTabInNormalMode`(default `true`).

**Comment by t9md** [comment]
Keymap things is always difficult to go opinionated, aggressive.
I'm very all-by-keyboard programmer so I understand for people who hate being broken their daily-using keymap by 3rd party package.

So I'm still keeping many of vmp feature default-keymap-undefined. 😢

**Comment by averrin** [comment]
> So I'm still keeping many of vmp feature default-keymap-undefined.
Thats reason, why i read change log. And thanks for it!
