### ISSUE TITLE
Add migration guide

### ISSUE THREAD

**Issue by averrin** [t9md/atom-vim-mode-plus#6]
I want to try your plugin, but i have some overwrites in keymap and dont want read docs for converting it. If you add some list of commands and classes like "old -> new", more people will use it

**Comment by t9md** [comment]
I don't have time to articulate this kind of documentation. 
If use have Vim experience, using vim-mode-plus should not be difficult, if user is former vim-mode user they can migrate their custom setting by cheking vim-mode-plus's keymap cson file as they did in vim-mode.

**Comment by t9md** [comment]
For vim-mode-plus original feature I feel I should provide some tutorial documentation.
I will put this kind of doc on wiki section soon.
