### ISSUE TITLE
how to add some setting from ./spec folder

### ISSUE THREAD

**Issue by wangsongiam** [t9md/atom-vim-mode-plus#604]
I tried to use some features like `vim-mode-plus:add-blank-line-below` in [here](https://github.com/t9md/atom-vim-mode-plus/blob/ce0a673e7d97fd61496e0a53d7c19f0fe85a095d/spec/operator-general-spec.coffee#L1326-L1329), but those are not working by just adding to `keymap.cson`. So how can I add those setting again? like these two below:
```
'atom-text-editor.vim-mode-plus.normal-mode':
  'enter': 'vim-mode-plus:add-blank-line-below'
  'shift-enter': 'vim-mode-plus:add-blank-line-above'
```

**Comment by t9md** [comment]
Read issue template, and read it's linked documentation. You've seen when you write this question right?
The short answer is put it in your `keymap.cson`.

**Comment by wangsongiam** [comment]
@t9md yes, I've read those, I've tried to put those in my `keymap.cson`, like this,
<img width="585" alt="screen shot 2016-12-14 at 3 24 08 pm" src="https://cloud.githubusercontent.com/assets/19645990/21199405/6592a628-c211-11e6-962b-c6eeb5b67001.png">
 but it's just not working, and I couldn't use them in `Command Palette`

**Comment by t9md** [comment]
Strange.
If you read and this is keymap issue, so how was the result of keybinding-resolver's observation?
Which key is mapped when you typed `:`?

**Comment by t9md** [comment]
You use macOS, windows, atom version?
All information need to investigate is in issue template so that i don't have to ask you like this:)

**Comment by wangsongiam** [comment]
I'm sorry, i am using macOS `10.12` and other info is here:
### Check list
- Atom version info(`atom --version`)
```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
- vim-mode-plus version.
	`0.66.1`
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
`yes`

***
also, these are what happened after I hit `:` ,`enter` ,`shift-enter` in keybinding-resolver 
<img width="1440" alt="screen shot 2016-12-14 at 7 21 21 pm" src="https://cloud.githubusercontent.com/assets/19645990/21206901/d1ea7ece-c232-11e6-8528-42bb12e4aace.png">
<img width="1440" alt="screen shot 2016-12-14 at 7 21 35 pm" src="https://cloud.githubusercontent.com/assets/19645990/21206906/d4cc6332-c232-11e6-950a-104efe3ff557.png">
<img width="1440" alt="screen shot 2016-12-14 at 7 21 48 pm" src="https://cloud.githubusercontent.com/assets/19645990/21206908/d73b0916-c232-11e6-9c62-a049c7b74ef0.png">
so when I hit `:`, it showed the Command Palette, but when I was hitting `enter`or`shift-enter`, nothing happened

**Comment by t9md** [comment]
- The latest vim-mode-plus contains these command
- But latest vim-mode-plus is available for [Atom-beta](https://atom.io/beta)(1.13.0-beta8 now).
- You use atom-stable 1.12.x so these command is not available yet. Need to wait 1.13 become new stable.

**Comment by wangsongiam** [comment]
Thanks a lot! And please keep this great work continued.
