### ISSUE TITLE
Support stable atom versions

### ISSUE THREAD

**Issue by absynce** [t9md/atom-vim-mode-plus#606]
I can't install the latest vim-mode-plus (>0.66.1) with the latest stable atom version (1.12.7).
![image](https://cloud.githubusercontent.com/assets/289969/21199912/1033d63a-c20b-11e6-8b37-4fc1a9cbdf08.png)

This issue was introduced in v0.67.0: https://github.com/t9md/atom-vim-mode-plus/commit/97417897986fd716e68f6f7010ce3069a0c2f491#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R10.

# Check list

- Atom version info(`atom --version`)
```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

- vim-mode-plus version.
Any > 0.66.1

- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
Yes.

- Tried to latest stable atom version with latest vim-mode-plus. 
Yes, that's the issue. I can't install the latest vim-mode-plus with the latest stable atom version.

- Restarting Atom itself solve your problem?
No.

- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
No.

**Comment by t9md** [comment]
Current beta become come to stable channel soon.
I don't want to maintain for both. 
So just wait.
