### ISSUE TITLE
Can't navigate to last character / shift+a doesn't go insert after last character

### ISSUE THREAD

**Issue by dvcrn** [t9md/atom-vim-mode-plus#61]
Not sure why but when vim-mode-plus is activated, it is impossible for me to navigate to the last character. Even with arrow keys. 

When I hit `shift-a`, the cursor jumps to the 2nd last character and goes into insert mode. When deactivating vim-mode-plus, all is back to normal. 

1. "hello | world"
2. Shift-a
3. "hello worl | d"

```
  "vim-mode":
    useClipboardAsDefaultRegister: true
    useSmartcaseForSearch: true
  "vim-mode-plus":
    useSmartcaseForSearch: true
    incrementalSearch: true
    flashOnUndoRedo: true
    useClipboardAsDefaultRegister: true
    wrapLeftRightMotion: true
    showHoverOnOperate: true
```

**Comment by dvcrn** [comment]
Whoops, should have read that I am supposed to deactivate vim-mode beforehand.

**Comment by t9md** [comment]
Yes absolutely!! :smile:

**Comment by dvcrn** [comment]
@t9md so I have a little question. Are you regularly merging upstream changes back into vim-mode-plus or will this be a independent fork? I love some of the features but the collision with vim-mode makes me a bit worried. 

vim-mode seems to have a lot more development muscle behind it, thats why the question.

**Comment by t9md** [comment]
Originally forked from vim-mode.
Timing is 2013.8.1.
After that I occasionally check issue reported to upstream vim-mode.
But now code is completely different ( vim-mode-plus 1000 commit ahead of vim-mode)
Along that intensive commit I fixed many of bugs or minor inconsistent behavior and added some bugs.
So issue reported to vim-mode is not necessarily applied to vim-mode-plus.
So to say simply its not compatible, independent project now.
If vim-mode invite active developer like me its likely to surpass vim-mode-plus easily in future, in that case I will recommend to use vim-mode.

**Comment by dvcrn** [comment]
Interesting, okay. 
I am currently working on a atom configuration system called [proton](https://github.com/dvcrn/proton). A core part of that system is vim. This means that every user of proton will use either vim-mode or vim-mode-plus. 

Would you recommend using vim-mode-plus for the 'normal' user, or normal vim mode?

**Comment by t9md** [comment]
Not sure, my-vim-mode provides more vim like experience for beginner vim-user since its support cursor visibility in visual-mode and visual-block like etc...
But my vim-mode-plus is too aggressive to adding new feature like bundling surround, text-object-function etc... for that part advanced Vim user not agree with my approach.
I myself don't aiming to mimic all of pure Vim feature.
Please evaluate by yourself which is better.
