### ISSUE TITLE
how can I temporarily disable vim-mode-plus?

### ISSUE THREAD

**Issue by hdarwin** [t9md/atom-vim-mode-plus#618]
I don't want uninstall vim mode plus. but I need to disable vim-mode-plus temporarily. how can i do that?

**Comment by t9md** [comment]
I don't know.
Manually disable from settings-view by mouse clicking `Disable` button of vmp.
Or try `disable package` link in atom.io.

https://atom.io/packages/search?q=disable+package

**Comment by otundra** [comment]
This may be a good feature

**Comment by t9md** [comment]
Just starting `insert-mode` doesn't do what you want?

**Comment by ashutoshmjain** [comment]
Same question  - I want to quickly disable vim mode plus to be able to use superscript or subscript (assuming vim mode plus doesn't support digraphs - please correct me if I am wrong ). ..is there a way ?
