### ISSUE TITLE
maximize-pane doesn't maximize the horizontal split panes to full area

### ISSUE THREAD

**Issue by wangsongiam** [t9md/atom-vim-mode-plus#623]
# Check list

- Atom version info(`atom --version`) `1.13.0-beta8` && `1.12.7`
- vim-mode-plus version. 0.75.0
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
- Tried to latest stable atom version with latest vim-mode-plus. 
- Restarting Atom itself solve your problem?
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-
plus/wiki/IssueReport#some-keybinding-not-working).
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

![2016-12-20 02 20 24](https://cloud.githubusercontent.com/assets/19645990/21341594/549ff9b2-c65b-11e6-8820-1811ab22c9af.gif)

**Comment by t9md** [comment]
I could reproduce it, thanks for reporting will check.

**Comment by wangsongiam** [comment]
thank you!
