### ISSUE TITLE
shift+number is broken for fr_FR layout

### ISSUE THREAD

**Issue by romseguy** [t9md/atom-vim-mode-plus#63]
Hi, thanks for this awesome plugin.

I'm using [atom-keyboard-localization](https://github.com/andischerer/atom-keyboard-localization) with `fr_FR` layout on Linux Mint 17 (Ubuntu 14.04 fork):

Any combination involving numbers doesn't work at all for me, e.g:

`d3j` to delete 3 lines after current line
`54G` to go to line 54

Since I don't have a numpad on my laptop keyboard, I have only tested with `shift+number`.

**Comment by romseguy** [comment]
I switched back to `vim-mode` and try if it works and got same issue as https://github.com/andischerer/atom-keyboard-localization/issues/79

**Comment by t9md** [comment]
So you have keyboard which need `shift-` combination to enter any number.
What does keybinding-resolver says when you enter number with shift combination?
If you configure keymap in your `keymap.cson` from what 'keybinding resolver resolved' to `vim-mode-plus:set-count` can be solution?

https://github.com/t9md/atom-vim-mode-plus/blob/master/keymaps/vim-mode-plus.cson#L183-L191

**Comment by romseguy** [comment]
It resolves `to shift-X` so I added this to `keymap.cson`:

```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'shift-1': 'vim-mode-plus:set-count'
  'shift-2': 'vim-mode-plus:set-count'
  'shift-3': 'vim-mode-plus:set-count'
  'shift-4': 'vim-mode-plus:set-count'
  'shift-5': 'vim-mode-plus:set-count'
  'shift-6': 'vim-mode-plus:set-count'
  'shift-7': 'vim-mode-plus:set-count'
  'shift-8': 'vim-mode-plus:set-count'
  'shift-9': 'vim-mode-plus:set-count'
```

Now it triggers `TypeError: Cannot redefine property: keyIdentifier` when I'm in normal mode and pressing `shift-number`. In insert mode, I get the numbers just fine.

Maybe it should resolve to `shift-&` instead of `shift-1` because `1` is the result of "shifting" the `&` key.

**Comment by t9md** [comment]
Could you try following workaround solve your problem?

1. set following custom command in your `init.coffee`.

```coffeescript
{buildKeydownEvent} = atom.keymaps.constructor
keydown = (num) ->
  editor = atom.workspace.getActiveTextEditor()
  editorElement = atom.views.getView(editor)
  event = buildKeydownEvent(num)
  editorElement.dispatchEvent(event)

atom.commands.add 'atom-text-editor.vim-mode-plus:not(.insert-mode)',
  'user:0': -> keydown '0'
  'user:1': -> keydown '1'
  'user:2': -> keydown '2'
  'user:3': -> keydown '3'
  'user:4': -> keydown '4'
  'user:5': -> keydown '5'
  'user:6': -> keydown '6'
  'user:7': -> keydown '7'
  'user:8': -> keydown '8'
  'user:9': -> keydown '9'
```

2. then define keymap in your `keymap.cson`

```coffeescript
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'shift-0': 'user:0'
  'shift-1': 'user:1'
  'shift-2': 'user:2'
  'shift-3': 'user:3'
  'shift-4': 'user:4'
  'shift-5': 'user:5'
  'shift-6': 'user:6'
  'shift-7': 'user:7'
  'shift-8': 'user:8'
  'shift-9': 'user:9'
```

**Comment by romseguy** [comment]
I get the same error.

**Comment by t9md** [comment]
How about mapping normal key like `a` to `user:X`
```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'a': 'user:2'
```

In my environment I can use `a` as `2`(work as if invoke `vim-mode-plus:set-count` via `2` key).
Check  `aj` work as `2j`.

If it worked, then check you can map `shift-num` key to more common atom native command like `core:save`, `core:close`.
Does it work?

How about disabling keyboard-localization package the error would change?

**Comment by romseguy** [comment]
> 'a': 'user:2'TypeError: Cannot redefine property: keyCode

**Comment by t9md** [comment]
Ok, I much clearer issue than before.
I think I can provide workaround command to put on your init.coffee. But dont want to include as vim-mode-plus for now. I'll put later.

For behavior you did tried both phenomena should also be notified to keyboard-localization package to improve to provide more limitless, transparent key translation.

**Comment by t9md** [comment]
How about this workaround?
Hope this solves!!

```coffeescript
# Workacound for fr_FR keyboard layout with keyboard-localization package.
# Issue #63
#=================================================
# init.coffee
# -------------------------
atom.packages.onDidActivatePackage (pack) ->
  return unless pack.name is 'vim-mode-plus'
  {getEditorState} = pack.mainModule.provideVimModePlus()
  scope = 'atom-text-editor.vim-mode-plus:not(.insert-mode)'
  prefix = 'vim-mode-plus-user:set-count'
  for num in [0..9]
    do (num) ->
      atom.commands.add scope, "#{prefix}-#{num}", ->
        getEditorState(atom.workspace.getActiveTextEditor()).count.set(num)

# keymap.cson
# -------------------------
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'shift-0': 'vim-mode-plus:move-to-beginning-of-line'
  'shift-1': 'vim-mode-plus-user:set-count-1'
  'shift-2': 'vim-mode-plus-user:set-count-2'
  'shift-3': 'vim-mode-plus-user:set-count-3'
  'shift-4': 'vim-mode-plus-user:set-count-4'
  'shift-5': 'vim-mode-plus-user:set-count-5'
  'shift-6': 'vim-mode-plus-user:set-count-6'
  'shift-7': 'vim-mode-plus-user:set-count-7'
  'shift-8': 'vim-mode-plus-user:set-count-8'
  'shift-9': 'vim-mode-plus-user:set-count-9'

'atom-text-editor.vim-mode-plus.with-count:not(.insert-mode)':
  'shift-0': 'vim-mode-plus-user:set-count-0'
```

**Comment by romseguy** [comment]
It works! Thanks for your awesome support.

> phenomena should also be notified to keyboard-localization package to improve to provide more limitless, transparent key translation.

I'm not sure how to add more useful info than what's already over here https://github.com/andischerer/atom-keyboard-localization/issues/79

**Comment by t9md** [comment]
Example command and keymap and result(work when disabled, work only when enabled) will give author of keyboard-localization hint.
I can summarize point, but I don't want to for now...

**Comment by andischerer** [comment]
Hey guys,
I fixed the `shift+number` keybindings in the latest version(1.4.13) of atom-keyboard-localization.
There is also support for vim-mode-plus builtin.

The workaround from @t9md shouldn't be neccessary anymore.

**Comment by t9md** [comment]
Great work! Thanks for sharing!

**Comment by t9md** [comment]
@romseguy, @andischerer 
From next vim-mode-plus release v0.12.0, vim-mode-plus no longer extract original keystroke from event. Removed this dynamic extraction.

Before v0.12.0 `set-count` command mapped from multiple number key from 0 to 9. So this demand extracting original keystroke from event argument and sometime cause trouble in special keyboard and keycode translation package.

So workaround I provided this issue is no longer work.
Please remove workaround setting when v0.12.0 is released and installed.

Each set-count command have distinct command-name(1-to-1), so I believe user can easily workaround by modifying their keymap(If they have any issue), and I think keyboard-localization package don't need special care for vim-mode-plus.

```
'0': 'vim-mode-plus:set-count-0'
'1': 'vim-mode-plus:set-count-1'
'2': 'vim-mode-plus:set-count-2'
'3': 'vim-mode-plus:set-count-3'
'4': 'vim-mode-plus:set-count-4'
'5': 'vim-mode-plus:set-count-5'
'6': 'vim-mode-plus:set-count-6'
'7': 'vim-mode-plus:set-count-7'
'8': 'vim-mode-plus:set-count-8'
'9': 'vim-mode-plus:set-count-9'
```

**Comment by romseguy** [comment]
Thank you @andischerer and @t9md I removed the workaround, everything works fine :+1:

**Comment by t9md** [comment]
@romseguy I want to know if works properly AFTER you install vim-mode-plus v0.12.0(which I will release in a few days).
Please put result(work fine or bad) that information would be great help for me.

**Comment by romseguy** [comment]
Just updated to 0.12.0 and it doesn't work anymore. `keyboard-localization` is 1.4.13.

**Comment by t9md** [comment]
So you mean you can not se count by shift-N?

**Comment by romseguy** [comment]
Exactly.

**Comment by t9md** [comment]
It strange.
make me confirm.
What the keymap resolver says?
Now vim-mode-plus's set-count-N is provided for each number nothing special when compared to other atom commands.

When you want to input some number do you need shitt-num? Or simply num without shift?
What the purpose if keyboard localization package.

**Comment by romseguy** [comment]
I'm sorry, now it's working. I didn't make any change so it must be that restarting Atom fixed the problem.

**Comment by t9md** [comment]
OK, thanks.

**Comment by t9md** [comment]
Note in futre reference.

From atom-vim-mode-plus v0.12.0, set-count feature have distinct commands.
When some special keyboard need `shift-` combination to input normal number like `0`.
User have to set following keymap in your `keymap.cson`.

```coffeescript
# keymap.cson
# -------------------------
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'shift-0': 'vim-mode-plus:move-to-beginning-of-line'
  'shift-1': 'vim-mode-plus-user:set-count-1'
  'shift-2': 'vim-mode-plus-user:set-count-2'
  'shift-3': 'vim-mode-plus-user:set-count-3'
  'shift-4': 'vim-mode-plus-user:set-count-4'
  'shift-5': 'vim-mode-plus-user:set-count-5'
  'shift-6': 'vim-mode-plus-user:set-count-6'
  'shift-7': 'vim-mode-plus-user:set-count-7'
  'shift-8': 'vim-mode-plus-user:set-count-8'
  'shift-9': 'vim-mode-plus-user:set-count-9'

'atom-text-editor.vim-mode-plus.with-count:not(.insert-mode)':
  'shift-0': 'vim-mode-plus-user:set-count-0'
```

But keyboard-localization package doing special treatment for `shift-` combination key.
So without above keymap setting, `shift-N` might work, but this special treatment is essentially not required.
