### ISSUE TITLE
vim-mode-plus's package load time is too BIG

### ISSUE THREAD

**Issue by llpamies** [t9md/atom-vim-mode-plus#645]
I noticed that vim-mode-plus dominates my atom loading times (atom 1.13 beta10):
![screenshot from 2017-01-05 13-01-49](https://cloud.githubusercontent.com/assets/452871/21697450/49ae7e04-d347-11e6-90e8-6c02001cdd43.png)

Is that a known problem? Is there any way to improve it?

**Comment by t9md** [comment]
Yes I know. But my current stance is...
- Please help me to reduce load time or
- Please accept this slow load time as long as you'd be kore efficient by vmp

Vmp is collection of utility command, It's equivalent to install 100 separate packages.
I want to improve load time but priority is not high.
My focus now is still stabilize, cleanup, fix broken part.
Performance tuning comes after that(but I have no idea what I can do now)

**Comment by t9md** [comment]
This is mine, on MacBook Pro Late 2016. 
BEFORE I upgraded my Mac(was MacBook Air 2011), I remember it took over 1sec.

```
$ atom-beta --version
Atom    : 1.13.0-beta10
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

<img width="577" alt="about_this_mac" src="https://cloud.githubusercontent.com/assets/155205/21748671/9ef39510-d5cd-11e6-8333-ae6d55432f72.png">


<img width="689" alt="timecop_ ___github_atom-vim-mode-plus" src="https://cloud.githubusercontent.com/assets/155205/21748666/7a29995a-d5cd-11e6-84ff-af43f66df61c.png">

**Comment by t9md** [comment]
![timecop_ ___github_atom-vim-mode-plus](https://user-images.githubusercontent.com/155205/32886100-f57c96e0-cb02-11e7-94c2-7f1e00509396.jpg)

This is vmp 1.20.0 + Atom-v1.23.0-beta1.

Most of works to improve startup time is done in https://github.com/t9md/atom-vim-mode-plus/pull/758
