### ISSUE TITLE
Spec needed

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#65]
There are lots of feature lacking spec, but I put here for feature should be prioritized(editing feature) among those.
- SplitString
- JoinByInput and its cousin
- LatestChange text-object
- setCursorToStartOfChangeOnUndoRedo setting
- stayOnOperator setting

**Comment by Byron** [comment]
In case it suits you, I recommend using the 'help-wanted' label, as it is picked up by services trying to broker developers your way, in turn attracting PRs. This works the better the smaller the tasks are.

**Comment by t9md** [comment]
Mos of it has specs already.
