### ISSUE TITLE
"Replache" brokes font-size

### ISSUE THREAD

**Issue by Aleksandern** [t9md/atom-vim-mode-plus#651]
Hello

I press 'r' button and vim-mode-plus changes font-size of editor
Look at GIF please:
![111](https://cloud.githubusercontent.com/assets/5274465/21795202/059abd28-d733-11e6-8250-5a54a618b95f.gif)

How can I fix it?

I have change style.less of course:
> .editor {
  font-size: 14px;
}

It's not happening if I delete "font-size: 14px;" from "style.less" file

- Atom version info 1.12.9
- vim-mode-plus version  0.66.1
- You disabled vim-mode? yes

**Comment by t9md** [comment]
Why you don't set change fontsize from setting view?

**Comment by Aleksandern** [comment]
There is no any fontsize option in setting view.

**Comment by Aleksandern** [comment]
oh. sorry. I found it. it's ok now
