### ISSUE TITLE
Undo not working as expected

### ISSUE THREAD

**Issue by five9media** [t9md/atom-vim-mode-plus#658]
Undo has never worked as expected with vim-mode or vim-mode-plus. Currently using Atom 1.13.0 with vim-mode-plus 0.80.0. After inserting multiple lines of text, if you go to command mode and issue an undo (using u) it will undo all changes across multiple lines that were made during that insert "session". This is **not** how Vim handles undo - as an example:

1. Start new document/buffer
2. Enter insert mode
3. Type the following (each on a new line):
Line 1
Line 2
Line 3
4. Enter command mode
5. Press 'u' for undo

In Atom using vim-mode-plus **all three lines are undone**. The _correct behavior_ as happens in Vim would be for Line 3 to be removed, hitting undo again would remove Line 2, hitting undo a third time would remove Line 1.

I have also tested this functionality using Visual Studio Code with the amVim plugin: https://marketplace.visualstudio.com/items?itemName=auiworks.amvim and this particular Vim plugin mimics the correct behavior.

**Comment by t9md** [comment]
You really checked with pure Vim?
Pure(or regular) Vim undo the **all** text inserted at single insert session.
Thus "**all three lines are undone**" you are saying is expected behavior.

What version of pure Vim you see the behavior with **separate undo with single insert session**?
P.S. I'm curious why you use amVim over VSCodeVim plugin for VSCode?

If you what different undo handling, try `groupChangesWhenLeavingInsertMode` setting.
Check it from vim-mode-plus setting view, but as far as I understand this is vim-mode-plus's **original enhancement** not provided in pure-Vim.

If you seed same granular undo behavior in different Vim emulator plugin, this is maybe just directly using `undo` feature.

**Comment by five9media** [comment]
Thank you for the quick reply! I was just getting ready to add a new comment myself. After submitting the issue I decided to double check the default behavior using a fresh .vimrc file and removed all of my plugins. Of course, _you are correct_ - the default behavior is to **undo all three lines**. I'll have to go through my .vimrc and plugins to determine how I have this behavior set.

I don't typically use VS Code and just recently installed it to test performance with larger files and decided to try out a couple of Vim plugins. I did install VSCodeVim first, but found the same (now I know default) undo behavior so I decided to install the second entry on the list (sorted by number of installs) which was amVim and strange enough its undo worked as I expected.

Unchecking `Group Changes When Leaving Insert Mode` provided the undo behavior that I prefer, thank you!

**Comment by five9media** [comment]
After reviewing my .vimrc file, I found that the following line was causing the undo behavior:

`inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"`

The comment above it points to the following page: http://vim.wikia.com/wiki/Make_Vim_completion_popup_menu_work_just_like_in_an_IDE

Doing something like `inoremap <Space> <Space><C-g>u` will cause undo to _break_ at every space.

Is there a reason you decided to reopen this issue after I closed it? It's clearly working as designed and the **Group Changes When Leaving Insert** seems to work fairly well.

**Comment by t9md** [comment]
Oh I didn't noticed I **accidentally reopened**.
Will close now.
Thanks for the report, for the `<C-g>u`, it's special command in `insert-mode` which manually **break undo sequence**(you can see it in vimhelp).
What I can take it is new enhancement TODO to support `<C-g>u` and `<C-g>U` in vmp.
But priority is not high.
