### ISSUE TITLE
No keystrokes are handled by vim-mode-plus

### ISSUE THREAD

**Issue by phorust** [t9md/atom-vim-mode-plus#664]
Noticed that I can't move, or enter insert mode (none of `hjklAaIio` work) on my files recently (probably started having this problem a couple days ago). I'm stuck, immobile, in normal mode. Keybind resolver doesn't show `vim-mode-plus` grabbing anything. My keymap is at the bottom, if it's helpful.

I've switched to reinstalling `vim-mode` and disabling `vim-mode-plus` for the time being. Any ideas what's up?

Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
vim-mode-plus version: 0.80.0

```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'ctrl-h'  : 'window:focus-pane-on-left'
  'ctrl-j'  : 'window:focus-pane-below'
  'ctrl-k'  : 'window:focus-pane-above'
  'ctrl-l'  : 'window:focus-pane-on-right'
  'ctrl-H'  : 'window:move-active-item-to-pane-on-left'
  'ctrl-J'  : 'window:move-active-item-to-pane-below'
  'ctrl-K'  : 'window:move-active-item-to-pane-above'
  'ctrl-L'  : 'window:move-active-item-to-pane-on-right'
  # tab movement
  'ctrl-n'  : 'pane:show-next-item'
  'ctrl-b'  : 'pane:show-previous-item'
  # i got used to tmux splits > vim splits
  'ctrl-a v': 'pane:split-right-and-copy-active-item'
  'ctrl-a V': 'pane:split-right-and-move-active-item'
  'ctrl-a s': 'pane:split-down'
  'ctrl-a x': 'pane:close'
  # like my vimrc
  ';'       : 'vim-mode-plus-ex-mode:open'
  '\\ a'    : 'atom-alignment:alignMultiple'
  '\\ c'    : 'editor:toggle-line-comments'
  'ctrl-i'  : 'cursor-history:next-within-editor'
  'ctrl-o'  : 'cursor-history:prev-within-editor'

# like YCM. holy fuck atom is amazing DEVELOPER SUPPORT EVERYBODY
'atom-text-editor:not(mini).autocomplete-active':
  'enter'    : 'autocomplete-plus:confirm'
  'tab'      : 'core:move-down'
  'shift-tab': 'core:move-up'

'atom-workspace':
  'ctrl-shift-p': 'core:move-up'
  'ctrl-p': 'core:move-down'
```

**Comment by t9md** [comment]
Os ver, restar atom, keymap ovserve by cmd-., disable other package to narrow down cause(enable vim-mode-plus only works?).

**Comment by t9md** [comment]
I need ALL info to investigate.

**Comment by phorust** [comment]
OS Ver: OS X 10.12.2
restarted atom, doesn't help
observed keymap for cmd-., vim-mode-plus is not catching anything.
disabled all other plugins, still failing.

**Comment by t9md** [comment]
OK. Understood. Can you invoke vmp command from command palette?(probably not).
What you can try the lest is  try with clean installed Atom.Like download atom and execute it from that place directly and see it's work.
Other thing to try is try older version `apm install vim-mode-plus@0.7X.X`.
But vim-mode-plus don't include significant change recently, what is most aignificant change is upgrading Atom(by auto update).. possibly something broken such as partially failed the upgrade process?

**Comment by phorust** [comment]
I poked around after updating and noticing some weird behavior and found in my atom config that `packages-with-keymaps-disabled` was set to `['vim-mode-plus']`. I have no idea how that got there.

thanks for looking into this @t9md, will close
