### ISSUE TITLE
Support for Relative/Absolute Line Number

### ISSUE THREAD

**Issue by themccallister** [t9md/atom-vim-mode-plus#666]
This is not a bug, merely a question/suggestion. 

It would be amazing if this package could support relative/absolute line numbers. 

See this post on SO for more information:
http://stackoverflow.com/questions/8324349/display-relative-and-absolute-line-numbers-simultaneously-in-vim

**Comment by themccallister** [comment]
Oh man, the worst possible number for an issue - awesome... LOL

**Comment by ithil** [comment]
Why don't you just use [relative-numbers](https://github.com/justmoon/relative-numbers)? If you put the following in your `config.cson` it will show both absolute and relative line numbers side by side. :)
```
  "relative-numbers":
    showAbsoluteNumbers: true
```

**Comment by themccallister** [comment]
Thanks, closing this out!
