### ISSUE TITLE
Visual mode selection and last character

### ISSUE THREAD

**Issue by naquad** [t9md/atom-vim-mode-plus#667]
# Check list

- Atom version info(`atom --version`)
```
Atom    : 1.13.0
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0
```

- vim-mode-plus version
```
0.82.0
```

- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
**Yes**

In visual selection mode select a line and then select a line above (press `k` or up arrow). You will always have last character of previous line selected: ![actual](http://i.imgur.com/bptdQlJ.png)

In VIM and even plain Atom selection you can select just EOL: ![expected](http://i.imgur.com/0H4hpk1.png)

Not a high priority bug, but a very annoying subtlety breaking my workflow :(

**Comment by t9md** [comment]
Yes I know but I gave up to support this compativle behavior.
In Atom it was difficult to implement in consistent manner.

Will keep open in case I motivated again for this compativility.

**Comment by naquad** [comment]
Could you please provide some hints on where can I look into the issue? Can't say I'll definitely fix it, but maybe I'll get to some decision good enough to be used at least until the problem will get more your attention.

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/blob/master/lib/motion.coffee#L131-L145

This is one of very **sensitive**, **important** part of vmp, if you change these code, you can fix. But you break something, it affect all other part. I don't think I can accept simple PR for this part.

**Comment by t9md** [comment]
![vc-can-select-new-line](https://cloud.githubusercontent.com/assets/155205/23988146/518d09dc-0a70-11e7-8695-8e9b9dc5bb98.gif)


Now I'm working hard! I want to fix this.
This is one of heaviest change in vim-mode-plus's history, but will do!! 👍

**Comment by naquad** [comment]
This is awezome! :tada: You're wizard! :star2: Thank you very much :)

**Comment by hnguyen94** [comment]
👍
