### ISSUE TITLE
jj shortcut. How to implement this? 

### ISSUE THREAD

**Issue by kingluddite** [t9md/atom-vim-mode-plus#669]
I want to type `j` + `j` to enter normal mode. It worked on vim-mode but does not work on vim-mode-plus

[I used this link](https://github.com/atom/vim-mode/issues/334#issuecomment-85603175) and changed it from `vim-mode` to `vim-mode-plus` but it did not work

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#escape-from-insert-mode-by-typing-jk-quickly

**Comment by kingluddite** [comment]
Thanks t9md! Worked like a charm.
