### ISSUE TITLE
[unexpected behavior] TextObject operations are sensitive to keystroke interval.

### ISSUE THREAD

**Issue by hytor-yang** [t9md/atom-vim-mode-plus#670]
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

vim-mode-plus 0.82.0
vim-mode disabled.
Consistently reproducible after restart.

TextObject operation, such as `v` `i` `w`, behaves inconsistently with different keystroke intervals. A case is, with 2s+ interval between `i` stroke and `w` stroke it behaves like `v` `w`.

It appeared (and interrupted the flow) more frequently with 'skilled' key combinations such as `v` `i` `{`. 
Typing quickly to workaround, but better to figure out as it may confuse users.

**Comment by t9md** [comment]
I can't provide direct-fix for this issue in current design of vim-mode-plus.
I know how to fix and approach, and the side-effect it will introduce it.

This is related to `partialMatchTimeout` of atom's keymap system.

You can try to make it very long by set this from chrome dev-console or paste it in your `init.coffee`.

`
# 10 sec wait before give up the match
atom.keymaps.partialMatchTimeout =10000;
`

**Comment by hytor-yang** [comment]
Tried and exactly as you mentioned. At least those suffered get a way of tuning now.
Thx.
