### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reset' of undefined

### ISSUE THREAD

**Issue by dcalhoun** [t9md/atom-vim-mode-plus#674]
Steps to reproduce:

1. Open a file
1. Open `vim-mode-plus:search` (<kbd>/</kbd>)
1. Search for a string that is found in the file
1. Close the file before the `1/#` indicator dismisses

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.82.1

### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of undefined

```
At /Users/davidcalhoun/.atom/packages/vim-mode-plus/lib/search-model.coffee:58

TypeError: Cannot read property 'reset' of undefined
    at SearchModel.module.exports.SearchModel.resetHover (/packages/vim-mode-plus/lib/search-model.coffee:58:33)
```

### Commands

```
     -0:12.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:08.0 nerd-treeview:toggle (input.hidden-input)
     -0:07.2.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:05.7.0 core:confirm (input.hidden-input)
     -0:04.9.0 vim-mode-plus:repeat-search (input.hidden-input)
     -0:04.4.0 vim-mode-plus:search (input.hidden-input)
     -0:03.5.0 core:confirm (input.hidden-input)
  4x -0:03.1.0 vim-mode-plus:repeat-search (input.hidden-input)
     -0:01.8.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
.bin undefined 
atom-wrap-in-tag 0.6.0 
csscomb 0.3.1 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
ex-mode 0.13.1 
file-icons 2.0.15 
gist-it 0.9.2 
highlight-line 0.12.0 
language-diff 0.7.0 
language-generic-config 1.3.0 
language-liquid 0.5.1 
language-postcss 1.3.0 
linter 1.11.23 
linter-coffeelint 1.2.1 
linter-js-standard 3.8.1 
linter-rubocop 0.5.3 
linter-stylelint 3.8.0 
nerd-treeview 0.4.3 
one-dark-vivid-syntax 1.7.1 
react 0.16.2 
sort-lines 0.14.0 
standardjs-snippets 2.5.0 
tabs-to-spaces 1.0.3 
vim-mode-plus 0.82.1 
vim-mode-plus-ex-mode 0.8.1 
vim-mode-plus-jasmine-increase-focus 0.2.3 
Zen 0.16.4 
```

**Comment by t9md** [comment]
OK, could repro. was difficult..
You too can't repro 100% every tryout right?
If you have easy way to repro. I want to know.

**Comment by dcalhoun** [comment]
Yes, I can reproduce easily everytime. It's easier to do if you search for the string and then hit <kbd>n</kbd> to go to the next instance.

So, after searching for the string...
1. <kbd>n</kbd>
1. <kbd>Command</kbd>+<kbd>w</kbd>

**Comment by t9md** [comment]
OK now I understand. I couldn't understand `before the 1/# indicator dismisses` this part.
This is hover indicator for match count( I usually disabling it recently ).
Will fix in a few days.

If this really frustrate you, disable hover indicator for a while.

**Comment by dcalhoun** [comment]
Yeah, no rush. Sorry if I wasn't clear. If I have time, I'll look into a fix this weekend too.

**Comment by t9md** [comment]
Fix was very simple, so did now.
v0.82.2 is out.

**Comment by dcalhoun** [comment]
Thank you!
