### ISSUE TITLE
Incorrect description on `Stay On Delete` option

### ISSUE THREAD

**Issue by azoerb** [t9md/atom-vim-mode-plus#676]
In vim-mode-plus 0.82.2 the description for the `Stay On Delete` option says `Don't move cursor after yank` (same as the `Stay On Yank` option).

![screen shot 2017-02-14 at 09 27 13](https://cloud.githubusercontent.com/assets/1076807/22933068/523d9422-f298-11e6-968b-453db007abfe.png)

**Comment by t9md** [comment]
thanks
