### ISSUE TITLE
go to declaration not working (CTRL-])

### ISSUE THREAD

**Issue by arobson73** [t9md/atom-vim-mode-plus#677]
# Check list

- Atom version info(`1.14.2`)
- vim-mode-plus version. 0.82.3
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
only using vim-mode-plus
- Tried to latest stable atom version with latest vim-mode-plus. yes
- Restarting Atom itself solve your problem? no
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working

).
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!
tried the [cmd+shift+p]
tried the resolver. it recognise what I'm trying , but it won't go to definition
[file.zip](https://github.com/t9md/atom-vim-mode-plus/files/780553/file.zip)

**Comment by t9md** [comment]
keybinding issue, pls follow the checklist you can read above.

**Comment by arobson73** [comment]
tried the cmd+shift+p, tried the resolver also. resolver recognise, but cursor does not move to definition.

**Comment by t9md** [comment]
it's not likely. you use macOS? `alt-cmd-down` is `symbols-view:go-to-decralation`( which is also mapped from `ctrl-]` in vim-mode-plus)

observe keybinding-resolver carefully and then if you still have issue, then describe more elaborately what keybinding-resolver saying.

**Comment by t9md** [comment]
you have generated tags file? your project have tags file generated by ctags command in the first place.

**Comment by t9md** [comment]
If you can't jump via command-palette( I believe you are saying so ), it's not vim-mode-plus issue.
I think I can close this issue.

**Comment by arobson73** [comment]
sorry, my mistake. the ctags was located in the directory below. yes this can be closed.
