### ISSUE TITLE
Disable 'ESC' key if there is an autocomplete popup.

### ISSUE THREAD

**Issue by Gyubin** [t9md/atom-vim-mode-plus#678]
# Check list

- Atom version info(`atom --version`)
    + Atom: 1.14.2
    + Electron: 1.3.13
    + Chrome: 52.0.2743.82
    + Node: 6.5.0
- vim-mode-plus version: **0.82.3**
- You disabled vim-mode? **Yes**. I removed it when it was deprecated.
- Tried to latest stable atom version with latest vim-mode-plus: **Yes**
- Restarting Atom itself solve your problem? **Yes but it is not a problem but suggestion.**
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working): **No**
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

# Fix behavior dissatisfaction

I hope i don't enter the command mode with the 'ESC' key, when the autocompletion popup is open. I just want to close that popup and keep editing mode. Is there any method of Atom to get the status of popup? if so, I want to contribute about this.

**Comment by t9md** [comment]
In old issue, I implement your request, but reverted.
Some person( like you ) don't want to return to **normal-mode**, but others want to directly return to normal-mode.

## Read this if you want to know the detail.

https://github.com/t9md/atom-vim-mode-plus/issues/339

## Direct solution for your issue

https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#in-insert-mode-hitting-escape-to-close-autocomplete-popup-result-in-normal-mode-but-want-to-remain-in-insert-mode

**Comment by Gyubin** [comment]
I understand. Thank you 😄
