### ISSUE TITLE
At class 'Operator' not found

### ISSUE THREAD

**Issue by slavaGanzin** [t9md/atom-vim-mode-plus#679]
Hello thanks for your unstoppable work on this project.

I get this:

Exception:
```
At class 'Operator' not found
```

Code:
```
  @getClass: (name) ->
    if (klass = registries[name])? 
      klass
    else
      throw new Error("class '#{name}' not found")
```

I have only Base in ```registries```

What is that "classes"?
What I should look to fix this?

Thanks for any help

p.s. I reinstalled vim-mode-plus and atom and atom-beta before writing this

----------------

**Atom**: 1.15.0-beta3 x64 and 1.14.3 x64
**Electron**: 1.3.13
**OS**: linux 4.9.8-1-ARCH
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.82.3

### Stack Trace

Failed to activate the vim-mode-plus package

```
At class 'Operator' not found

Error: class 'Operator' not found
    at Function.Base.getClass (/packages/vim-mode-plus/lib/base.coffee:297:17)
    at /packages/vim-mode-plus/lib/operator-insert.coffee:11:30)
    at /packages/vim-mode-plus/lib/operator-insert.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Array.forEach (native)
    at Function.Base.init (/packages/vim-mode-plus/lib/base.coffee:274:7)
    at Object.activate (/packages/vim-mode-plus/lib/main.coffee:21:21)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
aligner 0.22.3 
atom-jade 0.3.0 
atom-typescript 10.1.14 
autocomplete-modules 1.6.7 
autocomplete-paths 1.0.5 
blame 0.10.2 
cdnjs 1.5.5 
clip-history 0.3.0 
cursor-history 0.9.1 
docker 0.7.0 
fast-eslint 3.10.0 
file-icons 2.0.15 
file-types 0.5.5 
git-blame 0.4.11 
git-diff-details 1.4.0 
git-time-machine 1.5.6 
highlight-line 0.12.0 
Hydrogen 1.5.5 
js-refactor 0.7.5 
language-docker 1.1.7 
language-dots 0.0.4 
language-gherkin 1.0.4 
language-ini-desktop 1.18.3 
language-lua 0.9.11 
language-markdown 0.19.1 
language-unix-shell 0.40.1 
last-cursor-position 0.9.0 
linter 1.11.23 
linter-eslint 8.1.2 
linter-jade 0.3.2 
local-history 4.0.1 
merge-conflicts 1.4.4 
monokai 0.22.0 
open-this 0.4.0 
pretty-json 1.6.1 
project-plus 0.9.0 
refactor 0.11.3 
regex-railroad-diagram 0.16.0 
Stylus 3.1.0 
sync-settings 0.8.1 
vim-mode-plus 0.82.3 
vim-mode-plus-move-to-symbols 0.2.0 
vim-mode-plus-subword-movement 0.2.2 
zentabs 0.8.8 
```

**Comment by t9md** [comment]
How you got this error? Does this occasional or happens-always issue?

I cannot understand why this happens. `operator-insert.coffee` is loaded after `operator.coffee`, so `class 'Operator' not found` must not happen.

Have you ever could use vim-mode-plus?

**Comment by slavaGanzin** [comment]
@t9md
 I launch atom editor and get this error. It's constant issue. As I remember it starts to occur after updating atom-editor and packages

I cannot understand it too. When I inspect it in developer tools operator.coffee was an empty IIFE:
```
(function (exports, require, module, __filename, __dirname, process, global) { 
});
```
But when I looked to ~/.atom/packages I has that file full of code. Is any meta-magic there?

Yes I used vim-mode-plus for a long time and on my other laptop it works well. Tomorrow I'll investigate this issue there

**Comment by t9md** [comment]
How about manually disable/enable package? I means Disable vmp and restart then enable.

**Comment by slavaGanzin** [comment]
> How about manually disable/enable package? I means Disable vmp and restart then enable.
Get the same error when enabled it again.

**Comment by t9md** [comment]
OK, thanks, but for now I have no idea how I can fix it since issue itself is completely contradict my understanding of how module is required in nodejs.

**Comment by slavaGanzin** [comment]
I think it's trouble with asar:

```
o = require('./operator')
console.log(o)
# Object {}
```

I'll close this issue for now

**Comment by t9md** [comment]
These are issues which are strange and fixed by re-installing vim-mode-plus.

https://github.com/t9md/atom-vim-mode-plus/issues/256

https://github.com/t9md/atom-vim-mode-plus/issues/456


One thing I can come up with is, in some reason coffeescript is compiled as incompletely and cached, then re-using that incomplete code on each restart.

So removing / re-installing kick re-compile/re-cache-to-atom coffeescript solve promlem( just assumption ).

**Comment by t9md** [comment]
Oh, OK.

**Comment by slavaGanzin** [comment]
> p.s. I reinstalled vim-mode-plus and atom and atom-beta before writing this
