### ISSUE TITLE
Jump to specific line?

### ISSUE THREAD

**Issue by hackjutsu** [t9md/atom-vim-mode-plus#680]
This is a question rather than an issue.

How can we jump to a specific line with line number specified? I cannot find a way to toggle the command mode to input the command. (If there is a tutorial mentioning about it, please just point me there).

**Comment by t9md** [comment]
If you install [vim-mode-plus-ex-mode](https://atom.io/packages/vim-mode-plus-ex-mode) you can jump to line 15 by `:15`.
Also when you open new file via core-bundled fuzzy-file-finder( `cmd-t` in macOS ) you can append `:15` to open file initially at line 15.

Here I input `cha:15` to open `CHANGELOG.md` at linet `15`.
<img width="765" alt="narrow-spec_coffee_ _spec_ ___github_atom-narrow" src="https://cloud.githubusercontent.com/assets/155205/23238950/deeda946-f9a7-11e6-98cc-2432fa303da2.png">

**Comment by hackjutsu** [comment]
Thanks! Just get it working. But does it mean there is no command mode here?

**Comment by t9md** [comment]
Yes, vim-mode-plus wont support sommand mode.
Learn atom, its not Vim.

**Comment by t9md** [comment]
Yes, vim-mode-plus wont support sommand mode.
Learn atom, its not Vim.

**Comment by brando90** [comment]
why won't it support command mode? [hopefully will inform future people that come to this issue]

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/issues/680#issuecomment-281847623

Read this comment.
You can get it by installing separate pkg.
Also you can jump to line 15 by `1 5 G`.
