### ISSUE TITLE
Implement sort motion

### ISSUE THREAD

**Issue by paradox460** [t9md/atom-vim-mode-plus#681]
Adding the ability to sort by more than just lines would be immensely useful. Things like sort by character/textObject would allow for sorting of a parameter list, for example.

This plugin provides a decent reference implementation for vim.
https://github.com/christoomey/vim-sort-motion

vim-mode-plus already has line sort, so I was somewhat surprised to find you hadn't implemented textObject sort like the plugin I linked does.

**Comment by paradox460** [comment]
Apologies if this isn't the place to ask for feature enhancements.

**Comment by t9md** [comment]
To be clarify what is now lacking in vim-mode-plus is **comma separated character sort** mentioned in that link right?

`
gsi( => Sort within parenthesis. (b, c, a) would become (a, b, c)
`

**Comment by paradox460** [comment]
Yes, but not just characters. Basically use the comma as a separator like you would use newlines in a line-based sort.

`dog, cat, fish, rabbit, duck, gopher, squid` => `cat, dog, duck, fish, gopher, rabbit, squid`

----
I thought about this on the way home, and what might make it more powerful is the ability to specify what to sort on, much like you do with the surround features.

I.e. I want to sort everything inside the parenthesis, dividing by spaces (useful for ruby array syntax sugar):

`%i(dog cat fish rabbit duck gopher squid)` + `gsi(⎵` = `%i(cat dog duck fish gopher rabbit squid)`

(where `⎵` is the space character).

**Comment by t9md** [comment]
OK got it. and agree with your suggestion for dynamically determine separator of word.
Will check later.

**Comment by paradox460** [comment]
Great, thank you!

**Comment by t9md** [comment]
I'm working on now. 
https://github.com/t9md/atom-vim-mode-plus/pull/748#issuecomment-293048634.

**Comment by paradox460** [comment]
Awesome, thanks!

**Comment by t9md** [comment]
Released in v0.89.0.
