### ISSUE TITLE
Vimrc?

### ISSUE THREAD

**Issue by JikkuJose** [t9md/atom-vim-mode-plus#682]
Anyway to honour system vimrc?

**Comment by t9md** [comment]
No

**Comment by heyitswither** [comment]
wow rude

**Comment by riazrizvi** [comment]
atom-vim-mode-plus is a Vim emulator written in Javascript, so it's a rewrite in of an app in Javascript. To import vimrc (and packages), you would need a Vimscript-Javascript transpiler. So it's not a small request.

**Comment by LeaveNhA** [comment]
Then, we should implement it !
I'm quite busy in these days. But I'll consider to be volunteer for this task.

@t9md; that was rude, btw. 😏
