### ISSUE TITLE
move-to-last-line doesn't  work~

### ISSUE THREAD

**Issue by javasgl** [t9md/atom-vim-mode-plus#687]
# Check list

- Atom version info( v1.14.4 )
- vim-mode-plus version (v.0.82.3).
- You disabled vim-mode? yes
- Restarting Atom itself solve your problem? no

in my `~/.atom/keymap.cson`,i overrided the default keymap `shift-G` to `G`:
```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'G': 'vim-mode-plus:move-to-last-line'
```
### but :
![image](https://cloud.githubusercontent.com/assets/5222868/23605450/ba3a8f76-0297-11e7-9bc0-360a8d71921a.png)
### why still is the `shift-G` instead of  `G` ?

I installed the `vim-mode-plus` and `vim-mode-plus-ex-mode`
![image](https://cloud.githubusercontent.com/assets/5222868/23605572/3a61096e-0298-11e7-8cd8-833ad9075fc8.png)

**Comment by t9md** [comment]
What't the problem? Are you saying your custom keymap solve your problem?

In setting view, shift-G means `G`, bare capital G means `g`.
This view representation doesn't come from vmp. 
If you want to know how keymap in vmp is defined check keymaps dir in vmp repo.

**Comment by javasgl** [comment]
in vim , move to the last line is `G`, instead of `shift-G`

**Comment by t9md** [comment]
I know vim, your issue is keymap issue, please investigate by your self and report with that information if you need help.
`gg` and `G` pass spec and works in my environment.
Don't stick `shift-G` and `G` diff, this is both capital-letter `G`. If you type capital `G` and didn't moved to last line, thats keymap issue you need to investigate by yourself.
You've seen guide issue template when you create this issue.

**Comment by javasgl** [comment]
Thanks!
here is the new information:
- atom --version
```
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
- `You can invoke any commands via "Command Palette"(Cmd+Shift+P). Invoking that command directly via Command Palette works?`  Yes , It works !

- Keybinding Resolver
  when  press the capital `G`, `key Binding Resolver` is `g`
  when press the 'g', `key Binding Resolver` still is `g`

It sames thats `'G': 'vim-mode-plus:set-input-char-G'`  not used

**Comment by t9md** [comment]
What type of keyboard are you using? When you type capital G, do you need press shift key?
Atom keybinding system normalize `G` to shift-G, to match to it, shift- modifier is necessary.
How you type capital G when you write this issue?

**Comment by javasgl** [comment]
when i type capital G ,i need ：
first press the `Caps Lock` , then press the `g`

**Comment by t9md** [comment]
Is this the only way to type G in your keyboard?
How that keyboard layout called?
This is not solely vim-mode-plus's issue, this is atom-key-binding issue, yo'd better to report that or akk in atom slack or find people who use same keyboard user who overcome this issue. I'm using normal us-layout keyboard, can't help much.

**Comment by javasgl** [comment]
well, thanks 👌 .
by the way , I'm using us-layout keyboard too~ 😥

**Comment by javasgl** [comment]
well, thanks 👌 .
by the way , I'm using us-layout keyboard too~ 😥

**Comment by t9md** [comment]
Really?
So you also can type G with shift-g combination?
If so why u use caps lock?

**Comment by javasgl** [comment]
That's just my habit 😅 
To type the capital  letters ,I usually use `caps lock` first 😺

**Comment by t9md** [comment]
So now clear. You have to do is report to atom-keybindings or contribute to it. Or change habit(recommended)
