### ISSUE TITLE
Occurrence operator modifier not working on "$variable"

### ISSUE THREAD

**Issue by mramiro** [t9md/atom-vim-mode-plus#689]
The occurrence operator-modifier does not work when used on variable names that start with a dollar sign if the grammar for the current editor is set to PHP or Perl.

# How to reproduce
1. Copy and paste the following code on a new atom editor pane:
```php
<?php

function test($var)
{
  return
"This is 1st paragraph $var.
2nd line also include $var $var $var.
3rd line include $var $var $var

This is 2nd paragraph $var.
2nd line also include $var $var $var.
3rd line include $var $var $var
4th $var";
}

echo test('foo');
```
2. Make sure the PHP grammar is set on the editor (`Ctrl+Shift+L` -> select PHP).
3. In normal mode, place cursor over any occurrence of `$var` and press `c o`

## What happens?
Nothing

## What should happen?
All occurrences of `$var` should be highlighted.

## Some notes

* Notice that the expected behaviour does occur when the cursor is over a non-variable (`paragraph`, for example).
* If you change the grammar to Perl and repeat the process, the result is the same.
* If you change the grammar to Plaintext or some other language, there's no issue.

As far as I know, the dollar sign works as a [sigil](https://en.wikipedia.org/wiki/Sigil_(computer_programming)) in PHP and Perl, so I'm guessing the corresponding atom packages that provide support for those languages are altering the behaviour of the editor. I also found that in the case of Perl the issue is also present on variable names that start with `@` and `%`, since it uses those as sigils too.

I've tried with some other languages that I know that use a similar syntax (Unix shell, Ruby, SQL) and it seems the issue is not present with them.

And that's all. Let me know if I there's anything else I can help with.

Regards.

# Check list

- Atom version info(`atom --version`)
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
- vim-mode-plus version.
0.82.3
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
vim-mode not installed
- Tried to latest stable atom version with latest vim-mode-plus.
Yes.
- Restarting Atom itself solve your problem?
No
- Keybinding issue?
Atom's Key Binding Resolver shows that the correct actions are called.

**Comment by t9md** [comment]
Good enough!
Concise, clear, I don't have to ask you anymore!
I like your issue report.

I could reproduce issue, will investigate what cause this.

**Comment by t9md** [comment]
![occurrence-php-var](https://cloud.githubusercontent.com/assets/155205/23622460/202d0b8e-02e2-11e7-8772-d360e18c5624.gif)

Found cause and fix locally, will include in next release after re-check.

**Comment by mramiro** [comment]
Wow. That was fast!

Thank you for your support. You're doing a great job here!

Regards.
