### ISSUE TITLE
Relative Numbers

### ISSUE THREAD

**Issue by hnguyen94** [t9md/atom-vim-mode-plus#69]
Hey can you add relative numbers to vim plus?
I know there is a plugin for that, but it's a little bit buggy.
If I use Visual Line, it shows me wrong numbers.

**Comment by t9md** [comment]
Relative line is useful for non vim-mode-plus-user.
So I think it should be implemented as stanalone package.

**Comment by crshd** [comment]
Should be fixed in justmoon/relative-numbers#3
