### ISSUE TITLE
Pasting blockwise visual selections only pastes last line of block

### ISSUE THREAD

**Issue by Bigd271** [t9md/atom-vim-mode-plus#690]
[blockwise-copy-paste-issue.mov.zip](https://github.com/t9md/atom-vim-mode-plus/files/831096/blockwise-copy-paste-issue.mov.zip)
# Check list

- Atom version info(`atom --version`): 1.14.4
- vim-mode-plus version. -0.83.0
- You disabled vim-mode? : Yes
- Tried to latest stable atom version with latest vim-mode-plus.
- Restarting Atom itself solve your problem? No
- Keybinding issue?No (ctrl -v, y, p) 

When selecting a block of numbers in blockwise mode, copying, and then pasting, it's only pasting the last line of the selection. I would expect this to perform the same way VIM does today and paste the entire block. I will attach a video to better explain.

**Comment by t9md** [comment]
duplicate
