### ISSUE TITLE
Visual Line Selection grabs an extra line

### ISSUE THREAD

**Issue by nobleach** [t9md/atom-vim-mode-plus#695]
# Check list

- Atom version info(`atom --version`)
1.15.0

- vim-mode-plus version.
0.84.1

When using visual line selection (`V`), and a downward motion, an extra line is selected:
![overselecting](https://cloud.githubusercontent.com/assets/217134/23840224/13e9b954-0769-11e7-8782-a5499703744f.gif)

It usually take about 500ms or it to highlight. If using visual mode to select something and then yanking that text (`y`). The next line will be included in the yank.

I've browsed the issues a little bit, but didn't see this exact issue. (I'm still looking - I'll delete this issue if I find that it's a duplicate)

**Comment by t9md** [comment]
I can't understand from GIF. Finding the problem from GIF is super frustrating, please describe.
- The sample text
- keystroke you did
- the result and what was different from your expectation.

**Comment by nobleach** [comment]
I'm sorry. 

I enter visual line mode. I am using `j` to select downward. I finish my selection. VMP selects one more line.

**Comment by t9md** [comment]
I watched GIF, but can't understand that's why I ask above question.

As I wrote, I need sample text and keystroke like this


# Example to describe your issue (This is not happen in my env)

- sample text, place cursor at `|`.

`
|a
b
c
d

`

- kesytroke `V j j`
- result
   - actual: four lines `a\nb\nc\nd\n` selected,
   - expectation: three lines `a\nb\nc\n` selected,

**Comment by nobleach** [comment]
What you have typed describes my issue exactly. That is my problem. If you're not seeing it in your environment, I'll investigate other causes.

**Comment by t9md** [comment]
I can't reproduce your issue with v0.84.1.

![vjj](https://cloud.githubusercontent.com/assets/155205/23841001/69b8f1d6-07ed-11e7-9117-6eebae5d5c4d.gif)

**Comment by nobleach** [comment]
I'll try lowering my key repeat rate. Perhaps it's triggering too many presses.

**Comment by t9md** [comment]
> It usually take about 500ms or it to highlight.

This is very slow, what your machine spec and OS?

**Comment by nobleach** [comment]
No, let me clarify. Selecting the lines I want to select is fast. After I am done, 500ms to 1000ms later, another line selects.

**Comment by t9md** [comment]
OK understand.

**Comment by adamalbrecht** [comment]
I've been experiencing this problem, as well.

**Comment by nobleach** [comment]
I have found that it totally was my fault. I was hitting visual line select, and hitting `j` until I had selected all the lines that I wanted. About a half second later, another line would be selected. To confirm, I did `7j` and it selected the correct amount of lines. I believe this problem exists because every downward select motion has to check whether it is the last line. I've gotten used to hitting `j` until I'm the line above the last one I want selected. (It's a bit annoying when I go back to regular Vim, but not too bad)

**Comment by synthetiv** [comment]
@nobleach / @adamalbrecht, you don't happen to have `j k` bound to `vim-mode-plus:activate-normal-mode`, do you? If so, Atom is just waiting 500ms to see if you're going to type a `k` next. I thought I had a similar problem for a while (although I use `k j` instead of `j k`) until I realized it was my keymap's fault. Now I use this to limit the binding to insert mode only:

```coffee
'atom-text-editor.vim-mode-plus.insert-mode':
  'k j': 'vim-mode-plus:activate-normal-mode'
```

**Comment by nobleach** [comment]
Wow! that was totally it! I had `'j k'` set for everything other than normal mode... which doesn't make sense at all. Thank you so much!

**Comment by adamalbrecht** [comment]
Good catch! That was my problem as well.

On Wed, May 24, 2017 at 10:05 AM, Jim Wharton <notifications@github.com> wrote:
Wow! that was totally it! I had 'j k' set for everything other than normal mode... which doesn't make sense at all. Thank you so much!

**Comment by NeilvB** [comment]
Thanks @synthetiv - I had this exact problem. Fixed after I used similar config to your comment.
