### ISSUE TITLE
Arpeggio keybindings?

### ISSUE THREAD

**Issue by JesseLeite** [t9md/atom-vim-mode-plus#703]
So I know we can setup an arpeggio keybinding, like `j,k` to reset normal mode:

```coffee
'atom-text-editor.vim-mode-plus':
  'j k': 'vim-mode-plus:reset-normal-mode'
```

However Atom's default keymap behaviour feels weird because `j` is not written to the buffer until either: A) The second keystroke matches `k`, or until B) A second or two passes without a `k` keystroke.

I found a little script [in this thread](https://github.com/atom/vim-mode/issues/334), which I modified to kinda reverse how this keymapping works.  Pressing `j` triggers nothing.  When `k` is pressed, the previous key is evaluated.  If the previous key is `j`, then vim-mode-plus resets normal mode 👍 

```coffee
'atom-text-editor.vim-mode-plus':
  'k': 'reset-normal-mode-if-preceded-by-j'
```
```coffee
atom.commands.add 'atom-text-editor', 'reset-normal-mode-if-preceded-by-j': (e) ->
  editor = @getModel()
  pos = editor.getCursorBufferPosition()
  range = [pos.traverse([0,-1]), pos]
  console.log(range)
  lastChar = editor.getTextInBufferRange(range)
  if lastChar != "j"
    e.abortKeyBinding()
  else
    editor.backspace()
    atom.commands.dispatch(e.currentTarget, 'vim-mode-plus:reset-normal-mode')
```

The above keymap+script works great!  However, the above command is very coupled to `j,k` and `vim-mode-plus:reset-normal-mode`.  I know some people like `j,j`, or other keybindings for normal mode.  I wonder if something like this could be worked into vim-mode-plus, or even the Atom core?  Thoughts?

**Comment by t9md** [comment]
See comment ( around bottom ) in following thread.

https://github.com/t9md/atom-vim-mode-plus/issues/130

The feature you requested above is NOT planned in vmp.

**Comment by JesseLeite** [comment]
@t9md fair enough.  I did mention the same keymapping suggested in #130, but was presenting an alternate implementation 😄 

```coffee
'atom-text-editor.vim-mode-plus':
  'j k': 'vim-mode-plus:reset-normal-mode'
```

>Atom's default keymap behaviour feels weird because j is not written to the buffer until either: A) The second keystroke matches k, or until B) A second or two passes without a k keystroke.
