### ISSUE TITLE
vim-mode-plus displaying numbers in the editor view

### ISSUE THREAD

**Issue by nwaywood** [t9md/atom-vim-mode-plus#706]
Since a recent update of vim-mode-plus it has started displaying numbers at the far left of the editor view (the number 2 in the screenshot below).

![image](https://cloud.githubusercontent.com/assets/3773641/24181578/e1c184c6-0f0f-11e7-982d-150646da584a.png)

It seems that the number displayed is `(linenumber - 1) % 10`, so line 21 to 30 would display 2, line 31 to 40 would display 3, etc.

I couldn't find any new setting in [settings](https://github.com/t9md/atom-vim-mode-plus/blob/master/lib/settings.coffee) to remove this so I'm assuming it must be a bug.

----------

Checklist:

- Atom version info

```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

- vim-mode-plus version - `0.84.1`
- You disabled vim-mode? Yes
- Tried to latest stable atom version with latest vim-mode-plus? Yes
- Restarting Atom itself solve your problem? No

**Comment by t9md** [comment]
what's the linenumber, when it's displayed? Does it come from vim-mode-plus?
Not investigated, you use relative-number package? how about disabling it?

**Comment by nwaywood** [comment]
I just tested, the issue goes away when the [relative numbers](https://atom.io/packages/relative-numbers) package is disabled. The bug must be related to vim-mode-plus though because:

1. The number only shows up in normal mode, in insert mode the number disappears
2. I have been using the relative-numbers package with vim-mode-plus for a long time and I haven't seen this issue until the last vim-mode-plus update

Is there any more information I can give you to help debug the issue?

**Comment by t9md** [comment]
I'm not using relative numbers, what is your expected result, please clarify actual vs expected result.

**Comment by t9md** [comment]
I installed relative-number and tried to reproduce, but couldn't .
Then, if you say it's bug of vim-mode-plus, I need the way to reproduce 100% to investigate further.
I still want to know the clear description of  actual-vs-expected result.

![issue-relative-number](https://cloud.githubusercontent.com/assets/155205/24187839/229a3c2e-0f22-11e7-9616-579f27df657a.gif)


<img width="483" alt="styles_less_ ___github_dotfiles_atom" src="https://cloud.githubusercontent.com/assets/155205/24187849/3682b798-0f22-11e7-9a51-763abf5c5f40.png">

```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by t9md** [comment]
As I wrote, I can't reproduce this.
I need

- The exact same file you can reproduce( via link or gist whatever )
- Minimum package combination you use to reproduce.
- Your OS information

I'm using http://www.cockos.com/licecap/ for GIF anime.

**Comment by nwaywood** [comment]
The exact file shouldn't matter, since I am experiencing this bug in all files. However, just in case, [here](https://github.com/nwaywood/react-async-examples/blob/master/native/app/src/containers/HomeContainer.js) is one of the files where I encountered this issue.

Minimum package combination to reproduce:
- [linter](https://atom.io/packages/linter)
- [linter-ui-default](https://atom.io/packages/linter-ui-default)
- [relative-numbers](https://atom.io/packages/relative-numbers)
- [vim-mode-plus](https://atom.io/packages/vim-mode-plus)

OS Information:

![image](https://cloud.githubusercontent.com/assets/3773641/24234563/26118b98-0fed-11e7-80c4-99ce1c76373d.png)

**Comment by t9md** [comment]
OK, will check.
Are you customizing your own style in `style.less`?

**Comment by t9md** [comment]
Could reproduce, by following your info, I installed linter-ui-default.

This issue is reproduced even in older version of vmp ( tried with vmp-v0.78.0 ).
My thought for this issue is this is issue of relative-numbers with combination of vmp or linter-ui-default package.

I cannot understand why you believe this bug is introduced by recent update of vmp.
And again without your above package information I could never reproduce issue.
I've tried several approach without information, but it's basically waste of time.

I'l investigate issue again if you or someone give me result of investigation on why relative-number shows number with vmp and liner-ui-default package combo.

**Comment by nwaywood** [comment]
Ok so I have done some more research and discovered that the number is coming from the `linter-ui-default` package

![span](https://cloud.githubusercontent.com/assets/3773641/24274869/7ac21a12-107f-11e7-8c96-baee8004dcdf.png)

for some reason it is visible in normal mode and not in insert mode. As far as I can tell the only thing that changes in the DOM is that the class in `atom-text-editor` changes from `normal-mode` to `insert-mode`. Unfortunately I am not experienced enough with atom development to know how to investigate this further.

But as a hacky fix to the problem I have added this to my `styles.less`:

```
/* Fixes https://github.com/t9md/atom-vim-mode-plus/issues/706 */
 .linter-cursor-line .relative {
     visibility: hidden;
 }
```

**Comment by t9md** [comment]
Did investigated a bit from your info.

# Short summary

- linter-ui-default use `line-number` CSS class Name of as gutter `linter-ui-default`.
- relative-numbers blindly target and modify element by searching `@editorView.rootElement?.querySelectorAll('.line-number')` which unnecessarily modify gutter used in linter-ui-default(where it shouldn't)

**Comment by nwaywood** [comment]
Thank you for tracking down the issue! I'll submit an issue to `relative-numbers` and hope for the best!
