### ISSUE TITLE
Switch to insert mode on multiple cursors

### ISSUE THREAD

**Issue by montogeek** [t9md/atom-vim-mode-plus#708]
# Check list

- Atom version info(`atom --version`) 1.15.0
- vim-mode-plus version. 0.84.1

Hi!

I am probably doing something wrong:
Use visual mode to select a word
Press `Cmd + D` to select other occurrences of the word
Press `i` so switch to Insert mode, this step doesn't work, pressing `i` does nothing

How can I do this with other workflow?

Thanks!

**Comment by montogeek** [comment]
After checking https://github.com/t9md/atom-vim-mode-plus/wiki/AdvancedTopicTutorial
I am using:
`ve` to select the word
`Cmd + D` to select all occurrences
`c` to change it

**Comment by t9md** [comment]
After you did `cmd-d`, you are now in `visual-mode`.
In `visual-mode`, `i`  is used as prefix of many inner-text-object.
- `i w`: `inner-word`
- `i p`: `inner-paragraph`.

If you want to shift `insert-mode` from `visual-mode`, you can use
- `c`: Change
- `I`: start insertion at start position of each selection.
- `A`: start insertion at end position of each selection.
