### ISSUE TITLE
How to i can break delay when i use my hotkey

### ISSUE THREAD

**Issue by haacki47** [t9md/atom-vim-mode-plus#709]
Hi, you made awesome plugin, i glad for it.

I use this commad:
```
'atom-text-editor.vim-mode-plus.insert-mode':
  'd f': 'vim-mode-plus:activate-normal-mode'
```
For use my own keys go to normal mode.
But when i press 'd' key when i code, editor has some delay, and after moment 'd' will be show

How to i can break it delay when 'd' pressed?

**Comment by t9md** [comment]
See this comments and also read issue.

https://github.com/t9md/atom-vim-mode-plus/issues/670#issuecomment-277502647

#130
