### ISSUE TITLE
`this.editorElement.getModel is not a function` on startup on Atom master

### ISSUE THREAD

**Issue by BinaryMuse** [t9md/atom-vim-mode-plus#717]
Hello!

On the latest `master` (I'm running `1.17.0-dev-9d5d09f34`), I receive `this.editorElement.getModel is not a function` when I start Atom. This could be related to some changes to the core text editor stuff recently (I'll ping @nathansobo just in case) but wanted to make you aware early. :)

Here's as much of the stack as is reported:

```
Uncaught TypeError: this.editorElement.getModel is not a function (vim-mode-plus/lib/search-input.coffee:44)
  registerElement @ vim-mode-plus/lib/utils.coffee:998
```

vmp v0.85.1

```
Atom    : 1.17.0-dev-9d5d09f34
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by t9md** [comment]
Tried with the latest master at this point.
And have no issue. You can see issue constantly?

```
Atom    : 1.17.0-dev-5b6cca4
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0
```


<img width="461" alt="mark-manager_coffee_ ___github_atom-vim-mode-plus" src="https://cloud.githubusercontent.com/assets/155205/24439118/2675fada-1487-11e7-8db4-f8b4fc5a4246.png">

**Comment by t9md** [comment]
Wow, surprisingly all vmp spec passed.

**Comment by t9md** [comment]
close is just mistake.

**Comment by BinaryMuse** [comment]
Ohh interesting... yeah I see it consistently. And I have other issues where suddenly the text editor stops adding characters when I press keys. I'll take a closer look soon.

**Comment by BinaryMuse** [comment]
This suddenly stopped happening. ¯\_(ツ)_/¯

**Comment by t9md** [comment]
OK. thanks!
