### ISSUE TITLE
disable new-line char selection in 0.85

### ISSUE THREAD

**Issue by prog666** [t9md/atom-vim-mode-plus#721]
> Improve: Now can select line ending new line char in visual-mode.
Is there any way of disabling this?

**Comment by t9md** [comment]
Want to know why?

**Comment by prog666** [comment]
I know it's native behaviour in vim, but i did like old behaviour in atom-vim

**Comment by t9md** [comment]
I like new behavior.
No motivation to support this.

**Comment by prog666** [comment]
how can anyone like this, you do `v $ d` and delete new line char

**Comment by t9md** [comment]
you can do `d $`.

**Comment by prog666** [comment]
and if you need to delete few strings to the end of last, you have to remember that there's new line char at the end, who need to select new line char?

**Comment by t9md** [comment]
I understand your point, but both behavior have some benefit.
For me as maintainer perspective, it's important for internal architecture consistency.
Previous behavior was just result of quick&dirty fix of original vim-mode(github maintained at that time).

**Comment by prog666** [comment]
thanks for your response
