### ISSUE TITLE
[breaking, tryout] Opinionated default setting.

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#728]
https://twitter.com/t9md/status/848413360668368896

https://twitter.com/t9md/status/848345603348209664

- I repect pure-Vim's behavior in most case.
- But I want CHANGE some default behavior of pure-Vim
  - So I introduced `stayOn` family setting. I want all `stayOn` to `true`
    - Maybe I don't need per operator `stayOn` setting, since who want `stay` feature, they want to `stay` for all operation.
    - Per operator tweaking should not necessary.
  - So introduce `keepColumnOnSelectTextObject`.( want set this to `true` )
    - This is similar preferences to `stayOn` feature, who want `stayOn` feature, this should be set to `true`.
- I want pure-Vim have more s [sensible](https://github.com/tpope/vim-sensible) setting.
  - Also want set `useClipboardAsDefaultRegister` to `true` by default.
  - make `incrementalSearch` set to `true`
  - Also `startofline` to `false`(pure Vim's default is `true`)
    - vmp have `moveToFirstCharacterOnVerticalMotion` for this, and so I want this to `false` by default.
      - This is similar preference to `stayOn` feature, furthermore `stayOnDelete` is splited out from `startofline` in pure-Vim.
- I want replace some non-useful keymap ( this is my selfish opinion I know ) to more useful-one.
  - Who use default `_`, `+`, `-` motion?
    - I want set `_` to `replace-with-register`: like [vim-operator-replace](https://github.com/kana/vim-operator-replace/blob/master/doc/operator-replace.txt#L76)'s example.
    - This is keymap I've been using for a long time from when I was pure-Vim user.
- I want set aggressive keymap when I can safely override.
  - vmp have unique feature which allow super granular keymap which is effective **only when specific operator is pending** (like when `d` is pending).
    - https://github.com/t9md/atom-vim-mode-plus/issues/215
    - This mean I can map `d` in opertor-pending-mode without affecting `d d` keystroke.

    ```coffeescript
    # comment-in by `g / /`
    'atom-text-editor.vim-mode-plus.toggle-line-comments-pending':
      '/': 'vim-mode-plus:inner-comment'

    # `c d` to change subword, `y d` to yank subword without affecting `d d`
    'atom-text-editor.vim-mode-plus.operator-pending-mode:not(.delete-pending)':
      'd': 'vim-mode-plus:inner-subword'

    # `d c` to delete current-smart-word, `y c` to change cursor-word.
    'atom-text-editor.vim-mode-plus.operator-pending-mode:not(.change-pending)':
      'c': 'vim-mode-plus:inner-smart-word'

    # Or I can ruin `c c` to change cursor-word by `c c`.
    # For original `c c`, `S` is available or `C ctrl-u` do that job.
    'atom-text-editor.vim-mode-plus.operator-pending-mode':
      'c': 'vim-mode-plus:inner-smart-word'
    ```

Tryout to achieve #728
Let's see how it goes.

The configs listed below is candidate to be changed, value is **new** default, so current value is opposite.

# [Category-1]: Bit aggressive but it's OK.

```
useClipboardAsDefaultRegister: true
clearHighlightSearchOnResetNormalMode: true
clearPersistentSelectionOnResetNormalMode: true
highlightSearch: true
incrementalSearch: true
smoothScrollOnFullScrollMotion: true
smoothScrollOnHalfScrollMotion: true
```

# [Category-2]: StayOn family, change behavior of motion, operator, text-object. But vmp's own goodness.

```
stayOnTransformString: true
stayOnYank: true
stayOnDelete: true
keepColumnOnSelectTextObject: true
moveToFirstCharacterOnVerticalMotion: false
```

# [Category-3]: Opinionated keymap.

Most of these new config is not necessarily need to be config option, but why providing these as config-option is..

- To share keymap that worked for me and help user to set keymap with checkbox( no need to consult keymap-file for new user ).
- I can use these setting to assumed keymap in document( tutorial, movie, doc ).

```
keymapCCToChangeSmartWord: false
keymapUnderscoreToReplaceWithRegister: true
keymapSemicolonToInnerAnyPair: false
```

### Shorthand keymaps

Theoretically and practically, there is NO possibility where another operator comes in `operator-pending-mode`.  
So `y D`, `y c`, `y x`, `y X`, `y d`, all of these are **invalid** operation in Vim.  
This also mean, we can safely remap these **unsuded**( since invalid ) keystroke as more useful one.  

Here is the idea based on my experience.

#### `operator-pending-mode` generally

- `c` as shorthand of `inner-smart-word`
  - So
    - `y c` to `yank inner-smart-word`( shorthand of `y i w` )
    - `g - c` to `dash-case inner-smart-word`( shorthand of `g - i w` )
    - `c c` to `change inner-smart-word` ( shorthand of `c i w` when `keymapCCToChangeSmartWord` was enabled )
  - Exception
    - `c c`( change line ) behave normally by default.
    - But I recommend enable `keymapCCToChangeSmartWord`. to make `c c` to `change inner-smart-word`.
    - Why? `change inner-smart-word` is more frequently used in my opinion.
      - And original `c c` is many alternate operation
        - `S`( equivalent to `c c` ), `^ C` or `c i l`(`change inner-current-line`), `d d O`.
- `d` as shorthand of `inner-subword`
  - So
    - `y d` to `yank inner-subword`( shorthand of `y i d` )
    - `c d` to `change inner-subword`( shorthand of `c i d` )
  - Exception
    - `d d`( delete line ) behave normally( NOT work as `delete inner-subword` )
      - This is inconsistent but you can delete by `c d escape` or your own `inner-subword` keymap.
- `C` as shorthand of `inner-whole-word`
  - So
    - `y C` to `yank inner-whole-word`( shorthand of `y i W`)
    - `c C` to `change inner-whole-word`( shorthand of `c i W`)
  - No Exception: This keymap is safe, no conflicts( `C` is operator )
- `p` as shorthand of `inner-paragraph`
  - So
    - `y p` to `yank inner-paragraph`
    - `c p` to `change inner-paragraph`
    - `d p` to `change inner-paragraph`
  - No Exception: This keymap is safe, no conflicts( `p` is operator )
- `;` as shorthand of `inner-any-pair`
  - This keymap is disabled by default. need to enable `keymapSemicolonToInnerAnyPair`
  - So
    - `y ;` to `yank inner-any-pair`
    - `c ;` to `change inner-any-pair`
    - `d ;` to `delete inner-any-pair`
    - `_ ;` to `replace-with-register inner-any-pair`
  - Conflicts: Original `;`( `repeat-find` )

#### `operator-pending-mode.toggle-line-comments-pending`

Keymap only when `g / ` is pending.

```coffeescript
'atom-text-editor.vim-mode-plus.operator-pending.toggle-line-comments-pending':
  '/': 'vim-mode-plus:inner-comment-or-paragraph'
```

- Currently `g /` is mapped to `toggle-line-comments`
- Currently `i /` is mapped to `inner-comment`
- So user can
  - `g / i /` to to comment-in existing commented region.
  - `g / i p` to toggle-comment for paragraph.
  - `d i /` to delete commented region.
- But from my experience, following operation is most frequently used operation
  - Comment-in already comment-out-ed region( `g / i /`).
  - Comment-out block of text( paragraph )( `g / i p`).
- Make above most-frequently-used-operation( MFUO ) more accessible and easy to type
  - `g / /` to `toggle-line-comments inner-comment-or-paragraph`

**Comment by calebmeyer** [comment]
This one is marked as discussion, so I'll post a comment:
I think there are a lot of weird bits that vim gets wrong due to being compatible with Vi and older versions of itself.
Copying text to `""` instead of `"+` by default is weird for anyone who is coming here not from many years of vim.
I personally hate that `Y` is the same as `yy`, even though `C` is `c$` and `D` is `D$`. I've mapped it in my keymap so that `Y` does what I would expect.

I'm fully in support of all of these changes. The only one I didn't understand was the `_` as `operator-replace`. Can you give an example of what this does and why it is useful?

**Comment by t9md** [comment]
> I personally hate that Y is the same as yy, even though C is c$ and D is D$. I've mapped it in my keymap so that Y does what I would expect.

Vmp have `yank-to-last-character-of-line` commands to behave as `y $`.
So user can map `Y` to `yank-to-last-character-of-line` to get consitency to `D` and `C`.

I think I can provide conditionalKeymaps configuration named `keymapYToYankToLastCharacterOfLine` as enhancement.

> I'm fully in support of all of these changes. The only one I didn't understand was the _ as operator-replace. Can you give an example of what this does and why it is useful?

`replace-with-register` is operator, so you can replace over any target(with `motion` or `text-object`) with your register text.

From `keymapUnderscoreToReplaceWithRegister` config param description.

Can: `_ i (` to replace inner-parenthesis with register's value<br>\nCan: `_ ;` to replace inner-any-pair if you enabled `keymapSemicolonToInnerAnyPairInOperatorPendingMode`

### Example

Will demonstrate several scenario to replace `xxx` with `ooo` when you have `ooo` in register.

## Config:

- `_` mapped to `replace-with-register`( you can do it manually or by enabling `keymapUnderscoreToReplaceWithRegister`).

### Replace inner paren with clipboard

Before: `callSomeFunction(|xxx)`
Keystroke: `_ i (` or `_ ;`(require `keymapSemicolonToInnerAnyPairInOperatorPendingMode`)
After: `callSomeFunction(|ooo)`

### Replace inner quote with clipboard

Before: `this is quoted "|xxx"`
Keystroke: `_ i "` or `_ ;`(require `keymapSemicolonToInnerAnyPairInOperatorPendingMode`)
After: `this is quoted "|ooo"`

### Replace function args

Before: `callSomeFunction(|xxx, yyy)`
Keystroke: `_ ,`
After: `callSomeFunction(|ooo, yyy)`

### Replace function args

Before:

```javaScript
function someFunction(xxx, yyy) {
  const val = xxx * yyy
  return 1000 - val / xxx
}
```

Keystroke: `_ o f`(`replace-with-register` for `occurrence` in `a-function`).

After:

```javaScript
function someFunction(ooo, yyy) {
  const val = ooo * yyy
  return 1000 - val / ooo
}
```

**Comment by lydell** [comment]
vim-mode-plus has so many cool features and, in my opinion, improvements compared to Vim! Sometimes it feels like I have trouble keeping up with all the new stuff coming out, and taking the time to come up with nice key bindings for vmp-specfic features. So I would very much like a well thought through, opinionated pre-made config!

**Comment by t9md** [comment]
@lydell I checked your [dotfiles](https://github.com/lydell/dotfiles) and happy to know you use all "cool" features(`stayOn`, `incrementalSearch`, smooth scroll etc.).

I want other non-config-interested user notice these "advancement" of vmp, so will change to **opinionated** default value in near future.

I think it would be no big trouble for normal user, for users who want more srict compatibilities  to pure-Vim, they can easily revert these changes via config options.

**Comment by lydell** [comment]
@t9md Oh, I do? I've seen lots of new vmp versions coming out but I haven't really paid attention to them so I thought I was missing out ;)

**Comment by t9md** [comment]
@lydell Oh, you are correct,  "all" in my sentence was not correct, but IMO `stayOn` is big config I want to embrace to try every vmp user.

Off course vmp have lots of features which user need to discover(cannot be enabled by trough default config change).
Here is quick-link(some of it you already know and use).

- Release note is primal resources since I write down every change(wiki doesn't have 100% feat coverage).
- https://github.com/t9md/atom-vim-mode-plus/wiki/YouDontKnowVimModePlus
- https://github.com/t9md/atom-vim-mode-plus/wiki/VmpUniqueKeymaps
- https://github.com/t9md/atom-vim-mode-plus/wiki/AdvancedTopicTutorial

**Comment by t9md** [comment]
DONE with following exception.
  - smoothScroll is still default `false`
  - conditional keybinding is default disabled( `false` ).
  -  making `smoothScrollOnFullScr`

But I'm comfortable with current status.
Will close now.
