### ISSUE TITLE
How to jump back last cursor position?

### ISSUE THREAD

**Issue by fireice009** [t9md/atom-vim-mode-plus#733]
I don't want another plugin if I can. e.g. <https://atom.io/packages/last-cursor-position>

**Comment by bronson** [comment]
t9md's cursor-history package is the official vim-mode-plus way to jump forward and back.

To keep things simple (ha), vim-mode-plus is just an editing component.  (mostly).   It takes a few more plugins to get buffer switching and some other vim features.

**Comment by t9md** [comment]
Simple `' '`  and ``` ` ` ``` works in vmp. which jump between two location(point before/after jump).

https://atom.io/packages/cursor-history
is mentioned in README of vmp, read it.
