### ISSUE TITLE
Type '#' to search for a specific character and press 'n' to find the previous search result.

### ISSUE THREAD

**Issue by uyu423** [t9md/atom-vim-mode-plus#737]
# Check list

- Atom Version
  - Atom: 1.15.0
  - Electron: 1.3.13
  - Chrome: 52.0.2743.82
  - Node: 6.5.0
- vim-mode-plus version.
  - 0.87
- Your OS
  - Windows 10
- You disabled vim-mode? 
  - not installed vim-mode, but installed vim-mode-plus, vim-mode-plus-ex-mode

Type '#' to search for a specific character and press 'n' to find the previous search result.
Conversely, typing 'N' (shift-n) will find the next search result. Is not this the opposite of normal?
Surprisingly, this only happens when you type '#', and it works correctly when you use '/'.

**Comment by bronson** [comment]
This is the way vim works, try it out.  When you start in backward mode, you remain in backward mode.

**Comment by t9md** [comment]
- `n`: continue last search in same direction.(NOT necessarily forwarding).
- `N`: continue last search in opposite direction.(NOTE necessarily backward)

- Following command is commands subjected to repeated by `n` or `N`.
- If original search was **backward**, some people like you think it's not intuitive(but it's how Vim behave as @bronson said).
  - search(`/`), search-backwards(`?`)
  - search-current-word(`*`), search-current-word-backwards(`?`)

**Comment by uyu423** [comment]
I just found that searches using '#' work this way in the original vim. first noticed using vim for several years. Shock
Thanks everyone.

**Comment by bronson** [comment]
:)  I've done that once or twice, and @t9md set me straight then too.
