### ISSUE TITLE
searching in development mode doesn't work

### ISSUE THREAD

**Issue by bronson** [t9md/atom-vim-mode-plus#738]
(super low priority, this is just a "things that make you go hm")

If I start Atom with --dev, then `/` doesn't start a search.  If I start Atom regularly, `/` works just fine.

cmd-. suggests it's not a keybinding issue...  but it could be some other brain damage on my end.

This shows up in the event log:

```
operation-stack.coffee:159 Uncaught TypeError: editor.displayLayer.findFoldMarkers is not a function
saveEditorState @ utils.coffee:91
Search.initialize @ motion-search.coffee:164
Motion @ motion.coffee:35
SearchBase @ motion-search.coffee:32
Search @ motion-search.coffee:149
OperationStack.run @ operation-stack.coffee:93
(anonymous function) @ base.coffee:490
module.exports.CommandRegistry.handleCommandEvent @ command-registry.js:259
(anonymous function) @ command-registry.js:3
module.exports.KeymapManager.dispatchCommandEvent @ keymap-manager.js:599
module.exports.KeymapManager.handleKeyboardEvent @ keymap-manager.js:390
module.exports.WindowEventHandler.handleDocumentKeyEvent @ window-event-handler.js:106
(anonymous function) @ window-event-handler.js:3
```

# Check list

- Atom version info(`atom --version`) 1.15.0
- vim-mode-plus version.  0.87.0
- Your OS(e.g. macOS Sierra 10.12.3)  10.12.4

**Comment by t9md** [comment]
It's strange, do you really use latest version in dev mode?
do `apm links` from CLI to see, maybe you have to do `apm unlink .` to remove symlink to old vmp checkout when you sent PR to vmp.

**Comment by bronson** [comment]
OH FFS, yep.  I totally forgot that, months and months ago, I used v-m-p in dev mode.  It was ancient.

Git pull and everything works great.

Sorry for the brain damage.  :)
