### ISSUE TITLE
Enhancement request for "cw" | "change word"

### ISSUE THREAD

**Issue by DanFreed** [t9md/atom-vim-mode-plus#739]
It would be super handy if you could add a feature to this that allowed some cut commands to not copy the removed text to the system pasteboard.  In particular the "cw" vim command.  

99% of the time I prefer that vim copy/cut commands do put the text in the system pasteboard, but when doing "cw" to change the current word, more often than not I want to paste something from the system pasteboard into the current editor.  When the text is cut with "cw" whatever I had in the current pasteboard buffer is replaced.  

I use Butler's pasteboard history currently to get my previous item back, but it would better if I could just avoid the situation.

I know it is not terribly "vim" like behavior, but it would be nice.

**Comment by t9md** [comment]
Agree. I'm thinking to add config option `dontUpdateRegisterOnChange`.
When enabled all `c` operation no longer update register.
Any thought?
