### ISSUE TITLE
Selecting a block with "V$%" doesn't work

### ISSUE THREAD

**Issue by bronson** [t9md/atom-vim-mode-plus#74]
vim-mode-plus suffers this too: https://github.com/atom/vim-mode/issues/936

It's because vim-mode-plus's linewise select doesn't allow the cursor to move horizontally.  Vim allows it.

So, `Vlhhllh` in Vim shows the cursor moving right and left within the selected line.  In vim-mode-plus, the cursor is frozen in place.

**Comment by t9md** [comment]
Yes I know it(I also occasionally check vim-mode's issue).
But to fix this, we have to independently manage virtual cursor position specially for visual-line mode.
And when side movement happen in visual-line mode, then update virtual cursor column accordingly.
This require big flight from native atom's way, I want to postpone this feature for a meanwhile..

**Comment by bronson** [comment]
This is fantastic.  It fixes the reported issue and I can't find anything wrong with it.  `o` during visual select even works.

:shipit: :ship: :+1:

**Comment by t9md** [comment]
Will ship today, thanks for checking behavior!!
