### ISSUE TITLE
put-*-with-auto-indent breaks occurrence modifier for paragraphs

### ISSUE THREAD

**Issue by nesmyslny** [t9md/atom-vim-mode-plus#746]
After mapping `p`/`P` to put-*-with-auto-indent, the occurrence modifier doesn't work in paragraphs, e.g. `cop` or `dop` has no effect.
Without those mappings it works like expected.

This is my keymap:
```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'P': 'vim-mode-plus:put-before-with-auto-indent'
  'p': 'vim-mode-plus:put-after-with-auto-indent'
```

---

* Atom version: 1.15.0
* vim-mode-plus version: 0.88.0
* OS: Linux

**Comment by t9md** [comment]
If you overwrite p and still want p as inner-paragraph on ocurrence operation, you need to remap p as inner-paragraph.

Why this happens is user keymap is always prioritized regardless of scope specificity.

What you need to do is add p to vim-mode-plus:inner-paragraph on operator-pending-mode.

**Comment by nesmyslny** [comment]
Thanks for the quick help! Works great :)

**Comment by t9md** [comment]
I decided to provide conditional keymap config so that user can remap `p` and `P` with **proper keymap scope** just by checkbox.
So that other user no longer hit this issue.
