### ISSUE TITLE
Vim surround targets

### ISSUE THREAD

**Issue by iovis9** [t9md/atom-vim-mode-plus#751]
From [vim-surround documentation](https://github.com/tpope/vim-surround/blob/master/doc/surround.txt):

> Eight punctuation marks, (, ), {, }, [, ], <, and >, represent themselves
> and their counterparts.  If the opening mark is used, contained whitespace is
> also trimmed.  The targets b, B, r, and a are aliases for ), }, ], and > 
> (the first two mirror Vim; the second two are completely arbitrary and
> subject to change).

I use these all the time and noticed they're not present (it actually surrounds a word with 'b' if I do `ysiwb` instead of brackets).

**Comment by t9md** [comment]
OK, so you want to use b as alias of `(`.

**Comment by iovis9** [comment]
Yes! I actually use all of them:
```
b — )
B — }
r — ]
a — >
```

**Comment by t9md** [comment]
Where `a - >` come from? is this widely accepted keymap?
If not I wont' set it and let user customize by themselves.

**Comment by iovis9** [comment]
As it says in the extract I quoted from vim-surround: b and B are more "official" than r and a in the vim community. But this piece of functionality is supposed to be a replacement of vim-surround, not vim.

**Comment by t9md** [comment]
I'm OK to set `r` shorthand, but for `a`,  I didn't think it's intuitive, so I asked for source of information of `a`, `r` is explained in surround.vim's help but `a` is not right?

**Comment by iovis9** [comment]
I don't think it's intuitive either but indeed it is explained on the docs: [Official surround.vim documentation](https://github.com/tpope/vim-surround/blob/master/doc/surround.txt#L99)
> The targets b, B, r, and a are aliases for ), }, ], and > (the first two mirror Vim; the second two are completely arbitrary and subject to change).

**Comment by t9md** [comment]
OK, I got source, thank you, think about later.

**Comment by t9md** [comment]
added `a` alias
