### ISSUE TITLE
triple-click-and-drag doesn't work in normal mode

### ISSUE THREAD

**Issue by bronson** [t9md/atom-vim-mode-plus#761]
In normal mode, when I triple-click-and-drag to select some lines, only the first line that I touched remains selected.

If I switch to insert mode and try the same thing, it works.

# Check list

Atom 1.16.0, vmp 0.91.0, Mac Sierra

**Comment by bronson** [comment]
Technically I should never touch the mouse of course.  : )

**Comment by t9md** [comment]
OK! thanks, mouse-things are always what I'm not motivated though too!

**Comment by bronson** [comment]
I hear it.

I'd guess it worked until relatively recently...  want me to bisect it?

**Comment by bronson** [comment]
This works!  Not sure when you fixed it but, at least with vmp 1.4.0 on atom 1.21.0-beta0, it appears to be working correctly again.  Excellent.

Closing.  👍
