### ISSUE TITLE
How to go to function declaration

### ISSUE THREAD

**Issue by fnokeke** [t9md/atom-vim-mode-plus#764]
Hi, 
Is there a way to jump to function declarations? I am aware of some atom packages that do this but they usually require clicking with mouse or moving my fingers to make odd key combinations. 

I tried `gd` but it doesn't do anything. I'm just looking for a way to be able to jump between a function usage (even if the definition is in a separate file). Any pointers would be helpful.

Thanks,

**My Specs:**

- Atom version info: 
1.16.0

- vim-mode-plus version.
0.82.10

- OS
macOS Sierra 10.12.3

- Yes, Vim mode is disabled

**Comment by t9md** [comment]
Not implemented.
And no plan.
Atom have symbols-view bundled by default.
How about using  `cmd-r`

**Comment by fnokeke** [comment]
got it. thanks for response.

**Comment by ajs139** [comment]
One possible solution is to install goto-definition, and add this to your keys.cson:
```
'atom-text-editor.vim-mode-plus.normal-mode':
  'g d': 'goto-definition:go'
```
