### ISSUE TITLE
Exercise Issue

### ISSUE THREAD

**Issue by pingshunhuangalex** [t9md/atom-vim-mode-plus#765]
No matter how hard I try, I can't get the to following exercise to work ...
`I j` then type `great-:` `insert` at start of six 'text' occurrences. six 'text' become 'great-text'.
`A j` then type `-editor:` `insert` at end of six 'text' occurrences. six 'text' become 'text-editor'.

**Comment by t9md** [comment]
Whre the link?

**Comment by pingshunhuangalex** [comment]
@t9md 
[Use with Motion section](https://github.com/t9md/atom-vim-mode-plus/wiki/AdvancedTopicTutorial#high-speed-tour-from-beginner-to-expert-in-7-steps)

**Comment by t9md** [comment]
Ok wiki is now get old, vmp have once default keymap for `I` and `A` when preser-occurrence was set.
I'll update wiki lator, you need to set insert-at-start-of-target for has-occuurence scope.
Why I removed this default keymap is its too aggressive and prevent user use normal `I` in `has-occurrence` scope.

**Comment by pingshunhuangalex** [comment]
Thanks for the explanation. Tried for 10 min, almost thought I'm probably too dumb for this...

**Comment by t9md** [comment]
Sorry! Thanks for make me notice that, keep open to remember me to fix wiki.
