### ISSUE TITLE
`` can not jump to the right place

### ISSUE THREAD

**Issue by oknixus** [t9md/atom-vim-mode-plus#769]
the problem is always existing.
Thanks a lot for this nice vim-mode-plus

**Comment by t9md** [comment]
What the right place, read issue template you deleted.

**Comment by oknixus** [comment]
Like vim, jump back and forth between the two places

**Comment by t9md** [comment]
That feature is already implemented and pass spec.
Read the issue template, you **deleted*, when opening this issue.
