### ISSUE TITLE
How'd you map combos like ggVGy into single key press like <C-A>?

### ISSUE THREAD

**Issue by lonelam** [t9md/atom-vim-mode-plus#771]
hi, I'm trying to replace vim with atom but I find it not that easy to tranfrom every function I had on previous editor into atom, even with the help of vim-mode.
And I find no tutorials or issues on this topic, wondering if something like this exist in atom configurations..

map \<C-A\> ggVGy

# Check list

- Atom    : 1.16.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0
- vim-mode-plus version. 0.91.0
- archlinux

**Comment by t9md** [comment]
You can't do that.
Atom's keymap customization is provided only for `keystroke to command`. Not for `keystroke-to keymap`.

Maybe my https://github.com/t9md/atom-keystroke package can help.
But I'm not actively use keystroke package, so don't expect any feature advancement.
