### ISSUE TITLE
ctrl-v followed by y and p don't work as expected

### ISSUE THREAD

**Issue by tiniusky** [t9md/atom-vim-mode-plus#775]
Version:

```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
vim-mode-plus: 0.91.0
```

```
os: openSUSE Linux
```

I've never installed vim-mode.

The Problem: when i marked the following block of numbers (all numbers from 1 to 9) in visual block mode (by `ctrl-v`):

```
123
456
789
```

and do a `y` (yank) and after that a `p` (cursor placed on numer 3), i get as result:

```
123789
456
789
```

But that's not what i expected. In original `vi`  i would get:

```
123123
456456
789789
```

btw: thank you for your great package!

**Comment by t9md** [comment]
Duplicate #415, If you don't think so, reopen.
