### ISSUE TITLE
Example in Extra complex operation (change-occurrence) not working

### ISSUE THREAD

**Issue by pingshunhuangalex** [t9md/atom-vim-mode-plus#776]
Was going through the examples in extra complex operation given [here](https://github.com/t9md/atom-vim-mode-plus/wiki/AdvancedTopicTutorial#8-extra-complex-operation), but can't proceed after step 3 `change-occurrence`. Atom just won't go into `operator-pending`.

I checked the `atom key resolver`, the keyboard action (`ctrl-cmd-c`) can be properly triggered using `ctrl-win-c` (see screenshot below), but the command itself just never works. Some explanation here would be appreciated. Thanks.

- Atom version info(`atom --version`)
```
Atom    : 1.17.0-beta5
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
- vim-mode-plus version.
`0.91.0`
- OS version
`Windows 10 64bit`
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
`No vim-mode installed, only vim-mode-plus`
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
Key is properly binded and called, but can never be activated
![image](https://cloud.githubusercontent.com/assets/17170199/25769511/817a3546-325e-11e7-984f-7d677831b01b.png)

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/blob/master/keymaps/vim-mode-plus.cson#L388-L390

Copy & paste above keymap and modify it.
Some keymap is defined for macOS only.
I'm not windows user, so couldn't decide what keymap is suitable.
If you have any good suggestion for windows keymap, I will consider it to se it by default.

**Comment by pingshunhuangalex** [comment]
Hi @t9md 
If you check my screenshot above again, you'll see it's not a key binding issue as `ctrl-cmd-c` can be recognised and called in windows. It's the vim-mode-plus command that's not doing its job.

I also took your suggesting binding the key map to something else, it still doesn't work. Could you please have another look into it? Maybe retest it in your mac to see if it still works on mac for a starter? Thanks.

**Comment by t9md** [comment]
Oh, I misunderstood, keymap is correctly binded. Will check later.
Wait for my next reply.

**Comment by t9md** [comment]
I read wiki again and updated to reflect minor change of default keymap.
What should be fired is `change-occurrence-from-search`, but as you can see in your screenshot, this keymap is defined in `darwin`(`macOS`) only.
If you want to follow this extra part, you need to set following keymap in your `keymap.cson`.

```coffeescript
'atom-text-editor.vim-mode-plus-search':
  'ctrl-cmd-c': 'vim-mode-plus:change-occurrence-from-search'

'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'ctrl-s': 'vim-mode-plus:transform-string-by-select-list'
```

As I already noted in Wiki, that part's assuming user is `macOS` user only.
So not working for win user is expected result, and I don't want this part very elaborate.

**Comment by pingshunhuangalex** [comment]
Thanks @t9md for the explanation. Sorry I didn't notice those 2 key commands were defined in `darwin`.

I set the keymap as you suggested, and it works like a charm now, so is there a reason why this is designed to be macOS only? Thanks.

**Comment by t9md** [comment]
Fine! you've done finally!

> I'm not windows user, so couldn't decide what keymap is suitable.
> If you have any good suggestion for windows keymap, I will consider it to se it by default.

This is the answer.

**Comment by pingshunhuangalex** [comment]
Right, I thought there may be some conflicting issue on win machine that's blocking the feature.

Well, the 2 keymaps you suggested works pretty well. Personally, I would keep `vim-mode-plus:change-occurrence-from-search` to `ctrl-cmd-c`, and change `vim-mode-plus:transform-string-by-select-list` to `ctrl-cmd-s`. Luckily those 2 commands are not used by windows built-in features.

Especially for `vim-mode-plus:change-occurrence-from-search`, I think it's a pretty powerful feature which would be shame if we leave it behind in Windows :)

**Comment by Alwayswithme** [comment]
save my day
