### ISSUE TITLE
[ExtendVimModePlusInInitFile] InsertSpaces operator example doesn't work

### ISSUE THREAD

**Issue by x0zzz** [t9md/atom-vim-mode-plus#781]
I've followed this: [[Basic] InsertSpaces operator which insert specified count of spaces](https://github.com/t9md/atom-vim-mode-plus/wiki/ExtendVimModePlusInInitFile#basic-insertspaces-operator-which-insert-specified-count-of-spaces) and nothing seem to happen on keypress. How can I make it work? And how can I insert spaces **before** the cursor position?

EDIT:
After Atom restart I get an error:
> Failed to load ~/.atom/init.coffee
> Base is not defined

# Check list

- Atom version info(`atom --version`)

> Atom    : 1.16.0
> Electron: 1.3.13
> Chrome  : 52.0.2743.82
> Node    : 6.5.0

- vim-mode-plus version.
> 0.91.0
- Your OS(e.g. macOS Sierra 10.12.3)
> OS X El Capitan 10.11.6
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
> Yep.
- Tried to latest stable atom version with latest vim-mode-plus.
> Yep.
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
> Nope. I checked.

**Comment by t9md** [comment]
You should follow from start. The answer is very first section of that wiki.

https://github.com/t9md/atom-vim-mode-plus/wiki/ExtendVimModePlusInInitFile#simple-moveupmovedown-motion
