### ISSUE TITLE
cw will replace text in clipboard

### ISSUE THREAD

**Issue by huang47** [t9md/atom-vim-mode-plus#786]
# Check list

- Atom version info(`atom --version`)
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

- vim-mode-plus version.
0.92.1
- Your OS(e.g. macOS Sierra 10.12.3)
10.12.3
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
vim-node is not installed
- Tried to latest stable atom version with latest vim-mode-plus.
It lasts for a while 
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

repro video: https://youtu.be/nVAjLshHq1w

**Comment by t9md** [comment]
You can disable it by confing. `useClipboardAsDrfaultRegister`

**Comment by huang47** [comment]
oh cool, found this in another issue https://github.com/t9md/atom-clip-history/issues/4

probably better to set it to false by default to align with vim? thoughts?

**Comment by t9md** [comment]
It was old default setting, but I changed it to true by default. I know it's controversial.
Wiki have dedicated section for incompatibility with pure vim.

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/wiki/DifferencesFromPureVim
This is very draft state though.
