### ISSUE TITLE
p should paste on *visible* next line when cursor is at folded line

### ISSUE THREAD

**Issue by dylnmc** [t9md/atom-vim-mode-plus#788]
**versions**
```
Atom: 1.17.0
Electron: 1.3.15
Node: 6.5.0
vim-mode-plus: 0.92.1
OS: Windows 8
```

Please paste line when cursor is on fold after the fold. Not on the next line (inside the fold).

e.g.

```
    [f]unction ImAFoldedFunction(yay) { [...]
```

where `[f]` denotes that the cursor is on the first letter of the function (the 'f'). When I press `p` after I have `yy`'d, then it pastes the line(s) into the fold -- rather than below the fold (I believe vanilla vim pastes after the fold).

edit
---
I've also noticed that `-` and `+` do not skip the fold. If, for example, I have 3 lines in a fold, and I am below the fold, then pressing `-` will stay on the fold for three `-` presses, and when I get to the first line in the fold, it finally "snaps" out of the fold. However, the cursor never moves, so it is pretty odd behavior.

Great stuff; sincerely,
dylnmc

**Comment by t9md** [comment]
> Please paste line when cursor is on fold after the fold. Not on the next line (inside the fold).

Yes I want to fix this, but it's not easy. keep open until I fix this.

**Comment by t9md** [comment]
Implemented,
`yyp`  on folded function copy whole fold, then paste to next-line of foldEnd line.

The diff is that the pasted function is NOT folded like pure Vim.
But this diff comes from the way how fold is managed by editor, different topic in implementation-wise(will handle in different issue if I found it necessary).
