### ISSUE TITLE
Need way to skip current occurrence when .is-narrowed

### ISSUE THREAD

**Issue by mrthebob** [t9md/atom-vim-mode-plus#792]
When making a multi-selection using cmd-d (on a Mac), there needs to be a way to skip a selection I don't want to modify/manipulate.  The vim-multiple-cursors plugin for vim does this with it's ctrl-x mapping (https://github.com/terryma/vim-multiple-cursors#quick-start)

# Check list
- Atom version info(`atom --version`)
   N/A  (1.18.0-beta0)
- vim-mode-plus version.
   0.93.0
- Your OS(e.g. macOS Sierra 10.12.3)
    N/A  (OS X El Capitan 10.11.6)
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
   Yes
- Tried to latest stable atom version with latest vim-mode-plus.
   Yes
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
   Yes/no

**Comment by t9md** [comment]
Give me example text and explain what you want to do please.

**Comment by mrthebob** [comment]
Example text:
----------
$this->form->header = '...';
$birthDate = $this->form->birthDate;
$this->format = 'xyz';
foreach ($this->form->rows as $row) {
  ...
}
---------

So, let's say I want to change all of the "form"s, but NOT the "format".  Using vim mode plus, I can start, in normal mode, on the first "form", type "v i w", then "cmd-d", which will put me on the "form" on the second line, then "cmd-d", which will put me on "format" on the third line.  Now, here's where I'd need to SKIP "format" and go to the next instance of "form", because I don't want to touch "format", only the "form".  In the plugin I mentioned above for vim, this is done with a ctrl-x mapping.  It would skip format and go to the next form.  I believe there's also a mapping to ignore the current selection and NOT continue to the next one as well...

**Comment by t9md** [comment]
There are many thing I can tell you, try it by yourself, learn each.

# `cmd-d` is provided by `find-and-replace` built-in atom package.

- You can use `cmd-k cmd-d` to "skip current and select-next", `cmd-u` to "unselect current selection".
- You don't need `v i w` to just select word. You can just type `cmd-d` then it auto-select word.
- When `cmd-d` select word from empty, it **remember** original selection is created from empty
  - In that case, subsequent `cmd-d` intelligently skip non-word-boundary match(means skip partial match).
  - e.g. When `cmd-d` at word `form`, subsequent `cmd-d` would not select `format`.
  - BUT, this **intelligent behavior is broken in vim-mode-plus's visual-mode, I need to fix I know but it's not such easy**.
  - If you start `cmd-d` from **insert-mode**( you should be able to use it unless you override keymap), the behavior I explained above is available( intelligent word boundary recognition and avoid partial match).

# vim-mode-plus have unique features named **occurrence** and also **persistent selection**.

- This is maybe too much for you at first glance, but **occurrence** is way useful compared to `cmd-d`.
- You can pre-set **occurrence** marker by `g o` keystroke, `g o` again **unmark** preset-occrrence, then change thse marked instance(= occurrence) in bluk like select range then `c` to change.
- Or you can change all `form` occurrence in paragraph by `c o p` or `c o i p` in-bulk.
- Here are pointers to learn these feature.
  - CHANGELOG of vim-mode-plus
  - [Short tutorial on Wiki](https://github.com/t9md/atom-vim-mode-plus/wiki/AdvancedTopicTutorial#high-speed-tour-from-beginner-to-expert-in-7-steps)
  - My tweet for occurrence include GIF https://twitter.com/t9md/status/849872727540342784

**Comment by mrthebob** [comment]
OK - this is AWESOME.  I love this.  I just finished going through all this
- nice features, all of them!  and THANK YOU!!!  I think you've just
changed my life! :)

**Comment by t9md** [comment]
Happy to hear that thanks!!!

**Comment by dylnmc** [comment]
I just learned about `o` recently. It's amazing, as are you, t9. E.g., `co4j` (when cursor is on a semi-colon) deletes all occurrences of semi-colon -- but only where semi-colons exist -- and put multi-cursors in edit mode at each of these found locations, but only for the current line and four lines down.
