### ISSUE TITLE
Can't type backslash in search box

### ISSUE THREAD

**Issue by mrthebob** [t9md/atom-vim-mode-plus#793]
I can't type a backslash ("\") in the search box.  It just doesn't appear.  Nothing happens

# Check list

- Atom version info(atom --version)
1.18.0-beta0
vim-mode-plus version.
0.93.0
Your OS(e.g. macOS Sierra 10.12.3)
OS X El Capitan 10.11.6
You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
Yes
Tried to latest stable atom version with latest vim-mode-plus.
Yes
Keybinding issue? Read this.
Yes/no

**Comment by dylnmc** [comment]
Perhaps I am misunderstanding. Are you saying that when you type <kbd>/</kbd> (to seach in `vim-plus-mode`) and then <kbd>\</kbd> (to perhaps escape a <kbd>.</kbd> or another meta-character that is interpreted by vim-plus-mode in the search bar), then it does not work, or are you referring to another "search box."

If it is the former, please press <kbd>ctrl</kbd><kbd>.</kbd> then press <kbd>/</kbd><kbd>\</kbd> and look in the `Key Binding Resolver` to see where it is coming from.

Also, do you have any user-defined key-bindings in your keymap.cson?

**Comment by mrthebob** [comment]
Arg - that was it.  An old keybinding.  Sorry!  Thank you...

**Comment by dylnmc** [comment]
It happens to the best of us; just close this issue. cheers
