### ISSUE TITLE
Unexpected cursor movement if "show cursor on select" is OFF

### ISSUE THREAD

**Issue by UmkaDK** [t9md/atom-vim-mode-plus#794]
# Check list

- Atom version info(`atom --version`)
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

- vim-mode-plus version.
0.93.0

- Your OS(e.g. macOS Sierra 10.12.3)
macOS Sierra 10.12.5

- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
vim-mode not installed

- Tried to install latest stable atom version with latest vim-mode-plus.
Both Atom and vim-mode-plus are at their latest stable version.

# What I expect to happen
I expect not to see the cursor when I disable "Show Cursor on Selection" in [Settings > Editor] and make a selection in the editor.

# What actually happens
There is no cursor while I'm making a selection with a mouse. However when selection is made (either with a mouse or via the keyboards, eg `vip` in Normal mode) the cursor is placed _after_ the selection. In other words, a character under the cursor is not a part of the selection (this differs from pure vim). 

What is even more confusing, is that when you then copy that selection with Cmnd-C, the cursor jumps to the last character of the selection.

# Example
A picture is worth a thousand words, so:

* This is what a selection looks like after placing the cursor inside of the work `background` and doing `viw`. Note that the character under the cursor (`-`) is _not_ part of the selection:
<img width="266" alt="after-selection" src="https://user-images.githubusercontent.com/2833247/26871215-51d0c902-4b6a-11e7-91ea-d641a508dc86.png">

* On copying the above selection with Cmnd-C, it is updated to look like this (now, the the character under the cursor (`d`) _is_ part of the selection):
<img width="272" alt="after-selection-n-copy" src="https://user-images.githubusercontent.com/2833247/26871393-dfab4b80-4b6a-11e7-95fa-b64613ca66dc.png">

**Comment by t9md** [comment]
Before I investigate, I want to ask you.

- Do you really use vim-mode-plus with `show cursor on selection` disbled?
- In that case, you no longer effectively use `o` in visual-mode, also all characterwise motion like `w`, `$`, `%` in visual-mode become useless.

So I'm curious why you want to disable it in the first place.

My impression for this issue is having root in bug of vmp, so will investigate anyway.

**Comment by UmkaDK** [comment]
Well... to put this bug into a bit of a context, I was trying to find a work around for this:

During the selection a block of text with a mouse (while having `show cursor on selection` _enabled_) the cursor is placed just after the selection. Which is very confusing for my simple mind since in vim the cursor is part of the selection (even while I'm making it). It seems like not a big deal but this behaviour makes it very difficult to see what string I'm selecting at a glance, and is very disruptive as I often have to select the same string multiple times because I've selected one character to few/many.

So I did a bit of digging around and found a comment in one of the issues (can't remember where now) that there are limitation in atom cursor handling and vim-mode-plus already does a lot of aggressive cursor optimisation. So I figured that behaviour is unlikely to change.

My next step was to see if I can fix the issue by hiding the cursor during the selection and only showing it after the selection is made, which is the way vim-mode-plus behaves when `show cursor on selection` is disabled. This works really well for making a selection but then it puts the cursor in the wrong place until I copy the selection with Cmnd-C (after that, the cursor jumps to the right place). Which again is a little confusing...

Ideally, when `show cursor on selection` is OFF, I'd like the cursor to be hidden during the selection (current behaviour) but appear in the correct place after the selection is made (without the need for additional Cmnd-C). ... But that's like saying "I found a problem but could you only fix half of it, 'cos I like the other half"

So I figured, I'd raise an issue and see what you think... :)

PS: On the whole, I 100% agree with visual mode without the cursor does not make sense.

**Comment by t9md** [comment]
Thanks for the background.
I agree, selecting by mouse is difficult because of current behavior of vmp and I think it has to be improve somewhat by hiding cursor or updating cursor pos more lively.

So the issue is 'creating/modifying selection by mouse is difficult while its not difficult without vmp'.

**Comment by UmkaDK** [comment]
Basically, yes. :) But I would go further and define it as:

- when `show cursor on selection` is ON
  - creating/modifying a selection with a mouse is difficult
  - creating/modifying a selection with a keyboard works as expected 

- when `show cursor on selection` is OFF
  - creating/modifying a selection with a mouse is easy
  - creating/modifying a selection with a keyboard places the cursor in unexpected location

**Comment by t9md** [comment]
Thanks for further clarification.
Btw, I expect all vmp user set  'show cursor on selection' enabled.

**Comment by t9md** [comment]
I'm looking into this issue to fix.

Only for this comment, I couldn't understand what you are saying.
> creating/modifying a selection with a keyboard places the cursor in unexpected location

**Comment by UmkaDK** [comment]
Hmm... it looks like as of Atom 1.19.0 and vim-mode-plus 0.96.2 you can no longed see the cursor when `Show Cursor OnSelection` is deselected (OFF). That, sort of, resolves the original ticket.

However, everything we've discussed in this ticket for when `Show Cursor OnSelection` is selected (ON) still stands, ie:

- creating/modifying a selection with a mouse is difficult
- creating/modifying a selection with a keyboard (eg `viw` in Normal mode) works as expected

**Comment by t9md** [comment]
Ok and I believe I could fix most of mouse frustration in vmp's norma and visual mode in #826.

but I still couldn't understand your original comment bellow.

> creating/modifying a selection with a keyboard places the cursor in unexpected location

If you still find mouse issue with next version of vmp, create new issue.
