### ISSUE TITLE
dot (.) repeat command does not work across buffers/tabs

### ISSUE THREAD

**Issue by mrthebob** [t9md/atom-vim-mode-plus#796]
When I issue a command in one tab, if I switch tabs to another file and issue a repeat command, using dot (.), it reissues commands that have only taken place in that tab or buffer - not globally.

# Check list

- Atom version info(`atom --version`)
1.18.0-beta2

- vim-mode-plus version.
0.93.0

- Your OS(e.g. macOS Sierra 10.12.3)
macOS El Capitar 10.11.6

- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
Yes

- Tried to latest stable atom version with latest vim-mode-plus.
Yes

- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
No

Thank you!

**Comment by t9md** [comment]
known issue. #301
