### ISSUE TITLE
how to add vim setting

### ISSUE THREAD

**Issue by liganega** [t9md/atom-vim-mode-plus#797]
# Check list

- Atom version info(`atom --version`)
- vim-mode-plus version.
- Your OS(e.g. macOS Sierra 10.12.3)
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
- Tried to latest stable atom version with latest vim-mode-plus.
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

**Comment by liganega** [comment]
atom : 1.17.2
vim-mode-plus: the newest
OS: mac OS Sierra 10.12.5

I am wondering whether and how it is possible to add some vim setting like

set noimd

Any help would be appreciated.

**Comment by t9md** [comment]
for `set imdisable`, vmp have no support for this and no plan to fix it.
see https://github.com/t9md/atom-vim-mode-plus/issues/205.


I believe https://atom.io/packages/vim-mode-plus-auto-ime is package providing workaround for this issue.
But I've not tried yet.

Also There is no general vim config read/translation mechanism supported.

**Comment by liganega** [comment]
Indeed, the tool you linked solved the problem.
In fact, I encouraged the developer to upgrade his tool to satisfy my requirement, and he did.
