### ISSUE TITLE
Can't move up while linewise visual mode

### ISSUE THREAD

**Issue by ystkme** [t9md/atom-vim-mode-plus#8]
On wrapped lines, I can't move up by hitting <kbd>k</kbd> while linewise visual mode (<kbd>shift-v</kbd>).

In the GIF below, I'm trying to move up on line 12 and keeping pressing <kbd>k</kbd> !! ..but I can't.

<a href="https://gyazo.com/cdbb220e4535a07c6561a61d52741da8"><img src="https://i.gyazo.com/cdbb220e4535a07c6561a61d52741da8.gif" /></a>

**Comment by t9md** [comment]
Softwrap not work well in vim-mode.
Workaround is to disable it.

This is the limitation long existing from long ago.
I even wrote PR to official vim-mode but stopped.
It isnt easy to fix with minor change.

https://github.com/atom/vim-mode/issues/785

**Comment by ystkme** [comment]
I didn't know vim-mode dosen't work well with soft wrap.

But in my case, it seems that the problem happens only with moving up. I can move down normally from wrapped lines.

**Comment by t9md** [comment]
Yes, I already described issue on vim-mode.
I cant fix this issue very soon like I described above issue and related PR on official vim-mode.
This fix involve overall cursor movement handling change.

**Comment by t9md** [comment]
Note, If you disable Line wrap and it fixed, then its same issue.
If you still can't move up even after you disable soft wrap, this is the bug I need to solve immediately.
Which is the result?

**Comment by ystkme** [comment]
I think it's the same issue. I can move up if I disable soft wrap.

**Comment by t9md** [comment]
Ok thanks.
I didn't care this issue in vim-mode rerwiting process.
Now Im in the mood to start tuckling to solve this issue.
Thanks for reporting this and your GIF report is very explanatory I like it!

**Comment by ystkme** [comment]
Thanks. I'm looking forward to the progress!

**Comment by t9md** [comment]
Currently `cursor.moveDown()`, and `cursor.moveUp()` move in relative position of *screenPosition*.
But when move 1 row up in screenPosition-wise, it still remain same bufferRow.
Movement in visual-mode is actually handled by the Motion::select and Motion::select only care its change of bufferRow.
So the movement not change bufferRow is equivalent to no-movement.

The issue user notice is or not is depending on selection.isReversed() state and the motion direction.
I think this issue only happen in visual, lineiwse interactive operation.
There is more consistent elegant way to solve this issue. but I don' want to affect other area of code in this time.
So fix should be OK at this time.

**Comment by t9md** [comment]
After some evaluation and re-thinking, then I decide to release, I will close this issue, until then keep open.

**Comment by t9md** [comment]
Released. v0.1.5.
