### ISSUE TITLE
search case-insensitive reverse the lookup order 

### ISSUE THREAD

**Issue by huang47** [t9md/atom-vim-mode-plus#800]
# Check list

- Atom version info(`atom --version`)
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
- vim-mode-plus version.
0.93
- Your OS(e.g. macOS Sierra 10.12.3)
macOS Sierra 10.12.3

- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
Yes I did

- Tried to latest stable atom version with latest vim-mode-plus.
Yes

- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
Nope

- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!
reproed video: https://www.youtube.com/watch?v=wGeaDTq6fmo&feature=youtu.be

**Comment by t9md** [comment]
Describe your isssue and expectation with samle text and keystroke and purpose.
Then use movie as complementary material.
I dont want to FIND OUT issue from movie. Actually i havent watch it since so many user just upload movie wich is NOT obvious what it is happening.

**Comment by huang47** [comment]
Issue:
When search in case-insensitive mode (key: ?), it's working in the opposite way that n navigate in  descending order (and N in ascending order)

Expectation:
n should navigate in ascending order and N should work in descending order

**Comment by t9md** [comment]
First of all, `?` is NOT case-insensitive search, it's search command same as `/` but it searches upward.

And the issue here is duplicate, see comment here.(it's how pure Vim works but some user feel it's not intuitive)

https://github.com/t9md/atom-vim-mode-plus/issues/737#issuecomment-292404449

**Comment by t9md** [comment]
I haven't even checked movie, but this is one example why movie is not helpful to share WHAT THE ISSUE IS.
Since expectation who watch movie is varied by person, I need word to explain the feeling/opinion of issue reporter to understand background correctly.
