### ISSUE TITLE
support z A

### ISSUE THREAD

**Issue by demands** [t9md/atom-vim-mode-plus#801]
Hey, thanks for all your hard work on this plugin, it's awesome and makes Atom a viable editor for me! 😸 

One of the commands that I use all the time in regular vim is "toggle fold recursively", or `z A`. Here's what [the vim documentation says about it](http://vimdoc.sourceforge.net/htmldoc/fold.html#zA):

```
                                                        *zA*
zA              When on a closed fold: open it recursively.
                When on an open fold: close it recursively and set
                'foldenable'.
```

I am happy to continue the work from #774 in a PR, if you support the idea. Probably while I'm at it I'd want to implement `z O` and `z C` too.

**Comment by t9md** [comment]
Sorry for my slow response, I agree with implementing it.
I'll work on it by myself.
