### ISSUE TITLE
Keybinding proposal:  numpad0-9

### ISSUE THREAD

**Issue by robrez** [t9md/atom-vim-mode-plus#803]
### Description
The numeric keypad does not work as expected. I'd like to propose using the same keybindings for the numeric keypad that are used for the default (non-keypad) numeric keys.

### Expected outcome
Numeric keypad functions identically to the default (non-keypad) numeric keys

### Actual outcome
Except for in "open" mode, input from the numeric keypad does nothing.

### Proposed keybindings
The proposed keybindings were copied from those used on the  default (non-keypad) numeric keys:

```cson
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'numpad0': 'vim-mode-plus:set-count-0'
  'numpad1': 'vim-mode-plus:set-count-1'
  'numpad2': 'vim-mode-plus:set-count-2'
  'numpad3': 'vim-mode-plus:set-count-3'
  'numpad4': 'vim-mode-plus:set-count-4'
  'numpad5': 'vim-mode-plus:set-count-5'
  'numpad6': 'vim-mode-plus:set-count-6'
  'numpad7': 'vim-mode-plus:set-count-7'
  'numpad8': 'vim-mode-plus:set-count-8'
  'numpad9': 'vim-mode-plus:set-count-9'

'atom-text-editor.vim-mode-plus-input-char-waiting':
  'numpad0': 'vim-mode-plus:set-input-char-0'
  'numpad1': 'vim-mode-plus:set-input-char-1'
  'numpad2': 'vim-mode-plus:set-input-char-2'
  'numpad3': 'vim-mode-plus:set-input-char-3'
  'numpad4': 'vim-mode-plus:set-input-char-4'
  'numpad5': 'vim-mode-plus:set-input-char-5'
  'numpad6': 'vim-mode-plus:set-input-char-6'
  'numpad7': 'vim-mode-plus:set-input-char-7'
  'numpad8': 'vim-mode-plus:set-input-char-8'
  'numpad9': 'vim-mode-plus:set-input-char-9'

'atom-text-editor.vim-mode-plus:not(.insert-mode):not(.with-count)':
  'numpad0': 'vim-mode-plus:move-to-beginning-of-line'
```

_Edit:_  Modified my post to add the additional selector for `numpad0` toward the bottom of the codeblock above.

- Atom version `1.18.0 ia32`
- vim-mode-plus version `0.93.0`
- windows 7 pro

**Comment by t9md** [comment]
Thanks for suggestion.
