### ISSUE TITLE
Global text transformation doesn't work as I expected.

### ISSUE THREAD

**Issue by PythonicArt** [t9md/atom-vim-mode-plus#804]
i just studied the "8.Extra complex operation" in "AdvancedTopicTutorial",the ouput result was not same as the case in the tutorial.I had enabled incrementalSearch setting. Here is my operating process.

![ouput](https://user-images.githubusercontent.com/19612522/27986754-cc1aa57c-63c8-11e7-8095-f246f31c6f6e.gif)

- Atom version info
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
- vim-mode-plus version 0.93.0
- OS:Ubuntu 16.04

**Comment by t9md** [comment]
Might not be obvious though, I said it `Assuming macOS keymaps` in that section.
In macOS `ctrl-cmd-c` is mapped to `change-occurrence-from-search`(not `change-occurrence`).
I updated wiki to describe precise command name(= `change-occurrence-from-search` )

The following issue is very similar, he is windows user seem to invoke cmd-key, but it's only mapped on macOS by default, so defining by himself solves issue. Of course you can follow tutorial by manually invoking necessary command from command palette.
https://github.com/t9md/atom-vim-mode-plus/issues/776

**Comment by PythonicArt** [comment]
Thank you! I have referenced the #776 and it solved my problem. change-occurrence-from-seach is a wonderful function!
