### ISSUE TITLE
Can't re-enable keybindings?

### ISSUE THREAD

**Issue by tyleryoungblood** [t9md/atom-vim-mode-plus#811]
Checklist Items
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
vim-mode-plus: 0.94.0
macOS Sierra 10.12.5
vim-mode: not-installed

There was a checkbox at the bottom of the vim-mode-plus settings list that said somethign like "disable keybindings to override them". I checked the box, but now the box is gone (so I can't uncheck it, and I can't confirm what it originally said, it's just gone). 

This has eliminated my ability to use vim mode (the cursor looks to be in normal mode, but hitting escape does nothing, hitting "i" does nothing, and typing other keys do nothing). If I disable vim-mode-plus I can edit files like normal, but I have no vim movements or functions available to me. 

I had been messing with my kemap.cson and init.coffee files to try to remap the escape key to "jk" (via https://github.com/t9md/atom-vim-mode-plus/issues/130) but I could never get it to work. So I thought maybe I needed to check that box to enable overriding of the built-in keymappings, but apparently that's not the issue. 

I've tried to disable/enable and uninstall/reinstall vim-mode-plus but the missing checkbox doesn't reappear. I have reverted my changes to keymap.cson and init.coffee (so that they are now blank except for the original comments).

I don't want to reinstall Atom if I can avoid it because i have a lot of other custom settings in Atom already and it would take a day to get my dev environment back to normal. 

Any help would be greatly appreciated!

**Comment by t9md** [comment]
Open your config.cson. And remove vim-mode-plus from packagesWithKeymapDisabled array.

**Comment by tyleryoungblood** [comment]
Excellent, thank you! That worked. 

Now I need to figure out why editing my keymap.cson and init.coffee files didn't work. But at least I can edit files again without disabling vim-mode-plus. Thanks for the prompt reply!

**Comment by tyleryoungblood** [comment]
BTW, is this an actual known issue? Should the checkbox have completely disappeared or is there something funky with my setup?  I would have thought I could go back and re-check the box, but it was gone. 

For the benefit of others searching for this fix - the original checkbox was under the heading of "Keybindings" and simply said "Enable" with the description of "Disable this if you want to bind your own keystrokes for this package\'s commands in your keymap."

**Comment by t9md** [comment]
In design, user should be able to disable and enable.
If not and you can reproduce it, it's BUG of atom itself or settings-view package( this is package to provide user interface of package setting gui).

Better to report issue to those project.

**Comment by tyleryoungblood** [comment]
Understood, I'll see if I can reproduce the issue, and if I can I'll report as an Atom bug (and/or a settings-view package bug). Thanks again for your help!

**Comment by altescape** [comment]
I also had this problem and removing `vim-mode-plus` from `packagesWithKeymapDisabled` array solved it.

Thought I was going mad.

**Comment by t9md** [comment]
Someone reported this issue to upstream?
This is not vmp issue as my understanding. so close now.
