### ISSUE TITLE
In insert mode, Ctrl-W (delete word) swallows whitespace, newline and preceding word

### ISSUE THREAD

**Issue by mb21** [t9md/atom-vim-mode-plus#814]
Sorry if this has been reported already or is intended behaviour, however it's different from default vim.

Say you have the following text:

    function bar
      where
        more stuff

Now place the cursor in insert mode just left of the `more` and press `Ctrl-W`.

**Expected behaviour**: only all the whitespace on the same line left of `more` is deleted. Only on a second press of `Ctrl-W` the linebreak would be deleted, and only on a third press `where` is deleted.

**Actual behaviour**: everything is swallowed including `where`.

**Comment by t9md** [comment]
when you type `ctrl-w` in `insert-mode`, the command executed is `editor:delete-to-beginning-of-word` which is provided by Atom-core.


So essentially, IMO this is Atom's issue, not vmp, vmp is not trying to re-implement or patch inconsistency with pure-Vim, vmp is just delegating insert-mode's functionalities to Atom's core.

Aside from that.
The behavior you reported seem to by buggy(or a bit surprising) at a glance.
My suggestion is try to report to Atom-core. vmp would not FIX this part.

**Comment by mb21** [comment]
Thanks for the quick reply.

Seems this has already been reported upstream: https://github.com/atom/atom/issues/3816

However, the suggested solution seems to be `editor:delete-to-previous-word-boundary` instead of `editor:delete-to-beginning-of-word`. Maybe vmp could do that as well?

**Comment by t9md** [comment]
I like that behavior, but don't want to touch too much for keymap in insert-mode, that confuse me a lot.
I want keep vmp's `insert-mode` being default-experience-of-Atom-editor as much as possible.
So don't want to change keymap in vmp.

**Comment by mb21** [comment]
Okay, I just added the following to keymap.cson:

    'atom-text-editor.vim-mode-plus:not(.normal-mode)':
      'ctrl-w': 'editor:delete-to-previous-word-boundary'
