### ISSUE TITLE
gw keybinding

### ISSUE THREAD

**Issue by dionyziz** [t9md/atom-vim-mode-plus#817]
`gw` should "go wrap" the currently selected text to the specified column width.

# Check list

- Atom version info(`atom --version`)
```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
- vim-mode-plus version: `0.95.0`
- Your OS(e.g. macOS Sierra 10.12.3): `macOS Sierra 10.12.5`
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously: Yes.
- Tried to latest stable atom version with latest vim-mode-plus: Yes.
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

**Comment by t9md** [comment]
I didn't know the `gw` feature.

- As far as I understand form vim-help and behavioral check, it's same as `gq` except it keep cursor at original position.
- `gq` is supported in vmp.

Will check to support `gw` by deriving it from already supported `gq`.
