### ISSUE TITLE
Target `i f` and `a f` for functions does not work for Rust and `language-rust` package

### ISSUE THREAD

**Issue by fkjogu** [t9md/atom-vim-mode-plus#819]
The target `function` does not work with rust source files using the [`language-rust (0.4.11)`](https://atom.io/packages/language-rust) package. It does, however, work for [`atom-language-rust 0.21.1`](https://atom.io/packages/atom-language-rust). Is this a problem of `language-rust`? Where does vmp get the information of what is a function?

To reproduce try to use `function` as target, for example `v i f` in the following snippet.
Rust code example:
```rust
// A function which takes a closure as an argument and calls it.
fn apply<F>(f: F) where
    // The closure takes no input and returns nothing.
    F: FnOnce() {
    // ^ TODO: Try changing this to `Fn` or `FnMut`.

    f();
}

// A function which takes a closure and returns an `i32`.
fn apply_to_3<F>(f: F) -> i32 where
    // The closure takes an `i32` and returns an `i32`.
    F: Fn(i32) -> i32 {

    f(3)
}
```

```
atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

vmp 0.95.0

**Comment by fkjogu** [comment]
Correction, with [`atom-language-rust`](https://atom.io/packages/atom-language-rust) it does not work for methods (`impl <type> { fn foo() {} }`), only for functions.

**Comment by t9md** [comment]
Before investigate, let me ask
- which is better in your opinion `atom-language-rust ` vs `language-rust`? I'm not using rust.
- Your issue is only happen in `atom-language-rust`, not in `language-rust` is my understanding correct?

**Comment by t9md** [comment]
If you put me comment, please paste both working and not working  function definition so that I can reproduce and compare easily.

**Comment by fkjogu** [comment]
`language-rust` has ten times the installs, but I cannot tell you which one is better. I did some experimentation and astonishingly the snippet does not work, because of the **comment**

```rust
/// This comment makes it fail
pub fn new() -> Foo {
    1 + 1;
    Foo {}
}
```

Using `atom-language-rust`. When deleting the comment also methods work fine.

**Comment by t9md** [comment]
> Correction, with atom-language-rust it does not work for methods (impl <type> { fn foo() {} }), only for functions. Maybe they are declared differently?

I cannot understand this part.
Again, I'm not rust user, don't use method/function terminology since I have no correct understanding for rust language.
Instead pleas communicate with **actual example text** which greatly reduce my difficulty to understand / reproduce the issue.

**Comment by t9md** [comment]
I confirmed behavior of atom-launguage-rust.
For comment jut above function definition affect how `i f` or `a f` works is grammar definition bug of atom-lanugage-rust(in my opinion).
Try to fold that function by clicking gutter, and see adding/removing comment affect how fold are create.

In vmp function area is retrieved from folded area, it assume language grammar correctly define folded area which atom-lanugage-rust doesn't seem to correctly handle folded area when comment is inserted just above function.

**Comment by t9md** [comment]
Why your example affect by comment is because of comment line starting with `///`, it affect fold( that itself is bug of `atom-language-rust` grammar).

Here is example I checked with atom-language-rust, see `[OK]`, `[NG]` comment.

```rust
// [OK]
fn main() {
    fizzbuzz_to(100);
}

// [OK]
fn is_divisible_by(lhs: u32, rhs: u32) -> bool {
    // Corner case, early return
    if rhs == 0 {
        return false;
    }

    // This is an expression, the `return` keyword is not necessary here
    lhs % rhs == 0
}

struct Point {
    x: f64,
    y: f64,
}

impl Point {
    // [OK] This is a static method
    fn origin() -> Point {
        Point { x: 0.0, y: 0.0 }
    }

    // [OK]
    fn new(x: f64, y: f64) -> Point {
        Point { x: x, y: y }
    }

    // [OK]
    fn ok_hint(&self) -> (usize, Option<usize>) {
        self.iter.size_hint()
    }

    /// [NG] because of tripple `///` instead of double `//`
    fn ng_hint(&self) -> (usize, Option<usize>) {
        self.iter.size_hint()
    }
}

```

**Comment by t9md** [comment]
language-rust doesn't have triple comment issue, in that part language-rust is better, why `i f` doesn't work is need fix by vmp side.
It's easy I believe, so after I fixed it, I recommend to use language-rust over atom-language-rust only from the fact language-rust correctly handle `///` starting comment.

**Comment by fkjogu** [comment]
Yes, I confirm what you are describing. Thanks for looking into it.

**Comment by t9md** [comment]
try v0.96.0 I just released, reopen if you still noticed any problem.
Thanks for reporting this.

**Comment by fkjogu** [comment]
Awesome, works fine! 👍

**Comment by fkjogu** [comment]
There are still issues, if the function signature is not just a one-liner:

Example:
```rust
fn my_function(
    arg1: i64,
    arg2: u64,
    arg3: String,
) -> i64 {
    let sum = 1 + 1;
    sum + 2
}
```

Which is not an uncommon formatting (it is even suggested by `rustfmt`, the official beautifier, if the arguments do not fit into one line).

If the cursor is in the argument list, dogin `v i f` will select all arguments. Inside the body it does not work at all.

**Comment by t9md** [comment]
Sorry for not responding, I don't want do heavy work for specific language / language-by-language.
So postpone to solve this issue.

Anyway user can create/release vim-mode-plus plugin which support **better* function text-object for rust's function.

**Comment by t9md** [comment]
In next version, `a f` and `i f` can correctly select function in https://github.com/t9md/atom-vim-mode-plus/issues/819#issuecomment-318629360 :tada:
