### ISSUE TITLE
Regression in 0.96.0: `gqq` doesn't work anymore to reflow a single line

### ISSUE THREAD

**Issue by nesmyslny** [t9md/atom-vim-mode-plus#820]
I think there's a regression in version 0.96.0 related to the `reflow` feature. When there's a too long line I used to use `gqq` to reflow it to the preferred line width. This doesn't work anymore, but e.g. `gqip` does work.

* Atom version: 1.18.0
* vmp version: 0.96.0
* I don't have any key bindings related to `reflow` (or the previous `auto-flow`)

**Comment by t9md** [comment]
Thanks for reporting. v0.96.1 is out.
