### ISSUE TITLE
Support numbered register

### ISSUE THREAD

**Issue by edenkl8** [t9md/atom-vim-mode-plus#821]
- v1.19.0-beta5
- 0.96.2
- Win7 64-bit
- I have not installed vim-mode, only vim-mode-plus

Hi :)
When I yank something in vim it goes to the  0 register so if I delete a line with dd
I can afterwards past what I have yanked before with: "0p
I have seen that this is not the case with vim-mode-plus, is there a way to fix it?

Thank you :)

**Comment by dylnmc** [comment]
Adding to this discussion (I'm on linux) …

`yy` (for example) seems to yank into all *numbered registers`.

When I do `"0p` or `"1p` or `"2p` etc, I get the most recently yanked/deleted text.

**Comment by t9md** [comment]
Duplicate #293
