### ISSUE TITLE
Add Common command combination keybinding to wiki

### ISSUE THREAD

**Issue by arijoon** [t9md/atom-vim-mode-plus#824]
My apologies if this isn't a real issue, didn't find a better place to suggest it. a common practice within vim users is to combine existing commands into another. e.g. 
```
no <down> ddp
no <up> ddkP
```

I believe it would be very useful to have a section in wiki that explains the procedures in doing exactly that (adding keybindings by combining existing commands in order). Given my understanding they'll need to be read in init file and inherited from base classes with the functionality.

**Comment by t9md** [comment]
In atom keystroke to keystroke mapping is not supported.
I experimentally create https://atom.io/packages/keystroke package, but I don't know its still work.
Also similar https://atom.io/packages/sequential-command maybe better.

For your example specifically, there is vim-mode-plus-move-selected-text package.

There is already wiki page to extend vmp through init file.
If you find something useful, feel free to add extra section or give me suggestion.
https://github.com/t9md/atom-vim-mode-plus/wiki/ExtendVimModePlusInInitFile

**Comment by t9md** [comment]
With using newest version of [keystroke](https://atom.io/packages/keystroke) package, you can do like this.

```coffeescript
'atom-text-editor.vim-mode-plus.normal-mode':
  'down': 'keystroke d d p'
  'up': 'keystroke d d k P'
```

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#map-keystroke-to-keystroke-like-nnoremap-vnoremap-in-pure-vim
