### ISSUE TITLE
Add zero-width match into regex search

### ISSUE THREAD

**Issue by mrthebob** [t9md/atom-vim-mode-plus#825]
Need some kind of zero-width match like vim has:
(@<=...)

# Check list

- Atom version info(`atom --version`)
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
- vim-mode-plus version.
0.96.2
- Your OS(e.g. macOS Sierra 10.12.3)
macOS Sierra 10.12
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
Yes
- Tried to latest stable atom version with latest vim-mode-plus.
Yes
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
No
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

**Comment by t9md** [comment]
I want to use JavaScript's RegExp as-is, don't want to do heavy-lifting by vim-mode-plus package.
So I  have no plan to support any pureVim compatible regexp(I understand it's super useful though).
