### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by ibqn** [t9md/atom-vim-mode-plus#830]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.97.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /home/ibqn/.atom/packages/vim-mode-plus/lib/vim-state.js:446

TypeError: Cannot read property 'dispose' of undefined
    at HTMLElement.handleMouseUp (/packages/vim-mode-plus/lib/vim-state.js:446:30)
```

### Commands

```
     -0:28 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-typescript 11.0.6 
autocomplete-modules 1.6.10 
autocomplete-paths 2.6.0 
busy-signal 1.4.3 
drag-drop-text 0.1.4 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.10 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-pycodestyle 2.0.2 
linter-tslint 1.7.0 
linter-ui-default 1.6.5 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
monokai-seti 0.9.0 
simple-drag-drop-text 0.3.4 
trailing-spaces 0.4.0 
vim-mode-plus 0.97.0 
```

**Comment by ibqn** [comment]
This one does appear every time when I click within the file with the mouse in the insertion mode, very annoying...

**Comment by t9md** [comment]
sorry for this regression, from my understanding this issue happen for use who enabled `startInInsertMode`.
You enabled this right?

anyway try v0.97.1 just released now.

**Comment by ibqn** [comment]
yes, correct, I forgot to mention this!

**Comment by chesleybrown** [comment]
I'm getting this error still (running latest stable atom and version of this package). I'm not using `startInInserMode` (I did try toggling it on and off to no affect though)

**Comment by t9md** [comment]
@chesleybrown with the vmp v0.97.1? you restarted atom after updating vmp?

**Comment by chesleybrown** [comment]
Yup, I restarted and verified the problem persists.

![screen shot 2017-08-15 at 11 55 15 am](https://user-images.githubusercontent.com/492166/29320103-c4300b58-81b0-11e7-9a7c-209bcc5ddc09.png)

It seems to only happen when I'm doing a search across my project and I click on a result to open the file.

**Comment by t9md** [comment]
Thanks I could reproduce.

> It seems to only happen when I'm doing a search across my project and I click on a result to open the file.

This information was helpful.

Why I couldn't repro is I don't noticed is I don't use find-and-replace's project-search usually and also set `Direction to open results pane` setting to `right`.
After I set this config to `none` I can reproduce issue.


```
  "find-and-replace":
    projectSearchResultsPaneSplitDirection: "right"
```

**Comment by t9md** [comment]
When `find-and-replace` config have `projectSearchResultsPaneSplitDirection: "none"`.(default),
Clicking project-find's results view immediately open matched entry on **same pane**, because of timing issue to **reuse** same pane, it fire  `mouseup`  even only on newly opened editor.
I didn't expected to come `mouseup` without preceeding `mousedown` event, but its what happened.

So I added dirty and explicit mouse-event life-cycle assuring to just ignore unexpected mouse event .

**Comment by t9md** [comment]
@chesleybrown 
Could you check with v0.97.2 (just released now)?

**Comment by chesleybrown** [comment]
Can verify the problem is now resolved. Thank you for the prompt fix! 🙏

**Comment by t9md** [comment]
Thanks for reporting with proper repro condition!
