### ISSUE TITLE
move-to-pair not working as expected with {} in some grammars

### ISSUE THREAD

**Issue by depeele** [t9md/atom-vim-mode-plus#836]
- Atom version 1.19.2
- vim-mode-plus version 0.93.0
- OS: Windows 10
- vim-mode is not installed, just vim-mode-plus;

I use '%' extensively to navigate through code.

In the following snippet, I would like to be able to use '%' to jump between the top and bottom braces. This works fine in vim and *I thought* it used to work in vim-mode-plus, but today it's not working.
```html
<!-- Main content { -->
<div>
  ... many lines of HTML ...
</div>
<!-- Main content } -->
```

When the cursor is over one of the braces and I press '%', instead of jumping between braces, it jumps to the beginning of the line the cursor is on. A second '%' jumps to the end '>' and a third seems to be ignored completely.

If I switch the grammar to Javascript, braces are matched as expected.

(Unexpectedly, switching to the C grammar *does not* work. I expected it to act like the Javascript grammar but instead it acts just like the HTML grammar.)

**Comment by t9md** [comment]
After I pasted the your example text as-is, I couldn't find behavioral diff between HTML/C/JavaScript grammar.
And there is no 0.93.0 version of vmp released.

Please re-check with lated vmp verision. And re-define what the problematic grammar, behavior for clarity.

**Comment by depeele** [comment]
Strange. Looking at my Installed Packages (Settings > Packages), vim-mode-plus had 0.93.0 listed as the version.

Looking in Available Packages (Settings > Install), I see vim-mode-plus listed as 0.97.2 but there is no "Update" option.
So, I uninstalled 0.93.0 and re-installed 0.97.2 and things now work as expected.

If you didn't release 0.93.0, I wonder how it became an option in Available Packages when I installed it several months ago? Very strange!

**Comment by t9md** [comment]
Sorry!!

> Strange. Looking at my Installed Packages (Settings > Packages), vim-mode-plus had 0.93.0 listed as the version.

Sorry, v0.93.0 is definitely released version. 
You can see all released version and timing here.
https://github.com/t9md/atom-vim-mode-plus/releases

> And there is no 0.93.0 version of vmp released.

So above my sentence was incorrect.
I misunderstood it as future version(like v0.98.0) at first glance, sorry.

I'm not sure why "Update" option was not available, where it should be able to "Update".
