### ISSUE TITLE
Can't use the keymap ctrl-cmd-c 

### ISSUE THREAD

**Issue by ericsimith** [t9md/atom-vim-mode-plus#837]
# This is A Keybinding issue.
1. I have _Incremental Search_ lit the Settings button
2. I'm through Key_Binding_Resolver tracking, after a conflict detection without buttons
3. In strict accordance with [the tutorial](https://github.com/t9md/atom-vim-mode-plus/wiki/AdvancedTopicTutorial#8-extra-complex-operation), but has not been successful.

# The target
If my this ISSUES is a mistake in my wrong operation or Settings, I want to be able to get detailed answers, if not, please let us know and solve quickly.
thank you

# Check list
- Atom version info(`atom --version`)  1.19.2 x64
- vim-mode-plus version. 0.97.2
- My OS is Windows 10 x64
- My disabled vim-mode.

**Comment by t9md** [comment]
https://github.com/t9md/atom-vim-mode-plus/issues/776

**Comment by t9md** [comment]
That keymap is defined for macOS only by default.
You beed to set it manually, I think I should update wiki to guide manual keymap setup for win user.
