### ISSUE TITLE
How do you pass a count argument into a keybinding?

### ISSUE THREAD

**Issue by thouqht** [t9md/atom-vim-mode-plus#839]
I use atom mainly for prose and because of that I use a lot of wrapped (visual) lines. Currently there's no way to go to the beginning or end of a visual line (issue raised [here](https://github.com/t9md/atom-vim-mode-plus/issues/443)) in vim-mode-plus so this is what I've done so far in my  keybindings:

```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':  
   ')': 'vim-mode-plus:move-to-column'
```

Which gives me the ability to go to the beginning of a visual line. To get to the end of a visual line, I would like to pass in a large count to `move-to-column` such as 1000 to get to the end of the column. So something like
```
  '_': 'vim-mode-plus:move-to-column[1000]'
```
Problem is that's not how you do it and I don't know the correct way. Any help would be greatly appreciated, thank you.

**Comment by t9md** [comment]
You cannot pass count via keymap, to do that

- you need to define your own command just for pre-binding fixed count to command. [example](https://github.com/t9md/atom-vim-mode-plus/wiki/ExtendVimModePlusInInitFile#basic-5-lines-moveupmovedown-motion).

OR

- you might can use my [keystroke](https://atom.io/packages/keystroke) package, but this is not perfect, some operations are not be able to simulate by this package.

**Comment by t9md** [comment]
I released improved [keystroke](https://atom.io/packages/keystroke).

If you install this, you should be able to define count bounded keystroke like this.

```coffeescript
'atom-text-editor.vim-mode-plus:not(.insert-mode)':  
  '_': 'keystroke 1 0 0 0 |' # Move to 1000 column
```

But this is not you want to do, since `move-to-column` move to 1000 column of **buffer row**, not **screen row**.
Now vmp support `g 0`,  `g ^`, `g $` use these commands for that purpose.
