### ISSUE TITLE
System undo doesn't undo every occurrence after `cop`

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#853]
# Check list

- Atom version 1.19.2
- vim-mode-plus 1.0.0
- macOS Sierra 10.12.6
- Disabled vim-mode
- Tried latest stable atom version with latest vim-mode-plus.

Repro:

`cop` on any two occurrences, then `cmd-z`. See that only one occurrence undone. `u` doesn't have this problem.

**Comment by t9md** [comment]
OK.
I can fix this, should I?
Do you use `cmd-z` instead of `u`? and why?

**Comment by chenglou** [comment]
Only because of muscle memory =)

Is it hard to fix? Does it even make sense to fix?

**Comment by t9md** [comment]
- vmp manually **bundle** multiple changes at the timing of escaping insert-mode.
- You see `d o p` have no similar issue with `cmd-z`.
- When you do `c o p`, you are in `insert-mode`, multiple changes made by occurrence is not bundled.
- I might can fix it, but I don't think it easy.
- And for insert-mode `cmd-z`, keeping undo step as granular as now might benefits for some user.

**Comment by chenglou** [comment]
Ok, makes sense. Feel free to close this if it's not worth the trouble. I'll shake off the muscle memory of cmd-z too at the same time =)

**Comment by t9md** [comment]
I cannot fix `cmd-z` in `insert-mode` issue, but if you use `cmd-z`  in `normal-mode`, just remap `cmd-z` in `normal-mode` to `vim-mode-plus:undo` will OK.

**Comment by t9md** [comment]
Will close now, I thinks it's worthwhile to consider alternate possibilities for undo-bundling. :
Might check when I'm in that mood in future. 😄
