### ISSUE TITLE
Highlighting inconsistent with "automatically escape on pane item change"

### ISSUE THREAD

**Issue by irrationalistic** [t9md/atom-vim-mode-plus#855]
Steps to reproduce:
- Ensure setting "Automatically escape insert mode on active pane item change" is toggled on
- Open a text file, have at least one line of text that's at least one word long
- Enter or stay in insert mode and ensure cursor is at the very end of the line
- Switch to another atom tab
- Switch back
- Observe that you are back in normal mode, but whole line is highlighted.
<img width="82" alt="screen shot 2017-09-01 at 1 29 29 pm" src="https://user-images.githubusercontent.com/851856/29986742-a4a8c0ba-8f19-11e7-979c-4200bde74e5f.png">

---
Atom: 1.19.4
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
OSX Sierra: 10.12.6

**Comment by t9md** [comment]
Could reproduce, thanks for detailed repro steps.
Will check to fix this.

**Comment by t9md** [comment]
Done quick investigation.
Current my impression is this is upstream issue.
From now I have to narrow down to find minimum condition to reproduce issue.
vmp's cursor-style-manager is nothing to do with this issue. still reproduce-able after comment out all call for this class.

**Comment by t9md** [comment]
Although I reported to Atom-core, I could avoid this issue by using more appropriate event.

- old: `onDidChangeActivePaneItem`
- new: `onDidStopChangingActivePaneItem`(this is better since this is not fired on super quick active pane-item change.)
