### ISSUE TITLE
[No Default Keymap] Insert At Start/End Of Occurrence

### ISSUE THREAD

**Issue by s3cy** [t9md/atom-vim-mode-plus#859]
`atom + vmp` is amazing! thank you! :heart:

Small question here. Under [wiki:Rename function parameters in bulk in refactoring ](https://github.com/t9md/atom-vim-mode-plus/wiki/AdvancedTopicTutorial#rename-function-parameters-in-bulk-in-refactoring), it says

>2. Mark that parameter name with `g o`(preset occurrence)
>3. Do whatever from following
    - `I f` or `I a f` to insert start-of-each occurrence, which is useful when you want to prefix it.
    - `A f` or `A a f` to insert start-of-each occurrence, which is useful when you want to suffix it.

But neither `I` nor `A` is mapped by default. What is the correct behavior?

### Check list

- Atom version info(`atom --version`)
```
Atom    : 1.19.4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
- vim-mode-plus version. `1.3.3`
- Your OS(e.g. macOS Sierra 10.12.3) `macOS Sierra 10.12.6`
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously. `yes`
- Tried to latest stable atom version with latest vim-mode-plus. `yes`

**Comment by t9md** [comment]
You are correct.
I removed some keymap from when I wrote that wiki.
I'll update wiki with proper instruction. thanks for asking this.

**Comment by t9md** [comment]
What I removed keymap is this.
Put this in your `keymap.cson`.

```coffeescript
'atom-text-editor.vim-mode-plus.has-occurrence:not(.insert-mode)':
  'I': 'vim-mode-plus:insert-at-start-of-target'
  'A': 'vim-mode-plus:insert-at-end-of-target'
```


Why I removed this keymap is I thought this is too surprising.
But now, I like this keymap again.
So I'll make it yet another conditional keymap(enabled based on configuration).
And update wiki after that.

**Comment by t9md** [comment]
Wiki now mentioning conditional keymap which will be available in vmp1.4.0 and later.
User still can set above keymap by themselves.

> For I f and A f in step 3 to work, you need to enable "keymap I and A to insert-at-start-of-target and insert-at-end-of-target" config(from v1.4.0).
