### ISSUE TITLE
Potential keymapping bug or incompatibility with proton-mode

### ISSUE THREAD

**Issue by jackcasey** [t9md/atom-vim-mode-plus#860]
Please see this issue: https://github.com/dvcrn/proton/issues/286#issuecomment-326710634

It seems that since a recent version of vim-mode-plus (`0.99.0`) something has changed with key mapping? (In particular the `g` key?)

I've reproduced this in quite a minimal install of both proton-mode and vmp.

I can't reproduce it with just vmp however; so I guess it's some interaction between the keymapping in vmp and in proton, probably the way in which they both do 'modal' key mapping?

Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

I will update both issues if I find anything more interesting.

**Comment by t9md** [comment]
- vmp 0.98.0 has no problem with proton
- vmp 0.9.90 has keymap issu with proton

Is this understanding correct?

**Comment by t9md** [comment]
diff from v0.98.0-v0.99.0
https://github.com/t9md/atom-vim-mode-plus/compare/v0.98.0...v0.99.0

For keymap, it addes `g 0`,  `g ^`, `g $` keymap.
That is super normal addition, I don't think it problematic.
Even if it have some conflicts in keymap with proton, throwing exception is bug of atom-keymap.
I think you can open it to atom-keymap project.

I'm now trying to produce by installing proton(first time), it take so long to install, now waiting to finish.

**Comment by jackcasey** [comment]
Thankyou very much for looking into it. 
It definitely might be some limitation or bug in atom-keymap. 

Side note: Proton and vmp are a great combo; I love both projects :)

**Comment by t9md** [comment]
Btw, proton seem to REPLACE all pkgs i've installed, I want recover it.
How can I do? manual only?

**Comment by jackcasey** [comment]
@t9md Proton handles package management from the `~/.proton` file.

Inside that file (the file type is like clojure what JSON is to javascript) you can enable and disable 'layers' (bundles of packages defined by proton). And also enable and disable individual packages.

For example to add a package that its not part of a proton layer you can add something like:
~/.proton
```clojure
  ...

  ;; Packages that are not part of a layer. List them here as keyword
  ;; All packages will be ensured to be installed. Stuff that is not listed here
  ;; Will get uninstalled so choose wisely!
  :additional-packages
  [
    :cursor-history
  ]
  ...
```

Then when you restart or reload atom it will automatically add that package for you.

**Comment by jackcasey** [comment]
Feel free to ping me on the atom slack if you need more help.

**Comment by t9md** [comment]
What i want to do is just RECOVER, since my investigation for proton is DONE.
I'm now manually recovering each pkgs. If there is better/quick way I want to know.

**Comment by t9md** [comment]
I didn't know proton replace all locally installed pkgs. I wanted to know before installing proton so that I can preserve pkg directory for easy restore.

**Comment by jackcasey** [comment]
Oh, I'm sorry I don't know of a way to restore packages that you had enabled before. I don't know that they're backed up anywhere. I think manual.

This won't help you now; but when I'm testing fresh installs etc in atom I use a different configuration by doing launching atom like this:
```bash
ATOM_HOME=~/.atom_testing atom .
```
So that my old atom configuration isn't modified.

Proton also changes settings as well. I'm really sorry that this caused an inconvenience for you :(

**Comment by jackcasey** [comment]
FYI: https://github.com/dvcrn/proton/issues/288  :/

**Comment by t9md** [comment]
Close since as my understanding, vmp do nothing special in it's default keymap.
Will re-open if proton's side investigation reveals it's still has something to do with vim-mode-plus.
