### ISSUE TITLE
Occurrence modifier does not work since 1.3.0

### ISSUE THREAD

**Issue by fkjogu** [t9md/atom-vim-mode-plus#861]
Issue
====
The occcurence modifier does not spawn multiple cursors anymore.

Example
=======
```
This is 1st paragraph .
2nd line also include t|ext text text.
3rd line include text text text
```
Pressing
`c o` => all instances of `text` are underlined with dashes
`i w` => only instance with cursor inside is changed, the rest untouched

Checklist
=======

- Atom version: 1.19.5
- vim-mode-plus version: 1.3.3
- Your OS: Debian Stretch

**Comment by t9md** [comment]
Not sure what you want to do.
`i w` is useless when combined with `occurrence`.
Try `c o p`, `c o j`.
In my environment occurrence works without problem in v1.3.0 and test spec also passes without any issue.

**Comment by fkjogu** [comment]
Sorry, my bad. Makes sense of course, that a scope/movement is required.
