### ISSUE TITLE
Compatibility with vim jump list

### ISSUE THREAD

**Issue by nocksock** [t9md/atom-vim-mode-plus#865]
I used `c-o` and `c-i` very extensively in vim. Would love to see this added to vim-mode-plus.

[More info](http://vim.wikia.com/wiki/Jumping_to_previously_visited_locations)

# Check list

```
$ atom --version
Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

- vim-mode-plus version: `1.1.1`
- Your OS: `macOS Sierra 10.12.5`

**Comment by t9md** [comment]
currently ``` `` ``` and `''` is supported.
And I've also released complemental [cursor-history](https://atom.io/packages/cursor-history) package.
README.md includes that info as long as other helper packages.

In atom, there are lots of command which is not aware of vim, managing jumplist in internally in vim-mode-plus is not practically useful and far from perfection.
So I create and managing as separate package.
