### ISSUE TITLE
Cursor resetting when using vim visual and atom search.

### ISSUE THREAD

**Issue by AlbinDaleby** [t9md/atom-vim-mode-plus#872]
I recently switched from Sublime Text to Atom and something I frequently did in vim was select a word (vim visual) with either **cmd-d** or vims: **v**+**i**+**w**.

- Then I copy that word with **cmd-c**  and paste that in search **cmd-f**

- I hit enter a couple of times until I find the code I want.

- I then hit escape once to exit the search, then escape again to exit vim visual mode.

In that case I want my cursor to move to the word that was currently highlighted, not the first word which I selected. GIF below.

Is there a some setting or something that I'm missing?

![vimsearch](https://user-images.githubusercontent.com/11645355/30322527-1210eac6-97ba-11e7-85f0-6546ace76dfa.gif)

# Check list

- Atom version: 1.19.7 x64
- vim-mode-plus version: 1.3.3
- Your OS macOS Sierra: 10.12.6

**Comment by t9md** [comment]
You are correct will check what's happening.
