### ISSUE TITLE
Folds don't work

### ISSUE THREAD

**Issue by srustamo** [t9md/atom-vim-mode-plus#876]
# Check list

- Atom version info(`atom --version`) 
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
- vim-mode-plus version.
1.4.0
- Your OS
OS X 10.9.5
- You disabled vim-mode? 
Yes
- Tried to latest stable atom version with latest vim-mode-plus.
Yes
- Keybinding issue? 
No

I can't get any of the fold commands work. No other packages are user packages are installed, and it is a fresh Atom install with vim-mode-plus package as the only user package.

**Comment by srustamo** [comment]
In fact, the only <kbd>z</kbd> commands that work are <kbd>zz</kbd>, <kbd>zt</kbd>,<kbd>zb</kbd>, <kbd>z Enter</kbd>

**Comment by srustamo** [comment]
A bit more of investigation: folding works in an .xml file but does not work in a .h header file. Is this  expected behaviour? If yes, is there a list of file types where folding works?

**Comment by srustamo** [comment]
It looks like folding works only in white space indented files.

**Comment by t9md** [comment]
Fold manipuration works as long as atom create fold for that editor.
Atom create fold indent based.
Vim-mode-plus NOT aware of range of fold, Atom knows.
You can see fold by hovering your mouse to gutter on leftside of editor.

**Comment by srustamo** [comment]
Thank you.
