### ISSUE TITLE
make vmp's ctrl-] work with hyperclick?

### ISSUE THREAD

**Issue by bronson** [t9md/atom-vim-mode-plus#884]
Any chance of making v-m-p aware of Hyperclick?  This is related to Atom's IDE features: http://blog.atom.io/2017/09/12/announcing-atom-ide.html

It's easy enough to get Hyperclick working with this:

```cson
'atom-text-editor.vim-mode-plus.normal-mode':
  'ctrl-]': 'hyperclick:confirm-cursor'
```

I really like it so far: it applies in lots of places and there's no need to run ctags.

However, `ctrl-t` doesn't work anymore.  That's not surprising, but I miss it a lot.

Any chance of making vmp's ctrl-] take advantage of Hyperclick, and ctrl-t return?  (I suppose it would fall back to current ctags behavior if hyperclick isn't available.)

**Comment by t9md** [comment]
Hyperclick have been long available as independent package before announce of atom-ide.

Are you suggesting to vmp provide above keymap as default keymap?
Btw, you should be able to use cursor-history for `ctrl-t` to back from jump by hyperclick.

https://github.com/t9md/atom-cursor-history/issues/32

**Comment by bronson** [comment]
Ah, from the blog post I thought atom-ide-ui was becoming an Atom project...  but I guess it's still just Facebook.

Never mind.  But I might reopen this if atom-ide becomes super popular.  :)

You're suggesting binding `ctrl-t` the same as `ctrl-o`?  That's close, but `ctrl-t` always jumps back to where you hit `ctrl-]`.  If you've looked around a bit, it'll take a few hits on `ctrl-o`.

**Comment by bronson** [comment]
Ah, I didn't realize vmp used symbols-view for ctrl-]/ctrl-t.  That makes all kinds of sense.

So I'm barking up the wrong tree.  All I want is for hyperclick to push a location onto the symbols-view stack.  Seems doable, I might have to look into that.
