### ISSUE TITLE
Is there a way to delete without register?

### ISSUE THREAD

**Issue by chantisnake** [t9md/atom-vim-mode-plus#892]
# Check list

- Atom version info
```
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

- vim-mode-plus version: 1.7.0
- Your OS: Windows 10
- You disabled vim-mode? Yes

# Question

Typically when I use `x` ,`d`, or `c`, I will pip my result into black hole register (or any non-default register)

```
nnoremap d "_d
nnoremap dd "_dd
vnoremap d "_d
vnoremap p "_dP
nnoremap c "_c
vnoremap c "_c  
```

is there a way to do that in `vim-mode-plus`?

Sorry I am not familiar with atom or coffee script. I tried to figure it out my self, but failed...

**Comment by dylnmc** [comment]
similar (solved): https://github.com/t9md/atom-vim-mode-plus/issues/473
