### ISSUE TITLE
last cursor position not preserved when clearMultipleCursorsOnEscapeInsertMode is true

### ISSUE THREAD

**Issue by kentor** [t9md/atom-vim-mode-plus#899]
# Check list

- Atom version info(`atom --version`)
```
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
- vim-mode-plus version.
```
1.8.0
```
- Your OS(e.g. macOS Sierra 10.12.3)
```
macOS High Sierra 10.13
```
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
```
yes
```
- Tried to latest stable atom version with latest vim-mode-plus.
```
yes
```

Saw this https://github.com/t9md/atom-vim-mode-plus/issues/562 but seems to not work. Check out the gif:

![](http://g.recordit.co/vmQLRFzcEz.gif)

**Comment by t9md** [comment]
If you can reproduce it, give me complete set of

- sample text
- keystroke
- expected result(final-text and description)
- actual result(final-text and description)

**Comment by kentor** [comment]
this is with `clearMultipleCursorsOnEscapeInsertMode: true`

sample text:
```
aaaa bbbb
aaaa bbbb
```

put cursor on top row `b` (any one, they all behave the same)
keystrokes:
```
cmd+d
cmd+d
c
cccc
escape
```

cursor will be on last c of last row
expect cursor to be on last c of first row

**Comment by t9md** [comment]
> cursor will be on last c of last row
> expect cursor to be on last c of first row

Cursor should be at 2nd(=last) c, this is designed behavior.
Last cursor is the cursor added most recently, see where autocomplete-plus's popup shows up at last cursor(2nd `bbb` position in this case).

So IMO, you have wrong expectation what last cursor is.

**Comment by kentor** [comment]
hmm interesting that the autocomplete-plus shows up on the 2nd cursor

but i would still expect the cursor to go back to where you originally started the multiple cursors with cmd+d, and i have two cases for why:

if you turn off vim-mode-plus, and repeat the same thing with
```
cmd+d
cmd+d
cccc
escape
```

the cursor will be on the first row.

this is also the behvior that i am used to on sublime text's vim mode + multiple cursor

**Comment by t9md** [comment]
For specific scenario you explained above, I understand your request.

But that behavior is based on behavior Atom-core not respect last-cursor position when merging multiple-cursor(or selections).
I intentionally depending that atom-core's behavior, it might good the scenario you explained, but bad for many other cases.

I can add this as optional feature request(not so motivated though for me).
Will keep open for a while to collect feedback from others.

**Comment by trkoch** [comment]
My expectations align with @kentor. With `clearMultipleCursorsOnEscapeInsertMode` enabled I'd expect the first added cursor's position to be respected.

In terms of tests found in `vim-state-spec.coffee` this is the expected behaviour.

```coffee
describe "clearMultipleCursorsOnEscapeInsertMode setting", ->
  beforeEach ->
    set
      text: 'abc'
      cursor: [[0, 1], [0, 2]]

  describe "when enabled, clear multiple cursors on escaping insert-mode", ->
    beforeEach ->
      settings.set('clearMultipleCursorsOnEscapeInsertMode', true)
    it "clear multiple cursors by respecting first added cursor's position", ->
      ensure 'escape', mode: 'normal', numCursors: 1, cursor: [0, 0]

    it "clear multiple cursors by respecting first added cursor's position", ->
      set cursor: [[0, 2], [0, 1]]
      ensure 'escape', mode: 'normal', numCursors: 1, cursor: [0, 1]

```

**Comment by trkoch** [comment]
By the way, I should add this (reversed) behaviour aligns with default Atom when adding cursors with `cmd+d`, making changes and finally clearing cursors with `esc`. Currently my workaround is to clear multiple cursors while in insert mode.
