### ISSUE TITLE
search and replace

### ISSUE THREAD

**Issue by francesco-losterzo** [t9md/atom-vim-mode-plus#900]
hi, I am using this package since a couple of days so I don't even know if I need to open an issue for this, but I googled and couldn't find a solution.

I am trying to search and replace some strings in a range of lines with the following command:
```
:13,38s/h_.* = \(.*\)/Helper.bookHistogram   \1/
```
but when I hit enter nothing happens. When I open my piece of code with vim on the terminal, this of course behaves as expected.

Is there anything I should enable in the settings (I took a look, but didn't find anything trivially solving it)?

# Check list

- Atom version info:
  - Atom    : 1.21.0
  - Electron: 1.6.9
  - Chrome  : 56.0.2924.87
  - Node    : 7.4.0
- vim-mode-plus version: 1.8.2
- Your OS: macOS Sierra 10.12.6

**Comment by t9md** [comment]
Open issue on ex-mode repo, I'm not maintainer of that pkg(this is wrong repo).

If you want immediate solution, learn atom's `find-and-replace`( `cmd-f`, `cmd-shift-f` ) via Atom's flight-manual.
