### ISSUE TITLE
Request: Add new setting or command to use `x` without going to clipboard

### ISSUE THREAD

**Issue by calebmeyer** [t9md/atom-vim-mode-plus#901]
Previously, @t9md suggested that I could delete using `x` without going to the clipboard by extending the DeleteRight class in my init.coffee, like this:
```coffee
consumeService = (packageName, providerName, fn) ->
  disposable = atom.packages.onDidActivatePackage (pack) ->
    if pack.name is packageName
      service = pack.mainModule[providerName]()
      fn(service)
      disposable.dispose()

consumeService 'vim-mode-plus', 'provideVimModePlus', (service) ->
  {Base} = service
  DeleteRight = Base.getClass('DeleteRight')
  class DeleteRightWithBackholeRegister extends DeleteRight
    @commandPrefix: 'vim-mode-plus-user'
    @registerCommand()
    execute: ->
      @vimState.register.setName('_')
      super
```

This has worked well for me, but it will be broken by #895. The solution is to convert to ES6 (from coffeescript) in init.js

In the meantime, I was wondering if we could enhance VMP to make this a setting instead of an extension. As a setting, it would be similar to the existing "Don't update register on change or substitute" setting.

**Comment by t9md** [comment]
The JS version of above extension is almost identical to example in wiki below.

https://github.com/t9md/atom-vim-mode-plus/wiki/ExtendVimModePlusInInitFile#advanced-deletewithbackholeregister


Also here is my init.js as example.

Finally I will consider your suggestion to make this behavior configurable via setting 👍

**Comment by calebmeyer** [comment]
I didn't realize this was in the wiki! Thank you so much for the link!
