### ISSUE TITLE
Move to pair doesn't work with quotes

### ISSUE THREAD

**Issue by barraponto** [t9md/atom-vim-mode-plus#903]
`%` on normal mode works fine with brackets, but not with quotes.

Vim Mode Plus: 1.8.2
Atom: 1.21.0
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
OS: Ubuntu Zesty (17.04) /  Linux 4.10

**Comment by t9md** [comment]
Not working with quotes is as designed.

**Comment by barraponto** [comment]
oh! any reason for that? i also noticed `ci'` doesn't work either.
Is it something that can be fixed through a plugin? I could develop that.

**Comment by t9md** [comment]
`c i '` should work. I don't know why not work in your env.
I cannot help unless you follow this.
https://github.com/t9md/atom-vim-mode-plus/blob/master/ISSUE_TEMPLATE.md.

**Comment by t9md** [comment]
Close in favor of #668, #661
