### ISSUE TITLE
Request: Option to remove status bar item

### ISSUE THREAD

**Issue by nmote** [t9md/atom-vim-mode-plus#913]
Right now, the only options are short and long -- there is no option to remove it altogether. I would prefer to not have this item taking up room in the status bar, since (1) I am only in insert mode while I am actively typing, after which I leave it immediately, so it's not hard for me to keep track of my mode, and (2) the cursor shape adequately indicates the mode.

I might be able to find time to put up a pull request if you would be amenable to this change.

**Comment by t9md** [comment]
It WAS possible via user's `style.less` as like described in https://github.com/t9md/atom-vim-mode-plus/issues/152.

But now I noticed this doesn't work in latest vmp(It's bug).
After I fixed this bug, use `style.less` to hide statusbar element.
I won't provide configuration option for this.
