### ISSUE TITLE
visual-mode becomes deactivated when navigating with ^ or $

### ISSUE THREAD

**Issue by pwrobinson** [t9md/atom-vim-mode-plus#917]
If I'm using visual mode and mark text using $ or ^, the editor instantly switches back to normal mode. 

# Check list
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
- vim-mode-plus version: 1.10.0
- Your macOS Sierra 10.12.3)

**Comment by t9md** [comment]
I cannot get your question.
What your keystroke and sample text?
`v $` and `v ^` works in my environment and test-spec also pass no problem.
So maybe this is keybinding issue, follow issue template guide you saw when opening issue.

**Comment by pwrobinson** [comment]
You're right, my bad!

**Comment by t9md** [comment]
So you could expand visual-selection area by `v $` and `v ^`?

**Comment by pwrobinson** [comment]
Yes, it was a key mapping issue - these keys were mapped to "editor:..." instead of "vim-mode-plus:..." commands.

**Comment by t9md** [comment]
OK, thanks.
Why you set your own `^` or `$` mapping?
It vmp's default keymap, so I want to know why.
