### ISSUE TITLE
Toggle highlight search broken in latest update

### ISSUE THREAD

**Issue by nwaywood** [t9md/atom-vim-mode-plus#918]
Since updating to the latest version of vmp (`1.10.0`) `vim-mode-plus:toggle-highlight-search` doesn't work.

# Check list

- Atom version: `1.21.1`
- vim-mode-plus version: `1.10.0`
- macOS Sierra 10.12.3
- You disabled vim-mode? Yes
- Tried to latest stable atom version with latest vim-mode-plus: Yes
- Keybinding issue? No, tried executing directly from `command-P`

**Comment by t9md** [comment]
OK I understand what you're saying, sorry.
It's actually semi-broken, will check to fix.

**Comment by nwaywood** [comment]
Ok great! Please let me know if you require any more information from me.

And thank you for such an amazing plugin! :)

**Comment by t9md** [comment]
try v1.11.0.

**Comment by nwaywood** [comment]
It is working again 👍  Thank you
