### ISSUE TITLE
How to disable(or switch) the input-method when leave from(or come to) input mode?

### ISSUE THREAD

**Issue by ericluo** [t9md/atom-vim-mode-plus#921]
First, I use atom and atom-vim-mode-plus all the time, and it's very helpful for my daily writings. Thanks

I use it in  Chinese language environment. When I write my blog in atom with vim-mode-plus, I often need to switch  from input mode to normal mode, or otherwise. After the switching, I still need another extra key stroke(for example, [Shift]) to change the input-method from chinese to english. When I return to the input mode from normal mode, I will need to switch to chinese input method, too.

What I want to is **a package or keymap** that will disable or switch the input method temporarily when I leave from or come to the input mode. Is there anything for this?  Could someone give me a clue?

Thanks in advance!

**Comment by t9md** [comment]
See this comment.
https://github.com/t9md/atom-vim-mode-plus/issues/446#issuecomment-327199374
