### ISSUE TITLE
Help needed creating custom operator

### ISSUE THREAD

**Issue by nwaywood** [t9md/atom-vim-mode-plus#927]
I have an operator that I want to make, which I will either release as a seperate vim-mode-plus plugin or include within vim-mode-plus, whichever you prefer :) However I need some help from you please @t9md 

## What the operator does

It operates on a visual mode line selection (or a single line if it normal mode) and creates a copy of the selection and comments out the original.

For example, if I had three lines selected in visual mode

![image](https://user-images.githubusercontent.com/3773641/31918806-50b60aa2-b8aa-11e7-9748-0d4c52b662f3.png)

executing this new operator would result in the code turning into this:

![image](https://user-images.githubusercontent.com/3773641/31918837-6a524e26-b8aa-11e7-8cce-8a3087f5ce56.png)

Similarly, operating on a single line would turn

![image](https://user-images.githubusercontent.com/3773641/31918870-8b3999e6-b8aa-11e7-8c4a-cfd605192662.png)

into 

![image](https://user-images.githubusercontent.com/3773641/31918879-95760390-b8aa-11e7-8e69-5fa38f6db89c.png)

I would really appreciate any help on how I would write this.

Thanks in advance

**Comment by t9md** [comment]
I like your idea.

experimentally introduce DuplicateWIthCommentOutOriginal in next-release.
See how I implemented from PR's changes if you want.
