### ISSUE TITLE
Running `:sort` on line selection includes extra line

### ISSUE THREAD

**Issue by sophiebits** [t9md/atom-vim-mode-plus#935]
If I have a file

```
d
c
b
a
```

and I select the middle two lines using `V` (visual line selection) then run `:sort` (really, `:'<,'>sort`), I end up with a file that reads "d a b c" and a resulting selection of *three* lines long. It should output "d b c a" with still two lines selected.

Atom: 1.21.1
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0
vim-mode-plus: 1.13.0
OS: macOS Sierra 10.12.6
You disabled vim-mode? Yes

**Comment by t9md** [comment]
`:sort` command is not included in this pkg.
So this is wrong repository, open on ex-mode repo.

**Comment by sophiebits** [comment]
Ahh sorry. Thanks.

**Comment by t9md** [comment]
Ya, I'm not maintainer of that pkg.
Btw vmp have own `sort` operator, you can invoke it via `g s`.
So `g s p`(or `g s i p`) to sort paragraph.
Also you can invoke it from command-pallette(`cmd-shift-p`) or vmp's select-list for specific operator(`ctrl-s` on macOS).

**Comment by sophiebits** [comment]
Nice, that one works well for me.

**Comment by t9md** [comment]
Nice 👍
