### ISSUE TITLE
vim-surround support seems broken

### ISSUE THREAD

**Issue by bendavis78** [t9md/atom-vim-mode-plus#94]
For example, I can't use `cs{[` to change surrounding "{" to "[".

**Comment by crshd** [comment]
[Default keymaps for surround are disabled](https://github.com/t9md/atom-vim-mode-plus/blob/master/keymaps/vim-mode-plus.cson#L216)

**Comment by t9md** [comment]
See [keymap example](https://github.com/t9md/atom-vim-mode-plus/wiki/Keymap-example)
