### ISSUE TITLE
Hydrogen run command keybindings work in insert mode only and broken in normal mode

### ISSUE THREAD

**Issue by a-b** [t9md/atom-vim-mode-plus#955]
# Checklist

- Atom version 1.22.0
- vim-mode-plus version 1.17.0
- macOS Hight Sierra 10.13.2

Hydrogen "run commands" like  Option + Return works in insert mode only.
It would be great to be able to run them in normal mode too.,

**Comment by t9md** [comment]
Hmm, I'm trying to avoid conflicts in `insert-mode`.
But in `normal-mode`, vmp override/conflicts with other pkg, it's un-avoidable.
I want keep current `cmd-eneter` keymap for `vim-mode-plus:maximize-pane`.

To say simply, in this case, I won't fix `cmd-enter` conflicts with hydrogen.

You can override to hydrogen keymap win over vmp's one.

```coffeescript
'atom-text-editor':
  'cmd-enter': 'hydrogen:run'
```

**Comment by awillats** [comment]
in case people continue to look here for a solution in the future, for me, the proposed solution didn't quite work, I had to use:
```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'cmd-enter': 'unset!' #undoes maximize pane
 ```
and
 ```
 'atom-workspace':
  'cmd-enter': 'hydrogen:run'
 ```
