### ISSUE TITLE
Is moving lines supported?

### ISSUE THREAD

**Issue by eyaleizenberg** [t9md/atom-vim-mode-plus#959]
For example `:m-3`, `:m+2`

# Check list

- Atom version info(`atom --version`)
- vim-mode-plus version.
- Your OS(e.g. macOS Sierra 10.12.3)
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
- Tried to latest stable atom version with latest vim-mode-plus.
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

**Comment by t9md** [comment]
Not supported directly. And in case you misunderstanding, I'm not `:w` like ex-mode pkg maintainer.

vim-mode-plus does not provide any `:w` like command(command mode command).


## Then how can I do similar?

Atom natively support move lines command.


![Uploading atom-vim-mode-plus-1171013-706-k3tu1a_72002uik9_md_—__var_folders_f0_r8q_rcqd1g1104ktb8kjzn7w0000gn_T_How_to_re-map_subword_movement__·_Issue__960_·_t9md.jpg…]()



And if you want more intuitive way to move block of text.
I've released separate vmp-plugin package bellow. See GIF anime on project page.

https://github.com/t9md/atom-vim-mode-plus-move-selected-text
