### ISSUE TITLE
Scrolling commands (zz, zb, zt) not working on update

### ISSUE THREAD

**Issue by arcticmatt** [t9md/atom-vim-mode-plus#970]
# Problem
I updated vim-mode-plus this morning and these commands stopped working.

# What I Tried

* Updating atom
* Updating vim-mode-plus after updating atom
* Restarting atom
* Restarting my computer

# Versions
```
Atom: 1.22.1
vim-mode-plus: 1.20.0
macOS: Sierra 10.12.6 
```

**Comment by t9md** [comment]
Works in my environment
Check all this. You've seen when you open this issue.
https://github.com/t9md/atom-vim-mode-plus/blob/master/ISSUE_TEMPLATE.md

**Comment by arcticmatt** [comment]
Something in my keymap was causing this to not work. Sorry for the confusion!
