### ISSUE TITLE
Fix: No "1 left character" on escape key to Normal mode

### ISSUE THREAD

**Issue by techienaut** [t9md/atom-vim-mode-plus#972]
Description: When hitting Escape to get to normal mode, the cursor is moved 1 char left (not a cannon vim default).

If this could be fixed, or a keymap to do 'core:cancel" + move right that would be helpful.

Atom: 1.23.0-beta1

**Comment by t9md** [comment]
As my understanding move-left when `escape`-ed from `insert-mode` to `normal-mode` is how pure-Vim works.

http://vim.wikia.com/wiki/Prevent_escape_from_moving_the_cursor_one_character_to_the_left

**Comment by t9md** [comment]
I couldn't get understand what is the issue, moving-left is correct vim behavior with my understanding.
You can reopen, but give me more context.
