### ISSUE TITLE
Feature: Context-like vim shorcuts

### ISSUE THREAD

**Issue by devmessias** [t9md/atom-vim-mode-plus#978]
Implement a new context in keymap.cson to define distinct shortcuts if user is in visual mode.

Example, I'm using easy-motion in vim, with the following shortcut
"esc -, -," the shortcut only applies only in the visual mode

I would like to create a similar feature in keymap.cson, the reason is the easy-motion-redux (https://atom.io/packages/easy-motion-redux)

'atom-text-editor' if in visual mode:
     'ctrl-alt-e': 'easy-motion-redux: words'

I'm a  newbie in atom... I don't know if this type of feature is possible

```
atom --version
     Atom    : 1.22.0
     Electron: 1.6.15
     Chrome  : 56.0.2924.87
     Node    : 7.4.0
vim-mode-plus 1.20.0
```

**Comment by t9md** [comment]
LIke this?

```
'atom-text-editor.vim-mode-plus.visual-mode':
  'ctrl-alt-e': 'easy-motion-redux: words'
```

**Comment by t9md** [comment]
Anyway if not clear, ask in more general Atom forum or Slack channel.
Or read doc I put as issue template

https://github.com/t9md/atom-vim-mode-plus/blob/master/ISSUE_TEMPLATE.md
