### ISSUE TITLE
How do I enable “find by two chars”?

### ISSUE THREAD

**Issue by lydell** [t9md/atom-vim-mode-plus#980]
# Check list

You have to check all before open issue.

- [x] Try with latest Atom and latest vim-mode-plus.
- [x] Pick descriptive and non-ambiguous subject
- [x] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [x] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [x] Include real use case so that maintainer can understand "why" you need help.
- [x] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3). atom: 1.22.1, vmp: 1.20.0, os: Ubuntu 16.04
- [x] If keybinding issue, Read https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working

Hi! I really like the improvements to `f` (and friends) you did a while ago (find across lines, highlight matches).

As far as I remember, there was also some experiment to find by 2 chars instead of 1 (like vim-sneak)? I’ve looked through the wiki and some previous issues, but I just can’t figure out how to enable it! Is that feature still around?

Sorry if I’m missing something obvious :(

(Btw, I started playing with the `select` operator today. It’s pure awesomeness! Thank you so much!)

**Comment by t9md** [comment]
All the options in this GIF is for tune `f` motion.

In my case I set 100 then land by 200ms timeout.

<img width="752" alt="settings_ ___github_atom-vim-mode-plus" src="https://user-images.githubusercontent.com/155205/33239509-75709136-d2e6-11e7-88e1-9d2eeae65183.png">

**Comment by lydell** [comment]
Thanks!

I guess I expected that there would be two separate commands: One for one-char find, and one for two-char find. Probably because I’m used to vim-sneak. I _did_ scroll through all options, but for some reason it didn’t occur to me that those options did what I was looking for. However, now that you pointed them out to me they make sense (after reading them through a couple of times).

I’m currently trying out your config of “max 100, timeout 200”, and so far I like it!

Feel free to close this issue, unless you feel like trying to improve the descriptions for the settings or adding something to the wiki, and want to track that here. I tried to come up with some improved text, but it is hard. It’s a somewhat advanced, but very powerful, feature, and sometimes those are simply hard to describe :)

**Comment by t9md** [comment]
It might better to add `when you want search 2 char, set this value 2 or more` like description.
Anyway I wont' track that, so close.
