### ISSUE TITLE
Targets `i f` and `a f` do not work with multiline parameters

### ISSUE THREAD

**Issue by irrationalistic** [t9md/atom-vim-mode-plus#983]
I've only tested this with JS and PHP.

#### Example A:
```
function a(p1, p2) {
  console.log('test');
}
```
`v i f` on the console.log line will successfully select within the function

#### Example B:
```
function a(
  p1,
  p2,
) {
  console.log('test');
}
```
`v i f` on the console.log line will not select anything

The same applies for `v a f`.

```
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
MacOS Sierra: 10.12.6
Vim-mode-plus: 1.21.0
```

**Comment by t9md** [comment]
same as unresolved issue https://github.com/t9md/atom-vim-mode-plus/issues/819#issuecomment-318629360.

I will try to find how I can improve multi-line arg function detection.

**Comment by t9md** [comment]
Done! available in next release. possibly v1.22.0
