### ISSUE TITLE
Bug Report: Can't search for `.` and replace with `/`

### ISSUE THREAD

**Issue by justinjhendrick** [t9md/atom-vim-mode-plus#987]
Repro steps:
paste this line into atom:
`"java.lang.String"`

put your cursor on that line and input this command
`:s/\./\//g`

Expected: (this is what vim 7.4 does)
`"java/lang/String"`

Actual:
`"javaglang.String"`

vim-mode-plus version: 1.22.0
```
$ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
Mac version: 10.12.6

#Check list

You have to check all before open issue.

- [X] Try with latest Atom and latest vim-mode-plus.
- [X] Pick descriptive and non-ambiguous subject
- [X] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [X] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [X] Include real use case so that maintainer can understand "why" you need help.
- [X] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).
- [X] If keybinding issue, Read https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working

**Comment by t9md** [comment]
I'm not maintainer of ex-mode. So wrong repo.
Read this thread.
https://github.com/t9md/atom-vim-mode-plus/issues/935

**Comment by justinjhendrick** [comment]
Sorry about that. I'll repost it there.
