### ISSUE TITLE
vim mode cursor disappears in Atom 1.24-beta0

### ISSUE THREAD

**Issue by pingshunhuangalex** [t9md/atom-vim-mode-plus#998]
# Check list

You have to check all before open issue.

- [x] Try with latest Atom and latest vim-mode-plus.
- [x] Pick descriptive and non-ambiguous subject
- [x] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [x] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [ ] Include real use case so that maintainer can understand "why" you need help.
- [ ] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).
- [ ] If keybinding issue, Read https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working

**Comment by hultberg** [comment]
When I press `Ctrl+S` (save file - vim goes into Normal mode) the cursor appears, but its gone when I go in Insert mode again.

**Comment by dsandstrom** [comment]
It's the opposite for me.  The I-bar cursor is visible in insert mode.  The block cursor is not visible in normal and visual modes.  The cursor works fine in Atom v1.22 and the last beta (v1.23?).

**Comment by thancock20** [comment]
I guess I should have looked here before I started messing with my styles.less file. But at least I do know that commenting out the entire file still causes this problem.

To be more specific, the I-bar is visible in insert mode. The block cursor is not visible until I save the file, then it appears. But it disappears again if I switch to another mode and then back to normal.

**Comment by pertrai1** [comment]
Yeah, it is weird. As long as I save every time then it will come back. Do some work, save, do some work, save. etc...

**Comment by ykpythemind** [comment]
I had same problem.

Probably It is related to https://github.com/atom/atom/pull/16294 

I found Temporary solution.

Open file ~/.atom/packages/vim-mode-plus/lib/vim-state.js  ( https://github.com/t9md/atom-vim-mode-plus/blob/master/lib/vim-state.js#L497)
and Insert `this.editor.setReadOnly(false)` after line 497

sorry if it's not work

**Comment by pertrai1** [comment]
@ykpythemind  - that did the trick for now. Thank you

**Comment by hultberg** [comment]
@ykpythemind Works for me. Just wanted to say (in case others attempt the workaround), the line number 497 did not match in my local `vim-state.js` file.

**Comment by ykpythemind** [comment]
@hultberg 
I think you have to update vim-mode-plus to latest version (v1.24.0)

**Comment by t9md** [comment]
Hi, thanks for investigating issue, I'll look into this.
First, I'll update my Atom.app from now.

**Comment by t9md** [comment]
@ykpythemind

**Comment by t9md** [comment]
I cannot find reasonable way to fix this issue.
This is basically atom-core upstream issue.
I cannot fix this, and cannot do anything unless upstream just revert that bad PR.

**Comment by pingshunhuangalex** [comment]
Thanks @t9md 

At least for me, I'm aware Beta has a higher chance of breaking things. I think it's good we raise the issue now and narrow things down to an atom-core upstream issue. Otherwise, it'll sneak into the prod anyway, which will continue to spread frustration.

Thanks for the help, and feel free the close this issue whenever you see fit. Thanks.

**Comment by t9md** [comment]
keep this open.
Since it's not fixed, just pretending to be fixed by just showing cursor.
In current fix, buffer is actually editable, type `q` or enable IME and input some key.

**Comment by t9md** [comment]
Commit made on upstream-Atom-core which have bad effects to vmp was **reverted** now.
Thanks for github team for hearing vmp author/vmp users.

After Atom-v1.24.0-beta1 was released maybe tonight, and you updated vmp to just released vmp-v1.24.3, you should be able to use Atom-beta without problem :tada:

**Comment by dsandstrom** [comment]
Thanks @t9md it's fixed in v1.24-beta1
